### ISSUE TITLE
Where can I find comprehensive java tutorial documentation?...

### ISSUE THREAD

**Issue by WYBupup** [eclipse/elk#1028]
I am new to ELK, but even if I finished reading the [documentation](https://eclipse.dev/elk/documentation.html), I still have no idea how to solve my problem. Specifically, I want to use elk to compute the coordianates for my graph using graphviz dot layout algorithm.. 
Can anyone help point where the tutorial is?

**Comment by soerendomroes** [comment]
If I am not mistaken, you call ELK as specified [here](https://eclipse.dev/elk/documentation/tooldevelopers/usingplainjavalayout.html) and set the [algorithm](https://eclipse.dev/elk/reference/options/org-eclipse-elk-algorithm.html) to dot. You can find the supported dot options [here](https://eclipse.dev/elk/reference/algorithms/org-eclipse-elk-graphviz-dot.html).
[If you just want to call the algorithm](https://eclipse.dev/elk/documentation/tooldevelopers/usingalgorithmsdirectly.html), you can also try calling the [GraphvizLayoutProvider](https://github.com/eclipse/elk/blob/9bc93474e1dc649450e8c97abb45d16b7c88e35b/plugins/org.eclipse.elk.alg.graphviz.layouter/src/org/eclipse/elk/alg/graphviz/layouter/GraphvizLayoutProvider.java#L102) directly.

Is there a specific thing that "dot" can do that  "layered" cannot?

**Comment by WYBupup** [comment]
Thanks nfor your reply. Im now trying to layout my graph using TreeLayoutProvider. I want to span the tree  from left to right and write the following code:

```
LayoutMetaDataService.getInstance().registerLayoutMetaDataProviders(
    new LayeredMetaDataProvider(),
    new MrTreeMetaDataProvider()
);

layoutProvider = new TreeLayoutProvider();

KNode graph = ....

graph.setProperty(CoreOptions.DIRECTION, Direction.RIGHT);

//draw graph
```
but I still get the tree which span from bottom to up.... 

I think the problem may be ` graph.setProperty(CoreOptions.DIRECTION, Direction.RIGHT);`

Can you guide me to fix it?

**Comment by soerendomroes** [comment]
Oh, the documentation seems to be quite old. You should use the ElkNode that is actually available in ELK. The no longer used by ELK.

**Comment by Eddykasp** [comment]
The algorithm is working as expected here. The problem is simply that the coordinate system in the figure is the wrong way round. (0, 0) should be in the top-left corner and positive-y goes down instead of up.
