### ISSUE TITLE
ElkGraph: Set 'derived' flag of derived features

### ISSUE THREAD

**Issue by spoenemann** [eclipse/elk#103]
The derived features such as ElkNode.hierarchical and ElkEdge.selfloop should be marked as *derived* in the Ecore model.

We could also consider using *invocation delegates*:
http://stackoverflow.com/questions/37833618/programmatically-specify-implementation-of-derived-attributes

**Comment by le-cds** [comment]
Ah, good idea. I somehow got the impression that setting a feature to "volatile" would have to have the same effect. I'm not really sure how a volatile feature would not be derived, and vice versa (all examples I can think of from the top of my head don't make sense).

Based on a quick scan of the page you linked to, this is what I was using for the very simple implementations: things such as `ElkNode.isHierarchical()`, which just has to check whether or not the node has children. Some methods implemented in `ElkEdge` are a lot more complex, and I decided that I'd rather implement them in the Java editor and simply leave them there.
