### ISSUE TITLE
How to use Draw2DLayoutProvider?

### ISSUE THREAD

**Issue by WYBupup** [eclipse/elk#1035]
**Ask your questions**
I want to use Draw2D algorithm to layout my graph using Java APi.
However, I cannot include [Draw2DLayoutProvider ](https://github.com/eclipse/elk/blob/master/plugins/org.eclipse.elk.conn.gmf/src/org/eclipse/elk/conn/gmf/layouter/Draw2DLayoutProvider.java)into my project.

**(Optional) Expected behavior**
Any tips on how to import Draw2DLayoutProvider  in my project?

**(Optional) ELK Version**
0.8.1

**Comment by soerendomroes** [comment]
Hi, sorry for the late reply.
Have you looked at our documentation regarding this:
https://eclipse.dev/elk/documentation/tooldevelopers/usingplainjavalayout.html
https://eclipse.dev/elk/documentation/tooldevelopers/usingalgorithmsdirectly.html

What questions are still remaining?
