### ISSUE TITLE
Layered algorithm: is it possible to use fixed positions and generate positions for nodes without position?

### ISSUE THREAD

**Issue by VadimChiritsa** [eclipse/elk#1037]
**Question:**
We have nodes which can have different incoming/outcoming references with other nodes.
Layered algorithm works very good.
The problem, that we want to no change layout (x and y position) for previous nodes after expanding new nodes, for example:
- we layout positions for 3 nodes as initial load, get x and y position
- we expand some of the nodes and want to NOT change the positions for the "old" 3 nodes and generate x and y positions only for new expanded nodes.

Guys, maybe you faced without such problem or maybe you have some ideas how to achieve it?

**Expected behavior:**
- We can pass to Layered algorithm nodes with fixed position, and Layered algorithm calculates positions for nodes without position based on nodes with fixed positions.

**Current behavior:**
- We can not combine and Layered algorithm and Fixed algorithm - elk throws error
- Layered algorithm doesn't work with fixed positions for nodes and recalculate them - generate positions for the nodes with fixed position also

**Comment by soerendomroes** [comment]
Have you tried setting all layered strategies to interactive?
https://eclipse.dev/elk/reference/options/org-eclipse-elk-layered-cycleBreaking-strategy.html
https://eclipse.dev/elk/reference/options/org-eclipse-elk-layered-layering-strategy.html
https://eclipse.dev/elk/reference/options/org-eclipse-elk-layered-crossingMinimization-strategy.html
https://eclipse.dev/elk/reference/options/org-eclipse-elk-layered-nodePlacement-strategy.html
