### ISSUE TITLE
[Question] Increase process timeout for LibavoidServer 

### ISSUE THREAD

**Issue by MaximilianMrazek** [eclipse/elk#1042]
**Ask your questions**
When layouting unusually big diagrams (over 1000 Nodes and hundres of Edges, I cannot provide an exact number) with the Libavoid Algorithm, the response from the LibavoidServer is taking longer than the defined default process timeout value. Therefore, an Exception is thrown, and the process is terminated manually without returning a layout result. When checking the [references](https://eclipse.dev/elk/reference.html) mentioned in the [Contributor Guidelines](https://github.com/eclipse/elk/blob/master/CONTRIBUTING.md), I was not able to find a way to increase this value via the preferences. I would like to address the following points: 

1. **Is there an existing way to increase the timeout limit for the thread?**
   - If there is, could you please provide guidance or documentation on how to adjust this limit?

2. **If increasing the timeout limit is not currently possible, can I provide a patch to allow for this functionality?**
   - I am willing to contribute by creating a patch that introduces a configurable timeout value for the thread. If this is acceptable, please provide any guidelines or requirements for submitting such a patch.

**(Optional) Expected behavior**
- Configuration in LibavoidOptions.java to increase the timeout value of a Libavoid Server class

**Comment by soerendomroes** [comment]
I guess one should make [this constant](https://github.com/eclipse/elk/blob/3b2a57f3091692e6e6949035ff1dc65a560d23ee/plugins/org.eclipse.elk.alg.libavoid/src/org/eclipse/elk/alg/libavoid/server/LibavoidServer.java#L451) configurable via a layout option for libavoid.

Are you using the snapshot version such that a quick fix and merge to master would benefit you or are you waiting for a release (which might take more time)?

**Comment by MaximilianMrazek** [comment]
Thank you for the quick response and fix.

I can wait for the next version, this is not an urgent fix for me.
