### ISSUE TITLE
Create utility class to configure spacing values

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#105]
It can be tedious to configure desired spacing values on every element of a hierarchical graph. Create a utility class using some kind of builder pattern and fluent interfaces that takes care of this.

**Comment by spoenemann** [comment]
Something like `org.eclipse.elk.core. LayoutConfigurator`? :-)

**Comment by uruuru** [comment]
Kind of, but more spacing- and user-focused. I haven't thought a lot about it yet, but could imagine something like:
```
ConfigureElkSpacings.
  .base(20)
  .relativeNodeEdge(.5)
  .individualNodeNode(myVeryPreciousNode, 100)
  .apply(graph)
```
And there has to be an extending class which should be used (automatically) in conjunction with ELK Layered that is aware of the additional layer-related spacings.

**Comment by spoenemann** [comment]
ConfigureElkSpacings could internally use a LayoutConfigurator to apply the options.

**Comment by uruuru** [comment]
@DAGobertGans made me realize that this enhancement is rather important. We should also discuss if a plain `spacing` layout option should be available after all. @le-cds?

**Comment by le-cds** [comment]
> @DAGobertGans made me realize that this enhancement is rather important.

I think the only thing that was missing so far was someone to implement the idea. ;)

> We should also discuss if a plain spacing layout option should be available after all.

Not exactly sure what you mean...

**Comment by uruuru** [comment]
``spacing: 10`` resulting in reasonable (relative) spacing values for all other options.
