### ISSUE TITLE
Why do i get no width or height for my inner nodes

### ISSUE THREAD

**Issue by ymolists** [eclipse/elk#1055]
**Ask your questions**

Hi Folks

I have this [graph](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=FAehAIEMBsHMHsBOBLALgCwLYC5zUgJ4CmiRAJqBAMaLwDOdyAdrALLPKbIBekqy8JgDo6RLgEkmqEpCr8AbkVypEAVyKVwTeGSIAFfFTFEpIlXyKwCuAHIBRACoB1APIAlANIB9AMrjWegAydgAawJp0AA6yzLBC2ro2OkrgAOwADBHRVLHxyUm6AEJEqADuRCaBhCR0uABMAKxZMSxC5LBEBSmNzTmt7Z3JxWUVTFXEiLXgdZlg4FEtcQN2ZB31sxALfUurRCsdw+WV1ZO4AIxNwAlEWshkXumP6eAA3sDg4ETQANZCZMikOQCJi4AAiLicNneWmSVQARl86EJIoZjFJcAAiAASXmCADEHOAAGpeBwuPTgFwAVQcflBdgx0PwCOg4Ax0EejI+11u9yeZ1e0I+X1+-0B-EEYIhUI+3NhkBZSJRsjRqExOPxhJJhRcDjJrEpNLpDKFeAVXzZHLOXNlPKYdwejzqgtlsuZFvZ6TOjptHwAvqa7Q6ngBmF2us0sy1eh7W00B10DXmO9LOgC0AD5k6HwNCEzDdNnHgAWcPCn5-AFEIGS8BucQAcSxDkD8sVyNRmBMarZGrsBOJpPJhtp4npvsjHo5dQnQb5jwaZbd5tZnrqPvjrcL9vn6QAbEuPu7V9PYxP88LdkX0ovM9eD3noUmdymBXeX09S8AA8AgA) i am trying to convert to json

When i use the 0.9.1 librabry from java here is the [output](https://go.dev/play/p/p1GQj3EXAgT) i am getting. can anyone please help me figure why the inner nodes have no heights and widths ?

**(Optional) ELK Version**
elk: '0.9.1'

**(Optional) Additional context**
jdk17

**Comment by Eddykasp** [comment]
This is because elkt assumes default node sizes, when converting to json, however, only the information actually explicitly stored on the graph is translated. This is to ensure that translating back and forth maintains the same graph. So in json you have to actually write down the node sizes you want. Or you can set them elkt before you convert it.

**Comment by ymolists** [comment]
Thank you so much for that prompt answer.

i found a work around in that now if a node has no children i explicitly add a constraint like this

```
    nodeSize.constraints: MINIMUM_SIZE
```

With that i am now able to get correct sizes. Is there a better way to tell elkt to compute the size when it converts from elkt to json ? i dont plan to do the reverse . for now its a one way conversion and i dont want to do multiple pass to enforce the size.

Best regards and again thank you !

**Comment by Eddykasp** [comment]
No the conversion itself cannot directly do this for you, but I would suggest you give the nodes a size using `layout [size: 50, 50]` for example so you can actually control the minimum size rather than using the default values.

**Comment by ymolists** [comment]
thank you that solve this problem !
