### ISSUE TITLE
How do i make edge bending longer

### ISSUE THREAD

**Issue by ymolists** [eclipse/elk#1057]
**Ask your questions**
I have this [graph](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=FAQwNg5g9gTglgFwBYFsBcACMICeBTGPAE1DDggDsU8KFMBhAUQDkAVRgJWGAHoeNiEPBygBXBHAoRMAZQAKAGQCSzRjN79BwsRKkA6AM4AHMhTwG9KKETwMA8sxmcAagEFWS54w0ZYEPXgAxmRGBngBYADWhkYggZL+WoxEQpgAjAAMGT7GcQl6FNZ4zEWYAKzZfBi58fpaJTbpWTmxtYkpeMmpGABMzTX5hTYNeABCeAgA7ng0CrgEBpgALNkDdR0j41MzFHP4MIu9ZcBr7UJdYxPTs-MH5dmBUBQGcDYwALJFYHYwb4YIMBACDwEBwmGYdgAImoAPquZiQmGMSEAcTUwCGeDk2ECeGotD0ACNoloZACQOQkMCKAlMEp3nIOHYvDCZKwOK4lCiABKsVQydSY7FxPE0BB6ABmIAAbrAyYDKQgLocAaI8D4hTjRQSDOTgaDMKMOQjYQBpOyMOQAMQxRWFuPx4uJkrgAA9iK4yJRHZgOFzeZC7AB1ZjAQIwKAGF5Sd6SOAoOAALyBcCe-0B+rBGAUrgAmpxWUHGJawxGowlYzSE8mJGmwgmlLQCHEJNLbBhVersPt8rqMyCsyp2Bz6B4vMBuwR8gmKEHXsg9KIjEYCKMxBQiHZZ-OkJgALRpCe3aeSOdEBdLlcwPYERi6+Mpp4yQLgBJWluwfeH202DA0ogwlkWQYAA3sAGACFEehEHAhCBLWFCYIGIbgX+RRzISeBgBYJgij6GAAETcjCCiMFarAYM4MKsHYcgYHYACqrAyEo0IEah2CYWAhE2FYGRpOxEGYn+ryAVkaSgahEFYdEMFwQhSHBqGEFCehIBcThWr4URJFkRRVGjHYrA0e89FMSxbFSVg6lYYRYD8YJKnCf+YkZD0kkqWhNgyEm4SPM85KSAghzvCo9IMe8rJKAAWt4nkQZxtkEfZaRiY5EEAL5Wc5olAQAzB5TlFD5iZ+U8fYUrQIVhe8EVRbFVkJTZ3HJfxgECVZWWZahOUAUBSyFdJUFyUECkYMhylFTYGFYZpeFipgOmkeRlEwoZxl2KZjHMaxjDpdZXF2W5+29a5ZSDV5eAlWVAUKlVmChcw4WRSxDXxQdSX2T0aWddlRQiX1WQAGwXZi116P5FVBdVT21S9MVxfFiUtV97X7V1GAY6dQEAOwXTJ0GwaNqaIeNSl-dNzVzQ6C2EcRy36WtRkmWZO2WZ5yNHXlJ3-S5QEAByg8VvkQ+VgX3Rgj3PfViMc81XM-Z5GOqb+fNZAAnEL3ki5D4vBQ9NV1a9ssqZzrV5Wjv3dSreAA2JmT48NRPwSTikoZ5mIzdhei4TTtCLfTemretLPbRZe1WWb9lLDzqu5fxElgR7wulaLt2VfrkuG-Db1I-LrVLIrKnK5ddvie5SdTVdOti3dmdS3DMuNR9KMZIXDlW5jqFaGXQEFPH-EYHuAB8vdZP3gMZHj3cdGPGQT65Ekj3PC-9RgwBZcAQA)

**(Optional) Expected behavior**
the edge should be longer

**(Optional) Screenshots**
![image](https://github.com/user-attachments/assets/0c81d8b5-6c08-4cc9-be49-f85ec59c13c5)

**(Optional) ELK Version**
snapshot

i pasted the bend where i want the edge to be longer

Thank you !

**Comment by Eddykasp** [comment]
I think the option you're looking for is nodeEdgeBetweenLayerSpacing. Let me know if that works for you, otherwise I'll try to look into it tomorrow.

**Comment by ymolists** [comment]
thank you for that quick answer

```
spacing.nodeNodeBetweenLayers: 40
spacing.edgeNodeBetweenLayers: 25
spacing.edgeEdgeBetweenLayers: 50
```
this is what i tried but does not seem to affect it. the option you mention does not seem to exist or i cant find it.

**Comment by Eddykasp** [comment]
Those are the right options but in your example they are not applied to the relevant node. [This](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=FAQwNg5g9gTglgFwBYFsBcACMICeBTGPAE1DDggDsU8KFMBhAUQDkAVRgJWGAHoeNiEPBygBXBHAoRMAZQAKAGQCSzRjN79BwsRKkA6AM4AHMhTwG9KKETwMA8sxmcAagEFWS54w0ZYEPXgAxmRGBngBYADWhkYggZL+WoxEQpgAjAAMGT7GcQl6FNZ4zEWYAKzZfBi58fpaJTbpWTmxtYkpeMmpGABMzTX5hTYNeABCeAgA7ng0CrgEBpgALNkDdR0j41MzFHP4MIu9ZcBr7UJdYxPTs-MH5dmBUBQGcDYwALJFYHYwb4YIMBACDwEBwmGYdgAImoAPquZiQmGMSEAcTUwCGeDk2ECeGotD0ACNoloZACQOQkMCKAlMEp3nIOHYvDCZKwOK4lCiABKsVQydSY7FxPE0BB6ABmIAAbrAyYDKQgLocAaI8D4hTjRQSDOTgaDMKMOQjYQBpOyMOQAMQxRWFuPx4uJkrgAA9iK4yJRHZgOFzeZC7AB1ZjAQIwKAGF5Sd6SOAoOAALyBcCe-0B+rBGAUrgAmpxWUHGJawxGowlYzSE8mJGmwgmlLQCHEJNLbBhVersPt8rqMyCsyp2Bz6B4vMBuwR8gmKEHXsg9KIjEYCKMxBQiHZZ-OkJgALRpCe3aeSOdEBdLlcwPYERi6+Mpp4yQLgBJWluwfeH202DA0ogwlkWQYAA3sAGAYFU3KcN4EGnAEGxFFs1y7Lchw9McEF4FEehEHAhCBLWFCYIGIbgX+RRzIS2EWCYIo+hgABE3IwgojBWqwGDODCrB2HIGB2AAqqwMhKNCjHkdg1FgExNhWBkaQSRBmJ-q8gFZGkoHkVhOF4QRREkcGoYQcplEgNJtFagxzGsexnHcaMdisLx7wCcJonidpWDmdhTFgApSkmSp-7qRkPRaSZFE2DISbhI8zzkpICCHO8Kj0oJ7yskoABasGRd50l+Qp6mBRBAC+XnBWpQEAMwRUFRQxYmcVPH2FK0ClaXvBlWW5V5EFSb5jH+WkgGKV5FXleRVUAUBSz1Tp0R6UEBkYKRxkNTYVE0XodEOmKmA2WxHFcTCjnOXYrlCSJYmMKVBVDf5PT3TNoVlAtUV4E1LUJQqHWYKlzDpZlol9flD0ycNYUlRNlVFKps1ZAAbB9mLfXo8VtUlnVA91IM5XlkWDZDT1jfdk0YBTr1AQA7B92FLfhK2psRa1GXDW0+WAln0QdTEscd9lnU5LluTdnlE1zRU1S98MhUBAAcqONbFGOtYl-0YIDwO9YTJnE9LMORRTpm-vLWQAJzK9FquYxryUA11PWg3rA1S1DNVk7DU2m3gCPqZk9O6UzhEs4ZZGRZi23c7tVl80ddmnedovXR5d1eQbUNLLLZvVQpmlgZHKvNWrv3tQ7WtO-jYP5Zn-lLEbJkm59-saeFhebV9tvq39Ffa3juv9RDRUNwF3uU+RWit0BBR5wpGB7gAfNPWSz4jGR05PHQrxka+hZpS873vc0YMAFXAEAA) is the correct way. 
The option targets the parent, so it needs to be set on the node that contains the nodes and edges in question. In your example that is node `nid_0000`.

**Comment by ymolists** [comment]
thank you !!!
