### ISSUE TITLE
ref a node by id for child parent relationship

### ISSUE THREAD

**Issue by ymolists** [eclipse/elk#1058]
**Ask your questions**
Hi folks.

Is there a way a node can contain another node (by say a ref) without embedding the text for that child node ? i cant see from the eltk/json model docs  if that is possible

somthing like 

```
node n00 {
  children {
      n01,
      n02
  }
}

node n01 {
}

node n02 {
}

```

**(Optional) Expected behavior**
a child node would become children of a parent node

**Comment by Eddykasp** [comment]
This is not possible with the current version of the elkt language and it probably won't be implemented because it goes a bit beyond what the scope of the language is intended to be. But it is an interesting idea nonetheless.
