### ISSUE TITLE
Anyone can please help me figure why this edge name has a problem with the engine ?

### ISSUE THREAD

**Issue by ymolists** [eclipse/elk#1062]
**Ask your questions**
Hi folks.

i am trying to use uuid for edge name by using underscore instead of dash. but one of the edge is failing for no obvious reason to me

I have this [grahp](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=FDB2HsBMFMAIYLbgAwCZYG9i1gel7KAIYLQBc80Sa2eBEMFoAlpMuwIy36FTmXVUtIgBsA5uABOzAC4ALBBRFEAntEnRItaCIDWAOkjMNAYxnNwoWBQAiAeQDqAOVrKARjtgAiRClReQHAY4XzQAfWZQMWgAZxlMWhweYlIKUNQIqNiZRLpeRkJWdhocJPo+NKo-TOi4wNL3Tx8q8MjamQDc4IFqtuywmPUAN3UE0tLkkn50mv7ByRHJXLL8-hY2dgBmZbzgysFZuIHh9R3lFXAAV3iAbRjmAC9+TfYAGlgOdgBdHdEJaXkilg53Umh2OgMRlM5kstkcLnGOEaIm8Mz6R3miwC4wAvvUgnweq0skcAO7QNxjRGTVJEjLomRhcluHbJCqFDbIAAsrPKBTRJMZzLOqiut3uTwoL2Q70+yB+iNgfyksgUSlUoK0iohhmM0DMFlAcOcIo8KOaBwZTIp2NKeNymmisGgyE2LoAZqgTGEOJAiEQwlzkBxoGE3FyABwBojId2bDgATgjXJeAHYI-teoLjgtRgBaAB8dMOQopvNgAAciPIKJj1NaWTh7QSYMXoDIUVhxjTpi0Mu2RLk2QV1sUAGxDvm9g4D-HAohm1F9sID23N1ZtyCkqkrFLT6qaUmT1ZMIrsVPHvabo+5ZFLmdbtf1R1wMdEACsqZMSY4YXdMG9Lkx2gBMwgjJNUzCEwuRMWMiC5aBfXfDNiwZWBCzbDtjyrGtYCtWdtEgJ13XYEwOAjSAIzCeDIHdQMExdMMx1QUDNDfTYx2YzYuXfSBM3CAd0KLGZD2w6s5AoAcVy3YB7SAA) 

I dont understand why that edge is failing. the name is a uuid based name. 

**(Optional) Expected behavior**
i was expecting using uuid names with underscore would be fine

**(Optional) ELK Version**
snapshot

**(Optional) Additional context**

**Comment by Eddykasp** [comment]
All identifiers have to start with a letter not a number. This is a limitation of the elkt language. If you still want to use your uuids, I suggest simply adding an "n" for nodes and an "e" for edges at the beginning.
