### ISSUE TITLE
I can't make the children nodes consistent under a condition node, It's flip flopping / changes positions frequently.

### ISSUE THREAD

**Issue by Azim-Ahmed** [eclipse/elk#1069]
` const options = {
  includeHiddenNodes: false,
};

const layoutOptions = {
  "elk.algorithm": "layered",
  "elk.direction": "DOWN",
  "elk.edgeRouting": "ORTHOGONAL",
  "elk.layered.unnecessaryBendpoints": "true",
  "elk.hierarchyHandling": "INCLUDE_CHILDREN",
  "elk.layered.spacing.edgeNodeBetweenLayers": "10",
  "elk.layered.nodePlacement.bk.fixedAlignment": "BALANCED",
  "elk.layered.cycleBreaking.strategy": "DEPTH_FIRST",
  "elk.insideSelfLoops.activate": "true",
  'elk.layered.considerModelOrder.strategy':'NODES',
  separateConnectedComponents: "false",
  "spacing.componentComponent": "50",
  spacing: "50",
  "elk.layered.spacing.nodeNodeBetweenLayers": "20",
};

const elk = new ELK();

// Function to layout nodes using ELK
export const getLayoutedNodes = async (nodes, edges) => {
  const graph = {
    id: "root",
    layoutOptions,
    children: nodes.map((n) => ({
      id: n.id,
      width: 400,
      height: n.type !== "beat" ? 650 : 290,
      layoutOptions: {
        "portAlignment.default": "CENTER",
        portConstraints: "FIXED_SIDE",
      },
    })),
    edges: edges.map((e) => ({
      id: e.id,
      sources: [e.source],
      targets: [e.target],
    })),
  };

  const layoutedGraph = await elk.layout(graph);

  const layoutedNodes = nodes.map((node) => {
    const layoutedNode = layoutedGraph.children?.find(
      (lgNode) => lgNode.id === node.id
    );
    return {
      ...node,
      position: {
        x: layoutedNode?.x ?? 0,
        y: layoutedNode?.y ?? 0,
      },
      transition: "transform 0.8s ease", // Add transition for smooth animation
    };
  });

  return layoutedNodes;
}; `

In the layoutOptions
If I use `  'elk.layered.considerModelOrder.strategy': 'NODES_AND_EDGES',`
<img width="787" alt="image" src="https://github.com/user-attachments/assets/6e175a71-2c23-426b-af3c-bedf3fdf20fe">

then expected layout I am getting but while adding a new node under a condition node. the children nodes actually flip flow.
<img width="773" alt="image" src="https://github.com/user-attachments/assets/9f63ee93-4cb5-45cb-ac88-14eab226ec3f">

<img width="715" alt="image" src="https://github.com/user-attachments/assets/f59d2c3e-2e1f-4b82-bf25-b3b0c4bea483">

If I use `  'elk.layered.considerModelOrder.strategy': 'NODES',` only this.
then children nodes are not flip-flopping.

How can I make the consistent behavior without flipflopping children nodes.

**Comment by soerendomroes** [comment]
`'elk.layered.considerModelOrder.strategy': 'NODES'` is not a valid option. It might depend on the order of edges or ports you are using.
Additionally, INCLUDE_CHILDREN does not always work with model order.

**Comment by kanekv** [comment]
@soerendomroes what would be the right way to do this?

**Comment by soerendomroes** [comment]
The correct options values for `elk.layered.considerModelOrder.strategy` can be found [here](https://eclipse.dev/elk/reference/options/org-eclipse-elk-layered-considerModelOrder-strategy.html).

You can manually create the hierarchical edges and ports like [this](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUAMYQB2AzjAXgLIS0gDyUtUAdGUgA4U7k4ldHWYARAKIAZAPrMASpPlEi5RjjQxyJEAFdaAYQQwQBfEjQBvImltoA9PbQTywAEYgNAM2hoSUCEpKNGM8YBIELDRCMA0A3TgtMAAaNAIYSndPNB8oNAAiNSlsCAT86IJYyhs7UKhgKAisAAlgcgIQJPQASQA5AykAVUkZA2buqTF5CV6a2zVaNHIARis5u3n1JeWZLXI8dYBfFQ2FjXIAJjWN063L3fJ9vOsb14cnABVjYIy0ChAonAIGgAG4ZXSgGAALw0AHcEAI0G0KrE-G01HA0G4NJgsKU4IR1m93licCRgLpKBp4JofuQ0Ig4QFyGAQjAwo1IhwiW9cfi0ABtagw9DLAAMYtS4rFAF0ebZjhtjusYudlhwVg8nmgALQAPiWFw1Fy1Bw2qu2Gp2ezwuoNl2NpqgRGVZzQSDaEJAzXZ9U5URedjdK2ub0caDowAA1jhgpRdPgGQhgJjGWg+FBMZQeOEkrSMBBYbbEMi0xbs7mWdzieGvr9gCCIDRgrpHmTY5koFFse1KNW3hWSEkOBm4AAFaBwdAAVjQ8qWd2tbee88VbwtKytTrtlpgy3nG-VmpteX1u4uJzDTgnmeCQOirg8Gn8gWCdQaTRRsfno80q0DxK2HyCSCsKOCilKcrEmury-jAVwAYBwGYkK0LgWgyyQauRyXpsiyXKGry1t87rRrGaDxomJapgi6aTn8bC2gQEDkRifjJiyGhuMAVIEH89L1O0EBIPO4a0EO1AUD8XgYCUIG-Mx+zpra77+v2rxkFQND0OoLCMZwlBwPUBJgFg6C9OIEgAMoyAAgr0YgyBIYgAOLWSSrBIuQUQQDwiQUEmKb5mxaj7OpNzBiaJ6EYBxG-L8-yAsCYLxpCMJoPCiLIha5KPBAmLYrJeIJISgF2OG2LkpS1KYvF9JprCzKsqpTThcSyGgWhooSlKEpQWVdGZpoIaIQNRX8qhIoYVhY2HHY84bHBBGjQNHWTehmEYf1ZUwTcu3mpU5xGnuO4OvcJ4cFo+7Ehux1XGeZ1Rcul2XLhNzhjeQgMsCAhZM+ARBGyHKfqq1TEnB-4LXYa1gRBW3YeD9HwTF7VyShsPTfD0E4es4YSIddJJhomRIBoLWRCqh27qsD3HdddiHpd932ndb3hgY6L5aSaDxASBCpNQ2j-a+Ork1EoNIombGadQ7CleVTiM8ey6nUa53LrjitU5uyvarTjoni6QA).

**Comment by kanekv** [comment]
@soerendomroes thanks, worked perfectly! Sorry for filling the issue with offtopic: what setting I can use to prevent nodes being crossed by the edges?

**Comment by soerendomroes** [comment]
> @soerendomroes thanks, worked perfectly! Sorry for filling the issue with offtopic: what setting I can use to prevent nodes being crossed by the edges?

Nodes cannot overlap with edges. Maybe open a separate issue for this.

**Comment by soerendomroes** [comment]
@kanekv 
> what setting I can use to prevent nodes being crossed by the edges?

Typically, this is the result of using a rendering without setting a minimum size for a node that reflects that.
You need to set [node size contraints](https://eclipse.dev/elk/reference/options/org-eclipse-elk-nodeSize-constraints.html) to `MINIMUM_SIZE` (and other constraints if you need them) and set a [minimum size](https://eclipse.dev/elk/reference/options/org-eclipse-elk-nodeSize-minimum.html).

**Comment by kanekv** [comment]
@soerendomroes thank you! Let me try that
