### ISSUE TITLE
Bug when turning self loop example into JSON

### ISSUE THREAD

**Issue by saulshanabrook** [eclipse/elk#1070]
**Describe the bug**

I was trying to see how to replicate [the self loop example](https://rtsys.informatik.uni-kiel.de/elklive/examples.html?e=general%2Fspacing%2Flabels) in JSON. However, if I go and convert [it to JSON](https://rtsys.informatik.uni-kiel.de/elklive/conversion.html) the resulting graph is not displayed the same.

ELK DSL:

```
spacing.nodeSelfLoop: 30
spacing.edgeEdge: 10

node n1 {
	portConstraints: FIXED_SIDE
	port p1 { ^port.side: WEST }
	port p2 { ^port.side: EAST }
}

edge n1 -> n1
edge n1 -> n1
edge n1 -> n1

edge n1.p1 -> n1.p2
```

Converted JSON:

```json
{
  "id": "n0",
  "children": [
    {
      "id": "n1",
      "ports": [
        {
          "id": "p1",
          "layoutOptions": {
            "port.side": "WEST"
          }
        },
        {
          "id": "p2",
          "layoutOptions": {
            "port.side": "EAST"
          }
        }
      ],
      "layoutOptions": {
        "portConstraints": "FIXED_SIDE"
      }
    }
  ],
  "layoutOptions": {
    "spacing.edgeEdge": "10.0",
    "spacing.nodeSelfLoop": "30.0"
  },
  "edges": [
    {
      "id": "e0",
      "sources": [
        "n1"
      ],
      "targets": [
        "n1"
      ]
    },
    {
      "id": "e1",
      "sources": [
        "n1"
      ],
      "targets": [
        "n1"
      ]
    },
    {
      "id": "e2",
      "sources": [
        "n1"
      ],
      "targets": [
        "n1"
      ]
    },
    {
      "id": "e3",
      "sources": [
        "p1"
      ],
      "targets": [
        "p2"
      ]
    }
  ]
}
```

**Expected behavior**
This is the ELK DSL output:

![Screenshot 2024-08-23 at 12 34 49 PM](https://github.com/user-attachments/assets/76ffa383-bce3-45d3-800f-d30c30b631d2)

**Screenshots**
This is the output after converting to JSON:

![Screenshot 2024-08-23 at 12 35 18 PM](https://github.com/user-attachments/assets/bd6edbe5-14d2-4f63-b4ba-3eb74b424551)

**ELK Version**
0.9.3

**Additional context**

**Comment by soerendomroes** [comment]
Yes, ELK JSON always needs node sizes specified and this particular viewer does not set a minimum size.
