### ISSUE TITLE
ELK Live is down

### ISSUE THREAD

**Issue by RoddoWasHere** [eclipse/elk#1073]
![image](https://github.com/user-attachments/assets/587b027b-a29f-42c7-b3c5-142ab6b0862c)
 
Please can you provide any updates or alternative links

Thanks

**Comment by Eddykasp** [comment]
We are on it, but I can't give a promise how quickly it will be back up. Alternatively we offer a docker image that you can use yourself [here](https://github.com/kieler/elk-live/pkgs/container/elk-live).

**Comment by RoddoWasHere** [comment]
Thank you kindly
