### ISSUE TITLE
[Question]Is there an open source project that uses C++ to implement a similar ELK Layered algorithm?

### ISSUE THREAD

**Issue by daydayhappychao** [eclipse/elk#1078]
We need to use elk's layered algorithm to do some sorting, but we can't use the java virtual environment, so is it possible for us to use similar functionality in c++?

**Comment by soerendomroes** [comment]
There are probably implementations of the Sugiyama or layered algorithm in C++ but I have not yet tried any, so I cannot give any recommendations.

I am not sure what you mean by "sorting" and hence do not know what of ELK layered is interesting for your context.

If Java is no option, could you use the Javascript library elkjs? If you need something simple, I guess any implementation of the Sugiyama algorithm should be enough and I would rather look at C++ graph drawing libraries.

**Comment by daydayhappychao** [comment]
Thank you for your timely reply (respectful tone)!
My questions and replies are from Google Translate, so some of the words may not be accurate. In fact, I need to use the Layered algorithm in elk, and I need to draw nodes and lines into a graph according to the relationship.
Sugiyama alone cannot cover my needs, because I have some requirements like fixing some nodes in the first or last layer.

I will try to find out if there is a suitable open source project in C++.

If you know any C++ related projects, I would also appreciate your letting me know.

Thank you again for your reply!
