### ISSUE TITLE
while adding a new node by edge by tree structure , Need to have this behaviour.

### ISSUE THREAD

**Issue by Azim-Ahmed** [eclipse/elk#1080]
Here, 
<img width="1039" alt="image" src="https://github.com/user-attachments/assets/a72e2ba5-0322-413b-92b9-c6625d1b8cd0">
I am dragging a node from left sidebar from trigger node.
and this behaviour I am getting.

How can I achieve this behaviour.
<img width="1065" alt="image" src="https://github.com/user-attachments/assets/29ecda1e-40a9-4ff9-8bf5-bc1c7263b920">

**Comment by Eddykasp** [comment]
This does not look like an ELK issue. If it is an ELK issue please recreate it in elklive and link to that so we can look at the actual graph.

**Comment by Azim-Ahmed** [comment]
<img width="1100" alt="image" src="https://github.com/user-attachments/assets/596ff81b-0f0a-4c52-95fb-8cbb3ac81066">
Seems that's my issue.
