### ISSUE TITLE
[Question] Experimental Feature Support for Libavoid 

### ISSUE THREAD

**Issue by maxmrzk** [eclipse/elk#1090]
**Question**
Good afternoon!
We are currently using the ELK infrastucture and libavoid layout algorithm for routing in diagram editors.
Because of the positive experience, I planned on using ELK in another editor aswell. But to fullfill the requirements, I would have to use features ([clusterCrossingPenalty, crossingPenalty, fixedSharedPathPenalty ](https://www.adaptagrams.org/documentation/namespaceAvoid.html#a8a0154ae39129e7737d98e5a83daed19)) which are marked as experimental and not recommended for normal use by the libavoid developers. Therefore I wanted to ask:

1. Given that these features are not removed from libavoid itself, will they continue to stay available in ELK? 
2. Are you in some form of contact with the libavoid developers and have information about wether there are plans on continue developing these features (make them not experimental)?

I just wanted to confirm that it is secure and reliable to invest time in developing on the foundations of these features. Thank you very much in advance !

**Comment by soerendomroes** [comment]
Hi,

1. we have no plans to remove these properties as long as libavoid still provides them.
2. we are not in direct contact with the libavoid developers. The contribution of libavoid to ELK was done by [Typefox](https://www.typefox.io/). So I guess you would have to ask the libavoid developers directly.

Does this answer your questions?

**Comment by maxmrzk** [comment]
Hi, thank you! This does answer the questions.
