### ISSUE TITLE
KIELER LayoutOptions Compatibility

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#11]
To simplify the migration from KIELER, we should have (for a certain time period at least) a translation of the old KIELER layout options into the corresponding ELK options, for instance ``de.cau.cs.kieler.spacing -> org.eclipse.elk.spacing``.

**Comment by uruuru** [comment]
What about adding a ``legacyIds``  field to the meta data language's ``MdProperty`` and automatically registering those ids in the ``ILayoutMetaDataProvider`` implementations?

**Comment by le-cds** [comment]
I actually had the same idea today when waking up. :smile: I think it's a good idea, I'm all for it.

With these data available we could additionally write a program that automatically replaces layout options in a given set of files.
