### ISSUE TITLE
Publish ELK artifacts on Maven Central

### ISSUE THREAD

**Issue by spoenemann** [eclipse/elk#113]
My candidates for publishing:
 * org.eclipse.elk.alg.force
 * org.eclipse.elk.alg.graphviz.dot
 * org.eclipse.elk.alg.graphviz.layouter
 * org.eclipse.elk.alg.layered
 * org.eclipse.elk.alg.mrtree
 * org.eclipse.elk.core
 * org.eclipse.elk.core.meta
 * org.eclipse.elk.graph
 * org.eclipse.elk.graph.text
 * org.eclipse.elk.graph.text.ide

**Comment by uruuru** [comment]
Two questions:
* why core.meta?
* graph.text s.t. one can programmatically load elkt files?

**Comment by le-cds** [comment]
We're already publishing the meta data compiler on our own little piece of webspace because it is used by the automatic build to compile melk files (and by other people's automatic build, for that matter). So we may as well publish it on Maven Central.

**Comment by spoenemann** [comment]
> graph.text s.t. one can programmatically load elkt files?

One possible use case: By publishing graph.text and graph.text.ide we could create a demonstration web page with an editor for ElkGraph files and a graphical view that is updated automatically.

**Comment by uruuru** [comment]
We could also add parts of kiml.formats and replace kwebs ;)

**Comment by spoenemann** [comment]
Some documentation on how to set up the build:
http://central.sonatype.org/pages/apache-maven.html

**Comment by spoenemann** [comment]
Here's the Bugzilla for setting up the authorization:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=512767

**Comment by spoenemann** [comment]
We have snapshots:
https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/elk/

**Comment by le-cds** [comment]
@spoenemann Do you want this to go into 0.2.1 or is 0.3.0 sufficient?

**Comment by spoenemann** [comment]
0.2.1 would be cool, if it's not too much work :-)

**Comment by le-cds** [comment]
I guess we could mostly just transfer your build changes over to the release branch. @uruuru raised concerns as to whether we should wait for 0.3.0 to find more bugs.

**Comment by le-cds** [comment]
> 0.2.1 would be cool, if it's not too much work :-)

Sorry, but the build didn't work out of the box and there are still questions regarding how to publish the build properly. I'll have to move a proper Maven Central release to 0.3.0.
