### ISSUE TITLE
Remove GraphDataUtil?

### ISSUE THREAD

**Issue by spoenemann** [eclipse/elk#116]
`org.eclipse.elk.core.util.GraphDataUtil` seems not to be referenced anywhere. Can we remove it?

**Comment by uruuru** [comment]
It's used in several places of the KIELER pragmatics code.

**Comment by spoenemann** [comment]
Then it seems to be a KLighD specific class and should be moved to the KIELER code base?

**Comment by le-cds** [comment]
I don't see why we shouldn't move it to KIELER.

**Comment by uruuru** [comment]
It's used by kiml.formats plugins as well. Why not provide some utility methods in elk?

**Comment by spoenemann** [comment]
> Why not provide some utility methods in elk?

It's good to provide utility methods, but only those that are useful for
 * the internal implementation of ELK, or
 * users of ELK.

The more code we offer as API, the more users get the impression that ELK is an overly complex thing, so IMO it's good to clean up the API as much as possible.

**Comment by uruuru** [comment]
In general I agree. For the mentioned class there's no common plugin the KIELER plugins depend on where we could move this class. But I think the code isn't too complex to duplicate. 
I'll try to change the code and remove the class.
