### ISSUE TITLE
Layout algorithm resolving broken

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#118]
Passing ``mrtree`` as ``algorithmId`` resolves to the fixed layout in the recursive graph layout engine.

```
protected LayoutAlgorithmData getAlgorithm(final ElkNode layoutNode) {
        String algorithmId = layoutNode.getProperty(CoreOptions.ALGORITHM);
        LayoutAlgorithmData result = LayoutMetaDataService.getInstance().getAlgorithmDataOrDefault(
                algorithmId, getDefaultLayoutAlgorithmID());
   [...]
```

**Comment by uruuru** [comment]
First, I guess ```LayoutMetaDataService#getAlgorithmDataOrDefault(final String algorithmId, final String defaultId)``` should use ```getAlgorithmDataBySuffix(...)``` instead of ```getAlgorithmData(...)```.

Second, shouldn't ```LayoutMetaDataService#getAlgorithmDataOrDefault(final String algorithmId, final String defaultId)``` try the ``defaultId`` again, before selecting the first available layouter?

Third, shouldn't we throw an exception instead of selecting _some_ layouter if even the default layouter is unavailable?

**Comment by le-cds** [comment]
> First, I guess `LayoutMetaDataService#getAlgorithmDataOrDefault(final String algorithmId, final String defaultId)` should use `getAlgorithmDataBySuffix(...)` instead of `getAlgorithmData(...)`.

Yes, it could do so.

> Second, shouldn't `LayoutMetaDataService#getAlgorithmDataOrDefault(final String algorithmId, final String defaultId)` try the `defaultId` again, before selecting the first available layouter?

Definitely, I would consider this a bug in the implementation.

> Third, shouldn't we throw an exception instead of selecting some layouter if even the default layouter is unavailable?

I'm not sure about the exception, but if the default cannot be found, I guess the method would do well to return `null` instead of _some_ layout algorithm. I consider what happens with a `null` algorithm the responsibility of the calling code.

**Comment by uruuru** [comment]
I'm fine with ``null``.

**Comment by le-cds** [comment]
Fixed. I renamed the method to `getAlgorithmDataBySuffixOrDefault(...)` to reflect more closely what it does.
