### ISSUE TITLE
Content assist adds unexpected prefix

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#119]
Consider the following part of an `elkt` file. The layout option keys were completed by content assist. Why is it that ``direction`` is prefixed with ``elk.`` and ``edgeRouting`` is not? I cannot find any difference in their ``melk`` specifications. 
```
edgeRouting: POLYLINE
elk.direction: DOWN
```
While I'm at this subject, I propose that the groups of a layout option should _always_ be added as prefix when content assist is used.

**Comment by spoenemann** [comment]
The shortest suffix is computed that can be resolved via `ElkMetaDataService#getOptionDataBySuffix(String)`. For `edgeRouting` the last segment is already unique, while `direction` is used as last segment by multiple options, so we need one more segment. Isn't that cool? :-D

**Comment by spoenemann** [comment]
> the groups of a layout option should always be added as prefix

LayoutOptionData does not contain any information about groups. We can only propose what is available in the ElkMetaDataService.

**Comment by uruuru** [comment]
IIRC I added the group string a while ago.

**Comment by uruuru** [comment]
ahh, did forget about the ``priority.direction``. One could think about the allowed scope as well, since one applies to parents and one to edges. But I guess that would take it too far. 

We could also improve the ``No layout option with identifier 'direction' can be found.`` error, saying that it is ambiguous instead.

**Comment by le-cds** [comment]
> ahh, did forget about the `priority.direction`. One could think about the allowed scope as well, since one applies to parents and one to edges. But I guess that would take it too far.

I don't think it would necessarily take things too far, but we would have to be careful there. If I always had to add children to a node before getting access to parent layout options, I would be quite frustrated. If we solve these cases properly, however, I think it would be a good feature that would reduce the enormous number of layout options a bit.

> We could also improve the `No layout option with identifier 'direction' can be found.` error, saying that it is ambiguous instead.

Seems sensible to me, provided that there's a way to distinguish absence from ambiguity.

**Comment by spoenemann** [comment]
> the groups of a layout option should always be added as prefix

Note that you can always add group prefixes yourself: e.g. write `nodeS`, hit ctrl + space, and all options in the `nodeSize` group are offered.

> One could think about the allowed scope as well, since one applies to parents and one to edges. But I guess that would take it too far.

Currently I just use `ElkMetaDataService#getOptionDataBySuffix(String)`. If we wanted to consider the scope, it would have to be supported by that method.

> We could also improve the No layout option with identifier 'direction' can be found. error, saying that it is ambiguous instead.

`ElkMetaDataService#getOptionDataBySuffix(String)` just returns null, so we would have to enhance this method to give more information in that case (why is it null?).

**Comment by uruuru** [comment]
> Note that you can always add group prefixes yourself: e.g. write nodeS, hit ctrl + space, and all options in the nodeSize group are offered.

True. The reason why I'm suggestion to add the group as prefix are options such as `spacing.nodeNode` which would simply read `nodeNode` without the group. I claim that this is very confusing to a user.
Technically this should be possible by passing `group+suffix` as proposal and `suffix` as display string, right?

**Comment by spoenemann** [comment]
The responsibility on which suffixes are valid is in ElkMetaDataService, not the proposal provider. A proper solution would be to make sure that suffixes without group are not accepted for options that are contained in a group.

https://github.com/eclipse/elk/blob/master/plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/data/LayoutMetaDataService.java#L241

**Comment by uruuru** [comment]
I would allow the user to type ``nodeNode``, I would just automatically expand it to ``spacing.nodeNode``. I would also allow ``nodeNode`` as long as the user types it by hand and does not use content assist.

**Comment by spoenemann** [comment]
> automatically expand it to spacing.nodeNode

Done.

I also added some fancy prefix matching: if you type `e.s.e`, that will be expanded to `elk.spacing.edge*`  :-D

Anything else?

**Comment by le-cds** [comment]
Do we already match against the names of layout options or only against their ID? Often enough, I have better memory of names than of IDs, so matching against both would be marvelous.

**Comment by uruuru** [comment]
No we don't.

**Comment by uruuru** [comment]
The name of a layout option often contains spaces. I'm not sure if xtext can handle such a case where the first part of a name is likely not a valid token. 

Can xtext do "fuzzy" matching? E.g. suggesting `wrapping` if the user types `rapp`. The latest content assist in eclipse support this feature.

**Comment by le-cds** [comment]
> The name of a layout option often contains spaces. I'm not sure if xtext can handle such a case where the first part of a name is likely not a valid token.

Good point. @spoenemann, can you provide input on that?

**Comment by spoenemann** [comment]
Everything is possible if you put enough love into it ;-)
We just need to decide what is actually useful for that editor. And keep in mind that it will be mostly used by ELK developers, not by ELK users.

**Comment by uruuru** [comment]
If either of the two points, fuzzy and names, can be done without much effort. I would suggest we do it. Otherwise I'm fine with the id matching.

**Comment by le-cds** [comment]
+1 on what @uruuru said.

**Comment by uruuru** [comment]
@spoenemann you have the last word here.

**Comment by spoenemann** [comment]
![screen shot 2017-08-30 at 16 35 10](https://user-images.githubusercontent.com/4067210/29909027-5f9ab4f6-8e24-11e7-9998-f3ab6a7f91ec.png)

Now names of options and algorithms are considered based on `String#contains(String)`.
