### ISSUE TITLE
MelkDocumentationGenerator should consider only bundle members that actually changed

### ISSUE THREAD

**Issue by DAGobertGans** [eclipse/elk#122]
At the moment if a *.melk file is altered, the corresponding MdModel is processed completely. The main problem here is, that if a bundle member is renamed or deleted, the previously related Markdown file is not removed.
It would be nice, if only the documentation affected by the changes was updated.

**Comment by le-cds** [comment]
This is fixed by the fact that the documentation generator is now invoked in the build, not in the IDE.
