### ISSUE TITLE
PortConstraints are not FIXED_ORDER when node placement starts

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#125]
Shouldn't elk layered internally raise the port constraints of every node to fixed order after crossing minimization? I couldn't find any code related to this.

**Comment by le-cds** [comment]
I don't think this has caused problems so far. Each phase knows what it's allowed to do to the ports at most, so if the port constraints indicate more freedom than that it doesn't really make much of a difference. Indeed I think a case could be made that keeping the original port constraints around would allow later phases to know what they would be allowed to do if they wanted to do any fancy post processing.

**Comment by uruuru** [comment]
I guess we are not really following either of the two options at the moment, right? 
I was confused by an old piece of code of mine that throws an exception if the port constraints are less than fixed order during node placement. The code used to work pre-elk but fails with the aforementioned exception.

**Comment by le-cds** [comment]
> I guess we are not really following either of the two options at the moment, right?

Not religiously, as far as I'm aware.

> The code used to work pre-elk but fails with the aforementioned exception.

That's interesting. Has Alan removed code that changed port constraints?

**Comment by uruuru** [comment]
That's what I was thinking but I couldn't find anything suspicious so far. Still, as you pointed out it's hard to be consistent anyway. The greedy switch for instance is allowed to change port orders even if the crossing minimization phase fixed them ...

**Comment by le-cds** [comment]
Upon request by @uruuru, we close this because it's not really a problem.
