### ISSUE TITLE
Layout option entry with null id

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#126]
Specifying an invalid layout option id in an `elkt` file correctly yields an error in within the xtext editor. The corresponding model element (`ElkPropertyToValueMapEntryImpl`) is created with a `null` key. 

This causes some issues in other code where it is assumed that the key is non-null. I'm not sure how we solved this for the old `kgt`. Maybe unknown persistent entries were simply omitted? I'm also not sure how to properly manage it this time.

**Comment by spoenemann** [comment]
We can't omit the whole entry. We should just be careful when handling the models that have been parsed from text and avoid processing models with syntax or validation errors.

I fixed a potential NPE source. Do you have more places in mind where this should be considered?

**Comment by uruuru** [comment]
So far I found the following:
 * `ElkPropertyToValueMapEntryImpl#toString`
 * `LayoutOptionProxy#resolveValue`
 * In klighd's `KlighdLayoutConfigurationStore`

Can one tell from the parsed model if it contains errors?

**Comment by spoenemann** [comment]
Let's reopen if we find more NPE sources.
