### ISSUE TITLE
Port labels of parent nodes are not taken into account

### ISSUE THREAD

**Issue by eNBeWe** [eclipse/elk#127]
Even though the node size constraints are set to include port labels, these are not taken into account on parent nodes.

![portlabels](https://cloud.githubusercontent.com/assets/3796429/22447285/f1506b36-e751-11e6-9d2b-de6831836c99.png)

	knode P1 {
		properties:
		org.eclipse.elk.nodeSize.constraints=PORT_LABELS
		
		knode N1 {
			size: width=20 height=20
		}
		
		kport P1
		kport P2
		kport P3
		kport P4
		kport P5
		kport P6
	}

**Comment by le-cds** [comment]
I have verified the bug even with our current version. Here's the .elkt file:

```
```
