### ISSUE TITLE
Provide documentation ZIP file with each release

### ISSUE THREAD

**Issue by le-cds** [eclipse/elk#129]
We need a way to provide a ZIP file with each release that contains the documentation site relevant to that release. I have contacted GitHub support to find out whether or not they provide access to the generated site. If not, we will have to setup a process to compile a version of the site ourselves.

**Comment by spoenemann** [comment]
For Xtext we have a Hudson job that generates the website from the Markdown sources using Jekyll:
https://hudson.eclipse.org/xtext/job/website-deploy/

**Comment by uruuru** [comment]
Just to be aware of it: @DAGobertGans mentioned that sometimes the page generated by github looks slightly different than what manually executing Jekyll generated.

**Comment by le-cds** [comment]
> For Xtext we have a Hudson job that generates the website from the Markdown sources using Jekyll

Excellent, that's pretty much exactly what I was hoping for.

> @DAGobertGans mentioned that sometimes the page generated by github looks slightly different than what manually executing Jekyll generated.

I see. But I guess as long as the information are there, that should be alright.

**Comment by spoenemann** [comment]
I think it wasn't so easy to get Jekyll to run on Hudson. Maybe @dhuebner can give some hints on that. See also the [Xtext website README](https://github.com/eclipse/xtext/blob/website-master/xtext-website/README.md).

**Comment by dhuebner** [comment]
@spoenemann Install jekyll and call `jekyll build`

**Comment by le-cds** [comment]
That's the usual procedure. But you're not using the Eclipse build infrastructure, are you? I'll have to find out whether Jekyll is (or can be made) available there.

**Comment by dhuebner** [comment]
@le-cds You need to ask some of eclipse admins to pre-install it in your HIPP. Or you can create and run a script that installs jekyll on some writable hudson location. 
If recall it right I somehow managed to install rvm on our HIPP and did the following:

```
export PATH=$PATH:/opt/public/common/node-latest/bin/

rvm autolibs disable
rvm reinstall ruby-2.2.0
rvm use 2.2.0

~/.rvm/rubies/ruby-2.2.0/bin/gem install jekyll-markdown-block

```

**Comment by le-cds** [comment]
The zipped nightly documentation site is now built and [available for download](http://build.eclipse.org/modeling/elk/updates/nightly/elk-nightly-docs.zip).
