### ISSUE TITLE
Limit documentation generator to ELK projects

### ISSUE THREAD

**Issue by le-cds** [eclipse/elk#130]
The documentation generator currently generates documentation files for all melk files it finds in the workspace. It should limit itself to melk files in ELK projects.

**Comment by uruuru** [comment]
Maybe rather the possibility to place the documentation somewhere else? It makes sense to use the melk files to document third party algorithms as well.

**Comment by le-cds** [comment]
For the long term, that would be a nice feature. For the short term, I would simply disable it. If I remember correctly, setting up the proper path is already a PITA, so...

**Comment by le-cds** [comment]
Documentation generation is now disabled for non-ELK projects. I'll open another ticket for allowing other projects to generate documentation.
