### ISSUE TITLE
Package org.eclipse.elk.alg.layered.intermediate.wrapping not accessible

### ISSUE THREAD

**Issue by a-sr** [eclipse/elk#135]
The `org.eclipse.elk.alg.layered.intermediate.wrapping` package is not listed in the exported packages of the Layered plugin.
Hence `LayeredOptions.WRAPPING_STRATEGY` cannot be set because of access restrictions.
Other enumerations required for layout options seem to be placed in the properties package. Could that be done with the `WrappingStrategy` enumeration as well?

**Comment by uruuru** [comment]
I'm not a fan of placing the enumerations in an _unrelated_ package. Apart from that we should get rid of _properties_ and call it _options_.

**Comment by a-sr** [comment]
Ok, place it where you want but export the package please.

**Comment by uruuru** [comment]
Fixed. 

The more I think about the enumerations, the more I tend to agree that it's a good idea to have them in the same package as the `LayeredOptions` class. @le-cds should we make it a convention and move all other enumerations (that are values of layout options) as well?

**Comment by le-cds** [comment]
The way I see it, placing enumerations in the `properties` packages makes layout options easier to use for clients. Placing them where they are used by the algorithm makes it easier for the algorithm's developers. It also requires internal packages to be exported, but that argument is void since we do that anyway to allow for unit tests. All in all, I would favor ease of use for clients, so let's do that, yes.

**Comment by spoenemann** [comment]
> since we do that anyway to allow for unit tests.

I think we should either
- mark the algorithm packages as internal, or
- move the test code into a separate source folder of the same project (this is the usual approach for Java projects that are not Eclipse plugins).

**Comment by le-cds** [comment]
> move the test code into a separate source folder of the same project (this is the usual approach for Java projects that are not Eclipse plugins).

We are currently working on a test framework, so doing it that way might introduce additional dependencies that we don't want.

By the way, wouldn't that also require our plug-ins to include dependencies to JUnit? That's something we wouldn't want to have either. So far, I thought that was one of the main reasons for Eclipse projects to _not_ include their tests in a separate source folder of the same plug-in.

**Comment by le-cds** [comment]
By the way, the KIELER Semantics people need the property for their release, so I will probably add a commit for 0.2.1 that only moves the enumeration in question, but no others since service releases are not supposed to break compatibility.

**Comment by spoenemann** [comment]
> > move the test code into a separate source folder of the same project (this is the usual approach for Java projects that are not Eclipse plugins).

> We are currently working on a test framework, so doing it that way might introduce additional dependencies that we don't want.
> By the way, wouldn't that also require our plug-ins to include dependencies to JUnit? That's something we wouldn't want to have either. So far, I thought that was one of the main reasons for Eclipse projects to _not_ include their tests in a separate source folder of the same plug-in.

These problems are only present in the Eclipse world, where there is a single classpath per project. In standard Java projects, e.g. built with Maven (without Tycho) or Gradle, you can have separate dependencies for production code and for test code. However, changing the algorithm builds from Tycho to plain Maven would introduce a lot of complexity to the build, so I don't think that would make sense at the moment.
