### ISSUE TITLE
Rename 'properties' package to 'options'

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#137]
The `LayeredOptions` class is currently located in a package called `properties`. To clarify that it is concerned with layout options the package should be renamed to `options`.

Additionally, move all enumerations that are used for layout options to the `options` package. The rationale for this is better visibility for users.

**Comment by uruuru** [comment]
What about the `*Strategy` enums of the five phases? Should they stay in their sub-packages?

**Comment by spoenemann** [comment]
Not if we decide to mark the subpackages as internal.

**Comment by eNBeWe** [comment]
If there had been some discussion about this, I would have voted against this change. 
a) It unnecessary breaks stuff (again)
b) There is a difference between **Options* and *Properties*. Namely, *LayoutOptions* are a (mathematical) subset of *Properties*. For the same reason we are still calling it `MapPropertyHolder` and not `MapOptionHolder`

**Comment by uruuru** [comment]
Regarding b), we decided that _properties_ are the technical means to attach information to an element. _Layout options_ are used to configure the layout and are exposed to the user. As such everything that falls in the hands of a user should be named layout option. The same is true for the package. `elk.core` has its options in the `options` package. 

Regarding a), we are still in the process of cleaning up stuff and unifying our terminology. Naturally, that breaks things.

**Comment by le-cds** [comment]
In a small meeting, we decided to close the ticket once all internal packages have been marked internal. For ELK Layered, all packages except for the root package, graph, and options would be internal.

**Comment by uruuru** [comment]
I additionally left `networksimplex` visible. It's fine to use it from somewhere else.
