### ISSUE TITLE
Make wrapping strategies available

### ISSUE THREAD

**Issue by le-cds** [eclipse/elk#139]
This ticket tracks the original intent of #135 to be fixed in the next service release.

**Comment by uruuru** [comment]
I fixed it with the following commit 614316d3ad85592272972093cf75054b00c2a7f8. Sadly I forgot to reference the issue.

**Comment by le-cds** [comment]
Excellent, then I'll simply cherry-pick that commit to the 0.2.1 release branch (once one exists).

**Comment by le-cds** [comment]
Actually, the feature exported here is not currently part of 0.2.1 anyway. In fact, its ticket is set to release 0.3.0: #123. Do we want to cherry-pick the #123 code to 0.2.1 as well?

**Comment by le-cds** [comment]
No, we don't.
