### ISSUE TITLE
Orthogonal edge router should start new slots if edge spacing is too small

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#143]
In the screenshot below, the two vertical edge segments come closer than the specified edge-edge spacing. The orthogonal edge router should properly regard this spacing when computing the required routing slots. 

![smalledgespacing](https://cloud.githubusercontent.com/assets/7552459/23205761/4459a400-f8eb-11e6-8aa9-7373c217990b.png)

**Comment by le-cds** [comment]
We would have to decide which spacing value applies here. Edge-edge spacing might be too large.

**Comment by uruuru** [comment]
This is something that can be investigated together with #318.
