### ISSUE TITLE
Unconnected north ports collide with separateConnectedComponents set to false

### ISSUE THREAD

**Issue by eNBeWe** [eclipse/elk#148]
If `separateConnectedComponents` are set to false, unconnected north ports are placed on top of each other.

![portoverlap](https://cloud.githubusercontent.com/assets/3796429/23303750/2ba7fdd8-fa96-11e6-8b80-3e6b999839bd.png)

```
node N1 {
	portConstraints: FIXED_SIDE
	separateConnectedComponents: false
	
	port P1 {
		^port.side: NORTH
	}

	port P2 {
		^port.side: NORTH
	}
	
	port P3 {
		^port.side: EAST
	}
	
	node N2
	edge N2->N1.P3
}
```

**Comment by le-cds** [comment]
Fixed by the new port placement code.
