### ISSUE TITLE
Add upper / lower bounds to options and implement validation of input graphs

### ISSUE THREAD

**Issue by spoenemann** [eclipse/elk#15]
The default behavior should be to validate configured layout option values against their upper and lower bounds (and possibly also validate the graph structure) before any layout engine is executed. If an error is found, the process is canceled. A new global option should be added in order to disable validation. The Layout View should show error markers at entries that do not match the bounds.

**Comment by uruuru** [comment]
I added the code to specify the bounds. The validation has yet to be implemented.

**Comment by spoenemann** [comment]
The validator could be implemented as an `IGraphElementVisitor`. I'll give it a try.

**Comment by spoenemann** [comment]
Things left to do:
 * Handling of exclusive bounds (see below)
 * Write lower / upper bounds into the elkm files
 * Add error markers to layout view entries that violate the bounds

How should we handle exclusive bounds such as the lower bound 0 for Aspect Ratio? One idea would be to introduce a special Comparable that returns 1 when the values are equal (-1 for upper bounds). This solution would not require any additional API in IProperty and LayoutOptionData.

**Comment by le-cds** [comment]
Miro, your recent changes for me cause enum set options to stop working. Take the following layout option declaration in `Core.elkm`:

```
option constraints: EnumSet<SizeConstraint> { ... }
```

Expected result:

```java
    registry.register(new LayoutOptionData(
        // ...
        SizeConstraint.class,     // Layout option class type
        // ...
    ));
```

Produced result:

```java
    registry.register(new LayoutOptionData(
        // ...
        EnumSet<SizeOptions>.class,     // Layout option class type
        // ...
    ));
```

**Comment by spoenemann** [comment]
Last thing to discuss for this issue: Should we generalize the whole concept so we can associate a validator function with a layout option instead of upper and lower bounds? That would enable to validate options that don't have numbers as values, but something different. The bounds would then be a special case.

**Comment by le-cds** [comment]
Just to repeat here what I said in #38: I think it's a good idea to provide more general validation.

**Comment by spoenemann** [comment]
Ok. Maybe we should do this after the first release so it's not delayed too long (though we would have to change the API then).

**Comment by le-cds** [comment]
Agreed. We will change the API in the next release anyway because of the new graph structure. We're still an incubating project, after all... ;)

**Comment by spoenemann** [comment]
After rethinking this I'm not sure we really need a generalization of the bounds. I rather believe that most inconsistencies of the layout configuration can be found only when looking at all configured options of an element instead of just a single option. That could be solved by introducing algorithm-specific subclasses of LayoutOptionValidator.

**Comment by le-cds** [comment]
While I believe that an algorithm-specific validator would make more sense, I'm pretty sure we won't be able to maintain one. Especially keeping it up-to-date with changes in how the algorithm can be configured will be a major challenge. Finding out if the validator is out of date or not seems very difficult indeed.

**Comment by spoenemann** [comment]
Then let's keep the idea of algorithm-specific validators at the back of our minds and close this issue. Or do you see strong benefits in generalized validations for single options? The only option I could think of was `bendPoints`, where the vector chain could be validated to have at least two points. But that's a rather unusual option.

**Comment by le-cds** [comment]
Agreed.
