### ISSUE TITLE
Move 'ILayoutPhase', 'ILayoutProcessor', etc to a common place

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#151]
We have multiple `ILayoutPhase` and `ILayoutProcessor` interfaces for different layout algorithms. One can argue that this is a reasonable concept that can be used by most layout algorithms. I suggest to move the interfaces to a package `elk.core.alg` in the `elk.core` plugin. Any other opinions?

* `ILayoutPhase`
* `ILayoutProcessor`
* `IGraphTransformer`

Not necessarily:
* `layered.ILayoutPhaseFactory`

**Comment by le-cds** [comment]
Moving `ILayoutPhase` would require moving `IntermediateProcessingConfiguration` as well. That class, however, is customized for each algorithm to make it as easy as possible to set up a processing configuration. For ELK Layered, that would for example mean getting rid of the `Slot` enumeration which, in addition to making things easy, also makes it impossible to specify a processing slot that does not exist (verifiable at compile time).

If there's a way to move all those guys without sacrificing usability, I guess I'm indifferent.

**Comment by uruuru** [comment]
We could move the `Slot` enum as well and provide methods for, for instance, _up to_ 10 slots. I agree with the point regarding compile time verification. 
I would prefer this over having the same interfaces (and intermediate configuration code) for more than four layout algorithms though.

**Comment by le-cds** [comment]
I'm really not sure I like this concept. I'll think about something that will allow us to use custom enumerations with proper enumeration constant names (which, it turns out, could actually be more descriptive in the enumerations we currently use) while still factoring out the rest of the code.

**Comment by le-cds** [comment]
The new classes are now available in 'org.eclipse.elk.core.alg`. I'll update ELK Layered to use them as soon as possible.
