### ISSUE TITLE
Remove Xtext Dependency from Core Feature

### ISSUE THREAD

**Issue by SuperOok** [eclipse/elk#152]
The Feature org.eclipse.elk.feature seems to be the only "core" feature that gives smallest subset in order to allow to implement own layout algorithms (i.e. elk.core and elk.graph).

This feature, however, bundles the org.eclipse.elk.alg.layered algorithm. This has a dependency to 
org.eclipse.xtext.xbase.lib;bundle-version="2.10.0".

The implication is that you get this Xtext-Dependency if you want to implement your own layout algorithm.

Please remove the dependency or create an even smaller "ELK-Core" feature that creates a minimal set of dependencies.

**Comment by uruuru** [comment]
The code itself does not require xbase. I think the dependency is somewhat required such that the melk generator runs properly, see #28. However, I thought we solved it by adding `additional.bundles = org.eclipse.xtext.xbase.lib` to the `build.properties` file.

The explicit dependency was added by @le-cds in 299029344d96bc0a610720d8e17d62f552b899cc. Maybe he can share his motives :).

**Comment by spoenemann** [comment]
Just to clarify: the bundle `org.eclipse.xtext.xbase.lib` is very slim and has no dependencies except Guava, which is already a dependency of ELK anyway. IMO using this bundle should not hurt anyone.

**Comment by le-cds** [comment]
> The explicit dependency was added by @le-cds in 2990293. Maybe he can share his motives :).

IIRC, my motives were that the nightly build doesn't support additional bundles, which thus caused the build to fail.

**Comment by uruuru** [comment]
Shouldn't​ core fail as well in that case?

**Comment by le-cds** [comment]
Not if it doesn't use any feature that needs Xbase lib, such as negative default values. Which ELK Layered does use.

**Comment by SuperOok** [comment]
Not sure if I understand whether this is really required or not... the explicit version number in the requirement makes it even worse.

Back to the original idea: would it be possible to create a core-feature that does not bundle any layout algorithm?

**Comment by uruuru** [comment]
Given that the number of ELK layouters is rising, maybe it's time to have a _core_ feature and an _elk layouters_ feature.

**Comment by le-cds** [comment]
> maybe it's time to have a core feature and an elk layouters feature.

So be it!
