### ISSUE TITLE
LayoutConfigurator#findClassOptions() sometimes 'shadows' configured options

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#153]
Say a layout configurator `lc` is configured as follows:
```
lc.configure(ElkGraphElement.class).setProperty(A, x);
lc.configure(ElkNode.class).setProperty(B, y);
```

The way the `LayoutConfigurator#findClassOptions()` method is currently implemented results in an `ElkNode` being configured with option `B` but not with option `A`.

**Comment by spoenemann** [comment]
> core: fix shadowing of layout options in layout configurator #153

@uruuru can this be closed now?
