### ISSUE TITLE
ElkEdge: Add utility methods to set source and target

### ISSUE THREAD

**Issue by spoenemann** [eclipse/elk#158]
We could define `setSource(ElkConnectableShape)` and `setTarget(ElkConnectableShape)` on `ElkEdge`:

 1. Clear the list of sources/targets.
 2. If the given shape is not null, add it to the list of sources/targets.

**Comment by uruuru** [comment]
I believe @le-cds's decision was to implement such methods in `ElkGraphUtil`.

**Comment by spoenemann** [comment]
That's fine for me.

**Comment by le-cds** [comment]
It's fine for you to use the creation methods in `ElkGraphUtil`, or it's fine for you if such methods would be added to `ElkGraphUtil`? Those methods could get a boolean parameter that says whether or not the edge containment should automatically be updated as well.

**Comment by spoenemann** [comment]
After revisiting the already available utility methods, I think we can close this.
