### ISSUE TITLE
Inside port labels overlap with edges

### ISSUE THREAD

**Issue by eNBeWe** [eclipse/elk#167]
Inside port labels are misplaced and overlap with the edge originating or ending in the corresponding port. This is the case with external connections as well as with inside self loops.

This example demonstrates the issue in the current ELK master. The same issue is present in ELK 0.1.1.

```
node N1 {
	org.eclipse.elk.insideSelfLoops.activate: true
	org.eclipse.elk.portConstraints: FIXED_SIDE
	org.eclipse.elk.portLabels.placement: INSIDE
	org.eclipse.elk.nodeLabels.placement: "[H_CENTER V_BOTTOM INSIDE]"
		
	port P1 {
		org.eclipse.elk.^port.side: WEST
	}
	
	port P2 {
		org.eclipse.elk.^port.side: EAST
	}
}

edge N1.P1 -> N1.P2 {
	org.eclipse.elk.insideSelfLoops.yo: true
}

node N2 {
	org.eclipse.elk.portConstraints: FIXED_SIDE
	org.eclipse.elk.portLabels.placement: INSIDE
	org.eclipse.elk.nodeLabels.placement: "[H_CENTER V_BOTTOM INSIDE]"
		
	port P1 {
		org.eclipse.elk.^port.side: WEST
	}
	
	port P2 {
		org.eclipse.elk.^port.side: EAST
	}
	
	node N3
	
	edge N2.P1 -> N3
	edge N3 -> N2.P2
}
```

![insideportlabel](https://cloud.githubusercontent.com/assets/3796429/24609042/70181ed4-1879-11e7-9576-efbbc34ee068.png)

**Comment by le-cds** [comment]
There's some improvement with the new code introduced in #174:

![screen shot 2017-04-23 at 13 28 19](https://cloud.githubusercontent.com/assets/7465584/25313133/ce351490-2828-11e7-92f5-8c7569e335bc.png)

I'm using this ticket to continue to track this issue. The new code has to switch to compound node mode if inside self loops are enabled for a node.
