### ISSUE TITLE
eOpposite of references not set correctly after loading elkt

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#170]
Loading an `elkt` file doesn't set all references. For instance, `ElkConnectableShape#getOutgoingEdges()` isn't properly initialized by it's eOpposite `ElkEdge#getSources()`. IIRC xtext has issues with eOpposites, and we had the same issue with the KGraph once: [bug 452517](https://bugs.eclipse.org/bugs/show_bug.cgi?id=452517).

Adding the following pice of code  to the `ElkGraphRuntimeModule` resolves the issue.
```
    override bindILinker() {
        MyLinker
    }
    static class MyLinker extends Linker {
        override protected isClearAllReferencesRequired(Resource resource) {
            false
        }
    }
```

@spoenemann is this the way we want to solve the issue? In my opinion it's not really an option to refrain from using eOpposites.

**Comment by spoenemann** [comment]
Could you try the following instead?
```
    static class MyLinker extends Linker {
        override protected clearReference(EObject obj, EReference ref) {
            if (ref.EOpposite === null)
                super.clearReference(obj, ref)
        }
    }
```

**Comment by uruuru** [comment]
Seems to work, thanks.
