### ISSUE TITLE
Edge labels not placed properly in top-down layout

### ISSUE THREAD

**Issue by le-cds** [eclipse/elk#173]
In left-to-right layouts, edge labels are properly placed below one another. For vertical layouts, ELK Layered internally needs to place them along a horizontal line so that they end up being placed below one another in the final layout.

For example, in the following layout, "start = '1'" and "result = 5" are separate labels and should be placed below one another in the computed layout:

![state](https://cloud.githubusercontent.com/assets/7465584/24965906/b3ba1a24-1fa5-11e7-8e40-d56730e12738.png)

**Comment by le-cds** [comment]
Cannot reproduce, but was probably fixed with #199.

**Comment by tivervac** [comment]
Bug has indeed been fixed, thanks @le-cds!
