### ISSUE TITLE
JSON transformation to ElkNode failed with transformPrimitiveEdge error

### ISSUE THREAD

**Issue by idengrenme** [eclipse/elk#175]
Transforming this graph works:
```
        String inputGraph_WORKS =
                "{  id: \"root\", properties: { direction: 'LEFT' },    "
                + "children: [{      id: \"n1\",       labels: [ { text: \"n1\" } ],    "
                + " width: 100,       height: 100   "
                + " }] }";
```

OUTPUT = 
**TRANSFORMATION DATA: de.cau.cs.kieler.formats.TransformationData@5f184fc6
Execution time: 192.87050500000004 ms
n1: x = 12.0, y = 12.0
[{
  "children": [{
    "height": 100,
    "id": "n1",
    "labels": [{
      "height": 0,
      "text": "n1",
      "width": 0,
      "x": 0,
      "y": 0
    }],
    "width": 100,
    "x": 12,
    "y": 12
  }],
  "height": 124,
  "id": "root",
  "properties": {"direction": "LEFT"},
  "width": 124,
  "x": 0,
  "y": 0
}]**

Transforming this graph does not:
```
        String inputGraph_ERROR =
                "{  id: \"root\", properties: { direction: 'LEFT' },    "
                + "children: [{      id: \"n1\",       labels: [ { text: \"n1\" } ],    "
                + " width: 100,       height: 100   },{       id: \"n2\",       "
                + "labels: [ { text: \"n2\" } ],     width: 100,       height: 50,    "
                + "   ports: [{         id: \"n2_p1\",            width: 10,     "
                + "       height: 10        }],       children: [{              id: \"n3\",    "
                + "       labels: [ { text: \"n3\" } ],         width: 20,            height: 20   "
                + "     },{           id: \"n4\",           labels: [ { text: \"n4\" } ],     "
                + "    width: 20,            height: 20}       ], "
                + "       edges: [{         id: \"e4\", "
                + "          source: \"n3\",           target: \"n4\"        }]    },{"
                + "       id: \"n5\",       labels: [ { text: \"n5\" } ],     width: 100,"
                + "       height: 50    }],   edges: [{     id: \"e1\", "
                + "      labels: [ { text: \"e1\" } ],     source: \"n1\", "
                + "      target: \"n2\",       targetPort: \"n2_p1\" },{   "
                + "    id: \"e2\",       labels: [ { text: \"e2\" } ],   "
                + "  source: \"n1\",       target: \"n5\"    }]}";
```
Throws error:

**Exception in thread "main" java.lang.NullPointerException
	at de.cau.cs.kieler.formats.json.JsonImporter.transformPrimitiveEdge(JsonImporter.java:206)
	at de.cau.cs.kieler.formats.json.JsonImporter.access$2(JsonImporter.java:197)
	at de.cau.cs.kieler.formats.json.JsonImporter$2.apply(JsonImporter.java:169)
	at de.cau.cs.kieler.formats.json.JsonImporter$2.apply(JsonImporter.java:1)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at de.cau.cs.kieler.formats.json.JsonImporter.transformEdges(JsonImporter.java:176)
	at de.cau.cs.kieler.formats.json.JsonImporter.transform(JsonImporter.java:100)
	at my.elkagent.StandaloneELKEngine.performLayout(StandaloneELKEngine.java:38)
	at my.elkagent.StandaloneELKEngine.main(StandaloneELKEngine.java:150)**

Eclipse Neon project attached.
[KAgentELK.zip](https://github.com/eclipse/elk/files/931340/KAgentELK.zip)

Is there a workaround?

**Comment by uruuru** [comment]
Thanks for reporting this. Since it's an KIELER issue, I filed a bug over there: [KIPRA-1848](https://rtsys.informatik.uni-kiel.de/jira/browse/KIPRA-1848).
