### ISSUE TITLE
Modify code that cannot be compiled by GWT

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#179]
We plan to compile parts of the code to Javascript using GWT and create a standalone Javascript layout library (just like [klayjs](https://github.com/OpenKieler/klayjs) for KIELER). 

Not everything can be compiled by GWT, for instance, Java's reflection API is not supported.

This ticket should be referenced by any commit that modifies code with the goal to make something compatible with GWT.

**Comment by aranega** [comment]
That's great to see that the full ELK code will be GWT compatible. Do you plan to publish only the js compiled version or also a full GWT configured version (with `.gwt.xml`)?

In the current code state it seems that only the `.gwt.xml` are missing, as well as a special maven rule to "filter" the `elkjs-exclude-*` tags, do I missed something? (beside re-coding some parts that make a huge use of reflection)

**Comment by uruuru** [comment]
Currently the plan is to have a separate repository with a gradle script (containing the filter you mention) and the additional things required by GWT to create the js file (custom linker, some emulation code, etc). 

Apart from that the title of this ticket might be missleading. It's not the goal, if at all possible, to make everything compilable. We aim at the core plugin and the layout algorithms. As you say there's quite some code that uses reflection ...

We could think about bundling gwt plugins alongside a `.gwt.xml` with the filtered code, however, if people are interested in it.

**Comment by aranega** [comment]
I'm fully aware that the goal is not to have the whole ELK compilable, I was only refering to `core`, `graph` and some layout projects (beside the ones that use `graphviz`). All the eclipse plugin system related features are out of the picture.

From what I quicly saw, all the dependencies (EMF and GWAVA) are GWT compatible. There is perhaps some guava classes that are not GWT friendly, some persistence classes that need to be marked as `@GwtIncompatible` in the `core` plugin (`emf-xmi` related), as well as some emul classes to code/adapt.

I'm greatly interested in a GWT compatible version only. As we use GWT in the client side, the JS version  is not very interesting for us as it will be derived from the GWT version and it would result in the development of a jsinteropt bridge to connect to the JS version. 

I will fork the project and see if I can make something.

**Comment by uruuru** [comment]
If you have a week or two I might be able to publish a first version of the build script to compile everything to js. I guess it would include most of the work that has to be done to create the gwt compatible jars. 

For the `melk` files (specifying layout options etc) we use xtext. These files have to be compiled to java by the build script. Also there's an issue with an EMF feature that is not supported by the emf-gwt version published on Maven central. @le-cds is about to resolve this though.

**Comment by aranega** [comment]
I saw that the compilation requires some special threatments. Regarding EMF-GWT, this is not an issue, we have our updated version: https://github.com/Axellience/emfgwt, aligned on EMF 2.12. 

So far, I managed to compile everything by changing the EMF dependency to our EMF-GWT one, marking some class as `GwtIncompatible` and upgrading Guava as GWT-2.8 imposes Guava 21 at least. The EMF dependency replacement seems to work (I mean, it compiles fine), I just had to add the standard EMF dependency as `xtext` plugin dependency and exclude EMF-GWT dependency from the `elk.graph` plugin dependency. 

Actually, I quickly need to evaluate the potentiel work and impact on our architecture, that's why I experiment with the required modification (even if it's dirty atm). I progress slowly, but the code has a lot of project dependency and I not familiar with it or with the build process.

**Comment by le-cds** [comment]
> we have our updated version: https://github.com/Axellience/emfgwt, aligned on EMF 2.12.
To me, that seems to be very valuable information. @uruuru ?

**Comment by uruuru** [comment]
The relevant piece of code requires
`org.eclipse.emf.ecore.util.EContentsEList.FeatureFilter`, which is not
included in your version if I saw it correctly. It was introduced in emf
2.10 after the initial emf-gwt fork.

**Comment by aranega** [comment]
You're right! I think we missed some package during our EMF upgrade. As all our tests passed, we definitely let this on the side. I'm gonna check those packages and see if I can port this.

**Comment by aranega** [comment]
At first sight, it does not sound too difficult. I can try to patch our version to propose a better "updated" version. Could this interest you?
However, in our implementation, we do not rely on the GWT-RCP stuffs, meaning that annotations like `@GwtTransient` are not important for us at all, could it be an issue for you?

**Comment by uruuru** [comment]
At this point we don't use any gwt annotations. I guess we could give it a try to use your version.

**Comment by aranega** [comment]
I finished the "raw"-merge between our current version and the official repo. I'm going to check if everything went smoothly (of course, it won't work on the first try). I keep you in touch.

**Comment by aranega** [comment]
Hey, just to give you information about the upgrade process, the branch I am working on is here:
https://github.com/Axellience/emfgwt/tree/feature/check-2.12

At the moment, I only have a compilation issue when I use `-strict`, it does not ignore 3 classes that are placed in a non 'client' package, I don't know why yet. Beside that, the `FeatureFilter` is here. I'm going to test if everything is fine.

**Comment by uruuru** [comment]
Seems to work for me. At least the js compiles successfully. Do you plan to publish the artifacts on maven central? I saw that your plugins already contain pom files, probably only for building though. 

There are still some points that have to be addressed from the functional perspective:

Layout configuration uses reflections:
 - `Property#getDefault - clone
- `LayoutOptionData` - several things
- `LayoutConfigurator` - isAssignableFrom

`modCnt` in `ArrayList` not incremented
 - `NNode`'s `ChangeAwareArrayList` makes use of the `modCnt` field.

**Comment by aranega** [comment]
Last friday, I fixed the remaining issues with the `strict` flag activated, so indeed, everything compiles. However, I'm not sure everything is working fine at te moment. Before publishing it, I need to test first our application in depth to be sure that the upgrade didn't break anything, and also to check with the team.

Regarding the still problematic points here is some thoughts:

* `clone` invokation: modify and make use of the `Reflect` helper from EMF (even it implies that registration must done manually) or simply use a cast + `.clone()`. I'm aware that could break things for non public defined `clone` method, but at the moment, this is the only acceptable solutions I can come up with.
* `isAssignableFrom`: I put a dirty implementation in `EcoreUtil` (at the moment), the algorithm is not great as GWT cannot access implemented `Interface` by reflexion, but it is a first step.
* `newInstance`: use the `Reflect` helper from EMF?

Actually, the big question is: how close from the original source code would you want to be? As the ELK GWT and JS version would be produced from a fork, we could derived a little bit from the original implementation with easily mergeable modifications.

Regarding `ChangeAwareArrayList` isntances, they are used for a list union-caching system only, so, two solutions here:

1. we consider that the caching system is not important and could be ommited, which would have an impact on performances
1. we make `ChangeAwareArrayList` inherits from `BasicEList` instead which also provides a `modCount`. This field is not in our implementation as it is used only to have a thread-safe list implementation (if I understood correctly), but I can add it back. This solution sounds better to me, but I don't know if ìnheriting from `BasicEList` is an option or not.

**Comment by uruuru** [comment]
Thanks for your ideas. We already talked about the problem internally and may have other solutions but I'll consider your suggestions. 

> Actually, the big question is: how close from the original source code would you want to be?

At the moment we still plan to use the master for the JS version, which so far seems manageable to me. I'm not sure if it's possible for the gwt compatible version.

**Comment by le-cds** [comment]
> This field is not in our implementation as it is used only to have a thread-safe list implementation (if I understood correctly)

It's not only for thread-safety, but also for guarding against situations where code uses an iterator object to iterate over the elements in a list and manages to change the list while doing so. :)

**Comment by aranega** [comment]
Right! I totally forgot about those, shame on me! I will put the `modcount` back on in the implementation.

**Comment by uruuru** [comment]
With the latest changes the relevant parts (for the js lib) of the master branch can be compiled with gwt. Let me know if you have any further problems.

**Comment by aranega** [comment]
That's really a great news! Thanks a lot for the effort and the rewriting. 

Regarding the EMF-GWT version, I added back the `modCount`, everything compiles fine, but I encountered a regression in our application. Don't know yet if it comes from the EMF upgrade...

**Comment by uruuru** [comment]
@aranega I just realized that this [commit](https://github.com/Axellience/emfgwt/commit/42cf74add4f376b2a60a1015822f4ea7ef979dcd) is problematic for us. I assume the original implementation would be fine for us. Do you register a helper for every type you potentially use?

**Comment by aranega** [comment]
@uruuru I vaguely remember about this commit (and when it was done), but I don't remember exactly its point. If I recall correctly, it had something to do some issues with `EList` and some EMF `AddCommand` not playing correctly. Regarding the helper registration, we generate the code for the metamodel using the GWT target from the `.genmodel`, which automatically registers the objects helpers in the `*PackageImpl`.

Anyway, I will look in depth about this commit and try to find which was the problematic scenario.

**Comment by uruuru** [comment]
Maybe you can return `true` there if the type is not registered. For you that shouldn't change the behavior.

**Comment by aranega** [comment]
Indeed, I added a quick (and dirty) flag `STRICT` which can be set to `true` in order to keep an exception if the objet is not registered. By default, it is set to `false`, so you should have the previous behavior enabled by default.

**Comment by uruuru** [comment]
I'll close this issue for now. However, we should still refer to it when we change parts of the code to make it compilable by GWT. 

@aranega please let me know when your changes are on the master and if it's possible for you to publish your version to maven central.

**Comment by aranega** [comment]
@uruuru Sorry, I had some urgent issues to deal with, I let the emf-gwt upgrade on the side. I pushed the updated version in our `master` branch (2.12.4) and we will try to release a version on maven central very soon, but we need to check first if we have the right to let 'emf' or not as part of the name and how we will name the artifact.

**Comment by uruuru** [comment]
@aranega there's no rush. But nice to head that you are planning maven central (if it's possible). 
In case you didn't know: there's an [old emf-gwt](https://search.maven.org/#artifactdetails%7Corg.eclipselabs%7Cemf-gwt%7C2.9.0%7Cpom) version published on maven central that dates back to 2014.

**Comment by aranega** [comment]
@uruuru hey, sorry about the very late answer. With holidays running in, and a lot of discussion, we're ready to make our emf-gwt updated version part of maven central.
However, we are forced to rename the `groupId` for technical reasons from `org.eclipse.emf.gwt` to `com.genmymodel.emf.gwt`. Beside that, package names remains the same. Could this be an issue on your side?

**Comment by uruuru** [comment]
Shouldn't be an issue.

**Comment by aranega** [comment]
Great! I'm releasing it today.

**Comment by aranega** [comment]
Finally, after some other technical issues, our version of emf-gwt should be available in the maven central repository (at least very soon, deployment is done):

artifacts are:

**EMF Common**
```xml
<dependency>
  <groupId>com.genmymodel.emf.gwt</groupId>
  <artifactId>emf-common</artifactId>
  <version>2.12.4</version>
</dependency>
```

**EMF Ecore**
```xml
<dependency>
  <groupId>com.genmymodel.emf.gwt</groupId>
  <artifactId>emf-ecore</artifactId>
  <version>2.12.4</version>
</dependency>
```

**EMF Edit**
```xml
<dependency>
  <groupId>com.genmymodel.emf.gwt</groupId>
  <artifactId>emf-edit</artifactId>
  <version>2.12.4</version>
</dependency>
```

**Comment by uruuru** [comment]
Great! I'll incorporate it as soon as I find time.

**Comment by uruuru** [comment]
elkjs is now based on the published artifacts. Thanks again.

**Comment by aranega** [comment]
That's a great news, thanks a lot for the integration!
