### ISSUE TITLE
JavaDoc error messages from Maven

### ISSUE THREAD

**Issue by spoenemann** [eclipse/elk#185]
See the [nightly builds](https://hudson.eclipse.org/elk/job/UpdateSiteNightly/). There are a lot of error messages from JavaDoc. Some examples:

```
error: reference not found
     * {@link org.eclipse.elk.core.klayoutdata.KShapeLayout KShapeLayouts}
error: malformed HTML
     * are < epsilon, the algorithm stops.
error: malformed HTML
     * if x<0 or x>20
error: bad use of '>'
     * if n < 0 or n < 0 or k > n
error: unknown tag: emph
     * explicitly use the <emph>set</emph>
error: self-closing element not allowed
     * {@link IExplicitAttachmentProvider}<br/>
error: unexpected end tag: </p>
     * </p>
```

**Comment by le-cds** [comment]
Is there any tool that can show us a summary of such problems? It would be a bit cumbersome to wade through the error messages manually...

Many of the errors are missing `@param` and `@return` tags. I'm not sure whether anyone has the time to go through the code and add those. :/

**Comment by uruuru** [comment]
Is the javadoc still built?

**Comment by spoenemann** [comment]
Who uses JavaDoc nowadays? I think the only reason we build it is for publishing at Maven Central, though I'm not 100% sure the JavaDoc bundles are really required.

**Comment by le-cds** [comment]
Well, [the documentation](https://maven.apache.org/repository/guide-central-repository-upload.html) is not entirely clear on that. It lists Javadocs together with sources as requirements "for IDE lookup". Every modern IDE I know of simply extracts documentation from the source, though, not from generated HTML documents...

I'd be happy to stop building Javadocs if they are not in fact required after all.

**Comment by spoenemann** [comment]
You could try whether validation passes at https://oss.sonatype.org if you omit the JavaDoc JARs when you do the next release.

**Comment by le-cds** [comment]
Yep, I was thinking along those lines as well. I sure hope I'll remember... 😁

**Comment by uruuru** [comment]
@le-cds, I set the milestone so you don't forget :).

**Comment by le-cds** [comment]
Certainly a good idea, thanks! 😄

**Comment by le-cds** [comment]
> You could try whether validation passes at https://oss.sonatype.org if you omit the JavaDoc JARs when you do the next release.

Interestingly, validation (which includes a check for Javadocs) passes even in the absence of Javadoc files... I guess I'll just disable Javadocs, then.
