### ISSUE TITLE
EdgeLabels of Self Loops not placed

### ISSUE THREAD

**Issue by eNBeWe** [eclipse/elk#189]
Self Loop Labels are not placed
```
elk.direction: RIGHT

node N1 {
	port P1
	port P2
}

edge N1.P1->N1.P2 {
	label "Tolles Edge Label"
}
```
![selflooplabel](https://user-images.githubusercontent.com/3796429/27792450-14934d7c-5ffa-11e7-921e-0dc7841a676d.png)

**Comment by uruuru** [comment]
See #79.
