### ISSUE TITLE
Documentation should list the shortest possible layout option id

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#191]
Should be easy to add this to the documentation generator. 

If not documented it's a guessing game that it must be `elk.direction` instead of `direction`.

**Comment by le-cds** [comment]
I'm actually not sure whether it's that easy. I don't think the documentation generator has access to everything it would need, but I could be wrong.

**Comment by uruuru** [comment]
Mh, I believe you're right. It doesn't know about all the options that could potentially be registered. Also the shortest possible id depends on the _currently_ registered options. Pity.

**Comment by le-cds** [comment]
> Pity.

Quite so, indeed. Would be a cool feature.

I'm closing this, then.
