### ISSUE TITLE
Fixed position port constraints create unnecessary whitespace in hierarchical nodes

### ISSUE THREAD

**Issue by coinzz** [eclipse/elk#194]
The following elkt file creates the issue:

```
node r {
	
	org.eclipse.elk.portConstraints: FIXED_POS
	node n1
	node n2
	node n3
	node n4
	node n5
	node n6
	node n7
	node n8
	node n9
	
	port p1 {
		layout [ position: 100, 0 ]
		^port.side: NORTH
		^port.index: 1
	}
	port p2 {
		layout [ position: 150, 0 ]
		^port.side: NORTH
		^port.index: 2
	}
	port p3 {
		layout [ position: 200, 0 ]
		^port.side: NORTH
		^port.index: 3
	}
	port p4 {
		layout [ position: 0, 250 ]
		^port.side: WEST
	}
	
	edge n1 -> n2
	edge n2 -> n3
	edge n4 -> n5
	edge n2 -> p1
	edge n8 -> p2
	edge n5 -> p3
	edge n3 -> p4
}
```
Fixed pos:
![fixed_pos](https://user-images.githubusercontent.com/29376900/27863403-45026ac4-618a-11e7-9db1-fbdd0581df35.PNG)

Fixed ratio:
![fixed_ratio](https://user-images.githubusercontent.com/29376900/27863468-8554e994-618a-11e7-817b-bcbe55dd5254.PNG)

**Comment by le-cds** [comment]
I cannot reproduce the bug with `FIXED_ORDER` port constraints, as mentioned in the title. I can with `FIXED_POS`.

Regarding `FIXED_RATIO`, the result seems wrong but is simply undefined behavior. The algorithm tries to infer the desired ratio by looking at where the ports are in relation to the size of the node. Not specifying an initial size (as in this example) is undefined and thus not a bug.

**Comment by coinzz** [comment]
The title was wrong. Only `FIXED_POS` and `FIXED_RATIO` constraints as described in the pictures have to be considered here.
