### ISSUE TITLE
Rename 'properties' to 'layoutOptions' in elk json

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#206]
There's no keyword `properties` in `elkt` anymore (as opposed to `kgt`). I'm wondering if it might be less confusing for users if we called the corresponding key `layoutOptions` in the json format. @le-cds @spoenemann? 

```
{
  id: "n2", 
  width: 100,
  height: 100,
  properties: {
    'elk.nodeLabels.placement': 'INSIDE V_CENTER H_CENTER'
  }
}
```

```
{
  id: "n2", 
  width: 100,
  height: 100,
  layoutOptions: {
    'elk.nodeLabels.placement': 'INSIDE V_CENTER H_CENTER'
  }
}
```

**Comment by spoenemann** [comment]
Or just `options`?

**Comment by uruuru** [comment]
My idea was to make a clear distinction to regular/other options one may add to the json file.

**Comment by spoenemann** [comment]
Ok.

**Comment by uruuru** [comment]
The intention of calling it `layoutOptions` is to make the common case easy to explain. After all _most_ of the things put in there are layout options. 
Also, since we can simply add other keys to the json, other properties can be added to new keys: e.g. `style:` to specify styling information for the rendering framework.

I would have put the junction points in the `layoutOptions` but am open to other suggestions. At this point they are the only other thing, apart from coordinates and dimensio,n that is written back to the graph.
