### ISSUE TITLE
Layout Algorithm Selection Dialog: Ok Button should be disabled when a category is selected.

### ISSUE THREAD

**Issue by miklossy** [eclipse/elk#207]
In the Select Layout Algorithm Selection Dialog, when the User selects a category (e.g: Circle, Force, Layered,...) and clicks the OK Button, the Layout Algorithm will not be changed (that's desired, I think, since selecting a category as a layout algorithm would be an invalid selection.

I think it would be more convenient to disable the OK Button when a category is selected, and display a meaningful information message why the OK Button is currently disabled.
![elk_layoutalgorithmselectiondialog](https://user-images.githubusercontent.com/20393472/28358266-8b923a02-6c6e-11e7-91ea-7426feeaf520.png)

**Comment by uruuru** [comment]
Maybe disable the selectability for category elements while still allowing them to expand?

**Comment by spoenemann** [comment]
Some background: In an earlier version of KIML (the predecessor of ELK), it was possible to select a category as "layout hint". In that case a layout algorithm from that category was selected automatically. We disabled this feature, which leads to the problem reported here.

**Comment by miklossy** [comment]
I think selecting a category should still be possible (currently if the user selects a category, some description on the right side will be displayed about the category, that I find useful).

**Comment by le-cds** [comment]
I think disabling the OK button is a good idea. However, the UI might display some sort of a hint to make the user aware of what is necessary for the OK button to be enabled again.
