### ISSUE TITLE
Unexpected behavior in Spacing Layout Option

### ISSUE THREAD

**Issue by SimonBerggren** [eclipse/elk#212]
When I try to run the Elk layered layout from the live website ( http://rtsys.informatik.uni-kiel.de/elklive/json.html ), I can specify the spacing between nodes. Here, I encounter one problem: 
The spacing only affects nodes vertically. There are no difference in the spacing horizontally. Is this a feature? I am using the layered algorithm.

When I try to specify the spacing on a custom graph and then use the layout algorithm in TypeScript, the spacing property makes no difference at all. The properties looks exactly like the properties on your live version. 
I also tried sending the options to Elk in it's constructor, and as a second parameter to the elk.layout function with different combinations of names (such as actually typing the entire id of a property) without any success.

How do I specify the spacing (or rather properties in general) in TypeScript? It doesn't seem to make any difference as of now.

**Comment by le-cds** [comment]
> Here, I encounter one problem: The spacing only affects nodes vertically. There are no difference in the spacing horizontally. Is this a feature? I am using the layered algorithm.

@uruuru will correct me if I'm wrong, but I believe spacing of elements in different layers is controlled by the options [in this option group](http://www.eclipse.org/elk/reference/groups/org-eclipse-elk-layered-spacing.html).

Regarding the other questions, you will have to wait for @uruuru to reply. ;)

**Comment by uruuru** [comment]
```
{ 
    'elk.spacing.nodeNode': 30,
    'elk.layered.spacing.nodeNodeBetweenLayers': 30,
}
```

This works for me in the live json view. As mentioned in #105, I believe the current way of configuring spacing values is powerful but confusing to a user. 

Regarding layout options in typescript: the json you enter into the textbox is passed to the `layout(..)` method as is. Thus the options should get applied properly. If passing them as second parameter make sure it's an object with an object of layout options like so:
```
{
  layoutOptions: {
    'elk.direction': 'DOWN'
  }
}
```

Regarding the layout options passed to `ELK`'s constructor: I believe this is a bug. The options are not properly applied internally. I'll create a bug in elkjs for it.

**Comment by SimonBerggren** [comment]
I agree with the current way of configuring spacing values is a bit confusing. It was not an object with an object of the layout options, but after correcting that, everything works as expected. 

Thank you for your help!
