### ISSUE TITLE
Connected Components Compaction does not resize the graph

### ISSUE THREAD

**Issue by coinzz** [eclipse/elk#213]
When "org.eclipse.elk.layered.compaction.connectedComponents" is activated the compound graph won't be resized. The test graph is from the old models repository: graphs/klay_layered/hierarchical_ports/hierarchy03.kgt

![connected_components_compaction](https://user-images.githubusercontent.com/29376900/28670714-3b50535e-72da-11e7-8f45-4f488c613a0f.jpeg)

**Comment by le-cds** [comment]
@coinzz could you attach an elkt file that reproduces the issue?

**Comment by coinzz** [comment]
elkt files can't be attached here but I can copy the content of it here ;)

```
algorithm: layered

node Compound {
    portConstraints: FIXED_SIDE
    compaction.connectedComponents: true
    
    port CW1 {
        ^port.side: WEST
    }
    port CW2 {
		^port.side: WEST
    }
    port CW3 {
		^port.side: WEST
    }
    port CW4 {
		^port.side: WEST
    }
    port CN1 {
		^port.side: NORTH
    }
    
    ///////////////////////////////////////////////////////////////////////
    // COMPONENT 1
    
    node N1_1 {
        label "N1_1"
    }
    
    node N1_2 {
        label "N1_2"
    }
    
    ///////////////////////////////////////////////////////////////////////
    // COMPONENT 2
    
    node N2_1 {
        label "N2_1"
    }
    
    node N2_2 {
        label "N2_2"
    }
    
    node N2_3 {
        label "N2_3"
    }
    
    node N2_4 {
        label "N2_4"
    }
    
    node N2_5 {
        label "N2_5"
    }
    
    ///////////////////////////////////////////////////////////////////////
    // COMPONENT 3
    
    node N3_1 {
        label "N3_1"
    }
    
    ///////////////////////////////////////////////////////////////////////
    // COMPONENT 4
    
    node N4_1 {
        label "N4_1"
    }
    
    ///////////////////////////////////////////////////////////////////////
    // COMPONENT 5
    
    node N5_1 {
        label "N5_1"
    }
    
    ///////////////////////////////////////////////////////////////////////
    // COMPONENT 6
    
    node N6_1 {
        label "N6_1"
    }
    
    ///////////////////////////////////////////////////////////////////////
    // COMPONENT 7
    
    node N7_1 {
        label "N7_1"
    }
    
    ///////////////////////////////////////////////////////////////////////
    // COMPONENT 8
    
    node N8_1 {
        label "N8_1"
    }
    
    node N8_2 {
        label "N8_2"
    }
    
    node N8_3 {
        label "N8_3"
    }
    
    ///////////////////////////////////////////////////////////////////////
    // COMPONENT 9
    
    node N9_1 {
        label "N9_1"
    }
        
    node N9_2 {
        label "N9_2"
    }
    
    node N9_3 {
        label "N9_3"
    }
    
    node N9_4 {
        label "N9_4"
    }
    
    node N9_5 {
        label "N9_5"
    }
    
    edge N1_1 -> N1_2
    edge N2_1 -> N2_2
    edge N2_1 -> N2_3
    edge N2_2 -> N2_4
    edge N2_3 -> N2_4
    edge N2_4 -> N2_5
    edge N8_1 -> N8_2
    edge N8_2 -> N8_3
    edge N9_1 -> N9_2
    edge N9_1 -> N9_3
    edge N9_1 -> N9_4
    edge N9_1 -> N9_5
    
    edge ^CW1 -> N1_1
    edge ^CW2 -> N3_1
    edge ^CW3 -> N4_1
    edge N5_1 -> ^CW4

    edge ^CN1 -> N1_2
}
```

**Comment by spoenemann** [comment]
Or use [this link](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUEQHYQE5oDCESADhAK6kFoDeRa3ajUctUgGc4UYDFJwh6AGIBJABoBRACIB9AMpyVSrjwDGdesH1wYEUgDpDpUjlOFaDCzknS0opjj3cfvaHA0AOoAjBx+PGgAenxwlkIwlOhBShoAKn4Avn6xwQBM4QCQhTEB8Yk4yakZkdmRudRBAMxFJbHlSWgp6Vk5AcEALK2l-B2VXdW99f3UAHJhnMUjcQmdswDyAEppABJTPH4A9Mcnp2fnF5dX1zdnR4c06wCyAArrs0qzaWghfn7klDQ8zUCwiPEwACMcCA0AAiYEhWH7XyRAFUYEFTiRSKQ6FwjFI2p-SK3Ulk8kUw73R6vd6fb55Yk8NFAvIg8LY8HAKEw+FsxHItD-CjotmYsHcXG82Ziwk8OoHVEi1lqFpYzkYbl4vmquXcBUo5nKmVqIbqzlS-FsgZ6tAGoVKwEmgCsHI1lp1ztt9vulL9-vJ1OozzeHy+aCaTO4LNmTXZ5uxHtjIO9UbQAYzmcuQZDdPDAzTMYG8Ylmp5+OLAqJkV9WbrGZztLD32dheNzpLGrL2tmHar8rT9aHAcbofpaAAbG2nRPO+6tdLZ-39YPh2vAySHsGm+OAOzT9G7ucWhf4o-Lu2r9fX66jvPfAAcB6BD+PidP8NfF59jvRr-FXZJv+qY1r+L6qm6J7lp+uqCrWN4Iacd7NmgACcz6zKhb44h+mEpoKoFGk6WEAfO0F4XkIGKkR6JYWqpZJnRVGGtGxpYWaDG4exzEOjRQJYa6CY4eRAk8X4hBgOiITsgAtAAfEC0mMpEEmirJCkmspPCqSqYTySqkYqQQkkqgU+kmgWRkmSaLTmda4nGWpQx2WorZWX+6ngVp3A6bM-5oOZr6Gdpjn8Z5FEOdZWF6RpdGRbR4XsfFYUxWFbnUT5oVRI0qUIsl2VBGZGlxr87nRI0tkaZWyW9p5BUFvlcy5UpRCZEAA) :-)
