### ISSUE TITLE
Sloppy Splines broken at inverted ports without port labels

### ISSUE THREAD

**Issue by eNBeWe** [eclipse/elk#217]
See this elkt:

```
elk.direction: RIGHT
edgeRouting: SPLINES

node N1 {
	portConstraints: FIXED_SIDE
	
	port P1 {
		side: WEST
	}
	port P2 {
		side: EAST
	}
}

node N2 {
	portConstraints: FIXED_SIDE
	
	port P1 {
		side: WEST
	}
	port P2 {
		side: EAST
	}
}

edge N1.P2->N2.P1
edge N2.P2->N1.P1
```

It creates a weird bend at the outgoing inverted port:

![splineissue](https://user-images.githubusercontent.com/3796429/29016343-65cbdd26-7b52-11e7-972b-638315ca7590.png)

Same routing visible in layout graph.

**Comment by eNBeWe** [comment]
This might be related to #216 if that issue also relates to broken edges at the new inverted ports.

**Comment by uruuru** [comment]
There's an additional issue for #216 in either way.

For this issue you could check the `FinalSplineBendpointsCalculator` around lines 150-185. There's a TODO and a couple of uncommented lines.

**Comment by eNBeWe** [comment]
What is the desired behaviour for inverted edges? I think I would not route sloppy edges in the inverted case.
