### ISSUE TITLE
Port Order for west and south ports are currently reversed. North and east ports are fine.

### ISSUE THREAD

**Issue by coinzz** [eclipse/elk#227]
The result is:

![bug](https://user-images.githubusercontent.com/29376900/29623493-e094e7ce-8826-11e7-8ffc-47e710df1543.PNG)

And the .elkt code for this purpose is:

```
algorithm: layered

node Compound {
	portConstraints: FIXED_ORDER

	port CW1 {
		^port.side: WEST
		index: 1
	}
	port CW2 {
		^port.side: WEST
		index: 2
	}

	port CN1 {
		^port.side: NORTH
		index: 1
	}
	port CN2 {
		^port.side: NORTH
		index: 2
	}

	port CS1 {
		^port.side: SOUTH
		index: 1
	}
	port CS2 {
		^port.side: SOUTH
		index: 2
	}

	port CE1 {
		^port.side: EAST
		index: 1
	}
	port CE2 {
		^port.side: EAST
		index: 2
	}

	// /////////////////////////////////////////////////////////////////////
	// COMPONENT 1
	node N1_1
	node N1_2

	// /////////////////////////////////////////////////////////////////////
	// COMPONENT 2
	node N2_1
	node N2_2

	edge ^CW1 -> N1_1
	edge N1_1 -> N1_2
	edge N1_1 -> CN1
	edge N1_2 -> CN2
	edge N1_2 -> CE1

	edge ^CW2 -> N2_1
	edge N2_1 -> N2_2
	edge N2_1 -> CS1
	edge N2_2 -> CS2
	edge N2_2 -> CE2
}
```

**Comment by uruuru** [comment]
The port order is specified clock-wise, e.g. from right-to-left on the south side. If I see it correctly, your example behaves as expected.

**Comment by coinzz** [comment]
Well yes, I didn't think about that when I created the ticket. From a user point of view I think it is more intuitive when the north and south indexing both goes from left to right and the same for the west and east from top to bottom.

**Comment by le-cds** [comment]
It's indeed a bit unintuitive, but changing it might break old models.
