### ISSUE TITLE
Deactivating greedy switch breaks hierarchical layout

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#228]
For some reason hierarchical layout fails (always?) when greedy switch is deactivated. The simple example below is enough to reproduce it. 

Origin #226:
```
greedySwitch.type: OFF
hierarchyHandling: INCLUDE_CHILDREN

node augment_super_as {
	node augment_super_as_node
	node augment_sub0
	node augment_sub1
	node augment_super_as_node_ifEntry_augmentation 
	edge augment_super_as_node -> augment_super_as_node_ifEntry_augmentation
}
```

**Comment by uruuru** [comment]
The issue is that greedy switch is a hierarchical layout processor and is activated the default, which is the case for the inner node here. That setup then breaks the internal control flow of the hierarchical layout, effectively skipping large parts of the layout execution for the inner node.

**Comment by le-cds** [comment]
Why did I self-assign this? @uruuru did we discuss this ticket in the last meeting?
