### ISSUE TITLE
HierarchicalNodeResizingProcessor shouldn't depend on layer sweep

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#229]
The `HierarchicalNodeResizingProcessor` intermediate processor is activated by the `LayerSweepCrossingMinizer`. Instead it should be activated by the `GraphConfigurator` as soon as `INCLUDE_CHILDREN` is activated.

**Comment by le-cds** [comment]
Why did I self-assign this? @uruuru did we discuss this ticket in the last meeting?
