### ISSUE TITLE
Wrong Default PortAlignment

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#232]
The default value for the port alignment in `CoreOptions` is `CENTER`:

```
group portAlignment {
  option basic: PortAlignment {
    default = PortAlignment.CENTER
```

layered's default is `JUSTIFIED`:
```
supports org.eclipse.elk.portAlignment.basic = PortAlignment.JUSTIFIED
```

I presume due to #104 layered's result uses `CENTER`.

**Comment by le-cds** [comment]
Change core default to `JUSTIFIED`.
