### ISSUE TITLE
PortAlignment `JUSTIFIED` does not leave spacing at top and bottom

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#233]
Consider the attached screenshot. I would expect some spacing above `p3` and below `p1` to the border of the node. IIRC this was the case once upon a time. @le-cds maybe it is due to your latest changes?

![portalignment](https://user-images.githubusercontent.com/7552459/29763898-5b6b853c-8bd5-11e7-8de7-6896c94f4200.png)

**Comment by le-cds** [comment]
We decided to set the surrounding port spacing default to 10.

**Comment by uruuru** [comment]
Be careful with nodes being smaller than 10 tough.

**Comment by le-cds** [comment]
Well, people will have to configure the spacing to suit their diagrams anyway.

**Comment by uruuru** [comment]
```
node n1 {
	layout [size: 20,100]
	portAlignment.basic: JUSTIFIED
	spacing.portSurrounding: "[top=10.0,left=10.0,bottom=10.0,right=0.0]"
	port p1
	port p2	
}
```

**Comment by le-cds** [comment]
The surrounding port spacing is taken from the graph. To configure it on a node, use the spacing override facility.
