### ISSUE TITLE
Initially opening an elkt shows error markers

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#243]
Quite frequently I get error markers on edges after initially opening an elkt. Inserting a space somewhere and saving the file resolves the error markers. 

Example:
```
node n1 {
	port p1
	port p2
	node n2 
	edge n2 -> p2 
}
```

```
Multiple markers at this line
- Too many matches for reference to 'p2'. Feature targets can
   only hold -1 references but found 1 candidate
- Too many matches for reference to 'n2'. Feature sources can
   only hold -1 references but found 1 candidate
```

**Comment by spoenemann** [comment]
This is because the custom linker implementation uses `Linker` as superclass. It should be changed to `LazyLinker`. This is already done in #240.

**Comment by spoenemann** [comment]
@uruuru do you still see these problems?

**Comment by uruuru** [comment]
Seems to be fixed.
