### ISSUE TITLE
Unnecessary edge crossings

### ISSUE THREAD

**Issue by a-sr** [eclipse/elk#255]
The following SCG has some unnecessary edge crossings and a label crossing.
Seems to be a candidate for an ONO layout?

![screenshot](https://user-images.githubusercontent.com/25612037/31175407-81afb1da-a90f-11e7-91bc-e14aa313c14c.png)

Source: [scg-with-strange-crossings.kgx.txt](https://github.com/eclipse/elk/files/1355739/scg-with-strange-crossings.kgx.txt)

**Comment by le-cds** [comment]
The label crossing should already be fixed in the current version of ELK. The edge crossings are quite unfortunate indeed, but hard to avoid if all you can do is run a heuristic... 😉
