### ISSUE TITLE
Clean up preferences

### ISSUE THREAD

**Issue by le-cds** [eclipse/elk#257]
A fresh ELK installation puts several different top-level categories into the preferences dialog:

![screen shot 2017-10-09 at 11 00 52](https://user-images.githubusercontent.com/7465584/31331083-5b3bb474-ace1-11e7-9d43-3b36019863bd.png)

We should merge them all into a single top-level category.

**Comment by uruuru** [comment]
Also, the _Show Layout Progress_ checkbox doesn't show a progress dialog as indicated in its hover text. This might be a different issue though.
