### ISSUE TITLE
Applying layout multiple time doesn't work

### ISSUE THREAD

**Issue by chakraborty-slx** [eclipse/elk#260]
![elk_multiple_layout](https://user-images.githubusercontent.com/26390759/31496858-50e41a60-af5d-11e7-8739-81f73c7afde2.gif)
Please see the gif.

I am using 
`
LayoutConfigurator configurator = new LayoutConfigurator();
		// Configure layout options for all nodes
		configurator.configure(KNode.class).setProperty(CoreOptions.ALGORITHM, "org.eclipse.elk.layered").setProperty(CoreOptions.SPACING_NODE, 30.0f);

		DiagramLayoutEngine.Parameters params = new DiagramLayoutEngine.Parameters();
		params.getGlobalSettings().setProperty(CoreOptions.ANIMATE, true).setProperty(CoreOptions.PROGRESS_BAR, true)/* .setProperty(CoreOptions.ZOOM_TO_FIT, true) */;
		params.addLayoutRun(configurator);

		DiagramLayoutEngine.invokeLayout(null, diagramPart, params);
`

Is there any way to stop this weird behavior.

**Comment by spoenemann** [comment]
That's a Graphiti diagram, right?

**Comment by AChakraborty1982** [comment]
YES this is Graphiti based editor

**Comment by spoenemann** [comment]
It's a mismatch between the `buildLayoutGraph` and the `applyLayout` phases of the GraphitiDiagramLayoutConnector. This weird behavior has been there for several years, so it seems the Graphiti connection is not being used that much...

**Comment by uruuru** [comment]
Still to be fixed? Shall we discontinue graphiti support?

**Comment by le-cds** [comment]
It's probably still an open issue, but I was wondering about discontinuing Graphiti support myself.

@spoenemann What say you? Do you have a feeling regarding how popular Graphiti still is?

**Comment by spoenemann** [comment]
I have not seen Graphiti in any project I've been in touch with in the last 5 years. I'm fine with removing the plugin. We can resurrect it in case someone is interested in maintaining it.

**Comment by le-cds** [comment]
Issue #536 tracks that endeavour. If you have any preference concerning whether to deprecate Graphiti support in 0.7.0 before removing it completely in 0.8.0, feel free to weigh in on that issue.

In the same spirit, I'll close this issue.
