### ISSUE TITLE
Fixed side port constraint resulting in a bad layout and crashes

### ISSUE THREAD

**Issue by coinzz** [eclipse/elk#261]
I wanted to create an example diagram for my thesis and noticed that the layout of my graph doesn't quite work with fixed side enabled. Free and my implementation of fixed order is working fine.
Also for me the launched eclipse instance crashed without warning very often when trying to enable fixed side. In the following I have the code example and the resulting layouts as screenshots.

```
algorithm: layered

node Compound {
	algorithm: layered
	de.cau.cs.kieler.edgeRouting: ORTHOGONAL
	de.cau.cs.kieler.portConstraints: FIXED_SIDE

	port pn1 {
		^portSide: NORTH
		org.eclipse.elk.^port.index: 1
	}
	port pn2 {
		^portSide: NORTH
		org.eclipse.elk.^port.index: 2
	}
	
	port pe1 {
		^portSide: EAST
		org.eclipse.elk.^port.index: 1
	}
	port pe2 {
		^portSide: EAST
		org.eclipse.elk.^port.index: 2
	}
	
	port ps1 {
		^portSide: SOUTH
		org.eclipse.elk.^port.index: 2
	}
	port ps2 {
		^portSide: SOUTH
		org.eclipse.elk.^port.index: 1
	}
	
	port pw1 {
		^portSide: WEST
		org.eclipse.elk.^port.index: 2
	}
	port pw2 {
		^portSide: WEST
		org.eclipse.elk.^port.index: 1
	}

	node n1
	node n2
	node n3
	node n4
	node n5
	node n6
	node n7
	node n8
	
	edge pw1 -> n1
	edge n1 -> n2
	edge n1 -> pn1
	edge n2 -> n3
	edge n2 -> ps2
	edge n3 -> n4
	edge n4 -> pe1
	
	edge pw2 -> n5
	edge n5 -> n6
	edge n5 -> ps1
	edge n6 -> n7
	edge n7 -> pn2
	edge n7 -> n8
	edge n8 -> pe2
}
```

Free:
![free](https://user-images.githubusercontent.com/29376900/31509656-90c277b0-af82-11e7-9449-4650d85795b6.PNG)

Fixed Side:
![fixed_side](https://user-images.githubusercontent.com/29376900/31509663-95b432a4-af82-11e7-9cd1-38fc76225862.PNG)

Fixed Order:
![fixed_order](https://user-images.githubusercontent.com/29376900/31509667-993ea864-af82-11e7-9fa2-0fb921cb0211.PNG)

**Comment by le-cds** [comment]
I can't reproduce this any more, so it seems to have been fixed.
