### ISSUE TITLE
Missing junction points

### ISSUE THREAD

**Issue by ybl23** [eclipse/elk#265]
Hyper edges with same source port do not have a junction point.

For example:
```
node node1 {
	port p1
}

node node2 {
	port p1
	port p2
}

edge node1.p1 -> node2.p1
edge node1.p1 -> node2.p2
```

![junctionpoint svg](https://user-images.githubusercontent.com/27341933/31994964-d17612da-b982-11e7-873b-b81fa9843592.png)

**Comment by uruuru** [comment]
The default elk graph synthesis shows junction points in my setup. Can you share further details?
