### ISSUE TITLE
Eclipse Layout Kernel Configuration

### ISSUE THREAD

**Issue by LeeYufang** [eclipse/elk#270]
Hi,
Good afternoon.
I am a newbie to ELK, and I installed ELK in eclipse platform to layout my diagram(Sirius editor).
I found that every node can be configured in layout view,  seperately. If I have 100 nodes, I need to configure 100 nodes seperately, it is time-consuming.
(1).Is there a way to configure all nodes in one layout view or Is there a global settings for the same type elements, such as node, port, label?
(2). If not, can you give me some suggestions to implement the global settings with the seperated setting remained?
 
Thanks and hope for your reply.

**Comment by spoenemann** [comment]
Please consider asking questions in the [ELK Community Forum](https://www.eclipse.org/forums/index.php/f/321/) before creating an issue.

The Layout view is meant primarily to experiment with the layout configuration. If you're developing a Sirius editor, you should create the configuration programmatically and not manually through the Layout view. There are two ways to achieve this:

 1. Create a command (e.g. toolbar, context menu, main menu) that invokes the [DiagramLayoutEngine](https://github.com/eclipse/elk/blob/master/plugins/org.eclipse.elk.core.service/src/org/eclipse/elk/core/service/DiagramLayoutEngine.java#L235) with a custom configuration as parameter. This is the preferred solution in most cases.
2. Create a custom layout connector as subclass of [GmfDiagramLayoutConnector](https://github.com/eclipse/elk/blob/master/plugins/org.eclipse.elk.conn.gmf/src/org/eclipse/elk/conn/gmf/GmfDiagramLayoutConnector.java) and register it with a Guice setup (see [GmfLayoutSetup](https://github.com/eclipse/elk/blob/master/plugins/org.eclipse.elk.conn.gmf/src/org/eclipse/elk/conn/gmf/GmfLayoutSetup.java) and [plugin.xml](https://github.com/eclipse/elk/blob/master/plugins/org.eclipse.elk.conn.gmf/plugin.xml#L16)). The subclass can then set layout options on every created element. This approach is particularly useful if the default GMF layout connector (which is also used for Sirius) does not detect the graph structure of your diagrams correctly, wich can be corrected in a subclass.

See the [documentation](https://www.eclipse.org/elk/documentation/tooldevelopers/usingeclipselayout.html) for more information, especially the sections [Connecting to ELK](https://www.eclipse.org/elk/documentation/tooldevelopers/usingeclipselayout/connectingtoelk.html) and [Advanced Configuration](https://www.eclipse.org/elk/documentation/tooldevelopers/usingeclipselayout/advancedconfiguration.html).
