### ISSUE TITLE
Is it possible to have port fixed relative to node?

### ISSUE THREAD

**Issue by JokerNN** [eclipse/elk#274]
Hello, thank  you for this library first of all, I have a question rather than issue.

I'm trying to have port position fixed at some coordinate(relative to node coords). I found FIXED_POS constant for alignment, but I'm struggling with providing position of the port, `x` and `y` seems to be ignored for ports.

I'm using layered algorithm

Thanks in advance

**Comment by uruuru** [comment]
Did you configure `FIXED_POS` for the node the port belongs to? 
Can you share a minimal example?

**Comment by JokerNN** [comment]
@uruuru thanks for response, config is JSON

```
{
  id: "root",
  properties: {
    algorithm: 'layered',
    portConstraints: 'FIXED_POS'
  },
  children: [
    { 
      id: "n1", 
      width: 30, 
      height: 30, 
      portConstraints: 'FIXED_POS',
      ports: [
        {
          id: 'p1',
          label: 'p1',
          x: 1,
          y: 1,
          width: 5, 
          height: 10
        }
      ]  
    },
    
    { id: "n2", width: 60, height: 60 }
  ],
  edges: [
    { id: "e1", sources: [ "p1" ], targets: [ "n2" ] },
    //{ id: "e2", sources: [ "n1" ], targets: [ "n2" ] } 
  ]
}
```

[Link to online visualization](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYCIBOB7FAXBAacYAOqeApkupEQM7ygQQCGANgOYpKToAWAtvAOQN0AniSLReOWvlboAwigB2FdEjqR56KmF4AxAJIANAKIARAPoAFAPIBlXrgC+EsAGMOkBtCRF58ANq4IYDAA2hh4BHkARmxgyQgAdxhOeABmAAYsWLiOIkgmDnRUjKzJPGk5RWVVdU0dAxMLG3EQiDLSTX842hou0LgtPEjm3toBACMiBj5B4ZGwAA94SKcRwSWV3sToZLAAVkyW7Nz8wrBItMOIe0OAXQgQxxCQoLDEeQAmGK2dgDZinLyBXgfzA1wgNycoiYlD8zyg-QQRGimQoKAArkhnDCwL5EIMEGAIWB0HQkNCNH43p9CaCNgB6OkvBFET4o9GY7G4iLRQmZElkogUnFUgl3exZG4gexAA)

**Comment by uruuru** [comment]
You have to put the option in a `layoutOptions` object:

```
layoutOptions: {
  portConstraints: 'FIXED_POS'
},

**Comment by JokerNN** [comment]
Awesome! Thanks @uruuru 

[Updated working config JSON](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYCIBOB7FAXBAacYAOqeApkupEQM7ygQQCGANgOYpKToAWAtvAOQN0AniSLReuAL44IAYw6QG0JEQB28ANq4IwMFtox4CFQEZsu2rQDuMTvADMABizmLYDkUhMO6e05cW8VnQAYRQVCnQkOkgVdCowXgAxAEkADQBRABEAfQAFAHkAZV5pVwFBFABXdHy8MjD4mlcIQNJQ8Mjo2PiktKy8ovFmqT0WoPjNZu1R1wMEvGMSmYsBACMiBj4FpanaAA94AE5S3cF4YxOp62hbMABWZ2Xad09vc4cniRmAXQg9EYseh0cyMACYzNdbgA2PwvLw+MAwsBfCDfUqiJiUDRAqBwRBEUzOChVJAyLFgdSIBYIMBosDoOhITFxDSIFTg2nIy4Aem5wLxCCI4KJJLJEzZplpzgZTKILIpbI5vwkLm+IAkQA)
