### ISSUE TITLE
elkm files do not allow negative values for default and bounds

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#28]
Trying to set a negative ``default`` or ``lowerBound`` value in an elkm file raises an error. 

The used grammar rule is ``('default' '=' defaultValue=XExpression)?``.

**Comment by le-cds** [comment]
Shouldn't negative numbers be an instance of the `XUnaryOperation` rule which propagates up to the `XExpression` rule over this chain of rules?

```
XUnaryOperation
-> XMultiplicativeExpression
-> XAdditiveExpression
-> XOtherOperatorExpression
-> XRelationalExpression
-> XEqualityExpression
-> XAndExpression
-> XOrExpression
-> XAssignment
-> XExpression
```

What keeps XText from simply accepting this?

**Comment by spoenemann** [comment]
In Xbase operators are implemented through methods, which are defined in IntegerExtensions, DoubleExtensions, etc. Two options:
 1. We add a dependency to `org.eclipse.xtext.xbase.lib` in elk.core. This would also enable us to use Xtend in our core and algorithm code, which could be nice. The xbase.lib bundle is a very lightweight library with no further dependencies (except Guava, which we already have).
 2. We define our own operators in elk.core and use those in the elkm files.

**Comment by uruuru** [comment]
Remember that elk.core and elk.algs has to be compilable by gwt. I therefore vote against using xtend code in those parts of elk. 

I'm not sure I get the problem you mention. Why would a dependency to xbase help elk.core to accept a unary ``-``? The generated code shouldn't contain any xbase calls, should it?

**Comment by spoenemann** [comment]
> Remember that elk.core and elk.algs has to be compilable by gwt. I therefore vote against using xtend code in those parts of elk.

Xtend is GWT compatible.

> I'm not sure I get the problem you mention. Why would a dependency to xbase help elk.core to accept a unary -? The generated code shouldn't contain any xbase calls, should it?

Most operators are inlined, so the generated code does not have the xbase.lib references, but the Xbase editor for elkm files needs that dependency if we want to use the default operators.

**Comment by le-cds** [comment]
> I therefore vote against using xtend code in those parts of elk.

+1. I vote for keeping the core and at least the current algorithms to be as lightweight as possible in terms of required libraries.

> but the Xbase editor for elkm files needs that dependency if we want to use the default operators.

So it should be enough to add that dependency to the `elk.meta` plug-ins?

**Comment by spoenemann** [comment]
> So it should be enough to add that dependency to the elk.meta plug-ins?

No, because the elkm editor uses the classpath of the containing project to resolve links in elkm files, not the classpath of the elkm editor plug-in. Those already have Xtend code in them, anyway.

**Comment by spoenemann** [comment]
Please review the fix. The operators are *not* inlined because that would require references to annotations that are also defined in xbase lib. I only added the unary minus operator for now, but we can add more as we need them.

**Comment by spoenemann** [comment]
I found another option as alternative to the fix above: Add the line
```
additional.bundles = org.eclipse.xtext.xbase.lib
```
to the build.properties file of each plug-in using an elkm file. This adds the Xbase library to the development classpath, but does not change the runtime classpath.

**Comment by le-cds** [comment]
I prefer the latter solution because it gives people more flexibility without us having to maintain additional code. The need to add this additional bundle seems like putting the burden on users, but once we have a proper "New Layout Algorithm Project" wizard, that won't be that bad.

**Comment by spoenemann** [comment]
Ok, but there is one caveat with this simpler solution: If you use stuff from the Xbase library that is *not* inlined, e.g. `newArrayList`, the generated code will actually contain references to those library methods. The compiler will accept that and the code will work when you test it through a launch configuration, but it will fail when you package the plug-in and install it via update site.

One way to handle this could be to implement a validation that generates a warning whenever you use Xbase library methods that are not inlined.

**Comment by le-cds** [comment]
> One way to handle this could be to implement a validation that generates a warning whenever you use Xbase library methods that are not inlined.

That would allow people to include a dependency to Xbase if they really want to use that code. The warning could take the project configuration into account.

**Comment by spoenemann** [comment]
>> One way to handle this could be to implement a validation that generates a warning whenever you use Xbase library methods that are not inlined.

>That would allow people to include a dependency to Xbase if they really want to use that code. The warning could take the project configuration into account.

I think that would be hard to realize. There could be several ways how people specify their project dependencies. In a plain Java project the dependencies would be written into the build file (pom.xml, build.gradle, etc.) or directly into the `.classpath` file. We could add some means to suppress the warning with a comment such as

```
// Suppress Warning xbaseLibReference
default = newArrayList
```

**Comment by le-cds** [comment]
Sounds good.

**Comment by spoenemann** [comment]
After rethinking I don't like the idea of a warning anymore. That would help *us* because currently we don't use Xtend in the layout algorithms code, but if someone else wants to implement an algorithm with Xtend and also use some Xbase library stuff in the meta data file, the warning would be just tedious. I vote for leaving the current state as it is, i.e. we use the classpath trick with the build.properties file and make sure we use only inlined stuff from the Xbase library.

Here's some code for a validation that I started, in case we want to come back to that idea:
```
    @Check
    def void checkXbaseLibReference(XAbstractFeatureCall featureCall) {
        val feature = featureCall.feature
        if (feature instanceof JvmAnnotationTarget) {
            if (!feature.eIsProxy && feature.identifier.startsWith('org.eclipse.xtext.xbase.lib')) {
                val inlineAnnotation = feature.annotations.findFirst[annotation.qualifiedName == Inline.name]
                if (inlineAnnotation === null) {
                    warning("TODO", featureCall, XABSTRACT_FEATURE_CALL__FEATURE)
                }
            }
        }
    }
```

**Comment by le-cds** [comment]
Looks good and seems to be working fine. I added the entry to elk.core as well.
