### ISSUE TITLE
The maven build is broken

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse/elk#282]
Steps to reproduce:
- Run the maven build using the pom.xml located in /build/pom.xml
- This error appears "Could not resolve target platform specification artifact org.eclipse.elk:org.eclipse.elk.targetplatform:target:0.3.0-SNAPSHOT"

The issue seems to come from this line in the build/pom.xml file:
https://github.com/eclipse/elk/blob/bb2b53383d8b4fa302c385932de2ecb17469d718/build/pom.xml#L20

**Comment by le-cds** [comment]
Good call, thanks. We're currently having problems with the automatic build anyway since our build servers were switched to Jenkins. I'll update the `pom.xml` as soon as possible, though.

**Comment by spoenemann** [comment]
Maybe we can just use `project.version` instead of defining another property?

**Comment by le-cds** [comment]
I'll check once our builds servers are up and running again.

**Comment by le-cds** [comment]
I kept the `elk-version` variable around for expressiveness reasons, but initialized it with `project.version`.
