### ISSUE TITLE
NodeSizeConstraint PORT_LABELS creating overlaps

### ISSUE THREAD

**Issue by eNBeWe** [eclipse/elk#287]
See this example:
```
elk.direction: RIGHT

node N1 {
	nodeSize.constraints: "[PORT_LABELS, MINIMUM_SIZE, NODE_LABELS]"
	
	port P1 {
		label "Port 1"
		label "[-]"
	}
	port P2 {
		label "Port 2"
		label "[-]"
	}
	port P3 {
		label "Port 3"
		label "[-]"
	}
}

node T1
node T2
node T3

edge N1.P1->T1
edge N1.P2->T2
edge N1.P3->T3
```
![recreation](https://user-images.githubusercontent.com/3796429/36088090-f44184ee-0fd5-11e8-9aca-d21399549b0a.png)

The labels overlap massively and the node is not properly resized.

This behaviour also applies to downwards layout but then the label also stack in the wrong direction.

**Comment by le-cds** [comment]
For port labels to be respected the `PORTS` option needs to be set. If it is, multiple labels per port are supported for both outside and inside port labels.
