### ISSUE TITLE
Overhaul of Debug Views

### ISSUE THREAD

**Issue by le-cds** [eclipse/elk#292]
Layout algorithms tend to print stuff to the console if the debug option is set to `true`. We should use a more sophisticated logging concept instead.

**Comment by le-cds** [comment]
Large parts of this feature have been implemented by one of our students. This resulted in a major overhaul of our debug views in Eclipse:

* Layout Time View

   Hasn't been changed much.

* Layout Graph View

   Received a major overhaul. It not only shows the result of the most recent layout run, but also arbitrary intermediate graphs logged by layout algorithms. They are accessible through a tree view similar to the one provided by the layout time view.

* Layout Log View

   This view shows arbitrary text logged by layout algorithms. Algorithms should switch to using that instead of `System.out`.

Logging graphs and text works by calling new methods introduced in `IProgressMonitor`.

To develop all of these changes into something we can distribute, I have the following ideas and questions:

* I would like to get rid of the `DEBUG` layout option. I believe that whether we want to see debugging output or not should be a tool-level setting, not a graph-level one. Thus, a layout algorithm would decide to generate debug output not based on that option, but based on the progress monitor's settings (by calling `isDebugMode()`, for example).

* That raises the question of how debug mode gets enabled in progress monitors. If layout is invoked through the layout service, we can use preferences. We already have a preference that controls whether progress monitors measure execution time. I propose an additional setting that controls whether they collect debug infos. It should be a separate setting because we use execution times to judge the performance of our algorithms, and we don't want the generation of debugging information to skew our results. Of course, both settings should have shortcuts in the relevant debug views.

* The question is how we treat layout runs not initiated through the layout service. Do we care about such cases in the first place?

* Speaking of that: another question is whether we want log output to be persisted somewhere, just like debug graphs are currently often written to files. This could help debug other people's layout problems since they could just switch on debug mode and persisted logs and send us a zip file.

Any thoughts? @spoenemann @uruuru

**Comment by spoenemann** [comment]
Great!

> The question is how we treat layout runs not initiated through the layout service. Do we care about such cases in the first place?

No. If you want to, you can still configure the progress monitor manually, right?

> another question is whether we want log output to be persisted somewhere, just like debug graphs are currently often written to files.

Mmh... we could add another option for that, or just do it automatically if logging is enabled, but no consumer (such as the Layout Log View) is available?

**Comment by le-cds** [comment]
> If you want to, you can still configure the progress monitor manually, right?

Sure, both when using the `DiagramLayoutEngine` and when using the `RecursiveGraphLayoutEngine` directly. So I guess I'll just add appropriate configuration methods to our progress monitor interface.

> we could add another option for that, or just do it automatically if logging is enabled, but no consumer (such as the Layout Log View) is available?

I guess I'll add another option for that. Checking for available consumers seems less straightforward. ;)

**Comment by uruuru** [comment]
Can you share a screenshot of the new layout graph view?

**Comment by le-cds** [comment]
Sure. I'm currently implementing another feature suggested when I presented the feature here at our group, and then I'm going to produce screenshots and documentation for our website. :)

**Comment by le-cds** [comment]
> Can you share a screenshot of the new layout graph view?

You'll find documentation along with screenshots [over here](https://www.eclipse.org/elk/documentation/algorithmdevelopers/algorithmdebugging.html) after the next nightly build. :)
