### ISSUE TITLE
Nice screenshot 

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#294]
I propose to have a shiny screenshot decorate the readme page of this repository.

**Comment by le-cds** [comment]
That would be very agreeable. I propose to name the file `LOOKATME.png` (or whatever file type it is).

**Comment by le-cds** [comment]
We might take the opportunity to add a dedicated layout example to the website's landing page as well.

**Comment by spoenemann** [comment]
Please use an absolute URL when referring to images in the README, since that file might be rendered elsewhere apart from the GitHub page.

**Comment by orestesgaolin** [comment]
Hi there, sorry to disturb. Do you perhaps have input at hand that was used to generate this screenshot? I'd like to reproduce it myself.

**Comment by uruuru** [comment]
Should be this one (there are `elkt` and `json` files at the same location as well): 

https://github.com/eclipse-elk/elk-models/blob/master/realworld/ptolemy/hierarchical/ci_router_ComplexRouter.elkg
