### ISSUE TITLE
Move UI Contributions to Separate Feature

### ISSUE THREAD

**Issue by le-cds** [eclipse/elk#3]
As of now, ELK contributes a layout button, a preference page, and the layout view to the UI. Especially the layout view is not supposed to be seen by end users and will simply confuse them. Developers that use ELK also often want to hide the layout button and the preference page so keep them from being exposed to users.

A solution would be to move everything to an SDK feature intended for developers that want to integrate layout into their product. Once they found proper layout configurations, the SDK feature wouldn't be required in their final product anymore, leaving the UI as clean as possible.

**Comment by spoenemann** [comment]
Moving the UI to a separate feature is a good idea, but I don't think it should be the SDK feature. If we would declare the Layout view a developer feature, we should also remove all related API from the other plugins. We should rather make the UI adaptable, e.g. by allowing to restrict the visible options in the Layout view. The dependency injection approach should fit quite well to doing such things.

**Comment by le-cds** [comment]
I guess the point is that often, our users don't want automatic layout to contribute anything to the UI. No layout view, no automatically appearing layout buttons. So all of these contributions should be moved to a separate feature. It's perfectly fine if the core feature ships the relevant code for, say, the layout property view, but the actual UI registration should be done somewhere else.
