### ISSUE TITLE
Migrate debugging tools to ELK

### ISSUE THREAD

**Issue by le-cds** [eclipse/elk#31]
Our layout graph view and the timing view both are quite nice for debugging layout algorithms. I think it would be a good idea to add them to an `elk.debugging` plug-in and distribute them as part of the SDK feature.

**Comment by spoenemann** [comment]
I would even consider including the drawing code that is used for the layout graph view in elk.core.ui and improving it further. That could be a nice lightweight alternative to KLighD or Zest for simple use cases where people want to generate graphical views.

**Comment by le-cds** [comment]
Making the drawing code available in `core.ui` doesn't seem like a bad idea. However, the code's purpose should still be targeted towards debugging. That is, we shouldn't include any styling options or anything. The ELK project description specifically excludes the development of visualization frameworks, which I think is still a sensible thing.

I'll migrate the code over sometime soon.

**Comment by spoenemann** [comment]
> That is, we shouldn't include any styling options or anything. The ELK project description specifically excludes the development of visualization frameworks, which I think is still a sensible thing.

I agree. But at least a few options for choosing colors wouldn't hurt?

**Comment by le-cds** [comment]
> But at least a few options for choosing colors wouldn't hurt?

I guess not. ;)

**Comment by le-cds** [comment]
Done. The commits don't mention this ticket since I didn't have Internet access when I did this.
