### ISSUE TITLE
Alter GraphTransformer to perform rotate instead of transpose

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#310]
Currently the `GraphTransformer` performs a transpose of the graph elements' coordinates when it handles certain direction changes, for instance, `DOWN`. This, however, flips the order of the elements such that a cycle may be _clockwise_ in left-to-right layout and _counterclockwise_ in top-to-bottom layout. See the screenshot below. 

Performing a rotate instead of a transpose would solve the issue. 

![image](https://user-images.githubusercontent.com/7552459/36973681-36915b0e-2074-11e8-8ab4-c93671632a07.png)

**Comment by spoenemann** [comment]
What I like about transposing is that the order of elements is consistent regarding reading direction, i.e. left-to-right corresponds to top-to-bottom.

**Comment by uruuru** [comment]
We could make it an option 🙄.

**Comment by uruuru** [comment]
There's a layout option to configure this now: `directionCongruency: DirectionCongruency`. The default behavior corresponds to the old behavior (consistent reading direction).
