### ISSUE TITLE
Hugo errors

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#313]
At the moment `hugo` reports a couple of issues: 

```
$ hugo
Started building sites ...
ERROR 2018/03/08 17:18:10 Two or more menu items have the same name/identifier in Menu "main": "org-eclipse-elk-hierarchyHandling".
Rename or set an unique identifier.
ERROR 2018/03/08 17:18:10 Two or more menu items have the same name/identifier in Menu "main": "org-eclipse-elk-spacing-individualOverride".
Rename or set an unique identifier.
[...]
```

**Comment by le-cds** [comment]
We already generate algorithm-specific option documentation files if an algorithm contributes custom option documentation. However, those files get the same identifier as the regular option documentation file.

**Comment by le-cds** [comment]
There were also problems when names of different types of things (groups, algorithms, options) collided. This is now fixed by prepending each page ID by the type of what the page describes.
