### ISSUE TITLE
ELK Layered does not take minimum required node size into account with INCLUDE_CHILDREN

### ISSUE THREAD

**Issue by philip-alldredge** [eclipse/elk#316]
Using INCLUDE_CHILDREN can causes ports to be positioned improperly.
- Port sizes are either incorrect or they are positioned in a manner where they overlap
- If a node which contains ports also contains a child node then the ports may be placed outside of the port's node. See image below. The node size constraints for PORTS is not respected.

```
graph G1
elk.direction: RIGHT
hierarchyHandling: INCLUDE_CHILDREN
algorithm: org.eclipse.elk.layered
nodeLabels.placement: "[]"
minimum: "(40.0,35.0)"

node N30 {
	layout [ position: 177, 1130 ]
	nodeSize.constraints: "[PORTS, NODE_LABELS, MINIMUM_SIZE]"
	portConstraints: FREE
	port P53 {
		layout [
			size: 50, 200
		]
	}
	port P54 {
		layout [
			size: 50, 200
		]
	}
	
	node N31 {
		layout [ position: 233, 38 ]
		nodeSize.constraints: "[MINIMUM_SIZE]"
		minimum: "(246.0,35.0)"
	}
}

```

![result](https://user-images.githubusercontent.com/1376364/37484647-2222a46c-2857-11e8-9d94-7b4957447420.png)

**Comment by le-cds** [comment]
This problem ceases to occur once at least one port is connected to the child node. This is part of the problem described in #412, but I'm keeping this open to track this exact issue.
