### ISSUE TITLE
Allow Aligning Labels to the Top without Creating Extra Spacing

### ISSUE THREAD

**Issue by philip-alldredge** [eclipse/elk#317]
Placing labels at the top inside of a node results in an equal amount of spacing below the labels. It would be helpful if there was a way to to have the labels aligned to the top while not creating extra padding below the labels,

### Example Graph
```
graph G1
elk.direction: RIGHT
algorithm: org.eclipse.elk.layered

node N7 {
	layout [ position: 130, 12 ]
	nodeSize.constraints: "[NODE_LABELS]"
	nodeLabels.placement: "[H_CENTER, V_TOP, INSIDE]"
	label L1: "L1" {
		layout [ size: 103, 21 ]
	}
	label L2: "L2" {
		layout [ size: 103, 21 ]
	}
	label L3: "L3" {
		layout [ size: 103, 21 ]
	}
	label L4: "L4" {
		layout [ size: 103, 21 ]
	}
	label L5: "L5" {
		layout [ size: 103, 21 ]
	}
}
```

### Result
![example](https://user-images.githubusercontent.com/1376364/37779244-f4965d78-2db9-11e8-830f-fb5e6171c45d.png)

### Desired Result
![desired_result](https://user-images.githubusercontent.com/1376364/37779306-1cfd768e-2dba-11e8-800f-76b3549f71c9.png)

**Comment by le-cds** [comment]
You should be able to get the desired result either by configuring the labels as center labels (which I'm sure you don't want, or else you would have done so already ;) ) or by setting `nodeSize.options` to `ASYMMETRICAL`.

**Comment by philip-alldredge** [comment]
I had missed that option. Thank you!
