### ISSUE TITLE
/alg/layered/options/Spacings.java FIXME meaning

### ISSUE THREAD

**Issue by Nic30** [eclipse/elk#319]
Hello,

in https://github.com/eclipse/elk/blob/master/plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/options/Spacings.java#L21

There is FIXME in comment, what should be fixed exactly?

**Comment by uruuru** [comment]
I'd assume that it is a (forgotten) reminder for me to update the Javadoc.

**Comment by Nic30** [comment]
Ok, I was not sure if spacings should be integrated to global configuration or something like that.
