### ISSUE TITLE
Problems resolving layout option IDs in .elkm files

### ISSUE THREAD

**Issue by le-cds** [eclipse/elk#32]
Sometimes the .elkm editor fails to resolve layout option IDs in `support` declarations. For instance:

```
algorithm awesome(AwesomeLayoutProvider) {
    supports org.eclipse.elk.spacing.node
}
```

Sometimes, the ELK SDK fails to generate code because it was unable to resolve the layout option ID. Restarting Eclipse does not help. Reinstalling Eclipse does. Also, options declared locally in the same .elkm file can be resolved perfectly fine.

Is there a known cause for this problem and some way for fixing it?

**Comment by spoenemann** [comment]
I can't reproduce this. Do you have some hints for provoking the problem?

**Comment by le-cds** [comment]
Sadly and somewhat embarassingly, no. The problems went away with the new installation, and we couldn't think of anything that might have caused the issue. I thought some indices Xtext builds in the background may have been corrupted, and that there is some way of causing them to be rebuilt. If that could not be it, feel free to close the issue.

**Comment by spoenemann** [comment]
I have no idea how that could happen, so as long as we don't have a reproducible setup we cannot do anything.
