### ISSUE TITLE
python equivalent of elk.alg.layered

### ISSUE THREAD

**Issue by Nic30** [eclipse/elk#320]
Hello,
do you know about any python library with functionality of elk.alg.layered?

**Comment by uruuru** [comment]
What functionality are you referring to, exactly? 

The [NetworkX](https://networkx.github.io/documentation/stable/reference/drawing.html#module-networkx.drawing.layout) package has several drawing routines and afaik you can call graphviz from it. The _dot_ layouter is also based on the Sugiyama method and thus produces results similar to elk.layered.

**Comment by Nic30** [comment]
I would like to generate diagrams like one below:
![1](https://user-images.githubusercontent.com/5032806/38241559-d603a3ac-3732-11e8-931b-fae57cdae353.png)

As far as I know elk.alg.layered can do this, but does not have support for hierarchical ports, but it can be emulated. I was looking for another opensource library which can do same thing and I have found only original project from Keil.

**Comment by Nic30** [comment]
I am asking because I would like to  do a python port and:
* use it in experiments with evolutionary alg. 
* use it in frontend of opensource (MIT) framework for hardware development

**Comment by Nic30** [comment]
From my point of view it s stupid think to do. 
* I do not think that the original code will not change in time.
* I am skilled programmer but it is clear that I am not capable of such a task.
* Porting of such an amount of  code just for few projects is enormous waste of time.
* How long I will be able to maintain the project?
* It is possible to create wrapper for python.
* Implementation in python can be too slow.
 
But there are things that are making decision complicated.
* working distribution of *.jar-s in python packages is complicated
* I would like to understand the code, reading the paper + code is very effective method.
* Speed of porting can be greatly improved by use of automated tools.
* I would like to remove old algorithms and simplify/modify/replace the current ones.

As my personal challenge I try to rewrite essential parts of library or implement something similar.
* If it can be done in 40H I will do it. Otherwise I will experiment with evolutionary algorithms in java. If ti bring any profit I will send pull request.

**Comment by Nic30** [comment]
@uruuru You are right, edge routers has more dependencies than I expected, I was thinking that it is possible to get rid of most of the layout processors but it is not that easy.

I will implement python interface which will use ElkGraphJson.
