### ISSUE TITLE
Automatic size of nodes with children

### ISSUE THREAD

**Issue by Nic30** [eclipse/elk#322]
Hello,

is it possible to automatically to resolve size of children components in graph ?
I would like to specify children nodes like it is described in https://www.eclipse.org/elk/documentation/tooldevelopers/graphdatastructure/jsonformat.html. But I do not how to make nodes big enough for displaying the content.

**Comment by tylerlong** [comment]
As far as I can tell, if a node has children, its size you specified will be ignored and its size is auto calculated by its children's sizes.

So what you requested is already there. You can omit the sizes of nodes which have children.

**Comment by Nic30** [comment]
It seems that there is something wrong in my code, I will find out, thank you @tylerlong .
