### ISSUE TITLE
Hide  content of node in org.eclipse.elk.alg.layered

### ISSUE THREAD

**Issue by Nic30** [eclipse/elk#324]
Hello,

is there an property which controls rendering of child nodes?
I have a graph where some nodes has children nodes and children links specified I would like to hide them.

**Comment by uruuru** [comment]
There's an option [`NO_LAYOUT`](http://www.eclipse.org/elk/reference/options/org-eclipse-elk-nolayout.html) which can be set on nodes and edges that shall be excluded during layout. Maybe that's what you seek?

**Comment by Nic30** [comment]
NO_LAYOUT option excludes node completely from layout I would like to only hide child nodes inside of node. Currently I am using  NO_LAYOUT option on all child nodes.

**Comment by uruuru** [comment]
Can you elaborate, maybe with an illustration, what the difference between no layout and the behavior you desire is?

**Comment by Nic30** [comment]
Just ignore wrong offset of port markers for the moment.

I do have:
![screenshot from 2018-04-26 18-04-18](https://user-images.githubusercontent.com/5032806/39317671-76c8ec92-497c-11e8-8a92-c0bc9a88e419.png)

(node has single child named connection)

Desired output:

![screenshot from 2018-04-26 18-04-52](https://user-images.githubusercontent.com/5032806/39317689-7f299576-497c-11e8-82be-df8799135bf3.png)

(node still has single child and it has NO_LAYOUT property set)

Problem is that it is required to set NO_LAYOUT on all children, which can be time consuming.

**Comment by spoenemann** [comment]
What diagramming framework are you using?

**Comment by Nic30** [comment]
Diagram layout: https://github.com/OpenKieler/elkjs self updated to use elk 0.4.0-SNAPSHOT.
Graphic: https://github.com/OpenKieler/klayjs-d3 self updated + custom js.
Diagrams comes from hardware description and are modified for better readability.

 But I think NO_LAYOUT prop. is enough, I will close this issue as I no longer solving this issue.
