### ISSUE TITLE
Missing 'targets' in .elkm file should produce a warning

### ISSUE THREAD

**Issue by caspre24** [eclipse/elk#33]
When defining layout options in .elkm files, a missing 'targets' element should produce a warning.

**Comment by spoenemann** [comment]
That would mean the option is immediately marked with a warning when you start writing it. If we really want that, we should also add warnings for missing ids and missing names.

**Comment by le-cds** [comment]
How about some kind of a template mechanism that adds the typical elements you will always want once you enter the opening brace?

**Comment by spoenemann** [comment]
Yeah, we could just write a standard template for that.
