### ISSUE TITLE
Refer to builds on maven central

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#334]
Both the release and the nightly build information should include pointers to the builds published on maven central. These are particularly interesting for people who want to use the libraries in a pure Java context. 

Releases:
https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.eclipse.elk%22

Nightlies:
https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/elk/

**Comment by spoenemann** [comment]
Releases:
https://repo.maven.apache.org/maven2/org/eclipse/elk/
or
https://jcenter.bintray.com/org/eclipse/elk/
