### ISSUE TITLE
Layout partitioning (Throws NPE, too strict requirements?)

### ISSUE THREAD

**Issue by eNBeWe** [eclipse/elk#338]
Currently the layout partitioning in ELK layered requires a partition configured on every node.
If there is a node without a partition set it throws a NPE in `PartitionProcessor.java:70`. If assertions are enabled it creates an appropriate error message instead. This makes editing a graph quite annoying, as creating a new node immediately throws the NPE before I can configure the partition.

Thing a) Maybe the error should be a bit more descriptive.
Thing b) Why must every node have a partition? The "definition" of partitions sais that for all nodes in partition `i` the fact holds that nodes with partitions smaller than `i` are placed left and nodes with bigger partitions are placed right of the node. Nodes without a partition could just fit in the graph wherever they would be placed normally.

**Comment by uruuru** [comment]
I agree with b) and don't see any reason to require indexes for all nodes. 

Can you please verify that it behaves as desired?

**Comment by eNBeWe** [comment]
In my tests it is behaving as expected.
