### ISSUE TITLE
[layered] Superfluous bend points created with polyline routing

### ISSUE THREAD

**Issue by spoenemann** [eclipse/elk#341]
See [this example graph](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABBYEQJYCZQFzQHYAcC2BaOBTNuKeKAxgJ5YDmATgIZoAWUANOJFADa1kD2ArgBcA8mgEweKAM5IwoSPOi4OAawB0tDpR7UYAhhhmduuargSsF7JWrgxTJMRMMBVAAos2lqNdVnKuACV+MRRKQ1chABkATUiASQA5AFEoTzAAXwt2EgYYDjhTFBkAbTT5OUsFWARkKAABPVwYWgB6NFMANxhcAHcPSqqcvILCEoBdLIGIbzh-aWRiibLKowAjJXmwUqnKip2B6sMGhibW9twu3paudY5+-YOBXAAPASPG5rbO7r7Jh6rnjIAKx-f7sMjA0Fg6A9eB6GQARgADEDVAAWAAcaIAzAB2EHLMFQE4wSgMN7IBEY1RIgBsACYgYSpulmfIlg8oIDkDjVLj6UjcUjsQjGVCvBCedjqVjaUiAJx4gmc2FweGUhGozE4-HiqokskUsD06l0xnMzLMvZTQ61Y6nFokbS4e47KBDfKFcZ6+QzObetnsG4bEqByzW6HQeDvEmtJ2ma60W6uyPQJ6vGMO+Mun37LmQsM2yVgZWp6aq9VgDH0mmK3WFg4G8mIjENyCsh4cvPcsDytGqPvy+lU+uc4vIjG58twpjIIe1pVT6BNo0mi16iMraN2j6tMy6bQpg4ekZFBZdt1+XCbRZLtYhhZtiCbonb6D2z77gTaRPJpePF4jXqXcWi-Q9-xWHtSzLKBi2g1MoArWdewRVQGXgyNiSaQ0WyfDJCwvG0ezRXFVHpXFsR1DCVmLbEgVQxVaVxEdqK8JDESRVD0LvFcZDXAZLQGF8qjfYDY0TUI+Fof07xPL1zzvK8b0Ig5gw4G88OEzlRI-VouEk6Tr1-JQj2hKB0yA3SJMoKSZLw30oIgiUCzLac1WQ0VsVUUVWP+LDSWbSlqXNSMO32FTIL47FaW87EkQxIE61831i3ImsTWxeUsSVJFcpRO92MpbEvJ8njsMC41gqZASN0LW1FA4XAHGoJxZNyT1RgUuqlIDTk1I0yMtLzUSlCagQWpQYy7icqoLMMUbmta+z2Ec5bpjgmbfUKksYqRNFaQxUdXP8nCgrwsKdgirwe2RUj5X5WkgW4urizlAqZxkWldv2w7kvYXjkH4ypBN2OqdJAjpaB0JNGqwUxJB4DgOhMUyvDkzqtiuqoeq6vqkwfLZNLWqManfCGoeaVZYfhxHkeoKbUb8uad3EyHoap3A4evWmUc2laXOOjbicQj7KS+vkWL56YAbAKlzoIu8e0y9FRWRJK71S-l0XirKqLy-K6u2hFcRi5jfrKgLV1bGqrTB0mxIdYI0EERnfXRs9McU2Zr16vN+tDQbhfB8SncEBmpbTQDM0+UO3gj-NkD+t0hdcmFRd7GKEvV4WZapGl0PlztFcReV5QHejjcll6S+CjFctxDEfP1+l3vcjjM8Sxc6plk185C4Hau0+2rPaHgSGvaQ2uGeTPe673lLvf3H0D1P6odz5R-HyRJHD4XmbJ8TN4n13uwFmCU+Oo26XLkUxRz8qjTzs1quhC6pixhyZGxelM+RIEfqOsnGuZE66CkboyZurdKwIgRDFeUQJb5J2XA-PipoC42yEnbeajVFooBwDwHoKAOA8FoOYOq7tfaXnnpQm0S9CYr2OiNHB40JD4MIcQ0hu9V7728MwiabCiEkLIavVaq8L4wSNnFVQWcu6r1ztbV+Cs6o9iFKoJ6tI0TPw1oiFuht04Ik0dIzugCbQ9wUZYN+hE-Q+2XqDIehg8AECIIQcgiAR7fF6AAPistmE+0wEZ8GoOPaOZwPG-DqgIKG-hLIgV8XeAJQTcCuB4DAFARohrXRkFrRKxt5QHRMWOGQOIZT7QVEqQsIM3TrCIMk1JAgBrQgyURRE2J460VxGXRiZt8TnRmk0g4N1WnC3HFlEB9dwFAn1i-MEb8Bgf3YJE6g0TalpJkP0-mlJ4reRRAApBKUWm0gqeuW29jaiOMIMQVx7iLg-G8SBMC1A-HQAScElmDpziXHCZyRZ0SQmgVsN+R58T+CJJWekvCCdZacXRAyDE8otEQuLMU6RpSkoVLvNUuAYKF4RKibgAQYK1kQp7KM+Kxi9ngi-h0gc0VunTJZMczBpzoDnOcaQMgbiQIfNuVZfSNlDKTzqi8l0byN5hKeeZPFMTxJ8tsj7YFgTx6EuQOs6YgykSqGKplbKBS8xIulCiuUaKHiVJtJi7FAdGnCyVvSfsGI64yN1USdpnTaUsULuFO8Pz8XKtkMSr+trpEOvJTNWCX9cpqOKrrHKeV6UCUZXY4a9tWWXI5T450niFosKKAqxJfy4m4qWfi7BY0JoSuFb61V0AbqGNLka2RZlxzxXRXVc1KS0k4u+VKyt-rKS1ryWUp1RYZD2qORgxNbpRIppcWm+5ALtB3PEgWzkwq-kPIld66VWZnTlpBUq9t4LMIqJrExPJ5tEVf3ojSpi7qTUYouRa2xYIq2f0BmXNEqtB0UucsgOKGqEHar1rG3pRMRF8XfZ+7OYjgEmnGU3YDoUlFdqLQSg9RKj06NQj-Su57MLjmimOgeJyk0OPwBcmdnLxIPMXQ6WVArd2KpFQfB066vVSr+XRuyK691JLQyq3tst6ReTREOKueHL0MTdb9FtnI211M7XmTdPaMOAzrmolEjrv3QFohGgD0b8RTMIxYweJGzlkbZVcudB5qA0c+GzSm1NuZI15kKnja751AsLb80VrR7Mw05jTZznnuOMeU2ZElppNOhtolerpt79imoOHJjtlrn3Wp0aRXEzFtQNvPuG-9UadWTIQ4oouXmfV8b9SpwTmXstFei-l7WcKiuGZNQm8MWCzNONTZR2jtADJzFs3GHdubXnMc+Jx+V5Wt2fGXXmCtlWq2Qp-hB4cX6GuAy1hlfTxXcpxqI7Jh9B6GlpbA0VMuQpJkN1KsMviP9NVokZNdiBeV6QgYYTBQZF2URgJu9BykozYO-Ze3tj1l02MobC0SGtpEgS4ke2JxtByjMKES5AJpa9p3st6xN-r-LBtWVjgxvNPnrJysFch7z43WhE9G7xup6HwvhpPYqOiUGkebfShiQDMbQd3tbUd+TNDHjdsWwJxkXlpRkvZ86u7MVKJPYmc3FH8g0fPk6yy8zPXeV4-J0Nr4Y9j50447r+jEOqfr1CYb7exP90M-49V4qqJ7qoty35TWXOecGZKzsNXVRkv1OFysJTYvHcJRAcxdbF7Ab3YV3DpXr2VfthM5O5NWuKNZompmvhrC4AEMEaQ23THeGlqWpT4ttRM+5-zxw4R82eNQ78jWjVdao-ieQHKGTeYA8KbdCH+3VWmd9pbwOmX7uilIiTxAP3GOp3p+x1ZPzHMuYIyC-rubbpV2k6X451fdMN3sdJxvm0C2B9LZuuRPkdWqIbeNFrTRzWgN84S-empx3Uv-BfRsmrV+DH1duwDrXHBiDiiGDu-ObhVmfgJgiJRCrB0vklpmGkVIcm1uOh1sylAFjpZiHIIM7AIOviNq5oxn8rTtNvmoQSFqCqHkPsaAgpqsGmPoUoAWMsDrtkiG9vzodm-kLrjIpqLlAdVrAhqhRHtAgbfjASgQlu1goLPmnt1hRu4tbpIAQaYEXn8kfDbhATNsNqoXTo3pyErOHiaJHowXqjBqAs9mwRwS-gLtwSlrwX3vwasg7jQcbF5PajerhhzrLARqgcDGkGMCAOkEAA). At the time of creating this issue, the online JSON Editor does not support this model yet, but I [already fixed the cause of that problem](https://github.com/OpenKieler/elkgraph-web/commit/2515a84a4f93cd2215456c0c1313f7078e385d75).

There is a superflous bend point at the edge from `@theia/editor` to `@theia/variable-resolver`, which can be seen by the arrow having a wrong orientation. I can't exclude that this could be an issue of [elkjs](https://github.com/OpenKieler/elkjs), but my assumption is that it's a bug in [PolylineEdgeRouter](https://github.com/eclipse/elk/blob/master/plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p5edges/PolylineEdgeRouter.java).

**Comment by spoenemann** [comment]
@uruuru do we have a conversion tool from elkjs-json to elkt?

**Comment by uruuru** [comment]
@spoenemann no _tool_ as such but you can use KIELER's [_formats service_](https://rtsys.informatik.uni-kiel.de/confluence/display/KIELER/Graph+Formats+Service) with its export wizard: the `de.cau.cs.kieler.formats.json` plugin simply delegates to elk's json format.

**Comment by spoenemann** [comment]
In the [addBendPoint](https://github.com/eclipse/elk/blob/150fc359a36181eb59de5b4d0e9728820d67dfe2/plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p5edges/PolylineEdgeRouter.java#L433-L458) method, PolylineEdgeRouter tries to avoid unnecessary bend points. This does not work in this case because the points are not exactly equal.

When is the elkgraph-web page updated? The build has already run yesterday.

**Comment by le-cds** [comment]
The problem was that `@theia/variable-resolver` and `@theia/languages` were in the same layer, but the former had a slightly smaller height than the latter. Thus, the polyline edge router inserted a bend point at the layer boundary to ensure that the edge's last segment would be routed horizontally through the layer.

I added a new option that specifies how far into a layer an edge may extend before a horizontal segment is created for it. The option is now set to a very conservative setting of 2 by default.
