### ISSUE TITLE
ComponentGroupGraphPlacer not working properly

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#342]
The placer fails for [this model](https://github.com/eclipse/elk-models/blob/master/tests/layered/connected_components/all_four_port_sides.elkt). According to the model's comment this has been the case before. 

![image](https://user-images.githubusercontent.com/7552459/40536636-2513bbf0-600d-11e8-9ef3-8375e887c9bc.png)

**Comment by le-cds** [comment]
This is strange. The bug was fixed in response to ticket KIPRA-1423, but only half the fix seems to have made it to ELK. I added the other half, now it works again.
