### ISSUE TITLE
Json graph format should support 'json5' style

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#344]
Writing _correct_ json by hand, for instance for testing, is tedious. 

[JSON5](https://json5.org/) is intended as _JSON for humans_ and 
> is a superset of JSON that aims to alleviate some of the limitations of JSON by expanding its syntax to include some productions from ECMAScript 5.1.

Check if it's possible to support most of its features using the GSON parser.

**Comment by le-cds** [comment]
@uruuru Is there any chance this will be completed at some point? If not, how about closing it?

**Comment by uruuru** [comment]
It would still be nice and shouldn't be too much effort if the parser somehow supports it. However, since we're cleaning up, I'll close it for now.

**Comment by uruuru** [comment]
However, we can add gson's `setLenient()`.

**Comment by uruuru** [comment]
It turned out that with newer gson versions than the one currently required the parser actually has been lenient all the time (due to a bug in gson itself). 

I've now added support to switch the mode in `ElkGraphJson#import` though.

**Comment by uruuru** [comment]
The `lenient` option is now available and activated by default.
