### ISSUE TITLE
On-edge labels not always on polyline edges

### ISSUE THREAD

**Issue by le-cds** [eclipse/elk#347]
If inline edge labels are active, they may still end up being placed next to their edge if polyline edge routing is active.

Example with polyline edge routing:
<img width="792" alt="screen shot 2018-06-09 at 14 09 44" src="https://user-images.githubusercontent.com/7465584/41191371-d5d228a4-6bee-11e8-92fa-92aa27d2777a.png">

Same example with orthogonal edges:
<img width="792" alt="screen shot 2018-06-09 at 14 09 59" src="https://user-images.githubusercontent.com/7465584/41191374-dc4c98cc-6bee-11e8-8d5e-a31f5a9dfc4c.png">

Example file:
```
edgeRouting: POLYLINE

node A
node B
node C

node D
node E
node F

edge A -> B {
	label "Bla bla bla"
}
edge B -> C {
	label "Bla bla bla"
}
edge C -> D {
	label "Bla bla bla"
}
edge C -> E {
	label "Bla bla bla"
}
edge C -> F {
	label "Bla bla bla"
}
```

**Comment by le-cds** [comment]
A corresponding tickets was filed [for elkjs](https://github.com/OpenKieler/elkjs/issues/22).

**Comment by uruuru** [comment]
Can you set a corresponding milestone there (or 'properly' link the issue)?

**Comment by le-cds** [comment]
Where? At the elkjs repository? You set the milestone already, afaics?

Anyway, how do I link issues properly?

**Comment by uruuru** [comment]
Nevermind, I should have looked at the previous comments instead of just the last one via mail :).
