### ISSUE TITLE
org.eclipse.elk.alg.radial imports JUnit

### ISSUE THREAD

**Issue by rostigerloeffel** [eclipse/elk#349]
The bundle org.eclipse.elk.alg.radial imports the packages junit.framework and org.junit from JUnit but makes no use of them (as far as I can see). Unfortunately, this leads to some unnecessary requirements in my product build.

I'm using ELK 0.4.0 and the exact bundle version is 0.4.0.201802120309.

**Comment by uruuru** [comment]
Thanks for bringing this up. 

I already removed the dependencies seven days after your nightly version was build: c3521414487bc20b83afc788b77014ee54780416.

**Comment by le-cds** [comment]
That does mean that we can close the issue, doesn't it? :)

**Comment by uruuru** [comment]
I guess so, but the fix should be in 0.4.0 already.
