### ISSUE TITLE
SOUTH ports and NORTH ports are overlapped 

### ISSUE THREAD

**Issue by LeeYufang** [eclipse/elk#350]
Hi,
In my diagram, I have a compound node container which has several children, including its ports and children node containers. When my parent node container has SOUTH or NORTH ports, which are unconnected and have no edges, these SOUTH and NORTH ports are overlapped.
I have no idea about when these SOUTH and NORTH ports ' position are fixed. Can you give me some hints or tell me how to fix this issue?
I use this property: HierarchyHandling.INCLUDE_CHILDREN
ELK version is 0.2.2
Thanks and hope for your reply.

**Comment by le-cds** [comment]
This issue should be gone in 0.4.0.
