### ISSUE TITLE
Documentation's layout option ids contain wrong prefix

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#354]
On the [documentation page](https://www.eclipse.org/elk/reference/options.html) for the layout options, the id's are falsely prefixed with `option`. 

Like so:
`option."org.eclipse.elk.separateConnectedComponents"`

The same goes for the algorithms overview page (prefix `alg`) and the layout option group page (`group`).

**Comment by le-cds** [comment]
Oh, that's rather stupid... It's a consequence of my fix for #313. I'll check how I can solve that.
