### ISSUE TITLE
Issue with Sirius Custom Layout and ELK Layout

### ISSUE THREAD

**Issue by rakeshnidavani** [eclipse/elk#356]
Hello ,

When using Sirius with our custom layouts, we encountered an issue due to the presence of ELK plugins.

ELK Defines a generic laout provider which is contributed using the extension : org.eclipse.gmf.runtime.diagram.ui.layoutProviders
Plugin : org.eclipse.elk.conn.gmf

Problem 1 : The ELK Layout provider has a very general "provides" method :
/**
* {@inheritDoc}
*/
public boolean provides(final IOperation operation) {
return operation instanceof ILayoutNodeOperation;
}

Due to this, the layout provider is applicable for almost all use cases.
This is not an issue on its own, since a generic layout provider is expected to work this way.

However,

Problem 2 : The ELK Layout Provider is also contributed with the highest possible priority.
In the extension specification, the provider is assigned with the priority "Highest".

Due to the above two points, it is impossible to have a custom layout contributed when ELK Layout is included in the list of plugins.

Proposal :
Change the priority of the ELK Layout contribution to a lower value.
This will ensure that other custom layouts can be integrated along with ELK Layouts.

Regards,
Rakesh

**Comment by spoenemann** [comment]
Thanks, I created #357 for this.

**Comment by le-cds** [comment]
That pull request lowers the priority from `Highest` to `High`. Is that enough, @rakeshnidavani?

**Comment by rakeshnidavani** [comment]
Yes, This change will be sufficient,Thank you .

**Comment by rakeshnidavani** [comment]
Hello, When can we expect the release of 0.5.0 version? If required, will an intermediate minor release be made available with this fix ?

**Comment by spoenemann** [comment]
You can use the nightly update site:
http://build.eclipse.org/modeling/elk/updates/nightly/

**Comment by rakeshnidavani** [comment]
Hi, 
We found further issues integrating the layout provider with priority set to "Hgh". 
On further analysis, it seems to be the best approach to set the priority for the layout as "Lowest". 
Can you please incorporate this change too ? 

PS. By setting the layout to lowest, there are chances that other custom layouts (if not properly configured) will be invoked instead of the ELK Layout. However, this can be avoided by defining our own custom layout that extends ELK layout, but with a higher priority.

**Comment by spoenemann** [comment]
If you don't want ELK layout, why don't you just remove the plugins?
