### ISSUE TITLE
Design a proper logo

### ISSUE THREAD

**Issue by le-cds** [eclipse/elk#362]
The ELK project finally wants a proper logo.

**Comment by le-cds** [comment]
I have started working on an idea I've had. Feel free to hate all of these prototypes; I mainly want to get a discussion going which will hopefully result in a number of directions we might head into. Chip in with your own ideas, whether accompanied by sketches or not.

### 1
![artboard1](https://user-images.githubusercontent.com/7465584/44054736-b73644c4-9f43-11e8-91a5-223d6188af0d.png)

### 2
![artboard2](https://user-images.githubusercontent.com/7465584/44054745-bce9dc0a-9f43-11e8-8bf7-e76dee7f26d1.png)

### 3
![artboard3 artboard](https://user-images.githubusercontent.com/7465584/44054755-c3677dda-9f43-11e8-8a4e-436071889d3c.png)

### 4
![artboard3_2](https://user-images.githubusercontent.com/7465584/44054758-c76790e6-9f43-11e8-9fc9-aa2ba466ddc5.png)

### 5
![artboard3](https://user-images.githubusercontent.com/7465584/44054772-cbb32a7a-9f43-11e8-8e2c-6d1f638022c6.png)

I'm well aware that none of these includes an actual ELK. This is because I don't think an ELK will work well as a logo, and even if it will, I don't have the skills necessary to make it work. ;)

**Comment by le-cds** [comment]
@uruuru sent me a drawing which I just tried to recreate. The logo itself is more of an outline as it is now; the colours and everything would probably be way different in the final version, but I'm curious to hear what people think of the general idea.

![artboard6](https://user-images.githubusercontent.com/7465584/44082147-b6c6f318-9fb0-11e8-9b52-4132ec1a0185.png)

![artboard7](https://user-images.githubusercontent.com/7465584/44082151-b9f3fb80-9fb0-11e8-9cea-486af9da5891.png)

**Comment by le-cds** [comment]
@uruuru suggested going in a similar direction as the GitHub logo, as in using negative space in a dark circle or box. I'm not sure whether the previous attempt would be too complex for that. After all, the GitHub logo works not only as a logo, but also as a small icon due to its simplicity. So I tried to make the whole thing a little less complex as well. There's a few things that bother me, but I'll just let people weigh in with their opinion before tearing the whole thing to pieces myself. 😁 

![logo](https://user-images.githubusercontent.com/7465584/44311056-dcf75a80-a3e0-11e8-88d2-fe928f45f959.png)

**Comment by uruuru** [comment]
Some ideas based on a "grain kernel": 

![image](https://user-images.githubusercontent.com/7552459/81343713-c661cd00-90b5-11ea-8d7e-8440164e7995.png)


![image](https://user-images.githubusercontent.com/7552459/81343743-d5e11600-90b5-11ea-9af4-c92a18e7ac63.png)


![image](https://user-images.githubusercontent.com/7552459/81343759-e0031480-90b5-11ea-91fb-1974ff63963f.png)

**Comment by shean42** [comment]
Having some fun during lunch break - certainly there are many facets this could be improved upon. Just thought to throw out the idea :-))

![elkElk](https://user-images.githubusercontent.com/22164312/81396984-bf26d780-9126-11ea-9830-23c220e7f4d6.png)

**Comment by le-cds** [comment]
Nice, I like all of these ideas. They'll have to be refined, of course, but I like the ideas behind them! 🙂

**Comment by uruuru** [comment]
Places where to put the logo
 * file icons (elkt melk elkg)
 * ELK Website
    * top-left
    * jumbotron in the middle
* ELK Live
   * landing page middle above text
   * individual pages, top-left (ELK Demonstrators)


Try to create two logo versions for different backgrounds.

**Comment by uruuru** [comment]
@shean42 we'd be interested in trying some variants of your idea. To be on the safe side: did you derive your drawing from an existing one or did you create it from scratch?

**Comment by shean42** [comment]
Glad you like the idea! :-)

The sketch was thrown together with an arbitrary graph from the web and the elk borrowed from [here](https://www.cleanpng.com/png-red-deer-elk-reindeer-3937631/). Not sure if their license is appropriate for an 'official' logo though. 

Taking a look at the sketch today I think that it probably would look much better with light bluish shades for the elk, but opinions on that certainly differ :-)

**Comment by le-cds** [comment]
According to [this page](https://www.cleanpng.com/dmca.html), the images they provide are "believed to be in public domain" and "eblieved to be posted within ou rights according to hte U.S. Copyright Fair Use Act" [sic]. They don't seem to take any particular measures in order to ensure that, or at least have the posters sign some kind of declaration to that effect.

I believe that means we'll have to draw our own, custom ELK head. Still, we like the idea of the head and were already talking about plans of having it grace the background of our website (in much lighter colours). 🙂

**Comment by le-cds** [comment]
Thanks to @shean42 for triggering us on this again and his ideas, and thanks to @uruuru for finally giving us a logo! Well done!
