### ISSUE TITLE
Possible hierarchical edge routing problem

### ISSUE THREAD

**Issue by le-cds** [eclipse/elk#369]
There is a possible problem with routing short hierarchical edges:

![bug](https://user-images.githubusercontent.com/7465584/44527086-2d72fe80-a6e6-11e8-9616-3d1ae15f8895.png)

**Comment by uruuru** [comment]
Maybe it's offset vertically? Is the edge's source point adapted by KLighD?

**Comment by le-cds** [comment]
The whole child graph seems to be offset. Note how the edge connects not to the centre point of the right side of `a_port1`, but to a corner. There may be problems with paddings or some such.

**Comment by le-cds** [comment]
This was actually caused by #401.
