### ISSUE TITLE
Edge from child node to container's port breaks external layout

### ISSUE THREAD

**Issue by mezzario** [eclipse/elk#375]
In my project I found that edge from child node to container's port breaks external layout. Please see explanation below.

JSON example:

```json
{
  "id": "ROOT",
  "children": [
    {
      "id": "a",
      "width": 100,
      "height": 100
    },
    {
      "id": "b",
      "children": [
        {
          "id": "c",
          "width": 100,
          "height": 100
        }
      ],
      "ports": [
        {
          "id": "d",
          "width": 10,
          "height": 10
        }
      ],
      "edges": [
        {
          "id": "c-to-d",
          "sources": ["c"],
          "targets": ["d"]
        }
      ]
    }
  ],
  "edges": [
    {
      "id": "a-to-b",
      "sources": ["a"],
      "targets": ["b"]
    }
  ]
}
```

Try it here: https://rtsys.informatik.uni-kiel.de/elklive/json.html

Result:

![image](https://user-images.githubusercontent.com/2454284/45973268-cd2bf100-bff2-11e8-95bb-755856443bed.png)

Now remove edge inside container:

```json
{
  "id": "ROOT",
  "children": [
    {
      "id": "a",
      "width": 100,
      "height": 100
    },
    {
      "id": "b",
      "children": [
        {
          "id": "c",
          "width": 100,
          "height": 100
        }
      ],
      "ports": [
        {
          "id": "d",
          "width": 10,
          "height": 10
        }
      ]
    }
  ],
  "edges": [
    {
      "id": "a-to-b",
      "sources": ["a"],
      "targets": ["b"]
    }
  ]
}
```

Result:

![image](https://user-images.githubusercontent.com/2454284/45973410-3ca1e080-bff3-11e8-972e-795517df3c67.png)

It also affects other edges connected to container if added.

NOTE: Confirmed this behavior by inspecting actual JSON output from ELK (actual calculated coordinates of objects). I'm using [elkjs](https://github.com/OpenKieler/elkjs). Should i file bug there?

#### BEFORE

![image](https://user-images.githubusercontent.com/2454284/45974253-b33fdd80-bff5-11e8-9b58-a01c463bd697.png)

Now **ONLY** add edge from **E** to container's east port (there's small 1x1 port):

#### AFTER

![image](https://user-images.githubusercontent.com/2454284/45974104-3dd40d00-bff5-11e8-8260-735d6da659fe.png)

Notice how rest of layout is affected? Also, how tight layout become inside container?

**Comment by uruuru** [comment]
@le-cds can you verify that this is happening in ELK as well?

**Comment by mezzario** [comment]
I confirm it happening for ELK as well.

Go to: https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html

It uses custom ELK text format and compiles graph on server using real ELK (transport is done via web sockets).

Enter this graph:

```
algorithm: org.eclipse.elk.layered

node n1 {
    layout [ size: 50, 50 ]
}

edge n1 -> n2

node n2 {
    layout [ size: 50, 50 ]

    port p2 {
        layout [ size: 5, 5 ]
    }

    node n2_1 {
        layout [
            position: 12.807, 197
            size: 50, 50
        ]
    }

    edge n2_1 -> p2
}
```

You'll see same broken layout as in bug description. Remove `edge n2_1 -> p2` to fix layout.

**Comment by le-cds** [comment]
I think this is what eclipse/elk#60 is all about.

**Comment by le-cds** [comment]
Since this is a duplicate ticket, I'm closing this. Workaround is to always specify explicit ports. Feel free to reopen if you require further assistance.
