### ISSUE TITLE
Zero-size ports behave differently in ELKT editor vs. Java API

### ISSUE THREAD

**Issue by arotenberg** [eclipse/elk#376]
In the Java API, ports can be given a size of 0 x 0 and ELK appears to respect this when laying out edges, i.e. it treats the center of the port as being at the port's location for the purposes of edge endpoint placement. This is useful when working with diagram notations where the ports should logically contribute no size to the layout. On the other hand, specifying a 0 x 0 port in the ELKT online editor seems to magically result in a 5 x 5 port instead, although you can get arbitrarily close with e.g. a 0.1 x 0.1 port.

[Example ELKT editor link](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUEQHYQE5qkCMaA3kWsxthAK5xoDaaAzjABeOdDQAMAGjTi0AXSYsADtDgBhCKT5wowGKTh90AMQCSADQCiAEQD6ABQDyAZQXNlULorqMWv1lg4uXmUBOBgNUUk0AFZ+IRE0KLE5VzQAXyIM8kpqACYGVMwAzh444UipGXlfdzUNLR09A2Nza3tnVNq0RXyfP2YiwNKQ+HDSdCjYgXLEqWTqlgyMwjAqWgA6LzQAWgA+PM3coA). Note how the edge is aligned to the center of the 5 x 5 ports, rather than to the ports' locations as would be expected for a 0 x 0 port.

Example Java code:

    LayoutMetaDataService.getInstance();  // Forces initialization of ELK reflective classes.
    ElkNode rootNode = ElkGraphUtil.createGraph();
    
    ElkNode elkNode1 = ElkGraphUtil.createNode(rootNode);
    elkNode1.setDimensions(10.0, 10.0);
    elkNode1.setProperty(CoreOptions.PORT_CONSTRAINTS, PortConstraints.FIXED_POS);
    
    ElkPort elkPort1 = ElkGraphUtil.createPort(elkNode1);
    elkPort1.setDimensions(0.0, 0.0);
    elkPort1.setLocation(10.0, 5.0);
    
    ElkNode elkNode2 = ElkGraphUtil.createNode(rootNode);
    elkNode2.setDimensions(10.0, 10.0);
    elkNode2.setProperty(CoreOptions.PORT_CONSTRAINTS, PortConstraints.FIXED_POS);
    
    ElkPort elkPort2 = ElkGraphUtil.createPort(elkNode2);
    elkPort2.setDimensions(0.0, 0.0);
    elkPort2.setLocation(0.0, 5.0);
    
    ElkEdge edge = ElkGraphUtil.createEdge(rootNode);
    edge.getSources().add(elkPort1);
    edge.getTargets().add(elkPort2);
    
    LayeredLayoutProvider layeredLayoutProvider = new LayeredLayoutProvider();
    layeredLayoutProvider.initialize(null);
    try {
        BasicProgressMonitor progressMonitor = new BasicProgressMonitor();
        layeredLayoutProvider.layout(rootNode, progressMonitor);
    } finally {
        layeredLayoutProvider.dispose();
    }
    
    System.out.println(elkNode1);
    System.out.println(elkNode2);
    System.out.println(edge.getSections());

Java code output (note how the edge is aligned as if the ports actually have zero size):

    ElkNode (12.0,12.0 | 10.0,10.0)
    ElkNode (42.0,12.0 | 10.0,10.0)
    [org.eclipse.elk.graph.impl.ElkEdgeSectionImpl@1a9ad43 (startX: 22.0, startY: 17.0, endX: 42.0, endY: 17.0, identifier: null)]

**Comment by uruuru** [comment]
> On the other hand, specifying a 0 x 0 port in the ELKT online editor seems to magically result in a 5 x 5 port instead, although you can get arbitrarily close with e.g. a 0.1 x 0.1 port.

That behavior is hardcoded in the the onlne editor's [ElkGraphDiagramGenerator (line 134ff)](https://github.com/OpenKieler/elkgraph-web/blob/master/server/elkgraph-web/src/main/java/de/cau/cs/kieler/elkgraph/web/ElkGraphDiagramGenerator.xtend#L134). If no port size is specified it's simply set to 5. I guess it's like this to have a convenient demonstrator.

**Comment by le-cds** [comment]
> I guess it's like this to have a convenient demonstrator.

Yeah, I think so as well. Since the online editor is only meant as a (very simple) grounds for playing around with things a little, I don't think we should change that, really. ;)
