### ISSUE TITLE
Error when layouting graph

### ISSUE THREAD

**Issue by tivervac** [eclipse/elk#377]
While trying to layout a specific graph I get the error:
```
Failed to perform diagram layout.
Node '0' has its layer constraint set to FIRST_SEPARATE, but has at least one incoming edge.
FIRST_SEPARATE nodes must not have incoming edges.
```
When I remove an edge I can make it work again.
See attachments for the graphs, both with and without the error (.elkg disguised as .txt to be able to upload to github).

Response on gitter:
```
@tivervac I had a quick look at it and for me not every edge fixed the issue.
If I see it correctly, you have a combination of hierarchical edge, hyperedge, inverted port, and inside self-loop.
Can you please file an issue on github? It may simply be a bug.
```
[noError.txt](https://github.com/eclipse/elk/files/2456439/noError.txt)
[withError.txt](https://github.com/eclipse/elk/files/2456440/withError.txt)

**Comment by le-cds** [comment]
I was able to distill the example down to the following:

```
node N1 {
	portConstraints: FIXED_SIDE
	
	port P1 {
		org.eclipse.elk.^port.side: WEST
	}
	
	node N2
	node N3
	node N4 {
		portConstraints: FIXED_SIDE
		
		port P7 {
			org.eclipse.elk.^port.side: WEST
		}
	}
	
	edge N4.P7 -> N2
	edge N4.P7 -> N3
	edge P1 -> N4.P7
}
```

Feels like a cycle breaking bug. We'll have to look into it.

**Comment by le-cds** [comment]
@tivervac Do you mind if we publish that example as part of our project in our repository of test models?

**Comment by tivervac** [comment]
@le-cds No problem, go ahead!
