### ISSUE TITLE
 [ELK] Labels of edges are not correctly placed and overlapped in Sirius

### ISSUE THREAD

**Issue by LeeYufang** [eclipse/elk#378]
Hi, 
I am using ELK layered algorithm to layout my Sirius diagram. 
**Environment:**
 Eclipse: Photon
 Sirius: 6.0
 ELK: 0.4.1
 Model: family
**Configurations:**
Layout: ELK Layered in odesign file
Option: mergeEdges = true  in Layered.melk
Add "Begin Label" and "End Label" for "fatherEdge" and "motherEdge" in odesign of family

This is my layout result on family diagram by clicking "Arrange All" button.(see family_diagram.png)
From this picture, we can see that some edges are overlapped with labels, edges or icons.
The another picture is my layout result on the same diagram by clicking ELK Layout button in the toolbar.(see family_graph.png)
From the picture, we can see that all the edge labels are well placed without overlapping.

I am confused,  is it ELK's problem? Or is it connection problem between Sirius and ELK which causes this result?
Thanks in advance and hope for your reply.

**Comment by LeeYufang** [comment]
I  can not add attachment at github, please see eclipse forum:
https://www.eclipse.org/forums/index.php/m/1796388/#msg_1796388

**Comment by le-cds** [comment]
This is probably due to the Sirius layout connector (see the forum thread linked to above), thus this issue is closed.
