### ISSUE TITLE
Port Label Placement INSIDE seems to be broken

### ISSUE THREAD

**Issue by ssmifi** [eclipse/elk#380]
Port Label Placement INSIDE seems to be broken. There are images attached. The one with the inside conf stacks the ports at the same position. (Other settings are equal.)
![rd_plp_inside](https://user-images.githubusercontent.com/44293762/47218613-aa4feb00-d3ac-11e8-8c4a-0f9a79e5d34e.png)
![rd_plp_outside](https://user-images.githubusercontent.com/44293762/47218618-ad4adb80-d3ac-11e8-90c6-eab96f8ec4d9.png)

[T2.kgx.zip](https://github.com/eclipse/elk/files/2495818/T2.kgx.zip)

**Comment by le-cds** [comment]
@ssmifi I haven't been able to reproduce this issue with our current version. You're not using our nightly build, correct?
