### ISSUE TITLE
Merging edges on mrtree

### ISSUE THREAD

**Issue by bsalines91** [eclipse/elk#389]
I'm looking to merge edges while using the mrtree algorithm. Seems like the layered algorithm allows for this option along with many other customizations, however, mrtree does not.

**Comment by uruuru** [comment]
Compared to the layered implementation mrtree is rather primitive.

Depending on what your use case is and what you exactly mean by merging you
might be able to do it anyway. Can you provide a simple example?

**Comment by bsalines91** [comment]
So,

On layered, there is a property that allows you to merged edges. 

i.e. if a node has two children it will have a single outbound edge that splits and goes to each child node. 

However, using mrtree, only allows for every child node to have its own edges that comes from the parent. The issue with this is when you have many nodes, there ends up being many edges. The graph then looks messy and lines start to combine to make a giant line.

**Comment by bsalines91** [comment]
![screen shot 2018-12-06 at 2 19 25 pm](https://user-images.githubusercontent.com/34221084/49808715-36d2b600-fd2b-11e8-8562-bb7f1c277aea.png)
In the image above you can see the layered algorithm. The root node has a single edge coming from it.

![screen shot 2018-12-06 at 2 27 56 pm](https://user-images.githubusercontent.com/34221084/49808779-54a01b00-fd2b-11e8-96eb-00f147ee81c1.png)
In the image above you see the mrtree algorithm. The root node has many edges coming from it.

**Comment by le-cds** [comment]
Yep, the edge routing in Mr. Tree is definitely not optimal. I do suggest that you consider simply using the layered algorithm for your use case. :)

**Comment by bsalines91** [comment]
Is there a way to set the layered algorithm to build the graph symmetrically?

**Comment by uruuru** [comment]
Either try [node placement strategy](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-nodeplacement-strategy.html) `NETWORK_SIMPLEX` or `BRANDES_KOEPF` in conjunction with [favouring straight edges](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-nodeplacement-favorstraightedges.html) set to `false`.

**Comment by le-cds** [comment]
I've opened #406 to track the underlying feature request here. I'm thus closing this issue.
