### ISSUE TITLE
Edge spacing changes are not reflecting

### ISSUE THREAD

**Issue by vpachchi1** [eclipse/elk#393]
I am trying to change the default spacing.edgeEdge value from 10 to 50. it is not impacting in result. can any one help me with the steps or any kind of steps.

**Comment by uruuru** [comment]
Try 'nodeNodeBetweenLayers'.

**Comment by le-cds** [comment]
Since there hasn't been an update in over a month, I'm closing this. Feel free to reopen if you require further assistance.
