### ISSUE TITLE
Edges rendered as straight lines

### ISSUE THREAD

**Issue by chandusekhar** [eclipse/elk#395]
{
  id: "root",
  properties: { 'algorithm': 'layered' },
  children: [
    { id: "n1" ,children: [
    { id: "n4", width: 30, height: 30 },
    { id: "n5", width: 30, height: 30 },
    { id: "n6", width: 30, height: 30,children: [
    { id: "n7", width: 30, height: 30 },
    { id: "n8", width: 30, height: 30 },
    { id: "n9", width: 30, height: 30,children: [
    { id: "n10", width: 30, height: 30 },
    { id: "n11", width: 30, height: 30 },
    { id: "n12", width: 30, height: 30,children: [
    { id: "n13", width: 30, height: 30 },
    { id: "n14", width: 30, height: 30, ports :[ {id: "p3", width: 10, height: 10},
    {id: "p4", width: 10, height: 10}
    ] },
    { id: "n15", width: 30, height: 90,
    ports :[ {id: "p1", width: 10, height: 10},
    {id: "p2", width: 10, height: 10}
    ] }
  ]  }
  ] }
  ] }
  ]},
    { id: "n2", width: 30, height: 30 },
    { id: "n3", width: 30, height: 30 }
  ],
  edges: [
    { id: "e1", sources: [ "p1" ], targets: [ "p3" ] },
    { id: "e2", sources: [ "p2" ], targets: [ "p4" ] } 
  ]
}

![image](https://user-images.githubusercontent.com/9524949/51800245-883ef200-2252-11e9-84fc-663e329f1eee.png)

**Comment by uruuru** [comment]
Please add a little bit of text and a question to your issue :).

Edges have to be specified as described under 'edge containment' here:
https://www.eclipse.org/elk/documentation/tooldevelopers/graphdatastructure.html

I.e. you have to move the two edges to the parent node of the two nodes
with ports.

**Comment by le-cds** [comment]
Since there hasn't been an update in almost a month, I'm closing this. Feel free to reopen if you require further assistance.
