### ISSUE TITLE
Oomph Setup: Neon target platform is not consistent

### ISSUE THREAD

**Issue by spoenemann** [eclipse/elk#398]
The target platform currently requires Xtext 2.16.0, but that is not compatible with Eclipse Neon. We should remove the Neon target platform configuration.

I don't know about Oxygen. That one should be checked, too.

**Comment by le-cds** [comment]
I removed Neon. According to the [Xtext 2.16 release notes](https://www.eclipse.org/Xtext/releasenotes.html#/releasenotes/2018/12/04/version-2-16-0), Oxygen is supported (Oxygen.3a is the minimum requirement, to be exact), so we can leave that in, I guess. For this release, at least.
