### ISSUE TITLE
Failing unit tests

### ISSUE THREAD

**Issue by spoenemann** [eclipse/elk#399]
![screenshot 2019-01-28 at 11 34 54](https://user-images.githubusercontent.com/4067210/51830725-d1458380-22f0-11e9-9b59-915826440fe7.png)

**Comment by uruuru** [comment]
Have they been there prior to your changes in #396? 

I think I remember that last time I debugged something in the layer sweep they were successful.

**Comment by uruuru** [comment]
Btw: I feel this should be checked before the next release.

**Comment by le-cds** [comment]
@spoenemann since you added this ticket to our release milestone today, are you currently looking into it as well? Wouldn't want to interfere. ;)

**Comment by spoenemann** [comment]
I fixed a few tests, but there are more:

![screenshot 2019-02-21 at 16 44 08](https://user-images.githubusercontent.com/4067210/53181522-fbd8e280-35f7-11e9-9f85-73a5a639eb8b.png)

Here the expectations do not match the algorithm results. This seems like something that has been broken for a while. Are the tests actually executed on Jenkins?

**Comment by le-cds** [comment]
> Are the tests actually executed on Jenkins?

No, not at the moment, that's still on the agenda. We also have a new test infrastructure for layout algorithms, but that hasn't been enabled yet either. :/

**Comment by spoenemann** [comment]
:-/

**Comment by le-cds** [comment]
Those tests are fixed now as well.
