### ISSUE TITLE
Javadoc of class ElkLayered is out-dated

### ISSUE THREAD

**Issue by sailingKieler** [eclipse/elk#400]
See
https://github.com/eclipse/elk/blob/2929b17ef053936b60e2298ea83188aba0dac494/plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/ElkLayered.java#L47-L49

and
https://github.com/eclipse/elk/blob/2929b17ef053936b60e2298ea83188aba0dac494/plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/ElkLayered.java#L77-L79
for example.

**Comment by le-cds** [comment]
Chaned all mentions of KLay and KNodes in the whole ELK Layered project.
