### ISSUE TITLE
Add a reload button on the Layout Graph view

### ISSUE THREAD

**Issue by lredor** [eclipse/elk#421]
The goal of this new button is to reload the file already loaded before with the button "Load, layout, and display a saved ELK graph."
This allows to make modification in the file, reload it and quickly see the layout result.

![reloadButtonInLayoutGraphView](https://user-images.githubusercontent.com/1825882/57291472-d3716800-70bf-11e9-85b2-34d0fdba5017.png)

**Comment by lredor** [comment]
The pull request of the commit [1a7cbb6](https://github.com/lredor/elk/commit/1a7cbb662c75bac4a5af515b284b2f48e294f558) has been replaced by the [62656d0.](https://github.com/lredor/elk/commit/62656d0671647f4191d627a013a5724527e09c86)

**Comment by le-cds** [comment]
I added an implementation similar to yours to the new layout graph view. That view is currently on a development branch, but will be in master soon. Thanks again for your suggestion and your pull request (which I'll be closing)! :)
