### ISSUE TITLE
Can you tell me how to get the file "org.eclipse.elk.alg.layered.options.LayeredOptions"

### ISSUE THREAD

**Issue by dcsgman** [eclipse/elk#427]
I cant find this file. the following is the information about error:
![image](https://user-images.githubusercontent.com/16850481/58394192-94a65080-8074-11e9-919b-1b73af5fcf77.png)

**Comment by le-cds** [comment]
It is automatically produced during automatic builds of our project based on information in our `.melk` files.

What exactly are you trying to do?

**Comment by dcsgman** [comment]
I wanna know it works. But I failed to compile ELK source code.  So I want to run Layed directly. Can you tell how to solve it? Thank you!

**Comment by le-cds** [comment]
I guess you're trying to use ELK in a pure Java context (that is, outside of Eclipse)? If compiling from source using [this guide](https://www.eclipse.org/elk/documentation/contributors/buildingelk.html) does not work for you, you can always download the pre-compiled ELK libraries from Maven Central. You can find details on [our downloads page](https://www.eclipse.org/elk/downloads.html).

**Comment by dcsgman** [comment]
Thank you, I wanna change the source of the package "Layered" and recompile ELK. Do I have to compile the ELK source in Eclipse?

Best regards

Rongliang Fu
TEL:+86 18881814693

________________________________
发件人: Christoph Daniel Schulze <notifications@github.com>
发送时间: 2019年6月9日 17:54
收件人: eclipse/elk
抄送: Rongliang Fu; Author
主题: Re: [eclipse/elk] Can you tell me how to get the file "org.eclipse.elk.alg.layered.options.LayeredOptions" (#427)


I guess you're trying to use ELK in a pure Java context (that is, outside of Eclipse)? If compiling from source using this guide<https://www.eclipse.org/elk/documentation/contributors/buildingelk.html> does not work for you, you can always download the pre-compiled ELK libraries from Maven Central. You can find details on our downloads page<https://www.eclipse.org/elk/downloads.html>.

―

**Comment by le-cds** [comment]
No, we provide a Maven build for you to run, as explained in [this guide](https://www.eclipse.org/elk/documentation/contributors/buildingelk.html). This will give you a number of .jar files you can include in your own application.
