### ISSUE TITLE
Apply/Set maximum graph dimensions?

### ISSUE THREAD

**Issue by eckig** [eclipse/elk#432]
Is there any way to set the maximum dimension for the resulting graph?

In our use case we are using the ELK Layered algorithm programatically (Java) and we have a limited workbench size. I was able to to apply the `CuttingStrategy` using the aspect ratio but that is only a soft limit..

Side question: How can I reduce the spacing between individual nodes? I set the spacing to zero, but with no effect?

**Comment by uruuru** [comment]
We usually work around the "limited space" issue by scaling down the rendered version of the graph such that it fits. Maybe that's an option for you?

Which option did you try regarding spacing? 
For layered there's a couple of options:
* for _vertical_ spacing between nodes `org.eclipse.elk.spacing.nodeNode`
* for _horizontal_ spacing between pairs of nodes `org.eclipse.elk.layered.spacing.nodeNodeBetweenLayers`

There are further options if edges are between nodes. Look for node edge spacing [here](https://www.eclipse.org/elk/reference/algorithms/org-eclipse-elk-layered.html).

**Comment by eckig** [comment]
Scaling is not really an option, because most labels will then no longer be readable. We only use scaling for specific use cases but not in general.

As to the spacing options: Already tried them - I have set every spacing to `5.0` to no avail. I have several nodes that have more than 100 pixels between them.

We have a somewhat special diagram, as we use many connections. One thing that could improve the situation is to merge the connections by grouping them by their point of origin. The ELK model already supports that, but the Layered Algorithm does not?

**Comment by uruuru** [comment]
Can you share an (abstract) screenshot? Did you also try edge edge spacing?

**Comment by eckig** [comment]
Yes, I tried all the spacing options.

Attached are two screenshots, as you can guess by the minimap (top right corner) it is a very large graph with lots of connections. ELK does a very good job at performing a proper layout, but the result is wasting too much space:

Before:
![Before](https://i.imgur.com/xeIVfck.png)

Afterwards:
![After](https://i.imgur.com/s6EVlIE.png)

**Comment by le-cds** [comment]
> One thing that could improve the situation is to merge the connections by grouping them by their point of origin. The ELK model already supports that, but the Layered Algorithm does not?

ELK Layered does not support hyperedges as modelled in the ELK graph yet, but it will consider two edges that share the same source or target port two be part of the same hyperedge.

I noticed that your _before_ image does not place nodes in separate layers, really. @uruuru, perhaps your horizontal compaction algorithms might help here?

**Comment by eckig** [comment]
> I noticed that your _before_ image does not place nodes in separate layers, really.

What do you mean by that?

**Comment by le-cds** [comment]
@eckig The layered algorithm partitions the nodes of the diagram into so-called _layers_, which end up as sort of vertical columns that nodes are placed in. Nodes in the same column share intervals on the x axis, but nodes of different columns do not since the columns are placed next to each other, without overlaps. Your original drawing looks like you don't necessarily require the visual appearance of said columns. We do have ways to apply _horizontal compaction_ to graphs, which help save horizontal space, but destroy the appearance of those columns in the process.

**Comment by eckig** [comment]
Ok, got that - thanks for the explanation.

But how do I perform that _horizontal compaction_?

**Comment by le-cds** [comment]
@eckig Sorry, should have included that information right away. ;) You enable horizontal compaction by playing around with the layout options in [this category](https://www.eclipse.org/elk/reference/groups/org-eclipse-elk-layered-compaction-postcompaction.html). Set the options on the graph whose children should be compacted.

@uruuru Perhaps you can at some point expand the documentation of those options a little? :)

**Comment by eckig** [comment]
For a very small graph this works really well: The spacing is so small that the nodes are arguably too close to each other ;)

For a very large graph it works, but there is much more spacing in between the nodes.

I guess we have to take a different approach.. But thanks in any case for the explanations.
