### ISSUE TITLE
Label management does not update the label position/spacing of label on self-loops

### ISSUE THREAD

**Issue by a-sr** [eclipse/elk#434]
When activating or switching a label management strategy, labels are correctly transformed but the layout (position/spacing) for labels on self-loops is not correctly updated.

![selfloops_labelmanagement_before](https://user-images.githubusercontent.com/25612037/59504959-75952480-8ea4-11e9-9c14-4aa0359bac63.png)
![selfloops_labelmanagement_after](https://user-images.githubusercontent.com/25612037/59504966-77f77e80-8ea4-11e9-986a-c34ea7f51d07.png)

The example first shows the result after activating label management and then the correct positioning after performing an additional layout run.
Labels on normal edges work correctly, see transition B -> C.

**Comment by le-cds** [comment]
Fixed as soon as #446 is on master.
