### ISSUE TITLE
Edges between nodes with different containing sub-graphs don't have a "sections" attribute

### ISSUE THREAD

**Issue by barucoh** [eclipse/elk#435]
Simple graph to visualize the issue best:
`{
  id: "root",
  properties: { 'algorithm': 'layered' },
  children: [
    {
      id: "n1",
      children: [
        {
          id: "n4",
          width: 30,
          height: 30
        }
      ],
      width: 30,
      height: 30,
      edges: [
        { id: "e3", sources: [ "n5" ], targets: [ "n4" ] }
      ]
    },
    { id: "n2", width: 30, height: 30 },
    { id: "n3", width: 30, height: 30 },
    { id: "n5", width: 30, height: 30 }
  ],
  edges: [
    { id: "e1", sources: [ "n1" ], targets: [ "n2" ] },
    { id: "e2", sources: [ "n1" ], targets: [ "n3" ] }
  ]
}`

It doesn't matter if the edge `e3` is a descendant of "n1" or its sibling, the result is the same.

I have a visualizing wrapper for the resulting taskGraph and I cannot properly draw a connection between `n5` and `n4` as describe in the `e3` edge. It appears sprotty doesn't as well based on the live demo - https://rtsys.informatik.uni-kiel.de/elklive/json.html

**Comment by uruuru** [comment]
You have to change two things: 
First set `'hierarchyHandling': 'INCLUDE_CHILDREN'` ([explanation](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-hierarchyhandling.html)). 
Second, specify the edge `n5->n4` according to the conventions. See section on _Edge Containment_ [here](https://www.eclipse.org/elk/documentation/tooldevelopers/graphdatastructure.html).

``` 
{ 
  id: "root", 
  layoutOptions: { 
    'algorithm': 'layered',
    'hierarchyHandling': "INCLUDE_CHILDREN" 
  },
  children: [ 
    { id: "n1", 
      children: [ { id: "n4", width: 30, height: 30 } ], 
      width: 30, 
      height: 30
    }, 
    { id: "n2", width: 30, height: 30 }, 
    { id: "n3", width: 30, height: 30 }, 
    { id: "n5", width: 30, height: 30 } 
  ],
  edges: [
    { id: "e1", sources: [ "n1" ], targets: [ "n2" ] },
    { id: "e2", sources: [ "n1" ], targets: [ "n3" ] },
    { id: "e3", sources: [ "n5" ], targets: [ "n4" ] } 
  ] 
}
```

**Comment by barucoh** [comment]
Thank you! It fixed the issue.
I didn't have to move the edge to the external `edges` attribute though, only set `'hierarchyHandling': 'INCLUDE_CHILDREN'`
