### ISSUE TITLE
How to avoid edge overlap

### ISSUE THREAD

**Issue by wuleibobo** [eclipse/elk#441]
I have a diagram, I need the edge must be ORTHOGONAL, and not overlap, I don't care the direction of the edge.
I use layered layout algorithm, but the edges always overlap at the begin and end of the edge. I try to use MULTI_EDGE, but it can't reslove the problem.
I want to know how to configuration to avoid edge overlap.

This is a diagram data on JSON format, you can check the diagram on https://rtsys.informatik.uni-kiel.de/elklive/json.html
{
	"id": "root",
	"layoutOptions": {
		"elk.algorithm": "layered",
		"org.eclipse.elk.edgeRouting": "ORTHOGONAL",
		"org.eclipse.elk.direction": "DOWN",
		"org.eclipse.elk.layered.spacing.edgeNodeBetweenLayers": 40,
		"org.eclipse.elk.layered.nodePlacement.strategy": "NETWORK_SIMPLEX",
		"org.eclipse.elk.layered.wrapping.strategy": "MULTI_EDGE",
		"org.eclipse.elk.layered.wrapping.correctionFactor": 100
	},
	"children": [{
			"id": "node1",
			"width": 400,
			"height": 200,
			"layoutOptions": {
				"portConstraints": "FIXED_POS"
			},
			"ports": [{
					"id": "port1-1",
					"x": 50,
					"y": 200,
					"width": 10,
					"height": 10
				},
				{
					"id": "port1-2",
					"x": 100,
					"y": 200,
					"width": 10,
					"height": 10
				},
				{
					"id": "port1-3",
					"x": 150,
					"y": 200,
					"width": 10,
					"height": 10
				},
				{
					"id": "port1-4",
					"x": 200,
					"y": 200,
					"width": 10,
					"height": 10
				}
			]
		},
		{
			"id": "node2",
			"width": 400,
			"height": 200,
			"layoutOptions": {
				"portConstraints": "FIXED_POS"
			},
			"ports": [{
					"id": "port2-1",
					"x": 50,
					"y": 0,
					"width": 10,
					"height": 10
				},
				{
					"id": "port2-2",
					"x": 100,
					"y": 0,
					"width": 10,
					"height": 10
				},
				{
					"id": "port2-3",
					"x": 150,
					"y": 0,
					"width": 10,
					"height": 10
				},
				{
					"id": "port2-4",
					"x": 200,
					"y": 0,
					"width": 10,
					"height": 10
				}
			]
		}
	],
	"edges": [{
			"layoutOptions": {},
			"id": "edge1",
			"sources": [
				"port1-1"
			],
			"targets": [
				"port1-3"
			]
		},
		{
			"layoutOptions": {},
			"id": "edge2",
			"sources": [
				"port1-2"
			],
			"targets": [
				"port1-3"
			]
		},
		{
			"layoutOptions": {},
			"id": "edge3",
			"sources": [
				"port1-2"
			],
			"targets": [
				"port2-1"
			]
		},
		{
			"layoutOptions": {},
			"id": "edge4",
			"sources": [
				"port1-2"
			],
			"targets": [
				"port2-1"
			]
		},
		{
			"layoutOptions": {},
			"id": "edge5",
			"sources": [
				"port1-2"
			],
			"targets": [
				"port2-2"
			]
		},
		{
			"layoutOptions": {},
			"id": "edge6",
			"sources": [
				"port2-2"
			],
			"targets": [
				"port2-3"
			]
		},
		{
			"layoutOptions": {},
			"id": "edge7",
			"sources": [
				"port2-2"
			],
			"targets": [
				"port2-4"
			]
		}
	]
}

**Comment by le-cds** [comment]
All edges incident to the same port will overlap at least in the vicinity of that port. That behaviour cannot be switched off. If you don't want edges to overlap, you will have to ensure that they are all incident to different ports.

**Comment by wuleibobo** [comment]
> All edges incident to the same port will overlap at least in the vicinity of that port. That behaviour cannot be switched off. If you don't want edges to overlap, you will have to ensure that they are all incident to different ports.

Thanks for your reply, I know the edge must overlap at begin and end for ORTHOGONAL routing, but my question is how to avoid the overlap like this.
![image](https://user-images.githubusercontent.com/19942836/62424890-81b09c00-b707-11e9-93ee-5b6f52647a92.png)

The mergeEdge and multiEdge options not work for it, I don't know how to avoid this overlap.
Thank you very much.

**Comment by le-cds** [comment]
Oh, I see. Try setting [this option](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-mergeedges.html) to `false` on your graph. That should help.

**Comment by wuleibobo** [comment]
> Oh, I see. Try setting [this option](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-mergeedges.html) to `false` on your graph. That should help.

I had try to set this option, and it doesn't work.
I do not know is there any option must be set together?
I also tried merge hierarchy edge. and it doesn't work too.

**Comment by le-cds** [comment]
You're absolutely right, I'm sorry. I was under the impression that we had an option to switch that off. Turns out, we don't. If you like I can open a ticket at the ELK project to implement this (wouldn't be hard). However, it would take a while until the feature ends up at elkjs.

**Comment by wuleibobo** [comment]
> You're absolutely right, I'm sorry. I was under the impression that we had an option to switch that off. Turns out, we don't. If you like I can open a ticket at the ELK project to implement this (wouldn't be hard). However, it would take a while until the feature ends up at elkjs.
 
I'm very glad you can open a ticket to implement it. 
otherwise, I'm using elkjs. it's version is 0.4.1.
can I get this feature in elkjs?

**Comment by le-cds** [comment]
> can I get this feature in elkjs?

Sure, but don't hold your breadth. We usually only release a new elkjs version upon a new ELK release, and we currently don't know when exactly the next one will be.

**Comment by le-cds** [comment]
Actually, I just took another closer look at your example graph because something in the picture struck me as odd. The problem here is that you have self-loop which share ports with other edges. In fact, that result won't really change at all, at least not with orthogonal edge routing.

I suggest you use [polyline edge routing](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-edgerouting.html) instead.
