### ISSUE TITLE
Edge labels for overlapping edges should be consistent with the edge ordering

### ISSUE THREAD

**Issue by NiklasRentzCAU** [eclipse/elk#450]
View this graph:
```
graph tailEdgeLabel
edgeRouting: POLYLINE
node left {
    port p
}
node right1
node right2
node right3

edge left.p->right1 {
    label "label1" {
        edgeLabels.placement:TAIL
    }
}
edge left.p->right2 {
    label "label2" {
        edgeLabels.placement:TAIL
    }
}
edge left.p->right3 {
    label "label3" {
        edgeLabels.placement:TAIL
    }
}
```

![image](https://user-images.githubusercontent.com/47597619/63423042-c62c7f00-c40b-11e9-818a-142eb101941d.png)

The edge labels should follow the same order as the connected nodes to the right.

**Comment by le-cds** [comment]
This shouldn't be too hard, especially considering that end labels are processed after crossing minimization. When sorting the labels, we just need to be sure to handle in-layer edges correctly.
