### ISSUE TITLE
Strange edge in interactive mode

### ISSUE THREAD

**Issue by JanKoehnlein** [eclipse/elk#453]
See this [model](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=OYJwhgDgFgBAtgTwCYFMBmBnA+gFTAOwGssBBYASwBcxKUsBlSgewgnP2AChOwAbYJiCpQ4ALhiDgAOhQBjXuQgYUM3oSm8wCFCBRJOKNVKTldsyuSb5xAJQCSAcQASOThghhZ7afiaoAcn4o4gDMAAxuHl4cMkjAKIGoAEIolADuKCj4ADJaOhihEZraQjEYlOC0wAjidv44AKI2JADCOHYAag2Rnt5SvgFBKemZOXkgBTDhnLIgTBgY3gCy7ORw5ABeNJb4UuWVKNW19U2t7V2cAygACpqyKHBZlHsVNIc1MHWNzW2d3ey0cDmcgANxQNnQOiy92uTAB4hwAHlrlhsg0AGKuK4wbD4GAAb04AEhikwAK6UGAAbWJRIg8yoO3EAEYQsypAAmACsADYOQAWAAc-IA7PzmRzmcyADRTMKC2mLDbBGDMoVSACcXLZ3NlHMFUi5xIAusT6SBKC0rPswADJui7AANBoAEQYdhd3RJYAARoYcVheNYYAAiDAhgm00kU6m0ukMixWFlhWU8w1xpUqtNc2XMrnpolE03EgC+ZsElIwkcL0cpVJxmxVGqkgrCbbbzI1YRFISFPJCubCLfbHa7Pb7IRgxcLkhk8kUylU6gAeubnotUOIGiR6K4ZyBpHIFEoVIYV2upD7BKgQIi0JhUuIh0aiWWy9i0Fg8YTvQhyXXaXpRZE2DTsQikfsJSFUVxUlGUph5bNFUbcRBWzEVBQlHMYH1AtpyuehGykdZ8DWMkxFDAAKNDDQwrDpVwrkAEoQ3LC0rXwG07XEB1nTdegPS9TQ-V4GBPyDcQQzQCMf1-f9Y0LeNgKZVUUxgJDFMzUIWxFbC8wLItuFfNjKTQas5JjestJgZtWxHTtu17NCB1U4d7LHJz+ynIyiVnI8F1PIxVwrPZyE3GBt13Wk-PnE8lykYKLUva8dDvB9KCfAs30uIIYDAata2pBtlVCWz6JgfkuW84kCKIkiyIokNKJFZseV5XVKqkMIWJM3IRIwKQIDuB4nmOATPRqoJCOVKRZGtV5uNDKlrkRGwcHoWUVrW1ESCSBpsg2mB-ERT0dr2g7ZSWOo7CWABVJZ3QALQaY1WPjdj5vARbeNdLBVs9GwTLyrAIDCczCqslCbLc9sHPHZzBxh0dHInar90PWLFzPBKLw3FUAHUGiimtfX9MAQbCQNJNBmS4wh4qVQ5DkpH5MI+T0-MqunYyebXYGIGZcGtHkyGSuhuzYY8idEYl5H4a87mYuPLGgtxsKCaJvdvRE-nmSp0MBdpxT6espmWbZ3VVU5tGebLd7KXJiBJ1kk2odskcwjhzyXOZIdZc9qXnJtpWAvixL13Vrcdy14SyZBkJ9ZDJ2jZJv9LIZll+RbfVyv0rmfLt7LsR9ArhfT6yQjKy3KrR2qZvquByMk5rWvanNOu6t61z6wwBqGzwRvwDLPn8cavTrlQ5s4hah8mENltW9bNsXs79sO47TuyXa18u667oegTntekyOK42eeKdX7-qaIGfQpoW07rDPxY9r3pdc-236DxWDznZXAvPCFPG4hCbE21v6O+oNE403MhZJ+ptmas3Zrma23NC63xBoLF2Zd4FuyRgHFGCMP6v0DgrHyIc4rY3DqFcKoCY6k1EpAvWvBqbMhTnAoqCDzbIKtoaG26D7YwEgc7KMODOF4M-qQn2fsSGELIdFX+-lKGqyAZHCK0dRE62EdAkI7DXZizVNnTCls878NLJwMseh4gBjoOIXEewYAAFoAB8QjLz30JJYuIKAxJYFsb43YZkXF5SkI7MGniDDeKEfHPxWBxA+ncU7JxriwChMwZGMsQA). All edges should be routed in Manhattan style. In sprotty, I get a `ElkNode` with `height` `NaN`for the root element.

**Comment by uruuru** [comment]
Not sure about the `NaN` but try: 
```
crossingMinimization.semiInteractive: true 
```
instead of 
```
layering.strategy: INTERACTIVE
```

Maybe @le-cds can shed some light on the placement of dummy nodes during interactive layering - I do not properly remember it at this point.
