### ISSUE TITLE
Edge routing on long edges takes unnecessarily long path

### ISSUE THREAD

**Issue by NiklasRentzCAU** [eclipse/elk#454]
```
graph edgeRoutingProblem
node n0_0
node n1_0
node n1_1

node n2_0
node n2_1
node n2_2
node n2_3
node n2_4
node n2_5
node n2_6
node n2_7
node n2_8
node n2_9

node n3_0

edge n0_0->n1_0

edge n1_1->n2_7
edge n1_0->n2_0
edge n1_0->n2_1
edge n1_0->n2_2
edge n1_0->n2_3
edge n1_0->n2_4
edge n1_0->n2_5
edge n1_0->n2_6
edge n1_0->n2_7
edge n1_0->n2_8
edge n1_0->n2_9

edge n1_0->n3_0
edge n2_0->n3_0
```

When drawn, this graph looks like this:
![edgeRoutingProblem](https://user-images.githubusercontent.com/47597619/64429040-6e517180-d0b5-11e9-975f-18cc036d5b19.png)

The long edge from n1_0 to n3_0 is unnecessarily long. Instead of the routing between n2_2 and n2_7 it would result in a better edge routing if it is routed between n2_0 and n2_9 in the image.

**Comment by le-cds** [comment]
I'm afraid this is something we won't really be able to fix.
