### ISSUE TITLE
Non-intuitive layer assignment in hierarchical graphs

### ISSUE THREAD

**Issue by NiklasRentzCAU** [eclipse/elk#455]
```
graph hierarchicalEdgeRoutingProblem
hierarchyHandling:INCLUDE_CHILDREN

node o {
	node i1
	node i2
}

node right {
	portConstraints:FIXED_SIDE
	port west {
		^port.side:WEST
	}
	port east {
		^port.side:EAST
	}
}

edge o.i1->right.west
edge right.east->o.i2
```
This graph results in the following diagram:
![hierarchicalEdgeRoutingProblem](https://user-images.githubusercontent.com/47597619/64430411-8971b080-d0b8-11e9-8c73-9db808925fb1.png)

My intuition would say that the node i1 should be in the right layer and i2 in the left layer. I assume this layering is chosen because i1 is a source and i2 is a sink and therefore are assigned to the first resp. last layer. But because they are not connected further, they should be handled differently in a hierarchic graph.

**Comment by uruuru** [comment]
I believe this is due to hierarchical dummy nodes that are created in the first and last layer, respectively.
