### ISSUE TITLE
The multi fan out problem of hierarchical graphs

### ISSUE THREAD

**Issue by Flians** [eclipse/elk#468]
There is a node connected to all nodes in a layered graph. 
How can I put the node at the top of the graph and connect each node?  As shown in the following figure: 

![download](https://user-images.githubusercontent.com/16850481/69773635-51b56900-11ce-11ea-939e-3a4770571265.png)

**Comment by le-cds** [comment]
Currently, there is no way of forcing a node to the top of the diagram.

**Comment by Flians** [comment]
Oh, thank you! Maybe you can consider this question next release.

Best regards

Rongliang Fu
TEL:+86 18881814693

发件人: Christoph Daniel Schulze<mailto:notifications@github.com>
发送时间: 2019年11月28日 15:49
收件人: eclipse/elk<mailto:elk@noreply.github.com>
抄送: Rongliang Fu<mailto:rongliangfu@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [eclipse/elk] The multi fan out problem of hierarchical graphs (#468)


Currently, there is no way of forcing a node to the top of the diagram.

―

**Comment by le-cds** [comment]
I'll track this as a feature request for future versions.

**Comment by soerendomroes** [comment]
It should be possible to constrain a node to the top with multiple different layout options as detailed [here](https://eclipse.dev/elk/blog/posts/2023/23-01-09-constraining-the-model.html).
