### ISSUE TITLE
Self-loop not layered properly with ELK Layered algorithm

### ISSUE THREAD

**Issue by vrichard12** [eclipse/elk#469]
Here is attached an example of an elkg file to reproduce the issue. The middle node has 3 self-loops crossing other edges and with their labels overlaping each others.

![Self-loop-elk-layered-issue-example](https://user-images.githubusercontent.com/6783266/69798535-c76f0400-11d1-11ea-8058-d91d56f55e3d.png)

[Self-loop-elk-layered-issue-example.elkg.zip](https://github.com/eclipse/elk/files/3901148/Self-loop-elk-layered-issue-example.elkg.zip)

**Comment by le-cds** [comment]
@vrichard12 I tested your example with our new self loop implementation:

![469](https://user-images.githubusercontent.com/7465584/69885798-325a3100-12df-11ea-8114-233a95d6221d.png)

I'd count that as an expected result. I do remember you saying that you tried out the current master. However, we found out just a few days ago that the master did not build successfully since I merged the new self loop code -- without the server yelling at me. If I remember correctly, could you please try again with the current nightly builds?

**Comment by lredor** [comment]
@le-cds Hello, I've tested the layout of the diagram from Self-loop-elk-layered-issue-example.elkg.zip. And the result is always the same (same than the initial picture). Tested on:
* A runtime with the code from master branch
* An install with the update site https://build.eclipse.org/modeling/elk/updates/0.6.0/ (by the way, this update site contains a version 0.7.0. It seems strange...).

Are you sure that you have changed nothing in the layout option from diagram in Self-loop-elk-layered-issue-example.elkg.zip? I see no reason to have different result than yours.

**Comment by le-cds** [comment]
@lredor That is massively strange. I changed nothing (even downloaded the file again just now to be sure), and my result was what I posted. I'm not sure what's wrong here.

Regarding the update site: it contained version 0.7.0 because of a misconfiguration on my part: the release branch build checked out the master branch by mistake, which already moved to 0.7.0...

**Comment by lredor** [comment]
@le-cds With a new install of Eclipse 201909 and https://build.eclipse.org/modeling/elk/updates/0.6.0/ the result is always the initial result.
Even in [ELKLive](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=OYJwhgDgFgBA4gRgFABswE8D2BXALjAbRgGcBLALwFMAuGBABgFYA2AGhgGZGBOGAXSQRMIXABkwAI0opiAOgB2lAB64AKpgAKw3AEkAZluJkJKGjFwhslQdvFSZsiGgDGlALaV5uWjoByAZR0AEQBRJHlMABNKfwpKWWdMeWILMFIvYloAIgINAHkAJVV-dnyigH1RAEEAIRDREphfPNDK2vrGgFk-HU6AVU7ywIAtEL4spDAUYGFSXCg3WmFgWUpnFFIIYnjpAGtZNHRKEEpIpGIIMGd0ldPgSl8oyhrKXAB3Sk9xI5BMmAAmeiyehIO6UOzSORkaL+aRrXCkJK0fydKoVPoac6Xa7yW6Re4QlC0BjA8KYb44bwwPRTbZk6IwCDOci48rEFC7XAANxgAG8kABIQ6UwiCgVCMgIpEwHgAdnYABYFWKyFRaMwAByKkECgTi2ySSEKZRqTTafSGYymWgWKyCoQiQlyJxXdyeKl+QKhQURGFxBJJFLgdK4P45MrFUqFVRtOoNdjNVrVONdHr9QYjMYTAW+mL+tzpUhubCLGBZAAUCA4wNY-2r9AAlNm0PYYKIFdkmSzgCQOdysnyxcK8KKBWOJXNEfJaIx2IwxQLVWZGFq6POx3qBWCnY4XG6vLQAMIhXyqEIFMW5ncu1weA9lggACXKx9P5-YADVyqo8hp2J7gizQUAF8kFA3MYE6LkuT0JQuTcXEoEiLlMHKbAIAAK0wdZSHKPJIigXYghUCRIkHIUMBFAgxQnKVpzoegFXYHVFziWhAQQbVBT1B0xENBxFBUdQtBEC1MCMUgTDMW1rH1R1+OdPc7w9AJAJ9J5YioANklSEMw1yaNGgjWMOgTFoQhM+NILTAYhh0UZxnUv0tILeQixLbJK3rWt6ybQUW2kNtGGyKCYLghDgCQlCYHQrCcJgfDCOI3BSIHfkx2HfBqLHfVJSnGc5wXJdiW4Ti1zFTdtwU3dXWUo8TzPC8xyvaqb33KkcmfV9Gs-b9f3-VTQkcgVQK3fFKBgEJgsg6DYPgxDkNQ2LsI2PCCKIkiyIAWgAPhmsL5sixa0MwlbcMSjaUrI9KKKwEdsrHbZnDoyb-EYUccpSMARHY+gyoQdccs8SJaA1VcFRYscpHkSI-n+Bh2ABmAAB8AQRmANQ4FG6AQMrMYXTdN2WVYcK2HYOVkAA9MFZHmUhnF2RQjHY0kMv4ttmGyHRIjebAUHIWAAGkMNISJIj0eRsDeFQUDI3YlFIUgoAkXZdgAHXkMAZhIeQuXIUgYAAR2cGAMOcPQoC5MAeSqa5MBgABNYguVwYANaUcgYAkE2XeIEBdgZsB5HICQQGpYgsNwWQ0oXTKPvHcTJ2lUr2FlZActYtU6GYNgYAVQHdQXKr7EU2r3Xqt8mpGkDBTBSbOf2uaIqipbTpwtaks2mBdsb8KFpQk64tWi7ktI8jbqoor4SnV7mHjxdcG+qkc64jPgdB+hV5y6HYZnXPMex7h-nYfGcsJsVibWDYydWCnqfG2moHpxnKGZgFWYo1tRFlbJYgkGANCRCVjAVyRtIjYBAOgFWbhiDmB5LsYgmAUBvFINgUgGs3hUGpFyYgbglCMhAPIU2UBsDkF2DASgpBX6wAiAbUMkQlAa1UOQcSuwY45Tjg9BOeVpRbQQNwOc6dPpsToGDRUBdNxjQJK1JS5cYDdXPGKUao064hB-r3Q6LdB5nQ7pdMePdQpN37q3Ie511qj2ukOSi90p7PRniEfwsp57rxlODSGC8l60E3uVDOO8-hbWYMfNc2MAlBIPqjDg8oMYcAJhVC+IBbik22LffY997iP2fkzOGH8AooDbBqbIfR5C7A5GASCehiCEWALgdhbM7pZQXLlJO9EtrcCYjAHOjTioYyCQDWJQNxrXlkfeBRVdlFgXpBNCQ5A9BuAQobcolByAYVwHk9KnCSAiI1O0iG-B7QGhLsaISZpRIGHElaaSlhZK8SGWXe8AFvQ5g0v6RIOlgwZGyAZIoRloyWUaImCyyZTLWV8L0WymZhq5k0vEVy7lSwVirDWOswI-Kf0CqIbg2RpmzPmRQ5ZqzamcIXLRfKMpCrCKzrKdpfSNximLkaNqdV5ENUUc1J4tzbxyM6i+FlBReo-j-DAB5QFq6gVUQgWghi+5HQHstduI8u49y7KydknIeTrOsQ0x608kivQQPHL6P1OBMHYBwSGLi5Sp2VNvYGfwOD-FnMa7G9rHW4w1NjRgsooluo9V6q1cTC4Ckvkk8mqSaZ0wZlklmOpcltglWWAomA9DoDgCAQ25B8F6CiDAa4bwUAYXQJFMOAB6GAQRSAgDeJEQ2GsZjoBgKoSgGE3DAHYAADTeH7eAbwoCG3-pQTAnsuRKF2AwvQpBm2Es1fHEl0ouCOtlAXbpgIglmoDVI8EMi7lUlGTXMV41Jr-ElbNaVWi5XD3MYqvayrgBsj7Oq-y06HpPReg4-4BrF5GrNY6wERcYYzm4FE5g1qoa2toBwLg7BATOsgx0kDeo9TBuvskvYVNw1P0ja-bJMb2aiCPWWHQSg9AoFIfgjQIA9DAHkJrEAzhwESGwDAfELJXBKCgBrUtgtcDUZNsUmAwwqFKGIG8YAbg6ZTvqTOxOdFwOym8fDIqIiECylXSxSqgyt2cpGbyvdoID0hA4Meg6zdjrnrMZ3K63dr3MhVfe8iRLtV2N1Q4rGXDDVUm-Yjc1-6ZSAbnCBgUfiZx+oYr6qJjB4PcUFEhzYKG77ocyVh6Nj6v6GbLMMNY5BnDCZgILQ2mAMIRBKZgdAYBcE5rcLsMA2BoiYA45NCAtGIC9hgAARQY4oCd5BkH-0NpQMpAAxZBGFKAQA1jUOC0AoDoAk5PHKs76IcGYI6raCoNSKazggDUQT87rvpQ4Rlcjd2ir0-cSaHYvYzLmfIBZSyVl5IMSezRpm24Xos2PDVknn06qIQ4hUH7PEY3ab+oGPmGDA7U1FoNCSSbIdDWhh+EaX5v3+KSUCQA), I have the same result. What can I do to try to explain the difference with your result?

**Comment by lredor** [comment]
OK, I have the same result than yours. But for that I have to modified the initial elkg file. Indeed, the 3 self loop edges are not "declared" in the correct node. They are children of node "Mvvfxvmnghdvo upjocli OdhkDxtbd" and not of the diagram.
Here is the "fixed" version of the elg file: [Self-loop-elk-layered-issue-example.elkg-2.zip](https://github.com/eclipse/elk/files/3968059/Self-loop-elk-layered-issue-example.elkg-2.zip).

We can considered this issue as fixed. Thx

**Comment by le-cds** [comment]
Ah, edge containment is an important point. I'll revert my milestone change, which was completely unnecessary...
