### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by sancarn** [eclipse/elk#472]
I have a dataset with 181,166 edges and 181,167 nodes. Was hoping to use elkjs to create x-y data. Unfortunately it seems that the algorithm is based on recursion and gives me a "Maximum call stack size exceeded" error.

Doubt this will be very fixable however, as it would probably require a large amount of restructuring.

Layout being used is "mrtree"

**Comment by uruuru** [comment]
Can you share the stack trace? Sometime it's rather easy to replace the recursion.

**Comment by sancarn** [comment]
Woops only just realised I kinda posted this on the wrong repo, because I was using elk-js which is the transpiled version of this repo. Thus I don't actually have a stack trace...

**Comment by uruuru** [comment]
It's fine to post it here as the issue has to be fixed here :). However, mentioning that you used elkjs is helpful. 
If you use the non-minified version you might be able to have a look at the stack using your browser's developer tools.

**Comment by le-cds** [comment]
@sancarn Do you have a graph that reproduces the issue?

**Comment by le-cds** [comment]
I'll close this for the time being. Feel free to reopen if you can provide us with a graph that reproduces the issue. 🙂

**Comment by saulshanabrook** [comment]
FWIW I have opened an issue in elkjs about this with a reproduction https://github.com/kieler/elkjs/issues/314 https://gist.github.com/saulshanabrook/d8566e8ad1a69fdf045f2a5538771837
