### ISSUE TITLE
How can I obtain the number of edge crossings in the ELK Layered?

### ISSUE THREAD

**Issue by Flians** [eclipse/elk#474]
Hello!
When I directly use the layer algorithm, how can I obtain the number of edge crossings and bend points in the ELK Layered?
Thank you!

**Comment by uruuru** [comment]
The algorithm doesn't output such numbers. It solely outputs the layout. Hence, you'd have to compute them yourself. When it comes to the bend points this is rather easy: simply sum all edges' bend point counts.

**Comment by le-cds** [comment]
@Flians just to add to that, we have written code for both, it's just not part of the ELK project proper. You can find several analyses [over here](https://git.rtsys.informatik.uni-kiel.de/projects/KIELER/repos/pragmatics/browse/plugins/de.cau.cs.kieler.grana/src/de/cau/cs/kieler/grana/analyses).

**Comment by Flians** [comment]
I have got it, Thank you!

Best regards

Rongliang Fu
TEL:+86 18881814693

发件人: Christoph Daniel Schulze<mailto:notifications@github.com>
发送时间: 2019年12月9日 17:28
收件人: eclipse/elk<mailto:elk@noreply.github.com>
抄送: Rongliang Fu<mailto:rongliangfu@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [eclipse/elk] How can I obtain the number of edge crossings in the ELK Layered? (#474)


@Flians<https://github.com/Flians> just to add to that, we have written code for both, it's just not part of the ELK project proper. You can find several analyses over here<https://git.rtsys.informatik.uni-kiel.de/projects/KIELER/repos/pragmatics/browse/plugins/de.cau.cs.kieler.grana/src/de/cau/cs/kieler/grana/analyses>.

―
