### ISSUE TITLE
How to break line with multiple labels in a node

### ISSUE THREAD

**Issue by gvnt** [eclipse/elk#476]
Hello,

I'm trying to render multiple labels with break lines in a node (with ELKjs and Sprotty).

I got this :
![image](https://user-images.githubusercontent.com/25453472/71002545-c863c900-20df-11ea-8355-ab79c825b554.png)

But i expect this :
![Expected](https://user-images.githubusercontent.com/25453472/71002551-cd287d00-20df-11ea-89b8-ad2db43ecb91.png)

I cannot find a way to do it, do you have an idea ?

```
"labels": [
        {
          "height": 15.0,
          "id": "L1",
          "padding": 0,
          "text": "LB1",
          "width": 50.0
        },
        {
          "height": 15.0,
          "id": "L0",
          "padding": 0,
          "text": "LB2",
          "width": 50.0
        }
      ],

...

"elk.nodeLabels.placement": "[INSIDE V_TOP H_LEFT]"

```

**Comment by lredor** [comment]
Hello,

I find this [example](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUEQHYQE5qkCMaA3kWs9RTgMowBeOAdAMYRSAZzhRgMUnGHoARADkA8gBEAogH0AMgEEAQqs3tZTFuUqbgAIxwhhvAA6Z+OJDilyAEuoDCq+QBVVACU0ADV1f0UABTQASXl2WLVjFgwrGzQAcgBVe3s8C2sQTJNmTCKszQgAdwL04qIAXyIgA) in the [Gitter discussion](https://gitter.im/eclipse/elk?at=5ca7392031aec969e856cbb0).

Regards,

Laurent

**Comment by gvnt** [comment]
Thanks Laurent,

Your example helped me well.

The "elk.direction": "DOWN" in my layoutOptions is the problem.
When i remove it, that works well.

https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYCIBOB7FAXBAacYDGAFpADbRICmAdvANq4TBj0RRyKUCM2TLLA7jHQF4AFgAMWHrzAFykAOYF0oicwgJiAQwBG5YgGcEtNS1DTpCGEcQAZDmLHYTvBOnIAPTPAQ2AQlxxzF1kFJWsOAFYAOlUglgQBaCFw6LFnMABfQKCzOMQrbzsOACYnPMQ3T2sfX1LsuIQQxS8wSJj6oITBAhSY9IyTAF0O9S0ATxQAV3QAeQAHdEgUSkN4XPMEPQBrKMoUaHIbHT19KLmtPHIAWyoWhBoACQB9AGEAUQA5ABU3gCUwABqTy+MwACmAAJIfADKEIAIm9BggTANeKiwMNcBpNBNpvNFstVmB1ohtlFNMR5CgkJAhFdquNyBRoGV4mToJAKHgCZRqnCZgB1D7IiADDJAA

I will try to find a solution to keep "elk.direction": "DOWN" for graph, keeping the labels correctly positioned.

**Comment by lredor** [comment]
Maybe the fact the "elk.direction": "DOWN" impacts the label layout is a bug.

**Comment by gvnt** [comment]
I think you are right.

**Comment by lredor** [comment]
I analyzed the problem. The LabelCell, class responsible of computing the label location, has a notion of horizontalLayoutMode (Whether we operate in horizontal or vertical layout mode). But this field is not correctly initialized when the elk.direction is "DOWN" (it has always a true value). I will proposed soon a pull request.

**Comment by lredor** [comment]
I think that the pull request https://github.com/eclipse/elk/pull/477 fixes the problem. The data used for the test added in this pull request is available in another pull request: https://github.com/eclipse/elk-models/pull/2.

Steps to validate:
* Open the [476_multiLabelInHorizontalLayout.elkt](https://raw.githubusercontent.com/eclipse/elk-models/8c2b5a7e232a5f6cd06aef0d9c9a2e803738cb0d/tickets/layered/476_multiLabelInHorizontalLayout.elkt) file in the "Layout Graph" view
* Expected: 
    * An horizontal layout is done. The 2 labels of Node1 are centered, and one under the other. This behavior is OK without the fix
	* Look like [this](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=OYJwhgDgFgBCD28AuAoANmAnvArkmA2jAM4CWAXgKYBcMAbHQAwA0MAzEzALophrDwQpJFAC2tQcAB0lAMZpSEYpRloA1lIyZKISgBMUldVL2ldspKXgA7WgCUAkgHEAEgBUU1+ABksuJLQAZnzKnvB6lDAAcuGUAIwwAN4oAJBa-oSpKRDwZJY2tABMLDDFWWRURYwlcdWpPCleEQDKFCqyNsRI4KTWSMS0AEQEALIOUQ4jAKojAPrNDgBaAKJcg6lNlK1UUqK9pKI44jCDABTFjFIstZeMAJTraWAARkYw3nFDMRFxALQfgySWXSeEyKXBOTyVlsMAA7IVWIwsikKjQYABWOisOLorINRqxXyvNDEKQQDCySiiSh9IYEFyzADCyyibmWdlYADVZm4APIABVY4wWABFVo8AL6pDDE96FL6xP7eQqA5LgkH4AjIyHCaG0eHY3HglFtWiYw14rKbIlGUnksCU6m0k70pkstkcmDcvmCmDChxitapKVSzbRWKFIFPbCgrUQ3K6gqlNg1FPlU2larYuopBqbbbtTrdMC9fp0sYTaZzBYrIMElptXb7Q7HM4XK7MG5XB7Sl5vZUKiIqqPRjJx+NQpMADhKSONqNoABYakbc1bCX2SWSKVSaQEXQzmaz2VyeQKhVFReLgyhQ7FwxE2FGNWDsgn8jDF8vWIVl+nKpmNQ5nmsQFlIHTWF0PR9AMLoVpMMzzEs171lsjZ7NYBxHEM5zVB2Xb3I8Mr9mwg6UGwqrAn4sbau+eowDOiLIguMDfjAOKWuC1qbnaO5OvuwyHu6J5emevr+oGkq3oYejAJEyyfA+8QwL8AB8SmRmqL7jsoFjQjAyzNAk44okgYAgPucTFJ2ZTGjSehFCmnYzpxPBSvockGfKGkqep3zkc+1GauUcgfgZRmvqZ5n7mwTmFGmdnWA5rHfoUACcc5rmuEpAA)
* Open the [476_multiLabelInVerticalLayout.elkt](https://raw.githubusercontent.com/eclipse/elk-models/8c2b5a7e232a5f6cd06aef0d9c9a2e803738cb0d/tickets/layered/476_multiLabelInVerticalLayout.elkt) file in the "Layout Graph" view
    * Expected: A vertical layout is done. The 2 labels of Node1 are centered, and one under the other. KO without the fix.
