### ISSUE TITLE
Missing download for 0.6.0

### ISSUE THREAD

**Issue by bkolb** [eclipse/elk#478]
I wanted to download the release artefacts for 0.6.0. Unfortunately they are missing here: https://www.eclipse.org/elk/downloads.html

**Comment by le-cds** [comment]
Sorry about that – took me a few days to get around to updating the website. The release page should appear after the next nightly build, but for now here are the links it will contain:

* [Release log](https://projects.eclipse.org/projects/modeling.elk/releases/0.6.0)
* [Documentation](http://download.eclipse.org/elk/updates/releases/0.6.0/elk-0.6.0-docs.zip)
* [Update site](http://download.eclipse.org/elk/updates/releases/0.6.0/)
* [Zipped update site](http://download.eclipse.org/elk/updates/releases/0.6.0/elk-0.6.0.zip) (for offline use)
* [Maven central](https://repo.maven.apache.org/maven2/org/eclipse/elk/) (for building pure Java projects that use ELK)
* [Meta data language compiler](http://download.eclipse.org/elk/maven/releases/0.6.0) (for building layout algorithms with Maven)
