### ISSUE TITLE
RectPackingLayoutProvider not found in ELK 0.6.0

### ISSUE THREAD

**Issue by lredor** [eclipse/elk#479]
Hi,
It seems that ELK 0.6.0 has a build problem. The plug-in org.eclipse.elk.alg.packing.rectangles_0.6.0.jar contains no ".class" files. As consequence, there is a ClassNotFoundException:

> MESSAGE Plug-in org.eclipse.elk.alg.packing.rectangles was unable to load class org.eclipse.elk.alg.packing.rectangles.options.RectPackingMetaDataProvider. !STACK 0 java.lang.ClassNotFoundException: org.eclipse.elk.alg.packing.rectangles.options.RectPackingMetaDataProvider cannot be found by org.eclipse.elk.alg.packing.rectangles_0.6.0 	at ...
> org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155) 	at ...
> org.eclipse.elk.core.service.ElkServicePlugin.loadLayoutProviders(ElkServicePlugin.java:122) 	at org.eclipse.elk.core.service.ElkServicePlugin.start(ElkServicePlugin.java:66) 	at ...
> org.eclipse.elk.core.data.LayoutMetaDataService.getInstance(LayoutMetaDataService.java:64) 	at org.eclipse.sirius.diagram.elk.ELKAlgorithmProvider.getCustomLayoutAlgorithms(ELKAlgorithmProvider.java:50) 	at org.eclipse.sirius.diagram.ui.internal.layout.CustomLayoutAlgorithmProviderRegistry.parseExtension(CustomLayoutAlgorithmProviderRegistry.java:109) 	at org.eclipse.sirius.diagram.ui.internal.layout.CustomLayoutAlgorithmProviderRegistry.<init>(CustomLayoutAlgorithmProviderRegistry.java:79) 	at org.eclipse.sirius.diagram.ui.provider.DiagramUIPlugin$Implementation.start(DiagramUIPlugin.java:2

I think that this [commit](https://github.com/eclipse/elk/commit/3d2712a6368f3295280245c98881c1aaf9a21916#diff-e70d6c98cfd1e82fab1dab51cf513b9e) fixes the problem. Is there a 0.6.1 version planned to fix this problem?

For information, this problem was detected in our Sirius/ELK integration (bugzilla [559351](https://bugs.eclipse.org/bugs/show_bug.cgi?id=559351))

**Comment by le-cds** [comment]
If this is a case, it will be necessary to put out a new release. I'll get around to it in February.

**Comment by uruuru** [comment]
I just checked the jar created by the nightly build and it doesn't contain any class files either. That would indicate that the commit you refer to unfortunately didn't solve the issue.

**Comment by lredor** [comment]
I think that just a line is missing in build.properties file. See https://github.com/eclipse/elk/pull/480

**Comment by lredor** [comment]
Is there a way to launch a build on a specific pull request to ensure that the result is OK?

**Comment by uruuru** [comment]
I've merged the PR, you should be able to tell after the [nightly build](https://ci.eclipse.org/elk/job/IntegrationNightly/) tonight. There's no setup to launch a specific PR at the moment afaik. You would have to execute the build locally.

**Comment by uruuru** [comment]
Looks fine now - at least class files are included now:
[org.eclipse.elk.alg.packing.rectangles_0.7.0.202001250310.jar](http://build.eclipse.org/modeling/elk/updates/nightly/plugins/org.eclipse.elk.alg.packing.rectangles_0.7.0.202001250310.jar)

**Comment by lredor** [comment]
@uruuru OK. Thanks for the check! I think we can close this issue.

@le-cds Could you let us know when is a new release will be available?

**Comment by lredor** [comment]
@le-cds Is it expected to add this issue in 0.6.1 (https://github.com/eclipse/elk/milestone/14) ?

**Comment by le-cds** [comment]
@lredor Yep, this will be part of 0.6.1. My plans are to release 0.6.1 before the end of February. My colleague is currently working on rect packing algorithm improvements which are planned for that release as well.
