### ISSUE TITLE
Add ELK 0.6.0 update site to the Downloads page

### ISSUE THREAD

**Issue by miklossy** [eclipse/elk#481]
According to the [release plan](https://projects.eclipse.org/projects/modeling.elk/releases/0.6.0), the ELK 0.6.0 has already been released on Wednesday, December 18, 2019.

However, the corresponding update site is not yet listed on the ELK [Downloads page](https://www.eclipse.org/elk/downloads.html).

![screenshot](https://user-images.githubusercontent.com/20393472/73126713-3e4c3180-3fb6-11ea-9d36-90a17d2a2874.png)

Would it be possible to update the Download page with the 0.6.0 release with a link to the corresponding update site?

See also a similar issue: https://github.com/eclipse/elk/issues/478

Thanks in advance!
Tamás

**Comment by le-cds** [comment]
The page source exists in our website's sources, but the synchronisation script fails. I'm on it.

**Comment by miklossy** [comment]
Thank you @le-cds !

**Comment by le-cds** [comment]
It's more complicated than expected. I've filed [a ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=559889) with the Eclipse admins.

**Comment by le-cds** [comment]
Took two commits, but the website finally updates properly again. :)

**Comment by miklossy** [comment]
Thank you @le-cds !

**Comment by le-cds** [comment]
Cheers. Shouldn't have happened in the first place... 😉
