### ISSUE TITLE
RectPacking: NaN positions on a graph

### ISSUE THREAD

**Issue by NiklasRentzCAU** [eclipse/elk#483]
When using the RectPacking algorithm, the resulting layout sometimes has some NaN coordinates and sizes. Here I attached the output log for an example run:
[rectPackingNaN.zip](https://github.com/eclipse/elk/files/4128439/rectPackingNaN.zip)

```
<graph:ElkNode xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:graph="http://www.eclipse.org/elk/ElkGraph" height="774.0" width="NaN">
[...]
```

**Comment by soerendomroes** [comment]
You can reproduce this issue with the following graph
```
algorithm: rectPacking

node n0
node n1 {
	layout[size: 100, 100]
}
node n2
node n3
```
