### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [eclipse/elk#485]
Hello Eclipse Layout Kernel team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477)

If you are interested that the Eclipse Layout Kernel project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>

```
We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by le-cds** [comment]
Hi Tamás,

thanks for the opportunity. Here you go:

```
<tr>
	<td><a href="http://www.eclipse.org/elk">Eclipse Layout Kernel (ELK)</a></td>
	<td>ELK is a collection of diagram layout algorithms implemented in Java and provides ways for the algorithms to be easily used in Eclipse-based applications.</td>
	<td>EPL 2.0</td>
	<td>Library</td>
	<td>Ulf Rüegg, Christoph Daniel Schulze, Miro Spönemann, and lots of contributors</td>
</tr>
```

Cheers,
Chris

**Comment by miklossy** [comment]
Thank you @le-cds !

**Comment by miklossy** [comment]
The `Eclipse Layout Kernel (ELK)` project has been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html).

**Comment by le-cds** [comment]
@miklossy excellent, thanks. 🙂
