### ISSUE TITLE
Cleanup build

### ISSUE THREAD

**Issue by sailingKieler** [eclipse/elk#487]
Please remove the following lines from the target platform definition:
https://github.com/eclipse/elk/blob/3c28c0639585ebeab6fffab12d7e86cd581019ef/build/org.eclipse.elk.targetplatform/org.eclipse.elk.targetplatform.target#L30-L33

Besides, please change 
https://github.com/eclipse/elk/blob/3c28c0639585ebeab6fffab12d7e86cd581019ef/build/org.eclipse.elk.targetplatform/org.eclipse.elk.targetplatform.target#L28
to http://download.eclipse.org/modeling/emft/mwe/updates/releases/2.10.0/ or .../2.11.1

**Comment by le-cds** [comment]
Will be done. Taking the opportunity, a few other build problems need cleanup as well. These include:

* Changing the Maven Central repository URL in the main `pom.xml`
* Changing our Eclipse Maven repository URLs on the download pages to use https instead of http
