### ISSUE TITLE
Edge Routing / Horizontal Partitions?

### ISSUE THREAD

**Issue by shean42** [eclipse/elk#490]
Hi all,

While the layout for [this graph](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=FAb2AJwIgSwEygLmgJwPZoC5QDQWgMYAWMANnCgKYB2S4A2vpGJK9PHVOgO4D6AjLiasopAIYAjSqQDOdeuBDRMlAB7ZkXNN3CCc7BJp6DwAX3ABdPG0iixATzQBXTAHkADphhpqcxMOYAkXcxFC8vHxhqAHMAOjECLwA3MRU6TBQnSmsbUxy2KGIyChokIMYbViVYQ1R+XhkCepk9aHEpWXlFZTUNaBbcA05SXhRmpoaTcytobnhMIjoAJgBWfSgiShhooj7V9fFHFw8I3zpqkLCYU7p+MzN8m2qOI3HmpcG7Dr8GbqgVdScGQfdYvNqjN4ND73GZQOZwBbLNbQTbbXZIg4OZxuTzeM7IC6hcJ4273PJBZhDV4NCZiVpfaQ-BTVAF9KB0z5g0QQmn1Dkw9bwxHIfYorY7PbIuxHHGnH6Eq43ZB3czkyqUmqcMa83hiEFtSSMros3qcPWc2rc7WNPnQ6aC+aLEVS1ESjEGmUnPHy6CXYk+Umqx5sZ6W620gDMn3aRuQzJ6gM0YijoMtI3DfKjAtmjvdG3F6OdmM9uJ8PqgfuuJOVZODVSpdR1lHpMc6cb+rM4zYtwx5Nt43ezcNzRbFaMlxexXrL519RKrAZrQYpfy5GYH+oZbd+JsT0Eom656chB6gQ6FTvAovz47zhynpfxf0rSt0tZXoa1kOiLcN2-j-ympoP49pox46iB54jleLoFhOHoPnKs4VvOr4qg8H4Nlw4xLJM0Z-kyHZAf09JHn2BC4QMUEIpe16uoWMGTscj7li+1ZXu+6qrmGOFQvh3zGgmbLAqB4LhpRdqWA6NF5vR8HSoh3rIWxi4ccuXGftSjS4RymICe2u5srpWHgdpupTFJOYyaON5ujZ97MUhBJzoq7FLJx6qaY2ZnmnpsY7kJZqHmm5E6ZJsIXrJcF3lijlKc5KGuap7nqZ5WHibqKYGvpAWAXu7JZZqYGhZlZ72lZwqMWOdlVQpcUzglKm0CKHmVF52E0rh3Z+f+RH5ZQuiiVavGDuVw7WbVckxSWTnPqhbmtU86UjZuraEYZXZXkNpkURuZWWeNlV0dF9mxbK8VzUlzVqRhGnLZ1vAgT162BcBpEhRlkFjZFNlTadM0XQq-rXSlZhBFYQRQJQcDRJQfjlJhUAyM4KAEHDXQdf2VGwpgoSw5ghGY7S0KwlySyrAAZmIABscCUAAtAAnKsAAM9MACxwAAHAA7PTYgs+zjNMzzKwEBTLMECzcASELZV1hqyNOKj6PtkTtpnjjeOUATGProOpOWiz1MRgQKzs-wYj0wQPMEFzHMrDz7P0xISxwPw9M8xIFPs7z-ArNTVMU-LiNKyrhPriJB24yg+MR5Cyaa6mnAEOzSw2-w-ASPTLNLNTVtCzT-PU4zbMRoLEYU3ABCM4zVdTArfxh2j8c6on0fa7rav6yYhtdqn1Pe2IFOezzosc+7EZMxIXNWzzyYRmIjOi3AKxVyHd1IyjLd65C2PrDHce723vfJ5os+OxTlAUys9MSxIbPsxTdsu4zlD29T5Om+z5tc1z4sbzSlvZWO9u4J1PsoTurd+wGzPtAFmw8xBwBNs7CmXMlgj3ZgQKWLssEMyWFzFYXNqYrDrk-FmXNAFtX6NvVWvx1alQ7rHHW0CJingOlyCQPN85r3zvTT+5MOaSDgK-JYHtObcMoCQtOAcqFLWAeHY+-Z+Ra2YV3eh65IJ900OzbhP8KZ8IEUsIREgRESGZuIuAkjpGrGpnIkMNCQF0IUAwrRB8oFKLYSTOBUB2bsx4QYq2RiTFmIsRPax5tbH2PrAo0BGiTzeMgWo1hEkk5YQIGIdBq8IzO3ZuXBmFsJDZy5ozLB9MVjkzgHAJYEYH5o0ZtExWtCUl8SYUfMBD1zQcMtEUk2Psn70xqUsAuaCR5iH8XzV2EZP4EEDhLRmdjbpAObs47yu0o6qPafEzpWZtHQHJmIqpxs7480zhzSg7MGbeyIUzLmCDh5wEllIAgjSm7NM8TpCB-wPEdLMrArCy9qbcJts7Hm0zs5pwMfzMQDN+C1JWCsWWvMpFiFedUFZLSVHuOSR8va3TOARi5pQW2MKPYrDplPdmssRH-wIFPKW6CKFS3FhIRZaplnvN+btLFSStkuM+l8smejeFBIOSE0RliIkyLZY3dFnLtlmTcbylhuL2F7KgEsfxYgRX8LFezYRErwnUykZE2RSzqGxNWUTMKaTvk4q5V1RJRV9k0y5rU1lnsubV3ORTYWeoS53wpgY6G6CZ7ezRY4xRDq8JtJVdGnlzqoDUwQSsQWEgCDlNdrfPx-BnZiC9lbSg5ieZLEFgg3OWZ2UWoxbi9umy40Kt2mqnxhKb752vtbKxlLiEMwWVS-my9tVLykbPdmEbLWYqdYfBt-LwG2rJpQFYOSvbOwoSQiexzZ53PphGaunNKBSzEDTO04NhBVsUJDNc2heAgkhmtQSeU2Q8C2j4ng4U6x1XOg1IILB1SJWBlEOICRkipEoOkTI2QgjntsEUcgVBmoI03muSiEwBjPQfZ2TQaGTKjBQ80CyEVoLHVvP9RSDVLrA0DOa+RyGdQiXQwZV6-Rgq9hQHh1p30iOwRI7VByX6nxAwXNddC0GYm0eUb+HKAFMPQGMom9M7H+ScYmsRmq14+PTgEy5SjS5qMOMTWxtuq0CIYeIuyFjxVDPKPfRVWi3G1NSg0yxZS81VIidlelRThV72McfWaQqZErORn2oRlT9mGLqbOpp1irnhOLX0+Jthkn-LSbM91HDQX6ijQOj9SaJ1eNRec41WLVHRMakS1l4zUm+pslPD4hTTYbOHTs+sP6BWAbkcE2heLYmwzsaetlFLNXOADfk7hiCBHpJHXC-JJzs0uvsXc4jRLlFku9Q2lh96rGUOrZC1Nlr1UIuOcK-N7TQnlg9fK31h69HBvraY0jCzYkdscZy1x1r+XIsda0-+87LVUoWpW+ZfiQ2Nuya25Zl7Sm3thY+zxr7ZGftNQuwDmj12fJVdBw93yGWodNdy6po7TF+MxauijvTvWtRQ+8yZ3zMmCrbXGz5StMPptw4c8T6LLmyf-Yp1dqnD10tbhen5zQA0IfPcF5N2zUV4fHe+6TnTN0yvcQF38zH93Rf7hfbjwX+P3uHdmydwGZ3XygxV+1ILuFRs+dyvT0bgWXtfVZwd2yROEL1SRyV3nphwYfuhrDeGlQKgcqcRHdj+9lXqP5Ypp1ZNyZrxpnTJmrMJ6835oLYWy8xYSyljLOWfO3lh71rH2107o+oHY-8xNpaTZmwtlbG2L8f5Oxdm7D2XsfZ+wDkHcdNbu4R6nT8jRXn52WnTmnDOWcc55wLozIuNNS47orlXGudd3Z9-lTHtuuzsV8sr02QV4+D3+KHiPMe49OZwunrPT2C8l4rzXggQvcri8D7o188v4eT5j84AQ7VPMV8N8d8LMD8HMz89s5i78uqNSqcv8-8wcL+kacS2+EmZew+qBSWv+mgpaiCyCOSd86CmC2CbMssaMgyhCxCpCPsEslCSBE6JeO+6B9qI+jW2B+yXCAShieqBq5iYiRqJq0qm+b+rBaBsaFeXA-WR+f+ui1M+i3Bgi+qpihqEixqNiZqFuyBVqmWj0n+GBB+MCce4+fiXBoqihvBYSqhghUS9B-eohXizB++khN2Rhf+GSWSS6uS+SHMWcxSpSGaFSbs1StSkslADSthW+Bh6yQ+LBmBNq+KOBvSlcfiI8QyIyXMYyEybe0y6ccyLMCywhUa9hqS4h3+zO7BGqBy-ARy1MJyZylylyLsN89sjMdyR6VcTyB6hRKBURnyjhM6vRA40hOBgKwKreYKg8HMGCtRR6sK8KiKvsPMKK3R2hUOehsRgxzaWENSRKJKzY5SFKHM1K9MtK9KFCpa-8ksFMrKKxZR3K6xThVuuhFR5MwqgSMBxiShoS-BVh6hMqockRzhiqDxAxQJTarhOBmqphHx4qfBkqahpq-xm8dhcRuoMRjxL2WxNewy1MbqvSnq3qlyvq-MecwsQawa3MSwYaiBmhDB7+ZkkedqGJnSwx+yya2qaaARWaHMFseaBa9MRay8pa7M5aNStxjB5RpREp4JLxraAcMKI8BAXaHMPaTMch2cD+Q6b8uJ4y4p9J3K6JoJOhCa8ei6y6ssOcVBG6tRW6Zce6dMh6x6ZUp6bAvukAEMtgAeqs+AIeTSIhs6nShpEhxprJUAqgo0+AFgwAvuQAA) is nearly perfect I'm struggling to find layout options to properly route that one outstanding edge.

A requirement in the given case is the horizontal partitioning with the rows underneath each other, even though the rows don't have to be compounds.

Given this setting I have two questions:

a) Can ELK route the edge in the above example while preserving the rows?
b) Is there something like 'horizontal partitions' in addition to the  vertical ones ELK already supports, which could help to solve the above?

Thanks

**Comment by le-cds** [comment]
The edge you're talking about is what we call a [long hierarchical edge](https://www.eclipse.org/elk/documentation/tooldevelopers/graphdatastructure.html). By default, ELK lays out each level of hierarchy separately, but that doesn't work with such edges. Setting [hierarchy handling](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-hierarchyhandling.html) to `INCLUDE_CHILDREN` will fix that part of the layout problem.

Regarding your partitions, I'm not entirely sure whether that will work in this particular case, but I certainly invite you to try. 😉 The basic idea will be to switch the [layout direction](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-direction.html) in the topmost level to `DOWN`. That will already yield the two rows, but only because there is an edge running from the top to the bottom node. Enable partitions for force this order by setting the [layout partitioning](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-partitioning-activate.html) option to `true` on the topmost level and assigning the compound nodes appropriate [layout partitions](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-partitioning-partition.html).

I hope this works properly with the hierarchical layout mode. If not, feel free to get back to us and we'll see whether there's time to fix any bugs!

Cheers,
Chris

**Comment by shean42** [comment]
Thanks for your reply, this is quite insightful!

After playing around some more with the options here are a few findings:

- Direction 'down' is nicely working, but unfortunately I can't use it since the nodes in each 'row' need have the direction 'right'. I see from another discussion [here](https://github.com/OpenKieler/elkjs/issues/26) that different directions in a hierarchy are not supported yet, so this certainly would be an interesting feature!

- By trying to work around the above I'm testing a flat model. While the overall layout turns out quite nicely the separation and pre-defined order of the 'rows' naturally is not reflected in the output. Having horizontal partitions in addition to the already existing vertical ones could solve this, so maybe that's an idea for future developments too!

- Another approach to solve this could be to separately generate layouts for the 'rows' and in a second run route the inter-row edges. I see that edge routing without node placement has been asked for many times, so I'd like to ++ that counter :-)

Let me know if you have some more ideas about what could be done with the existing features! I was thinking about wrapping/cuts but could not get that to improve the overall situation.

viele Grüße :-)

**Comment by le-cds** [comment]
Thanks for your analysis and suggestions! Somewhat embarrassingly, I had not thought of the fact that hierarchical layout does not support different layout directions yet. I will in fact create an issue to track that, but seeing that it's a rather complicated part of our code base, you'd better not hold your breadth on that one. 😉 

Separate edge routing is a highly sought after feature indeed, and it is high on our agenda. Once we find a master student willing and capable of implementing it, we're good to go.

Viele Grüße zurück! 🙂

**Comment by shean42** [comment]
Cool, thanks a lot for all your efforts here!!

**Comment by le-cds** [comment]
Cheers. I'll close the issue for now. :)
