### ISSUE TITLE
Support PORT_LABELS_NEXT_TO_PORT_IF_POSSIBLE for outside ports

### ISSUE THREAD

**Issue by sailingKieler** [eclipse/elk#491]
Like demanded in #219 for inside port labels, it would be great if the same would work for outside port labels, too. This is beneficial for component diagrams showing e.g. a single component with its interface and also content within the component. For the encompassing component representation outside port label placement is the natural choice, but the actual port label placement is not optimal yet.

**Comment by le-cds** [comment]
I believe I finished implementing this feature. Was a bit harder than expected, but I managed to simplify the port label placement code in the process. 🙂

Would you mind checking whether this works as expected?

**Comment by sailingKieler** [comment]
@le-cds looks good to me

Just for curiosity: Is there any way to reduce/steer the indicated spaces in the following screenshot?
![Bildschirmfoto 2020-02-25 um 11 13 47](https://user-images.githubusercontent.com/8513883/75238794-df025c80-57c1-11ea-8e8b-631136d956ef.png)

They (at least the in-between ones) seem to be exactly the spaces being reserved for placing the port labels the classic way, like in
![Bildschirmfoto 2020-02-25 um 11 14 16](https://user-images.githubusercontent.com/8513883/75238851-fa6d6780-57c1-11ea-8a58-355d341e5ec7.png)

**Comment by le-cds** [comment]
@sailingKieler how are the node size constraints and options configured in your example?

**Comment by sailingKieler** [comment]
Here's the full description in `.kgt`:
```
kgraph graph
	properties:
	org.eclipse.elk.spacing.labelPort = 0
	org.eclipse.elk.spacing.portPort = 0
	org.eclipse.elk.spacing.portPort = 0
	org.eclipse.elk.spacing.portsSurrounding = 0
	org.eclipse.elk.direction = RIGHT
	
knode outer {
	properties:
	org.eclipse.elk.direction = RIGHT
	org.eclipse.elk.portConstraints = FIXED_ORDER
	org.eclipse.elk.portLabels.nextToPortIfPossible = true
	org.eclipse.elk.portLabels.treatAsGroup =false
	org.eclipse.elk.spacing.portPort = 0
	org.eclipse.elk.spacing.labelPort = 0
	org.eclipse.elk.spacing.labelLabel = 0
	org.eclipse.elk.nodeSize.constraints = "PORTS"
	org.eclipse.elk.spacing.portsSurrounding = 0
	org.eclipse.elk.padding = 0
	
	krectangle

	kport a {
		size: width = 20 height = 10
		properties:
		org.eclipse.elk.port.side = WEST
		org.eclipse.elk.port.index = 2
		klabel "afoo" {
			krectangle {
				ktext
			}
		}
//		klabel "baz" {
//			ktext
//		}
//		klabel "bar" {
//			ktext
//		}
	}
	
	kport c {
		size: width = 20 height = 20
		properties:
		org.eclipse.elk.port.side = WEST
		org.eclipse.elk.port.index = 1
		klabel "cfoo" {
			krectangle {
				ktext
			}
		}
		klabel "baz" {
			ktext
		}
		klabel "bar" {
			krectangle {
				ktext
			}
		}
	}
	
	kport d {
		size: width = 20 height = 40
		properties:
		org.eclipse.elk.port.side = WEST
		org.eclipse.elk.port.index = 0
		klabel "dfoo" {
			ktext
		}
		klabel "baz" {
			ktext
		}
//		klabel "bar" {
//			ktext
//		}
	}
	
	knode inner {
		size: width = 50 height = 20
		properties:
		org.eclipse.elk.portConstraints = FIXED_SIDE
		org.eclipse.elk.portLabels.nextToPortIfPossible = true
		krectangle
		kport b {
			size: width = 5 height = 5
			properties:
			org.eclipse.elk.port.side = WEST
			klabel "hugo" {
				ktext
			}
			klabel "ferdinand" {
				ktext
			}
		}
	}
	
	kedge (:a -> inner:b)
//	kedge (:c -> inner:b)
}
```

**Comment by sailingKieler** [comment]
Btw.: By accident I got the following drawing
![Bildschirmfoto 2020-02-25 um 13 43 54](https://user-images.githubusercontent.com/8513883/75248723-fb5bc480-57d4-11ea-8c35-d6fc1f2d314e.png)

when having the root level direction setting deactivated:
```
kgraph graph
	properties:
	org.eclipse.elk.spacing.labelPort = 0
	org.eclipse.elk.spacing.portPort = 0
	org.eclipse.elk.spacing.portPort = 0
	org.eclipse.elk.spacing.portsSurrounding = 0
//	org.eclipse.elk.direction = RIGHT
	
knode outer {
	properties:
	org.eclipse.elk.direction = RIGHT
	org.eclipse.elk.portConstraints = FIXED_ORDER
	org.eclipse.elk.portLabels.nextToPortIfPossible = true
	org.eclipse.elk.portLabels.treatAsGroup =false
	org.eclipse.elk.spacing.portPort = 0
	org.eclipse.elk.spacing.labelPort = 0
	org.eclipse.elk.spacing.labelLabel = 0
	org.eclipse.elk.nodeSize.constraints = "PORTS"
	org.eclipse.elk.spacing.portsSurrounding = 0
	org.eclipse.elk.padding = 0

```

**Comment by le-cds** [comment]
Everything works for simple nodes. The problems you're experiencing here are caused by the fact that yours is a hierarchical node. I'll try to find time to fix some of the problems, but one problem is the spacing between the hierarchical port dummies. I don't think I'll be able to fix that before the release, but I'll track the more general issue as #503.

**Comment by le-cds** [comment]
Note to self: the culprit is [this piece of code](https://github.com/eclipse/elk/blob/5fb648d1afdf33881e39f68880a964b439ef7323/plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/LabelAndNodeSizeProcessor.java#L154).

**Comment by le-cds** [comment]
Apart from the incorrect port-port spacing (#503), this is how it looks now:

![Screenshot 2020-02-27 at 16 00 55](https://user-images.githubusercontent.com/7465584/75456160-77dbd800-597a-11ea-9075-66ddc8d23410.png)

I'll merge the code into the 0.6.1 branch soon.
