### ISSUE TITLE
Variability in port label alignment

### ISSUE THREAD

**Issue by sailingKieler** [eclipse/elk#492]
I advocate an opportunity to steer the port label placement in some more fine-grained manner. This is especially important in case a port has several labels.
There may be different situations:
 * there will be at most one port label over the entire life time of the diagram
 * there are several port labels of equal importance
 * there will one (or more?) main port labels staying all the time and one (or more?) auxiliary port labels that may be added and removed during the diagram life time and that shall be nicely integrated into the diagram layout without changing the main labels position "too much"

Different approaches are illustrated by the following examples:
* vertically centered alignment of the entire label area of a port to the port
<img width="736" alt="Bildschirmfoto 2020-02-10 um 10 42 23" src="https://user-images.githubusercontent.com/8513883/74138857-9d36bb00-4bf2-11ea-8287-e6c84bfe5c52.png">

* vertically centered alignment of the first port label to the port, all remaining placed subsequently
<img width="731" alt="Bildschirmfoto 2020-02-10 um 10 40 36" src="https://user-images.githubusercontent.com/8513883/74139924-74afc080-4bf4-11ea-9267-2e91c52f14eb.png">

* vertical top bound alignment of the first port label and the port
  (no screenshot)

**Comment by le-cds** [comment]
My latest change introduces an option `PORT_LABELS_TREAT_AS_GROUP`, which is active by default. Deactivating it should yield the result you crave. 😉

As with #491, would you mind testing this?
