### ISSUE TITLE
INCLUDE_CHILDREN should support different layout directions

### ISSUE THREAD

**Issue by le-cds** [eclipse/elk#495]
As it stands right now, ELK Layered in hierarchical layout mode does not support different layout directions for each level of hierarchy. That should be changed.

**Comment by uruuru** [comment]
Didn't we discuss this a while back and decided it's too complex?

**Comment by le-cds** [comment]
True, I seem to have been a bit over-eager here... The topic came up in #490, and while I did mention that this is a hard topic, I didn't appreciate just how hard it is at the time. Hm... I guess I should close this one, then.
