### ISSUE TITLE
org.eclipse.elk.alg.layered.options.LayeredOptions not found

### ISSUE THREAD

**Issue by jiaxizheng** [eclipse/elk#496]
Is the file named org.eclipse.elk.alg.layered.options.LayeredOptions missing? Compile failed. Is that my problem?

**Comment by lredor** [comment]
This class is generated. You must have "XText" installed in your environment.
You can use Oomph to setup your environment : https://www.eclipse.org/elk/documentation/contributors/developmentworkflow/installingwithoomph.html

**Comment by uruuru** [comment]
On a side note, you can have a look at the [build.gradle](https://github.com/OpenKieler/elkjs/blob/master/build.gradle) of elkjs if you're interested in compiling the layout algorithms without installing an Eclipse environment.

**Comment by le-cds** [comment]
I'll close this for now. Feel free to reopen if there are any questions left. 🙂
