### ISSUE TITLE
Spline routing creates sharp bends on cross hierarchy edges

### ISSUE THREAD

**Issue by eNBeWe** [eclipse/elk#50]
(Migrated from KIELER Bugtracker - [KIPRA-1746](http://rtsys.informatik.uni-kiel.de/jira/browse/KIPRA-1746))
The following graph creates sharp bends on cross-hierarchy spline edges.
Depending on the edge routing configuration  of the inner node, the bends are placed different.

```
properties:
    de.cau.cs.kieler.layoutHierarchy=true
    de.cau.cs.kieler.kgraphsynthesis.defaults = true
    de.cau.cs.kieler.edgeRouting = SPLINES
knode A1 {
    kedge (-> B2)
}
knode A2 {
    properties:
//      de.cau.cs.kieler.edgeRouting=SPLINES
    knode B1 {
        kedge (-> B2)
    }
    knode B2
}
```

![hierarchy-splines-off](https://cloud.githubusercontent.com/assets/3796429/16764563/2a9d8f58-482f-11e6-9302-8bde6bff80dc.png)
![hierarchy-splines-on](https://cloud.githubusercontent.com/assets/3796429/16764566/2eac69d4-482f-11e6-92ac-42a600af53ec.png)

This is also related to the viewing infrastructure. Currently the KlighD viewer doesn't allow for different routing styles of edge segments.

**Comment by le-cds** [comment]
We simply don't support edges routed through areas with different edge routing styles.
