### ISSUE TITLE
Layouter id for rectPacking inconsistent

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#507]
Take a look at https://www.eclipse.org/elk/reference/algorithms.html 

Usually a layouter's id starts with `org.eclipse.elk.` and adds a single element for the layouter, e.g.
```
org.eclipse.elk.layered
org.eclipse.elk.mrtree
```

For the rectangle packing this is different: `org.eclipse.elk.rectpacking.rectPacking`.

I propose to align it to the common case.

**Comment by le-cds** [comment]
@uruuru Sören has changed that, and I ported the change to 0.6.1. This probably means laying hands on elkjs as well? Not sure.

**Comment by uruuru** [comment]
I wasn't necessarily aiming for a rename of the plugin itself (from `org.eclipse.elk.alg.packing.rectangles` to `org.eclipse.alg.rectpacking`). The `packing` part was added on purpose with the idea to place multiple packing algorithms in the same namespace (if there ever are multiple). 

I believe it would've been enough to change the algorithm's id in the corresponding `melk` file.

**Comment by uruuru** [comment]
And yes, elkjs has to be adjusted in either case.

**Comment by le-cds** [comment]
The ID is generated based on package names and the layout algorithm's name. Our thought was that not renaming the plug-in would have been a sure way to introduce strange inconsistencies. ;)

**Comment by uruuru** [comment]
Isn't the id solely based on the id prefix and the algorithm id within the melk file?

**Comment by uruuru** [comment]
After all, the id is still inconsistent: `org.eclipse.elk.rectpacking.rectPacking`

**Comment by le-cds** [comment]
> After all, the id is still inconsistent: `org.eclipse.elk.rectpacking.rectPacking`

Argh... Will be fixed in the next release.
