### ISSUE TITLE
How does elk.port.side work for SIDES_...?

### ISSUE THREAD

**Issue by shean42** [eclipse/elk#509]
A quick question for the experts concerning port sides. I'd like to have outgoing edges on any side of a node, except WEST. The port.side configuration has an option 'SIDES_NORTH_EAST_SOUTH' which may be what I'm searching for? However, setting this value does not give the desired result as you can see [here](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGBECWAmkC4oCcD2qAukA04oGMALaAG1mQFMA7RMAbTwglCdajlsgAYAmAQwAsANgDsAI1gBaAMwAOHkMkCRI2ZL48KATkmxYFWXwCMw2Fz05GbSCT4BPVAFcMAeQAOGaKioBnWizZWSDc+ZE9Pb1ojXECgihIAawA6N1QwgGFvHwxkPmgqDD8kSAAxAEkADQBRABEAfQBlMpqqy1iwAF8Y2Js+MXii+itAgPaISAwKAA8sJAByBqdkfAo57rH2eGKSOt5BUQkZeUVlVXVNHT0DY1NzeGG2DoeIAF1161SwwYYN0bGYLZQAAKRiMlgAkJDIcE0G4KGFoBRBqBgmkMEkfHAKJwmi0GnUAHIuABKABUABJ1KoAQQapMaLgAqhTLJApp90Zj9JwiWTyRCoVCOhsIM8mE92m8xWzaAJpFokjwBLItKq1WrZO8gnZaFoeIquIajcbDTwtUxIAB3OAYQhRLjSc3jQgUaAAc0IszAAFZpA8ug8-kEOMVpDx8N6BHLpLoTAAzJSwLSKFViPiSOPeoxCDRCSMUfBcNo9WwOZzuCK+fxi8YhBGV2hcJ0W+LJDmZXw5PIFQalSq1RrNVpigPtXr9EjfGtgIM9SYzWhzUmhN0UDBrafjENQHZhiNR6Qx2DxxPJySp9OZ7O5-OFyDTiWxKVjjlT36bzacIE8MHNoJuWF4U8JFq1rNEMSxTgAHUqjpe8RU6P9OjFN4xymWhvUVZV1RwkRk2bSAdSQZQklkb0TQos1pWtWBbXtR1pRdd1PQwv1Ai6QIrFnAFOD4I1YCVb0ZFUKQBD4LQjHPPghHwdR8GzHgeFkWARCEcxiyCUsnFcDwvCrJBZ1rUJwj0qJ-XNccBloH5YkMi15y9aJpx47Y6j4w0BIEITpBEpRxMkwwZLkhSlJUtT7naR9WGfax0KQaQTCwlUcI1CyiLAIxeANCiTSowIrRtO14oY-KmI9L1DysUcmG47dIGEOMhGVWAYy4AQKEkgQ42ESRk3wKQ4yMb1DBEfARFgIRBo0i0tPLXSslAno6xMyIkCMcyHksydrLFOzxgcqIkJcnc6gaprlNa9rOu6xQ+oGoaRrGiappHB4YqCOKwDlBUlWSlKtE1Tb0r1bKcqNPLrBoui1odCyypYpBfSq95asBSARF4LQCx4HQuukUTvS0Lh1C4PU5LEIw42kNMeDjHhvWm8ZZp0ytkWlZboAbNaNvy2wJzfWznIOtajrqnYMZx7HcapgmiZJsm+HwCmqZpumGdewJ3otT6hCMfURGw-6AbS+0uCSDGwfBiyoaKsBpCEOHXXK2h7eRrjNrqh0tDwoQeGJ5UEqUcieHPFQBEkJWKCVMQ6dgfA6cZnd7G0is9LZl9jM50zufYiy+aspAbJGIXpkc0W0Z2L2fb9pRZEDrzeFDg2I-6aPY-jnh4NiKKmC18ZPoSgQkqN42gftfU-ct01rcKl2SuseGKrY8UUY9tGhFgQnGpUSQuBWdNlSVKSjAoSRMqELHjHkFUGbz5O5tZxb8o5rmMp56x8+2wvdpLhcRecsWdQN5b1ECIXe+9a5H0MCfM+XAL4UCvkpLQ6tIpvQsjrPW5tDb-UBvldKmUzYWynhDIINsXYO02ovchbtWCo04L6MQ3oN59DPrIfAskBDhmJqqdqvUCy8DjOYPiYhO53zLCzNOT8PiZ1futXOm1P4C2LhsCYpdDoAIrnUBhTDYAsKMGwjhXDepaF4VjQstMhFcBEV3diaDNqfW+sPI2uDrDAwnlPaem0yEw3nkEKhiNl4QGqswNevFOEUDjGILqMghBiDEEoemagRERnUN7HyXA+DkW9HGOMidejiNTgtAy7MZHZzfvI3mfQC5DHaHtKAwsoBGDqG6ROwZNGCE0JE6J9s4kJOGpIZJQlxIiHSZkrg2TckazYH3KADiL5OJwSbJA3tQaWxIRabxX1fEWn8VsmhYAYqQAoLAVcSiZyhOKBQDGFAY5tTPlck4qpbr4GkKfCg2TFJ8EERfIwWg8k+CWCsM5QR3LmEEsJZSfkJJSSCorEKylVLqTsflDAK41zAotGdZql0OpKBur1GS91hp8FGuNSaYI3r7JCflOqvs8JdWhek0+nC969TjOIAZcg4wRP6EIWQeF-mApAt-McWKLq7yuninqd0MwPRJU9clNje4WVRcgVchQdpjglmYnGeL8ZBzlnxBWStKbUw0GrJVrwqXnJpWjEQcYJIiAoK8s+esTgCCseeIwsA1B8H5QIMQcDxnKmxBZAFjhljCpqT0MVLUJW4q6tKwlsriWkuehSzWKq0UapFT0YBWht5gL3ggyB4doGn3PpffRSCUHTOtXQy5Qgo6yGzPEnMhNIHEz4N28OWZCX9UEDckQgqI1As1TGya5041tQTfimVg1U0Kpepmzaqr1UYvGB0nl3TYnxM4f0wZqSRkYzGRMy1Bz60XKgMYb0hNpD4HTDwMQ+BcYKBjLIDJUg+KiAEB3b0ehRGbXDZGjdUAq7JhrgHTqwcm7h0jm3HgccE7IusGu9F478p7GEOIKQcgFBKBUL6i4uh9DQNuBYSlrBgk2usHVPiitfSZkkE2gQr6vLnnjjGIwBt2rvOGYwkdIGMPWHA77f2ddoON35c3eDAb27IZXSi7NoHIDaOYfE-R7CEmFmMaY-hFjdFWM7pRle7tbWcE0D6vtskjCvITO1b08S2EqnUHwZ1bDyIiAUKGoDQqVNYYOLh44BGzgaG0CR64JgN53HPTMiYynhNBHzYW8BJbD5luMBWuBVbr7INi5e8zxRZAqnvVY9MWg47S2OaksiSgxraDTFoMa1iw1+cSxaNTuiNMGO09wkxp8zECMsdYlDQQ0M5ujflZLoDUsH3kBlmBlaEHVpvvlqjq9CsECVipE+klvT4DlEoMQshT4U00L1aQ3oKBiWzO1DJgmx25vylurpCYel7sSQM8MQy0knqyTk2LWa1Xoae9YabO9i1zagZl2B8DEGrZM0EjbtG0ZGDEAbWQx2i0OjAQGsa6gbn+3R3E2Qygm0UB8-lYDj3JvWBBBm6ZQP13tfGN+Bn0UqqsDwIc5mhT9I0fGK2JIxB4ShCIHYckfAqCwBIPkFpxQygEnSAAGUZC0Oo6RyRlGVzUYkVQCTTSOYkFIpTvBy6SIrTwAA3PgkxaA5EcBQd4RvkjHNXMSbScuvwuGVwATWV4r1ozuhelnhMcpIABbeEq4qgnKjQ7p3VgXdJFD5QWAGIQj4HN1QVA+gCS54oAAITXJaCnVBlf2HhIMciwfjc+Ez9ngv+fuSIybEnoX9fFbm7dxQZv2JW-dCeE8EAQA) with the edge from 'Source' to 'Target'. Setting the config value to a single side like 'NORTH' works and I'm wondering why 'SIDES_xxx' is not picked up? Any insights on this, or even a minimalistic example of the feature?

Thanks!

**Comment by le-cds** [comment]
Ports can only be assigned to a particular side if the side is to be fixed. One exception are northern / southern ports, which can be configured to be assigned either to the northern or to the southern side, as the algorithm sees fit. Other port side combinations are not supported.

The purpose of the constants you mention is convenience for layout algorithms or other code that has to deal with port sides. The fact that they cannot be assigned to the port side option is evident since there's a type problem there: the port side option expects a value of type `PortSide`, while those constants are of type `Set<PortSide>`.

**Comment by shean42** [comment]
Great, thanks for clarifying! I was already wondering about the different between e.g. 'NORTH' and 'SIDES_NORTH' :-)
