### ISSUE TITLE
Remove UI dependency of layout test framework

### ISSUE THREAD

**Issue by le-cds** [eclipse/elk#527]
The layout test framework's main plug-in, `org.eclipse.elk.alg.test`, has a dependency on `org.eclipse.elk.debug.grandom.ui`, since that contains the class which actually produces random graphs: `GRandomGraphMaker`. That class, in turn, uses `GeneratorOptionsUtil`, which has UI dependencies. That, finally, causes Tycho Surefire to fail to start its runtime since it cannot resolve the UI dependencies.

**Comment by le-cds** [comment]
I tried to fix this by refactoring the code in 8b974a0957, but to no avail. Tycho Surefire exits with exit code 13, and I do not understand why that is.

**Comment by le-cds** [comment]
Now it works, it was just a matter of compiling with Java 1.8 instead of Java 10.

**Comment by uruuru** [comment]
Do you know what the difference is? It feels like a rather dumb reason to restrict oneself to 1.8.

**Comment by le-cds** [comment]
I totally agree, and it made me furious, but I could not for the life of me figure out what the problem is. As far as I could see, everything the test harness depends on was in the target platform. The usual suspect might be Java modules, which were introduced in Java 9, but that's just a wild guess.
