### ISSUE TITLE
Self-loop Edge on Port performs the Edge routing inside the Node

### ISSUE THREAD

**Issue by BjBe82** [eclipse/elk#532]
If a edge is referencing the same port it is routed inside the Node. Not sure if this is intended if "elk.insideSelfLoops.activate" and "elk.insideSelfLoops.yo" is false.

![selfLoopInsideNode](https://user-images.githubusercontent.com/61700870/77909420-9a208880-728d-11ea-9a2c-09b1fb593965.png)

Json
```
{
  "id": "graph",
  "layoutOptions": {
    "elk.algorithm": "layered",
    "elk.direction": "RIGHT",
    "elk.edgeRouting": "POLYLINE",
    "elk.layered.mergeEdges": "false",
    "elk.nodeSize.constraints": "[PORTS, NODE_LABELS]",
    "elk.nodeLabels.placement": "[H_CENTER, V_TOP, INSIDE]",
    "elk.portLabels.placement": "OUTSIDE"
  },
  "children": [
    {
      "id": "7f963681-6578-c0ce-2c8e-7e3e41efa0cd_block",
      "children": [],
      "edges": [],
      "labels": [{ "id": "7f963681-6578-c0ce-2c8e-7e3e41efa0cd_block_label", "text": "A", "x": 5, "y": 5, "width": 114.203125, "height": 16 }],
      "ports": [
        {
          "id": "59af73cb-119a-c65e-6390-ba56cbfd0d53",
          "labels": [{ "id": "853b4ae3-6b3e-771f-7412-e2ed36753744", "text": "aa:AA", "x": -5.734375, "y": 1, "width": 22.46875, "height": 9 }],
          "width": 11,
          "height": 11
        }
      ],
      "x": 12,
      "y": 22,
      "width": 124.203125,
      "height": 49
    },
    {
      "id": "eb4d1e26-b35a-9736-1a1b-5e2fae38b687_block",
      "children": [],
      "edges": [],
      "labels": [{ "id": "eb4d1e26-b35a-9736-1a1b-5e2fae38b687_block_label", "text": "B", "x": 5, "y": 5, "width": 114.203125, "height": 16 }],
      "ports": [
        {
          "id": "000a7ee5-e679-6b93-9ec7-f2439b6b0454",
          "labels": [{ "id": "a464e361-6927-0a3f-289d-6f0a45d3f90d", "text": "bb:BB", "x": -5.734375, "y": 1, "width": 22.46875, "height": 9 }],
          "width": 11,
          "height": 11
        },
        {
          "id": "759f91c4-f7bd-470b-1539-22b24774cf70",
          "labels": [{ "id": "0a7ee8df-e925-86ff-9610-195d43039fd1", "text": "loop:Loop", "x": -12.3515625, "y": 1, "width": 35.703125, "height": 9 }],
          "width": 11,
          "height": 11
        }
      ],
      "x": 156.203125,
      "y": 22,
      "width": 124.203125,
      "height": 49
    }
  ],
  "edges": [
    {
      "id": "00d672ab-6bf3-29b0-b3d6-b00e0e50d2bb_edge",
      "source": "7f963681-6578-c0ce-2c8e-7e3e41efa0cd_block",
      "sourcePort": "59af73cb-119a-c65e-6390-ba56cbfd0d53",
      "target": "eb4d1e26-b35a-9736-1a1b-5e2fae38b687_block",
      "targetPort": "000a7ee5-e679-6b93-9ec7-f2439b6b0454"
    },
    {
      "id": "02396688-b069-7922-376e-4161e878d73c_edge",
      "source": "eb4d1e26-b35a-9736-1a1b-5e2fae38b687_block",
      "sourcePort": "759f91c4-f7bd-470b-1539-22b24774cf70",
      "target": "eb4d1e26-b35a-9736-1a1b-5e2fae38b687_block",
      "targetPort": "759f91c4-f7bd-470b-1539-22b24774cf70"
    }
  ]
}
```

**Comment by le-cds** [comment]
We currently do not support such edges in ELK Layered. I'll classify this as an enhancement, but I have a hunch that implementing this would not be that easy. So please don't hold your breath. ;)

**Comment by BjBe82** [comment]
Thanks for the quick answer ;) . So maybe we will think about some post processing for such edges or live with it for the moment.

**Comment by uruuru** [comment]
@le-cds I'd suggest to report the issue back to the user (i.e. an edge with the same source and target port) as an invalid graph configuration exception, or the like.

**Comment by le-cds** [comment]
@uruuru Usually, I would agree, but given that @BjBe82 may choose to ignore the issue for the time being, I wouldn't want to force him to exclude the edge from layout and then post-process it. However, if you, @BjBe82, choose to post-process the edge, I'd follow the suggestion by @uruuru.

**Comment by BjBe82** [comment]
The picture and json above is only an example … the graph is based on some engineering data which should be visualized i.e. for a review. I was not questioning the engineering data at this point and only observed the edge which could be routed outside of the node. 

Since I am not an ELK expert, I only want to make sure that I was not doing something wrong (which could be easily solved by some options).

I need to check with the enduser how he wants to deal with it. :)

**Comment by uruuru** [comment]
@le-cds I was aiming in the direction of notifying the user that the graph as provided is actually not supported by the layout algorithm. Another option would be to discard such edges during layout in order to at least not produce _weird_ results. 

There are several ways to handle this and so far we've usually not really bothered telling the user if something fails silently :). 

The best way (imho) would be to discard the edges during layout but notify the user with a warning. However, there's no means to do so in our current architecture.

**Comment by le-cds** [comment]
> I need to check with the enduser how he wants to deal with it. :)

We'll be here waiting for the reply. 😉 

> I was aiming in the direction of notifying the user that the graph as provided is actually not supported by the layout algorithm.

Ah, I see. Yeah, warnings of some sort sound sensible. We'd need a proper strategy of when to throw exceptions and when to just trigger warnings, though.

**Comment by soerendomroes** [comment]
I guess currently, we would rather from an UnsupportedGraphException and report the problem.

**Comment by soerendomroes** [comment]
With ELK 0.6.0 this was fixed to look like [this](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=OYJwhgDgFgBAeqSUBQYA2wD2ICWAXKAWwC4Y0wBPAUxCoBNkq0BrAOjp1oGM8dMA7UgCUAkgHEAEgBVGdYFSGYArr37BSABQDyAGQCaOkQDkAoskI15JuVQDOpAGbpbVZP0x0qAZRwAvKqxcArZ44Dj8ePYwAEQA2tpCUl4ANDBGWgAiJgD6OgCCAEImOl4AutFuHlQ6YABGTLasEORcVBYRpHES2QDCJkZSJkKpAGrZUloaqcZeIlnlyBDYeDX1aI3NYK3teJ2xWgCqSXMmC+6eMLUA7A4AnABsAMz3ABwAjPcArFcvXAAMrQATFwXlQrlRHlQACxvKhOAF0bK1NCYLjMGAAb2QAEhyBRlHgYLEcdilrZ8HxBDA3oDUoDASTyf5SDSoaxAX9HjTPqkobccaUceQ1mQbg9nu8vj9-kCQWCIdDYfCuIjkajmNlhUxOnlopiSXiCUSSaTMOTeAJSDyYJ8TUyqCy3myOVzAdaPiTBdiAL44pYgQkQT63MAOK6PLi1N5vENcL5UJ63P61MCfe6Rhx0P50T6PfXY3GUI2xGD2x2paMwL2FkVoF652pQsAQ+61SFXK5vMMwwFUXt0Z5XXNXKFQzpgMDEPK6-MFw0qY0FgtkimWmAAWk+rHDUMeQ4rJuxZZg9NYUNe+5g-KX1d9PuQvvOVEuVEbdFhgNbj0+YFu4fubxgG8tSfH2TgQi8tQXkiKJovm86EsSy5mquVJvGm7KctydIMgWx6sphrrWnyApCnUTBkK+ULvn2X4-n+zyAcBoGAuBjyQdBapopq5FoJ0BR6lic5FguSHIealJWqktpLvhTqEdh1L3J6OJ3v6gZ-JpYDglQoH3FcDy1Lcjy3FQXA3ICu63FBtR-FCnxQrOCFEqWfgOtSbwVm8VYGrxZBgOeUIth8tyAlcfxgI8DiAi8tx0PcDgRfZA53NmnS1LUxAFAJs6FviomHiuFpUpu26PLul5vIex6nueLyXteBa3qpfrLDAEBDrcdxvFwUJhrUdBQuFUa5qFgK1JZHZQlwYZ-E5ImIa5zIeV5PnCbWEU6S8dAOFQoWfC8CV3ABfwxp8g2PJyXXvp0KKYBAxA6Jg92CSazlieJqGkOuNKsN+6H3G6B5LkebmkN+25YUDV4ms196+vQ8gwFQmnxVcgJ1K2DiPIC1nJo88W2X8KO6dm421NkiPudcx0Sh83y-ACfZyuCkIwnCYAIjB6pNMGobhpG0axvGibJqm6a1Jm2a5huAB8L5vh+dG-v+TEgWBzbsVB9Xc2iTSaZtVC6QmBmtsZpnmdFVk2XZDmyEjKOAiZ9yvJBfz3H+Y17vcioAVQ9XbQLlM2KQ9SK7Rbb0arQHq6xmscTrXFsB1wbdb1-WDcN6EmfSE1DSOM3hXLCvUUrkcq4xMcsWxCdXLryedWnfVXANQ3JtnY151Nhd-MgQA).

![Screenshot from 2022-11-15 16-56-09](https://user-images.githubusercontent.com/6419799/201965758-0b5feef2-162c-4893-b0d6-04a93e77686a.png)

@BjBe82 Would you rather have as report the problem or is this self-loop sufficient?

**Comment by BjBe82** [comment]
From my point of view, the self-loop is sufficient. I think the layout algorithm should only report problems if it has trouble to layout something which is not supported. 

Anything else is more or less on the semantic level and depends on the underlying data and will be covered (at least in our case) by consistency checks. Where the result is then shown as decorators on the edge, for example.
