### ISSUE TITLE
NPE in HierarchicalPortPositionProcessor.fixCoordinates with inside self loops and fixed ports

### ISSUE THREAD

**Issue by philip-alldredge** [eclipse/elk#548]
When attempting to layout a graph which uses inside self loops, a NPE is generated. Attached is a zip file with a minimal graph and stack trace. Tested with ELK 0.6.1.  Reproduced within the `Layout Graph` view.

[npe_details.zip](https://github.com/eclipse/elk/files/4439369/npe_details.zip)

**Comment by philip-alldredge** [comment]
It appears to be caused by the `PORT_ANCHOR` property being null. I'm unsure of how this node related to the port. The ports in question have a PORT_ANCHOR property set although that was removed from the minimal example.

**Comment by le-cds** [comment]
I can't reproduce this issue just yet because I'm running into another one first. The other issue is tracked in #562 and blocks this one.
