### ISSUE TITLE
elkt: Multiple unknown property keys yield an error

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#557]
From kieler/elkgraph-web#10:
> When both unknown properties are present, there is another problem: both are resolved to null, which leads to a collision of map keys and thus an EMF error message. We should create dynamic properties to avoid that.

This change is required to allow #556

**Comment by le-cds** [comment]
Another possibility might be to throw them away instead of adding them to the list in the first place.

**Comment by uruuru** [comment]
Please consider all de-/serializers to be consistent.

**Comment by uruuru** [comment]
Regarding my previous comment (de/-serialization of other formats): aligning this across all formats would be some effort, I presume.

Some examples:
* elkt -> json: it's possible to preserve the unknown key:value pairs by setting `omitUnknownLayoutOptions: false` in the `JsonExporter`
* json -> elkt: the `JsonImporter` currently drops all properties that are unknown to the `LayoutMetaDataService`
https://github.com/eclipse/elk/blob/9a0f2c234ff380fcee803db55c4efa88dd662d36/plugins/org.eclipse.elk.graph.json/src/org/eclipse/elk/graph/json/JsonImporter.xtend#L422-L423
* elkt -> elkg: also drops unknown properties
https://github.com/eclipse/elk/blob/9a0f2c234ff380fcee803db55c4efa88dd662d36/plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/util/persistence/ElkGraphXMISave.java#L51-L52


Hence, I propose to leave the current state-of-the-art for now and to adjust the corresponding format as soon as the need comes up.
