### ISSUE TITLE
JsonExporter exports empty junction points as part of layout options

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#559]
Since junction points are stored as a layout option and 
 * the option has `new KVectorChain()` as default value
 * the option is checked via `getProperty()` _prior_ to exporting the layout options themselves (and thus is constructed silently)

every edge of the produced json contains the following line: 
```
"layoutOptions":{"junctionPoints":"()"}}
```

**Comment by le-cds** [comment]
That relates somewhat to good old #10: Now that we have `IPropertyHolder.hasProperty(...)`, we could use that.
