### ISSUE TITLE
Spacing labelPort unexpected behavior

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#575]
Consider 
```
spacing.labelPort: 20
node n2 {
	port p1
}
``` 
which yields
![image](https://user-images.githubusercontent.com/7552459/80009005-c1ebc080-84c8-11ea-85ad-16e175e8121c.png)
 
It looks like the `labelPort` spacing is applied in both x and y. Although (at least I) would expect it to be applied only in x for west ports.

If `portLabels.nextToPortIfPossible: true` the behavior is as I'd expect.

**Comment by uruuru** [comment]
@le-cds, for some reason this ticket didn't occur during our discussion.

**Comment by le-cds** [comment]
Which discussion?

**Comment by uruuru** [comment]
Lets call it "discordussion".

**Comment by le-cds** [comment]
Hm... I guess one could argue that x and y need to be dealt with and be defined separately... I think we should not try to tackle this for 0.7.0. What do you think, @uruuru?

**Comment by uruuru** [comment]
> I guess one could argue that x and y need to be dealt with and be defined separately... 

Or one chooses single dimension depending on the port side. For instance, for `WEST` ports the `spacing.labelPort` would move the label further to the left and for `NORTH` further to the top. For me that feels like the most intuitive behavior. 

If more intricate label placement is desired, the user can still resort to fixed (self-computed) positions.
