### ISSUE TITLE
Some layout options declared programmatic although they are not

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#578]
From my understanding a `programmatic` layout option is one that is set (and only supposed to be set) internally be the algorithm or some preprocessing step. However there are a number of layout options marked as `programmatic` that are valid candidates to be configured by a user. 

```
programmatic option anchor: KVector {
     
programmatic option index: int {
    
programmatic option side: PortSide {
    
programmatic option borderOffset: double {

programmatic option commentBox: boolean {

programmatic option margins: ElkMargin {

programmatic option noLayout: boolean {
```

I suggest to turn them into regular layout options. 

By the way, did we document the meaning of _programmatic_ somewhere?

**Comment by le-cds** [comment]
I think what you mean are `output` options. `programmatic` options are documented on our website [as follows](https://www.eclipse.org/elk/documentation/algorithmdevelopers/metadatalanguage.html):

> Programmatic layout options are not shown in the Layout view at all, but only set through programmatic layout configuration. The reason is often that they are either highly specialized, or that values of their data type cannot be properly entered in the layout view.

That hardly applies to any of those options, though, so yes, I think they could all be turned into regular options.

**Comment by uruuru** [comment]
Thanks for pointing out the documentation. I'll change it then :).
