### ISSUE TITLE
Default value labelLabel spacing: zero

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#586]
The core melk defines the default value of `labelLabel` spacing as `0`. I feel it should be larger than zero. Also, in current layouts there's some space between the labels. Is a different option used there, @le-cds?

https://github.com/eclipse/elk/blob/a91730ded81b378967f9a84c051946bc2d60a574/plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/Core.melk#L269-L273

Layered does not re-define the default.

**Comment by le-cds** [comment]
I just tried this with a simple graph:

```
node n1 {
	label "Label 1"
	label "Label 2"
 	
	port p {
		label "Port 1"
		label "Port 2"
	}
}
 
node n2
 
edge n1 -> n2 {
	label "Edge label 1"
	label "Edge label 2"
}
```

In KLighD, I get this result, which looks just fine to me:

![labels_klighd](https://user-images.githubusercontent.com/7465584/81101270-2cabeb80-8f0e-11ea-8a42-53e5ad0c9adc.png)

The layout graph looks like this, and indeed there is no space left between the labels:

![labels_elk](https://user-images.githubusercontent.com/7465584/81101307-3b929e00-8f0e-11ea-8702-fc3382daff64.png)

How much of a problem that is probably depends on the graphics framework and how well it estimates the size of its labels. For example, in the [ELK Live editor](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=AQOw9gJgpqCMwG8BQxWklAMgQwEZQBsBnAOgAcDsBjKAWyhABcAuYAIgAkB9AYQFEAcgBU+AJWAA1XoJHiAkgIDKcgCJ82KNOGiKAlgC8oJKmBBFGAJ2y6mRVgIDyarpgCCAIT6ZFSFAEhKfAJ2HCDgWA1gALxCEJjggCZIv38yMAtGYDJEf2iwtgAFdMyI3MDYwuLgJP8AXxR64BRtGBAElBQoCABzVvgAWgA+UAScqPLgtj4emAnw5LmpmeA5muBGoA), the labels are indeed spaced too closely.

Whatever default we choose, it may not be right depending on the graphics framework.

**Comment by uruuru** [comment]
Ah I didn't realize that the present spacing is a result of the font estimation. 

Note that for the live editor no label size is computed automatically (afair), you would have to add it yourself. 

I agree regarding your last point - let's close this as invalid?

**Comment by le-cds** [comment]
A finalized discussion it is. _Invalid_ seems a bit harsh... 😄
