### ISSUE TITLE
Nodes of different partitions end up in the same layer

### ISSUE THREAD

**Issue by shean42** [eclipse/elk#591]
Partitions are defined in the [documentation](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-partitioning-partition.html) as "...a pair of nodes with different partition indices is placed such that the node with lower index is placed to the left of the other node (with left-to-right layout direction)."

While this is straight forward I'm wondering about the node order in this small [example](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=A4QwTgLgltD2B2V4HMB0IDG0BuIIFMAuAAgjAFd8AoK+WAE32PgEZiBvY0SGKBEtgBsQAI3yDiAIlaTiAX1oMm8AEwcu4aHHgk1wsROkrZCuo2YBmddy18dxAAzF94qfAsma+esmVsAtAB8zCpU3r7MAcHuQA). As it is, the node order is as expected and well reflects the partition numbers. However, if we change the partition number of n3 to '3' then n2 appears in the same layer even though n2 has a lower partition number and should be to the left according to the above definition. Interestingly the layout now is the same as with "partitioning.activate: false".

Not sure if I misunderstand partitions as a concept, so every insight is appreciated! :-)

**Comment by le-cds** [comment]
Nope, that's definitely a bug. Nodes from different partitions should never share a layer. I'll look into it, thanks for reporting. 🙂

**Comment by shean42** [comment]
Thanks for clarifying! :-)

A related(?) observation is that partition numbers need to be strictly consecutive to be picked up. If we change the partition of n1 in this [example](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=A4QwTgLgltD2B2V4HMB0IDG0BuIIFMAuAAgjAFd8AoeWAE32PgEZiBvY0SGKBEgJmIAbEACN8Q4gCIWU4gF8a9RvEEcu0OPBKsR4yTP5zF+OshWsAtAD4m-IA) e.g. to '3' the values don't seem to be evaluated anymore.

**Comment by le-cds** [comment]
The `3` is clearly a common thread through both problems. Perhaps we should simply forbid that particular number... 😜

But seriously, I'd expect non-consecutive numbering schemes to work as well. I'll have that in mind while wading through the code. ;)

**Comment by le-cds** [comment]
I created #592 to track the non-consecutive issue specifically.

**Comment by shean42** [comment]
Thanks for the timely fixes! As to be expected, 3 files were changed!!! :-)))

 viele Grüße

**Comment by le-cds** [comment]
🤣

**Comment by uruuru** [comment]
@le-cds could you briefly elaborate what the problem was?

**Comment by le-cds** [comment]
@uruuru Layout partitions are implemented simply by adding loads of edges that influence the layering. After layering, they are removed again. However, that removal happened too soon. Once the edges were removed, there was nothing to stop the node promotion and layer constraints processors from moving nodes around, which destroyed the partitions.

The fix was to remove the dummy edges only after those processors had run.
