### ISSUE TITLE
Configurable spacing between nodes and comments

### ISSUE THREAD

**Issue by le-cds** [eclipse/elk#594]
The space between a comment and its node is the standard node-node spacing, as seen here:

![comments](https://user-images.githubusercontent.com/7465584/81285144-5aed1080-905f-11ea-82b9-e3cdbc97293c.png)

We should introduce a layout option instead to make that configurable.

**Comment by le-cds** [comment]
We could also introduce an option to configure the spacing between two comment boxes.

**Comment by uruuru** [comment]
In line with our current options: 
```
spacing.commentNode
spacing.commentComment
```

To make things even more complicated and to differentiate "other" nodes and the comment's node:
```
spacing:commentOwnNode
```

**Comment by le-cds** [comment]
Comments are hidden from the algorithm and are thus not even visible to node placement. The spacings only affect the `CommentNodeMarginCalculator`. That is unless we in fact want to introduce another spacing between nodes and comments of other nodes. Then we'd have to introduce more or less complicated checks during node placement.

Personally, I think I would be just fine with the standard node-node spacing between comments and other nodes.

**Comment by uruuru** [comment]
Did you check if the spacing has to be added to layered's `Spacings` class? The precalculated node type spacings?

**Comment by le-cds** [comment]
That's a good point. I'll reopen the issue and implement that.
