### ISSUE TITLE
Problematic check if ports lists are sorted for FREE ports with set indices

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#599]
Issue occurred during hierarchical tests. 

The issue seems to be that `portConstraints` are set to `FREE` but the ports have a `port.index` set (to which the port list sorting comparator seems to be sensitive even though the ports should have been fixed after laying out the hierarchical node). Consider the following small example. When the `index` lines are removed, the test succeeds. 

![image](https://user-images.githubusercontent.com/7552459/81482744-917e8300-9239-11ea-9afc-f1bb25d211f2.png)

```
node N9 {
    nodeLabels.placement: "[H_LEFT, V_TOP, OUTSIDE]"
    portConstraints: FREE
    label L9: "CreateNode" {
        layout [ size: 69, 15 ]
    }
    port P17 {
        layout [ size: 8, 8 ]
        index: 0
        side: WEST
    }
    port P18 {
        layout [ size: 8, 8 ]
        index: 1
        side: EAST
    }
    port P19 {
        layout [ size: 8, 8 ]
        index: -2
        side: SOUTH
    }
node child
}
node N17 {
    layout [ size: 39, 46 ]
    nodeLabels.placement: "[H_LEFT, V_TOP, OUTSIDE]"
    portConstraints: FIXED_ORDER
    label L17: "BooleanSwitch" {
        layout [ size: 87, 15 ]
    }
    port P30 {
        layout [
            position: 39, 28
            size: 8, 8
        ]
        index: 3
        side: EAST
    }
}
edge E6: N17.P30 -> N9.P17
```

**Comment by le-cds** [comment]
Here's a smaller graph that reproduces the issue:

```
node N1 {
	port P1
}

node N2 {
	port P2_1 { index: 1 }
	port P2_2 { index: 2 }
}

edge N1.P1 -> N2.P2_1 {
	label "L" { edgeLabels.placement: TAIL }
}
```

The edge's end label causes the `EndLabelPreprocessor` to run, which fails an assertion which checks whether the port list is sorted properly. Indeed, it takes the port index into account even if that index is not of any importance.
