### ISSUE TITLE
CoreOptions not registered early enough

### ISSUE THREAD

**Issue by le-cds** [eclipse/elk#601]
To quote from #402:

> There seems to be an issue with the order in which the providers are loaded. I came across the following: In a plain Java environment the `CoreOptions` end up being loaded last. As a consequence all options registered in other layout algorithm providers via `supports` do not end up in the `knownOptions` map of the corresponding `LayoutAlgorithmData`.
> 
> I'm not sure if the bundle-based loading in `ElkServicePlugin` happens to load `CoreOptions` early enough by chance or if dependencies are resolved there.
> 
> A pragmatic solution would be to simply make sure `CoreOptions` are loaded first. The proper solution would be to leverage some dependency graph to derive the order.

**Comment by le-cds** [comment]
> The proper solution would be to leverage some dependency graph to derive the order.

I think that would be overkill. We currently don't have any algorithms that support options declared by other algorithms.

**Comment by le-cds** [comment]
@uruuru Could you confirm that my changes from #602 fix the issue for you (I should have asked you to review the PR before merging; didn't think properly before pulling the lever ;) )?

**Comment by uruuru** [comment]
LGTM.
