### ISSUE TITLE
Rename northOrSouthPort layout option

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#605]
Lets change it to something that's user-friendly and independent of the layout direction. The option is active when port constraints are either `FREE` or `FIXED_SIDE`. 

I feel it's hard to come up with an intuitive name though as we don't have defined terms for the different ports. Maybe one could call them _flow_ and _non-flow_ ports. The first one being those ports that are in line with the flow of the graph, i.e. the layout direction. 

Maybe: 
`option allowNonFlowPortsToSwitchSides`

Furthermore, the documentation should include the fact the the backing algorithms only aims at reducing edge crossings, not edge length. 

Opinions?

**Comment by le-cds** [comment]
I tried to find even better names, but failed. But I can see how the current names cause confusion for people who don't know how Layered operates internally, so... we can rename the option. We just need to be sure to adapt all of our files in the models repository.

**Comment by uruuru** [comment]
I'll add the old name as legacy option. But also adjust the models repo (if there are any in elk). I guess in the KIELER scg repo there may be more.

**Comment by le-cds** [comment]
> I guess in the KIELER scg repo there may be more.

I'll tell them that the name will change with the next release.

**Comment by shean42** [comment]
The original name initially caused quite some confusion for me so renaming it is great. Based on the above discussion here are a few more ideas:

noFlow[Direction]Port[Side]Flexibility

**Comment by uruuru** [comment]
Thanks for the input. When including `flexibility` I'd tend to want to use an enumeration as value. In this case a mere bool seems to be enough to me, though.
