### ISSUE TITLE
Have node order match input order in crossing free graphs

### ISSUE THREAD

**Issue by le-cds** [eclipse/elk#608]
Consider the following graph:

![simpleton](https://user-images.githubusercontent.com/7465584/81815322-1e6f5800-952a-11ea-83ae-fc328f216c53.png)

The nodes are declared in the graph file by ascending number: `n1, n2, n3`. If `n2` and `n3` appear in that order inside their layer, the graph is without crossings. The same is true if they are reversed, but then the user might get confused as to why their order was changed.

And indeed, unless the random seed is fixed, the node order switches unnecessarily in subsequent layout runs. This shouldn't happen.

This issue can be arbitrarily complex, but I think for now we should simply change one simple thing: while currently the crossing minimizer starts with a random configuration, I think we should start with the input configuration. If no random configurations after that yield fewer crossings, we simply take the input configuration.

**Comment by uruuru** [comment]
> I think we should start with the input configuration
I'd be fine with that. However, do all parts before that point preserve the input order? I could imagine that even (some of) the layering strategies intermix the nodes.

**Comment by le-cds** [comment]
> I could imagine that even (some of) the layering strategies intermix the nodes.

That's a good point. As I said, solving the issue in general is a lot harder than one might think at first. Perhaps we'll have to store the original order during import.

**Comment by soerendomroes** [comment]
![Screenshot from 2020-05-15 12-13-32](https://user-images.githubusercontent.com/6419799/82039782-cc534180-96a5-11ea-96e8-e515be299f47.png)
Even if we order the nodes accordingly, we also have to consider dummy nodes.
We could either consider the ordering of the outgoing edges or the order of the nodes itself, because these might be conflicting.

**Comment by le-cds** [comment]
> We could either consider the ordering of the outgoing edges or the order of the nodes itself, because these might be conflicting.

What do you mean, exactly?

**Comment by soerendomroes** [comment]
```
node n1
node n2
node n3

edge n1 -> n3
edge n1 -> n2
```
The node order would place n2 before n3, the edge order would place n2 after n3.

**Comment by uruuru** [comment]
Tbh I think that are different use cases that require completely different solutions. As soon as edges are involved it gets more complicated than simply setting the initial configuration for crossing minimization.
