### ISSUE TITLE
Edge priorities

### ISSUE THREAD

**Issue by le-cds** [eclipse/elk#61]
We allow to set a `PRIORITY` property for an edge. This is (depending on the configuration) evaluated during cycle breaking, layering, and node placement. However, direction, shortness, and straightness are different use cases and users may have different preferences. 

Any suggestions for more properties and their names :)?

_This used to be KIELER ticket [KIPRA-1751](https://rtsys.informatik.uni-kiel.de/jira/browse/KIPRA-1751)_

**Comment by uruuru** [comment]
We could add a `group` to the layered melk, where we address the three aforementioned use cases. I can imagine the case that crossings with a certain edge should be avoided but we don't support that at the moment.

**Comment by le-cds** [comment]
Yup, we could do that. I'm not sure if the general global priority option really makes sense. We could check if it would be worthwhile to remove it while we're at it.

**Comment by uruuru** [comment]
I wouldn't remove it. It's used in a couple of places, e.g. the box and force layouter. Its documentation states that the particular meaning depends on the algorithm.
