### ISSUE TITLE
Consistent algorithm names

### ISSUE THREAD

**Issue by le-cds** [eclipse/elk#611]
As our list of layout algorithms reveals, not all of our very own algorithms have the "ELK" prefix in their name:

![Screenshot_2020-05-15 Algorithms (ELK)](https://user-images.githubusercontent.com/7465584/82057425-9ae96e80-96c3-11ea-9ed9-36b275b229b5.png)

That should be fixed.

**Comment by uruuru** [comment]
Would you want to prefix the other ones as well? E.g. "Graphviz Circo"?

**Comment by le-cds** [comment]
That's a good point. I think I do, yes. I'll update my pull request.
