### ISSUE TITLE
Add visitor to configure recursively set properties and positions for multiple layout runs

### ISSUE THREAD

**Issue by soerendomroes** [eclipse/elk#614]
I suggest to allow generic `IGraphElementVisitor`s instead of only `LayoutConfigurator`s to configure multiple layout runs. 
This would allow us to not only set properties via the `LayoutConfigurator`, but also add new Visitors that are able to set positions of nodes based on previous layout runs, for example for the layered interactive strategies.

**Comment by uruuru** [comment]
Why is this not possible with layout configurators? Note that there's a `clearLayout` flag which preserves the node positions of a previous layout run. You can also have a `de.cau.cs.kieler.config.*` plugins. They contribute a textual dsl to configure layout runs. In particular, you can specify subsequent layout runs which base on the previous result.

**Comment by soerendomroes** [comment]
Does this allow me to set positions for nodes? How I understand it, this is only for properties. Please correct me if I am wrong.

**Comment by uruuru** [comment]
The layout configurator can _preserve_ node positions of a previous layout run. You cannot _set_ node positions using a layout configurator.

**Comment by soerendomroes** [comment]
Ok, but a IGraphElementVisitor could do this. This is why I need/want one.

For example the interactive strategies for the layered algorithms use positions from a previous layout run. But additionally to that I can set position and layer constraints on the nodes i.e. the `layerChoiceConstraint`. For this I have to change the actual position of nodes from the previous layout run.

**Comment by uruuru** [comment]
I'm not strictly against widening the API, however, I'd like to hear some other opinions. 

By the way: in your use case, what speaks against extending the `LayoutConfigurator` class with a method that allows to configure the position of a node as well? You'd benefit from what the class already offers.

**Comment by soerendomroes** [comment]
I only ever visit the root element of a graph.

I cannot just configure a position without taking the positions of other nodes in the same hierarchy into account.
I think this is rather complex using configure and filter.
With my custom visitor I can recursively go through the graph and set positions and other properties depending on the layout algorithm in that hierarchy level. If I could set positions for graph element in the `LayoutConfigurator`, I would most likely end up doing the exact same thing.

I never want to clear the previous layout.

What features of the `LayoutConfiguration` would be helpful for me? Currently I only see the `overrideWith` method but I am not sure whether this is really applicable.

The `LayoutConfigurator` would be sufficient if the would be layout strategies that would understand the interactive constraints directly. This way I could omit the pseudo position calculation which would make everything way simpler since layers are not direction dependent. Maybe this approach would be the best, but I need some time to implement this.

**Comment by le-cds** [comment]
I actually think extending the API here is a good idea. The `LayoutConfigurator` is pre-configured to set properties on certain graph elements. What @soerendomroes needs is to dynamically change the graph's configuration (including positions) after a first layout run to prepare it for the second layout run.

Changing the API to `IGraphElementVisitor` doesn't break anything either, so I'm all for it.
