### ISSUE TITLE
Ensure margins are strictly >= 0. 

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#616]
From a PR, comments from me and cds (in that order): 

> The issue is due to double imprecision and the >= comparison used in the test. Using a fuzzy compare with an epsilon in the test would solve the issue. @le-cds shall we do that or do you think the margins should strictly have no negative sign?
>> I find negative margins really quite irritating. I think my preferred solution would be to ensure they are at least 0 wherever they are set.

> Would you suggest to add a corresponding check and modification to the end of every processor that touches margins?
>> I'm dreading having to wade through that code and making it more complex, but yes, if I'm serious about my preferred solution, then this is what would have to happen. :/

**Comment by uruuru** [comment]
As mentioned in #616 only a single processor has been adjusted, which has been responsible for the negative margins. We'll leave it at that for the moment.

**Comment by le-cds** [comment]
Just to add why I thought this was enough for the moment: I believe the other processors only enlarge the margins, and only do so if there is a reason. My feeling is that this is why they didn't trigger the test failures. We can always revisit this problem if they make problems as well, but I think we're good now.
