### ISSUE TITLE
Should ELK transition to Java 11?

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#622]
To start a discussion and collect opinions (if there are any) and arguments: should we move to Java 11? 

### Prerequisites
* Do all Eclipse-related parts support Java 11? E.g. tycho? ❓ 
* elkjs should be fine with it as with the latest GWT release (2.9.0, May 2019) Java 11 support has been added ✔️ 
* AFAICT it's not possible to compile Java 8 anymore, thus we'd drop support for running our code on Java 8 jres. ❓ 

### Advantages (8 to 11)
* `var`

**Comment by soerendomroes** [comment]
At least from the Kiel University point of view, we could drop Java 8 support and also migrate to xtext 2.25 (see #702).
#785 might also be related.
I suggest to do this in elk 0.9.0, which hopefully will be released quicker than 0.8.0.
