### ISSUE TITLE
LayerConstraintProcessor moves nodes w/o constraints

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#623]
Consider the following graph 
```
    algorithm: layered
    cycleBreaking.strategy: INTERACTIVE
    layering.strategy: INTERACTIVE 
    
    node n1 { layout [ position: 100, 0 ] label "1" }
    node n2 { layout [ position: 200, 0 ] label "2" }
    node n3 { layout [ position: 00, 0 ] label "3" }
    edge n1 -> n2
    edge n2 -> n3
```

Which looks like this after layering:  `[L_0[n_3], L_1[n_1], L_2[n_2]]`. 

After the `LayerConstraintProcessor` it looks like this: `[L_0[n_1, n_3], L_1[n_2]]`.

However, there's no reason for the processor to merge the first two layers. Note that this is not limited to the interactive layouter but also true for a certain configuration of the coffman graham. 

The issue is not present in `0.6.0` but in `0.6.1`. Further note that also partitions are broken in `0.6.1` if one were to assign partitions 1,2,3 to nodes n1, n2, and n3. 

@le-cds do you know off the top of you head if something changed between these versions?

Edit: 100687ec872909a9b670ba21349e247784769e54 seems to introduce it.

**Comment by le-cds** [comment]
Partitions have since been fixed. Some changes to the layering are expected, but this is completely unnecessary. The processor wouldn't even have to be run in the first place. But even if it did, it should not be allowed to make these changes in an interactive layout.

**Comment by uruuru** [comment]
I gave it some further thought and feel the correction of you commit is not correct. Or at least not in line with what that part of the code should do. 

The layer constraint processor has basically the following steps:
 1) move constrained nodes to corresponding layers, let's call them `f_sep, 1, 2, ... n, l_sep`. 
 2) possibly move all nodes from layer 1 to layer 2
 3) possibly move all nodes from layer n-1 to layer n

The corresponding comment of 2):
```
        // If there is a second first layer. To be allowed to move all first layer's nodes to the second
        // layer, we need to check 2 things:
        // - if any of the first layer's nodes has outgoing edges to the second layer
        //      (In this case, we obviously can't move the nodes.)
        // - if any of the first layer's nodes has no layer constraint set
        //      (In this case, we are not allowed to move the node by definition.)
```

The last `if` is what makes me think your change was against the original purpose. 

Anyhow, the only reason I can think of for steps 2) and 3) is that a case occurs in which all, and solely, `FIRST` (or `LAST`) nodes have been moved to layer `1`. Even though they could well be placed in `2` - saving layer `1` and making the drawing narrower. 
Am I missing something? 

If so, a (probably) easier to understand and maybe more correct implementation would be to first check if layer `1` only contains `FIRST` nodes, and then move them if possible.

**Comment by le-cds** [comment]
The issue is slightly more complex, I'm afraid. The fix was originally meant to fix #455, in which we have the following graph:

![graph](https://user-images.githubusercontent.com/7465584/85558924-846ef500-b629-11ea-8128-61ab953fe820.png)

Before the `LayerConstraintProcessor` runs, the graph internally looks like this:

![bug1](https://user-images.githubusercontent.com/7465584/85559825-5b9b2f80-b62a-11ea-8bdd-ac81ec81cfef.png)

Since the external port dummies have `FIRST_SEPARATE` and `LAST_SEPARATE` layer constraints set, the constraint processor then originally yielded this result, which is not satisfying:

![bug2](https://user-images.githubusercontent.com/7465584/85559924-753c7700-b62a-11ea-981b-3a5444cde5d0.png)

But I do agree that the fix doesn't work well either. I thus propose to do this:

1. Process the layer constraints as usual.
1. If layer assignment is not in any way interactive:
    1. Check if all nodes from the original first layer can be moved to the second layer, regardless of constraints. If so, do that.
    1. Do the same for the nodes in the original last layer, but only if the next-to-last layer is not empty (this could after all be the first layer that just got all its nodes moved, as would be the case in the example above).
1. Remove empty layers.

**Comment by le-cds** [comment]
This example would still look odd, even with my proposed solution (the _first_ and _last_ nodes have the respective layer constraint set on them):

![graph](https://user-images.githubusercontent.com/7465584/85561747-2b549080-b62c-11ea-827d-2281bde91b12.png)

I think my proposed solution can be salvaged, however. What we do not want is to move only some nodes that have a `FIRST` or `LAST` layer constraint. They can only be moved if _all_ nodes in their layer (even the ones without layer constraint) can be moved. Thus, in step 2.i, we could do this:

1. Move all nodes to the second layer that have no layer constraint set and that have no successor in the second layer. In the example, this would move `i1` to the second layer, where it belongs.
1. While going through the nodes of the first layer, check if there is any node that cannot be moved.
1. If there is none, all can be moved to the second layer, so do so.

**Comment by uruuru** [comment]
The reason why we can't remove those nodes prior to layering and simply put them in a proper layer after layering is that they may have edges with labels attached to them etc. right?

**Comment by le-cds** [comment]
Yep. 🙂

**Comment by le-cds** [comment]
In offline discussions, we concluded that the whole problem is solely due to `FIRST_SEPARATE` (and to a lesser extent perhaps also `LAST_SEPARATE`) nodes. The idea is to remove them in a preprocessing step prior to layer assignment, and re-insert them directly afterwards.
