### ISSUE TITLE
How to put the node on top or bottom of the graph?

### ISSUE THREAD

**Issue by wuleibobo** [eclipse/elk#627]
I want some of the node put on top/bottom/left/right of the graph.
I found the layerConstraint option can work for left/right position, and it works.
but I don't know how to put node on top and bottom of the graph. 
I found InLayerConstraint option sames like work for this, but it is an InternalProperties, and I can't set it in the input data.
So how to put the node on top or bottom of the graph?

**Comment by uruuru** [comment]
If you know which nodes end up in the same layer, you could try semi-interactive crossing minimization, see [this example](https://rtsys.informatik.uni-kiel.de/elklive/examples.html?e=user-hints%2Flayered%2FverticalOrder).

Apart from that I believe there's no public-facing configuration option to mark certain nodes to "always end up at the top/bottom of their layer".

**Comment by le-cds** [comment]
If you have any follow-up questions, feel free to reopen this issue. 🙂
