### ISSUE TITLE
Hierarchical layout broken when HierarchyAwareLayoutProcessor not active for root

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#628]
See kieler/elkjs#78 for details.

**Comment by uruuru** [comment]
I was able to reduce the problematic graph to the following. 

It's not broken anymore as soon as one further node or port is omitted.

![image](https://user-images.githubusercontent.com/7552459/85130152-ad137b00-b234-11ea-8d13-85861ce8b0c8.png)


```
hierarchyHandling: INCLUDE_CHILDREN
node ab {
    layout [ size: 10, 10 ]
    port in_o0 {
        layout [ size: 2, 2 ]
    }
    port in_o1 {
        layout [ size: 2, 2 ]
    }
    port in_o2 {
        layout [ size: 2, 2 ]
    }
    port in_o3 {
        layout [ size: 2, 2 ]
    }
    port in_o4 {
        layout [ size: 2, 2 ]
    }
    port in_o5 {
        layout [ size: 2, 2 ]
    }
    port in_o6 {
        layout [ size: 2, 2 ]
    }
    port in_o7 {
        layout [ size: 2, 2 ]
    }
    port in_o8 {
        layout [ size: 2, 2 ]
    }
    port in_o9 {
        layout [ size: 2, 2 ]
    }
    port in_o10 {
        layout [ size: 2, 2 ]
    }
    port in_o11 {
        layout [ size: 2, 2 ]
    }
    port in_o12 {
        layout [ size: 2, 2 ]
    }
    port in_o13 {
        layout [ size: 2, 2 ]
    }
    port in_o14 {
        layout [ size: 2, 2 ]
    }
    port in_o15 {
        layout [ size: 2, 2 ]
    }
    port in_o16 {
        layout [ size: 2, 2 ]
    }
    port in_o17 {
        layout [ size: 2, 2 ]
    }
    port in_o18 {
        layout [ size: 2, 2 ]
    }
    port in_o19 {
        layout [ size: 2, 2 ]
    }
    port in_o20 {
        layout [ size: 2, 2 ]
    }
    port in_o21 {
        layout [ size: 2, 2 ]
    }
    port in_o22 {
        layout [ size: 2, 2 ]
    }
    port in_o23 {
        layout [ size: 2, 2 ]
    }

    node inner1 {
        layout [ size: 120, 70 ]
    }
    node inner2 {
        layout [ size: 120, 70 ]
    }
    node inner3 {
        layout [ size: 120, 70 ]
    }
    node inner4 {
        layout [ size: 120, 70 ]
    }
    node inner5 {
        layout [ size: 120, 70 ]
    }
    node inner6 {
        layout [ size: 120, 70 ]
    }
    node inner7 {
        layout [ size: 120, 70 ]
    }
    node inner8 {
        layout [ size: 120, 70 ]
    }
    node inner9 {
        layout [ size: 120, 70 ]
    }
    node inner10 {
        layout [ size: 120, 70 ]
    }
    node inner11 {
        layout [ size: 120, 70 ]
    }
    node inner12 {
        layout [ size: 120, 70 ]
    }
    node inner13 {
        layout [ size: 120, 70 ]
    }
    node inner14 {
        layout [ size: 120, 70 ]
    }
    node inner15 {
        layout [ size: 120, 70 ]
    }

    node comp_col_a_0 {
        layout [ size: 10, 10 ]
        port comp_col_a_0_in_o0 {
            layout [ size: 2, 2 ]
        }
        node comp_col_a_0_leaf_0 {
            layout [ size: 10, 10 ]
        }
    }
    edge _edge0: in_o0 -> comp_col_a_0.comp_col_a_0_in_o0
}
```

**Comment by uruuru** [comment]
Issue vanishes when setting `crossingMinimization.greedySwitch.type: OFF`

**Comment by uruuru** [comment]
Having thought about it a bit more I suggest the following. 

We activate greedy switch only for "small" graphs as it's impact is usually only visible in that case. During hierarchical layout it is not really possible (I believe) to activate greedy switch only for a subset of hierarchical nodes. The crossing minimization works on the whole hierarchy and a _local_ greedy switch may thus interfer with what the global crossing minimization has done before. 

Since graphs for hierarchical layout are usually larger anyway (conjecture), I'd say we deactivate greedy switch by default. 

To still allow a user to get a correct greedy switch behavior, I'd implement it as follows. Check if greedy switch is explicitly activated (using `hasProperty`), and if so, activate it for the root of the hierarchical graph.

**Comment by uruuru** [comment]
For completeness, a small graph to reproduce the issue: 
```
hierarchyHandling: INCLUDE_CHILDREN
crossingMinimization.greedySwitch.type: TWO_SIDED

node l1 {
    crossingMinimization.greedySwitch.type: OFF
    node l2_1 {
        layout [ size: 100, 100 ]
        crossingMinimization.greedySwitch.type: TWO_SIDED
        node l3 {
            layout [ size: 20, 20 ]
        }
    }
    node l2_2 {
        layout [ size: 20, 20 ]
    }
}
```

**Comment by le-cds** [comment]
I'm all for your suggested fix, but this I'm not on board with yet:

> To not change the default value of the layout option, but still allow a user to get a correct greedy switch behavior, I'd implement it as follows. Check if greedy switch is explicitly activated (using `hasProperty`), and if so, activate it for the root of the hierarchical graph.

I'm not sure yet if I understand. This is the way I understand it now:

* Since the default value will stay the same, greedy switch would be active by default for non-hierarchical graphs.
* If hierarchical layout is active, the default effectively changes to `OFF`, except for when `ONE_SIDED` or `TWO_SIDED` are explicitly requested. If the latter is the case, this is propagated up to the root node.

Is that correct? If so, this implicit change in behaviour seems confusing to me. One alternative might be to make this more explicit, for example by having five possible enumeration values:

* `OFF`
* `ONE_SIDED`
* `TWO_SIDED` (still default)
* `ONE_SIDED_HIERARCHICAL`
* `TWO_SIDED_HIERARCHICAL`

The hierarchical versions would be documented to propagate up to the root node of the graph hierarchical layout is computed for.

**Comment by uruuru** [comment]
It's even a bit more complicated. An since greedy switch's contribution isn't that significant but its configuration is rather intricate, I didn't want to give it too much thought: 

What happens if one child configures `ONE_SIDED` and another child in a different branch of the graph `TWO_SIDED`? 

Also, the implicit change to `OFF` would still be required and `ONE_SIDED` and `TWO_SIDED` whould have to be forbidden as soon as hierarchical layout is active (as they would lead to invalid configurations).

**Comment by le-cds** [comment]
For the record: we decided to introduce a separate option that controls greedy switch for hierarchical graphs.
