### ISSUE TITLE
ELK Layered node overlapping

### ISSUE THREAD

**Issue by chakraborty-slx** [eclipse/elk#636]
I am using elk with ZEST.
The graph has nodes with different sizes. The spacing between the nodes is not maintained unless nodes are of the same width.

See the image 

 ` configurator
        .configure(ElkGraphElement.class)
        .setProperty(
            CoreOptions.ALGORITHM, "org.eclipse.elk.layered")
        .setProperty(
            LayeredOptions.CROSSING_MINIMIZATION_STRATEGY, CrossingMinimizationStrategy.INTERACTIVE)
        .setProperty(CoreOptions.INTERACTIVE, true)
        .setProperty(CoreOptions.SPACING_NODE_NODE, layout.getNodeSpacing())
            .setProperty(
            CoreOptions.DIRECTION,
            Direction.DOWN)
        .setProperty(LayeredOptions.CYCLE_BREAKING_STRATEGY, CycleBreakingStrategy.INTERACTIVE)
        .setProperty(
            LayeredOptions.NODE_PLACEMENT_STRATEGY,
            NodePlacementStrategy.SIMPLE)
        .setProperty(
            LayeredOptions.LAYERING_STRATEGY,
            LayeringStrategy.INTERACTIVE)
            .setProperty(LayeredOptions.SPACING_NODE_NODE_BETWEEN_LAYERS, layout.getLayerSpacing())
        .setProperty(CoreOptions.ALIGNMENT, Alignment.AUTOMATIC)
      .setProperty(CoreOptions.PADDING, new ElkPadding(50f)) // Graph padding
    ;`

![Screenshot from 2020-06-11 15-23-13](https://user-images.githubusercontent.com/26390759/84391609-7d8fbd80-abf9-11ea-9ac1-2e3cdbbc7d1a.png)

**Comment by uruuru** [comment]
Does this also happen when you omit all the custom layout options? 

Can you attach the layout graph? You should be able to export it checking _store debug information_ in the preferences:
![image](https://user-images.githubusercontent.com/7552459/84413494-fd755200-ac10-11ea-9944-e991b1fefd38.png)

**Comment by chakraborty-slx** [comment]
[159190274.zip](https://github.com/eclipse/elk/files/4766807/159190274.zip)


Please find the logs in attachment

**Comment by chakraborty-slx** [comment]
[Uploading without_any_options.zip…]()

**Comment by uruuru** [comment]
Something seems to be off in your configuration. The graphs in your first zip all have `<properties key="org.eclipse.elk.algorithm" value="org.eclipse.elk.planar"/>` specified. 

Furthermore, all graphs (also the latest zip) only contain _four_ edges. From the layouter's perspective your graph looks like this
![image](https://user-images.githubusercontent.com/7552459/84432165-bbf2a000-ac2c-11ea-8b61-ed3c952e5f39.png)

Did you create your own layout connector? 

In case you have the _Layout Graph View_, you can take a look at the layouter results yourself.

**Comment by chakraborty-slx** [comment]
Great thanks,I  have found the bug in my code, Zest's EntityLayout uses the location as the center of the node, I have corrected my code.
