### ISSUE TITLE
Layered Partitions

### ISSUE THREAD

**Issue by shean42** [eclipse/elk#656]
In this [small example](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=A4QwTgLgltD2B2V4HMB0IDG0BuIIFMAuAAgjAFd8AoK+WAE32PgAYqBvK440SGKBCTbdgsSMQDu+AM4Ri7YtKiMSAdQCiAZQAqxAL5diAGxAAjfEeIAiYCytUDtBk3gBGDod7Q48Eu5FiclKy8orKRMQaOvqegcT4ICEKSirE6gCC0QbcJuaWNq72jnSMzABMHiLg3gK+xBUB4sFyyeFqWrrZPHEJSWGpGVmGuRbWwGVFNCUuACyVPNX8gvWx4r0t-RGDncNmozYTDjT49MguZajrxAC0AHzMrqjNVCdnzDOXiXJ35U8yEC9Ti5Hlcfqw-rIgA) the partition ordering is broken since nodes with different partitions end up in the same layer. Any insights on this from da Elk? :-)

**Comment by le-cds** [comment]
Layout partitions insert a whole number of dummy edges from nodes in lower partitions to nodes in higher partitions. They are supposed to force layer assignment to produce a layering which already adheres to the partitions. In this case, however, the dummy edges produce cycles with the regular edges. Unfortunately, our cycle breaker decided that it's a good idea to reverse some of the dummy edges, thus breaking our partitions.

This is a fundamental problem of the way we implemented layout partitions. I'll have to think about how best to salvage this... Running cycle breaking and layer assignment on each partition separately would be a solution, but that'll be hard to implement without over-complicating our cycle breaking and layer assignment algorithms...

**Comment by le-cds** [comment]
The pull requests fixes the issue for graphs where all nodes have a partition configured, as is the case here. 🙂

**Comment by shean42** [comment]
Thanks for the timely fix! 

At least in my setting all nodes have a partition configured all the time and thus this is not a restriction in any way.
