### ISSUE TITLE
Workaround comments exist in multiple files while the related issues are already fixed.

### ISSUE THREAD

**Issue by markxiaotao** [eclipse/elk#657]
In a research project, we analyzed the build file of repositories looking for comments with ready-to-be-addressed SATDs (self-admitted technical debt) that could be addressed. If the underlying issue is already resolved, the related code or comment can be removed or fixed. As we found an instance of this kind of asynchrony in elk, we decided to report the issue to contribute community.
Comments in multiple files claim that they are workaround for https://github.com/eclipse/xtext/issues/1231, and this issue has been closed long ago, they also provided new solution: https://github.com/eclipse/xtext/issues/1231#issuecomment-460184629.

Comments location:
https://github.com/eclipse/elk/blob/1c71b55859ad3385d1aeef60b49706e13582253d/plugins/org.eclipse.elk.alg.mrtree/pom.xml#L41
https://github.com/eclipse/elk/blob/1c71b55859ad3385d1aeef60b49706e13582253d/plugins/org.eclipse.elk.alg.graphviz.layouter/pom.xml#L46
https://github.com/eclipse/elk/blob/1c71b55859ad3385d1aeef60b49706e13582253d/plugins/org.eclipse.elk.alg.spore/pom.xml#L51

**Comment by uruuru** [comment]
Thanks for making us aware of this fact.
