### ISSUE TITLE
Node Labels are placed incorrectly in downwards layout

### ISSUE THREAD

**Issue by eNBeWe** [eclipse/elk#66]
When using layout direction "down", the node labels in bottom left and top right corner are switched.
Also labels in all positions are not stacked anymore but placed left to right.

```
properties:
org.eclipse.elk.direction=DOWN

knode n1 {
    klabel "Foo" {
        properties:
        de.cau.cs.kieler.nodeLabelPlacement = "INSIDE V_TOP H_RIGHT"
    }
    klabel "Bar" {
        properties:
        de.cau.cs.kieler.nodeLabelPlacement = "INSIDE V_TOP H_RIGHT"
    }
}
```

![nodelabels](https://cloud.githubusercontent.com/assets/3796429/16907398/abe2e23c-4cc3-11e6-95e4-eceddcafcdfa.png)

**Comment by le-cds** [comment]
What would be the behavior you'd expect? If a node label is configured to be inside at the top right, you would probably want it to end up exactly there, right? Thus, the node label placement configuration should not be interpreted relative to the layout direction?

**Comment by uruuru** [comment]
I guess so. It's relative to the node, not the overall layout direction.

**Comment by uruuru** [comment]
I believe this has actually been fixed by your rewriting of the label placement code, @le-cds.

Results of 
```
elk.direction:DOWN
node n1 {
    layout [ size: 100, 100 ]
    label "Foo" {
        nodeLabelPlacement: "INSIDE V_TOP H_RIGHT"
    }
    label "Bar" {
        nodeLabelPlacement: "INSIDE V_TOP H_RIGHT"
    }
}
```
![image](https://user-images.githubusercontent.com/7552459/79243218-a1db5200-7e75-11ea-81c6-0210aa768127.png)

`elk.direction: UP`:
![image](https://user-images.githubusercontent.com/7552459/79243271-b3bcf500-7e75-11ea-9250-85f7f81dccc7.png)

**Comment by le-cds** [comment]
Nice, well done me. 😁
