### ISSUE TITLE
JSON Export lacks layout information

### ISSUE THREAD

**Issue by xutong8** [eclipse/elk#664]
Why is there no information such as x and y in the ELKGraph JSON returned by ElkGraphJson.forGraph(graph).toJson()? However, graph.getX() can get the correct value.

`ElkGraphJson.forGraph(elkgraph).omitLayout(true).omitZeroDimension(true).omitZeroPositions(true)
				.shortLayoutOptionKeys(false).prettyPrint(true).toJson()`

when I invoked the above methods, the returned json string missed layout information such as x and y.

**Comment by le-cds** [comment]
Perhaps @uruuru will correct me on this, but I guess the culprit here is `omitLayout(true)`. I would expect this to cause the exporter to not export any layout information, which includes x and y coordinates.

**Comment by uruuru** [comment]
From what you describe I can only refer to @le-cds's answer: it's expected behavior. 

It may well be an oversight that the x coordinate of the graph itself is set, however, it should always be `0` anyway, I believe.

**Comment by xutong8** [comment]
Yeah! when I try to set omitLayout to false, the exporter can export layout information.&nbsp;Thanks for your answer!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Christoph Daniel Schulze"<notifications@github.com&gt;; 
发送时间: 2020年7月18日(星期六) 晚上6:58
收件人: "eclipse/elk"<elk@noreply.github.com&gt;; 
抄送: "徐彤"<2451836009@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [eclipse/elk] JSON Export lacks layout information (#664)





 
Perhaps @uruuru will correct me on this, but I guess the culprit here is omitLayout(true). I would expect this to cause the exporter to not export any layout information, which includes x and y coordinates.
