### ISSUE TITLE
Class diagram like layout

### ISSUE THREAD

**Issue by parnold-x** [eclipse/elk#670]
I want to achive a class diagram like layout with two kind of edges. **Generalisation** and **Association**
The inheritance edges should be layouted vertical and associations horizontal.
So for this example (ELK Layered, UP direction, Some spacing settings)
![image](https://user-images.githubusercontent.com/3041711/88803965-876f7f00-d1ad-11ea-9f48-968decf7cf7b.png)

**C** and **D** should be on the same horizontal line as **B**, I specified the EDGE_TYPE to EdgeType::GENERALIZATION, EdgeType::ASSOCIATION but it seems to not change something. I also tried various layout options without success.
Here http://rtsys.informatik.uni-kiel.de/~kieler/videos/ecore/media/ecore.mp4 the behavior looks pretty much how i want it.
Can you please point me to something.

Thank you for this really cool project!

**Comment by uruuru** [comment]
I don't think that this layout style can properly be achieved using ELK layered.

The layouter used in the video you linked is not ELK Layered but one of [OGDF's](https://github.com/ogdf/ogdf) layouters. The edge types such as `EdgeType::GENERALIZATION` are not supported by ELK Layered either but may be used in conjunction with OGDF, for instance. 

There's an OGDF bridge for ELK available via the [KIELER Pragmatics Update Site](https://rtsys.informatik.uni-kiel.de/confluence/display/KIELER/Downloads#Downloads-PragmaticsUpdateSite), which you may want to give a try.

**Comment by parnold-x** [comment]
I installed the OGDF packages and I somehow not manage to make it work?!
In the _Select Layout Algorithm or Type_ Dialog no new options are shown and if I adapt my code from
`addLayoutParam(CoreOptions::ALGORITHM, LayeredOptions.ALGORITHM_ID);`
to 
`addLayoutParam(CoreOptions::ALGORITHM, de.cau.cs.kieler.kiml.ogdf.options.PlanarizationOptions.ALGORITHM_ID);`
I get access restrictions errors. If I fix them and try it nothing changes and in the layout view it still shows ELK Layered as Algo.

**Comment by uruuru** [comment]
The access restriction error is something that should be fixed in the KIELER code (the packages do not seem to be exported). @le-cds or @soerendomroes could one of you take care of this? 

Apart from that I can only say that it works for me with the current sources in my current setup. 

Do you get any errors during startup? Did you include the new plugins in your runtime instance?

**Comment by parnold-x** [comment]
Yes I included all ogdf plugins in the runtime config and the get loaded fine. Mhh, strange. I setup a new eclipse tomorrow. You never know with eclipse :)
Thank you for your help!

**Comment by parnold-x** [comment]
So, i have installed a new eclipse, installed the ogdf plugins. Created a xtend class and tried to visualise the AST with the Diagram View. In the Layout View under Algorithm are just ELK and Graphviz listed. Also it does nothing if I try my example.
Should I do something additional to make this work?

**Comment by uruuru** [comment]
Maybe @le-cds or @soerendomroes can help here. They are more familiar with the current state of the KIELER features.

**Comment by parnold-x** [comment]
Ok, so I found time today to look at it again and the reason it is not useable seems to be that the **de.cau.cs.kieler.kiml.ogdf** plugin is not register the OGDF MetaDataProvider at the **org.eclipse.elk.core.layoutProviders** extension point. After I added that it works fine. 👍 
Just another question. Is there a way to set something that the layout change is preferable minimal. Like if a tree is shown and a new branch under a node is added, so that not all branches are reordered somehow randomly but more a deterministic order. I saw https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-considermodelorder.html but my LayeredOptions seems to not have this option.

**Comment by soerendomroes** [comment]
`considerModelOrder` was added in the ELK 0.7.0 release, what ELK version are you using?
But I think you want to use interactive strategies for the different phases instead.
`considerModelOrder` does not use previous positions of nodes and edges, but would order the nodes (and edges) according to their order in the model (file). If you are sure that this order of nodes and edges does not cause conflicts (e.g. unnecessary crossings) it can of course also be used to ensure minimal layout change.
I think these are the correct options:
```
LayeredOptions.CROSSING_MINIMIZATION_SEMI_INTERACTIVE: true or LayeredOptions.CROSSING_MINIMIZATION_STRATEGY: CrossingMinimizationStrategy.INTERACTIVE // probably the second one
LayeredOptions.LAYERING_STRATEGY: LayeringStrategy.INTERACTIVE
LayeredOptions.CYCLE_BREAKING_STRATEGY: CycleBreakingStrategy.INTERACTIVE
```

**Comment by parnold-x** [comment]
Ah ok, I am using 0.6.1. That's why it is missing. Thanks! I will look at this Interactive Strategy and how this can be applied at my problem. Thanks again for making Autolayouting accessible

**Comment by uruuru** [comment]
@soerendomroes shouldn't the registration for 0.6.1 work without the `org.eclipse.elk.core.layoutProviders`?

And for the current master of the ogdf plugin the registration has been added, right? 

In which combination of versions can this fail? 

@parnold-x you used ELK 0.6.1 and KIELER's nightlies?

**Comment by parnold-x** [comment]
The version of the odgf bridge is: KIELER Bridge for OGDF Layout	0.46.0.202003301359	de.cau.cs.kieler.kiml.ogdf
 If I remember right the nightly did fail on install due to some dependency thing.

**Comment by soerendomroes** [comment]
@uruuru I don't know whether it should work. For the current master the registration is not added via extension points.
The registration should work via java ServiceLoader, but I do not know whether this was correctly implemented for the ogdf plugin.

**Comment by le-cds** [comment]
> KIELER Bridge for OGDF Layout 0.46.0.202003301359 de.cau.cs.kieler.kiml.ogdf

That plug-in version had support added for service loaders, and support removed for extension points. It is thus expected that it only works with ELK 0.7.0 out of the box. Sorry about that, I didn't think about backwards compatibility.
