### ISSUE TITLE
Clean up build process

### ISSUE THREAD

**Issue by le-cds** [eclipse/elk#672]
The build process currently has a few problems, partly due to my limited understanding of things when I instated it, and partly due to things changing in the Eclipse Foundation's infrastructure.

* [ ] build.eclipse.org, which houses our nightlies, will be retired soon. As a consequence, our nightlies have to be moved to download.eclipse.org. [This Bugzilla ticket](https://eclip.se/565644) has more info.
* [ ] The first phase of our build, which builds the metadata compiler, creates a Maven repository at a local directory. That's completely unnecessary and complicates matters unnecessarily. We could probably simply push to Maven Central and use those artefacts in the second phase.
* [ ] This requires documentation on the website to be adapted as well.

**Comment by uruuru** [comment]
One question regarding your second point:

> We could probably simply push to Maven Central and use those artefacts in the second phase.

Is that the way you implemented it? During our discussions I understood that you use the _locally_ installed melk artifacts (in `.m2`).

**Comment by le-cds** [comment]
> > We could probably simply push to Maven Central and use those artefacts in the second phase.
> 
> Is that the way you implemented it? During our discussions I understood that you use the _locally_ installed melk artifacts (in `.m2`).

Nope, you're correct: we're now installing the artifacts locally. Since the artifacts produced by phase 1 will always be superseded by phase 2, I figured I'd spare Maven Central the trouble of updating them twice in quick succession. 😄
