### ISSUE TITLE
Add test to actions verifying that all example models are laid out correctly

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#673]

**Comment by le-cds** [comment]
What do you mean by "example methods"?

**Comment by uruuru** [comment]
Sorry, misstyped that one ...

**Comment by le-cds** [comment]
Still not sure what you're referring to here, though. 😄

**Comment by uruuru** [comment]
These ones: https://rtsys.informatik.uni-kiel.de/elklive/examples.html

**Comment by le-cds** [comment]
Ah! Makes sense.

**Comment by lredor** [comment]
> These ones: https://rtsys.informatik.uni-kiel.de/elklive/examples.html

I discovered this page. It is great. Is it a project to have similar examples on each option in the [reference documentation](https://www.eclipse.org/elk/reference.html)?
For example for [Comment Box](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-commentbox.html), it will be interresting to have [this example](https://rtsys.informatik.uni-kiel.de/elklive/examples.html?e=general%2Fspacing%2Fcomments) to illustrate it.

**Comment by uruuru** [comment]
@lredor there are no clear plans. I created the basis and was hoping that "people" (including me) find time to add an example once in a while. 

The examples are described in a single file in a simple text format, are added to the elk models repo and then automatically deployed to the website. See https://github.com/eclipse/elk-models/tree/master/examples Everyone is encouraged to add simple examples where sensible. 

Regarding your suggestion to add the examples to the reference documentation. The documentation website is created via a static site generator and I wouldn't include the layouter and a rendering engine there (if at all possible given eclipse guidelines). 
I must admit that I have thought about somehow merging the two sides before, though.

**Comment by uruuru** [comment]
We could add a list of links to available examples to the layout options in the reference documentation. The models repos is available during website construction. Given a base-url it should thus be possible to assemble the relevant links.

**Comment by le-cds** [comment]
That's an excellent idea. We'll keep the idea around, although I'll better refrain from assigning it a milestone...
