### ISSUE TITLE
Layout ID inconsistent with elkm file

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#68]
From the ``BoxLayoutProvider``:
```
    /** the layout provider id. */
    public static final String ID = "org.eclipse.elk.alg.box";
```
However, the elkm generates ``org.eclipse.elk.box``. 

I guess we can remove the ``ID``s from the layout providers and generate a corresponding field in the layout option classes which are generated for every layouter.

Check this for the other layouters as well.

**Comment by le-cds** [comment]
Seems like a good idea. I vote for generating an `ALGORITHM_ID` constant in the metadata class generated for each layout algorithm.
