### ISSUE TITLE
Melk target of nodeLabels.padding inconsistent

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#684]
While it seems that `nodeLabels.padding` has to be applied to parents to take effect, the melk specifies `targets: nodes`. 

Check which one should be the case and adjust the necessary parts.

**Comment by le-cds** [comment]
The target should be parents:

https://github.com/eclipse/elk/blob/c2906eb3e595b6b494d962ce250e89ac07f8c18b/plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/internal/NodeContext.java#L151-L157

I'll prepare a pull request to be sure that the target definitions of all of these options are correct.
