### ISSUE TITLE
Parse graph from String

### ISSUE THREAD

**Issue by Baltoli** [eclipse/elk#689]
Is there a simple way to parse an `ElkNode` from a `String` containing the textual representation?  I've been trying to adapt the approach taken [here](https://github.com/eclipse/elk/blob/4e545a5100eb647e94e8b52c34e37c327e262019/plugins/org.eclipse.elk.core.debug/src/org/eclipse/elk/core/debug/views/graph/LoadGraphAction.java#L115), but I'm seeing `NullPointerException`s when loading the `Resource`.

Let me know if I'm missing something obvious here - thanks for your help.

**Comment by Baltoli** [comment]
To give you a better idea of what I'm trying to do, see this code:

```java
String graphText = ...; // some valid ElkT

ResourceSet r = new ResourceSetImpl();
URI uri = URI.createURI("dummy.elkt");
Resource resource = r.createResource(uri);
var conv = new URIConverter.ReadableInputStream(graphText, "UTF-8");
resource.load(conv, null);

ElkNode graph = (ElkNode) resource.getContents().get(0);

final String json = ElkGraphJson.forGraph(graph)
                                .omitLayout(true)
                                .omitZeroDimension(true)
                                .omitZeroPositions(true)
                                .shortLayoutOptionKeys(false)
                                .prettyPrint(true)
                                .toJson();

return json;
```

**Comment by soerendomroes** [comment]
Can you provide us with a stacktrace for your `NullPointerException`?

**Comment by javierariasmoreno** [comment]
I reproduced the code and the stacktrace:
java.lang.NullPointerException
        at Main.main(Main.java:39)
[Ljava.lang.StackTraceElement;@4f933fd1

at line 39 there is resource.load(conv, null);

**Comment by soerendomroes** [comment]
Resource ResourceSetImpl.createResource(URI uri)
Creates a new resource, of the appropriate type, and returns it.

It delegates to the resource factory registry to determine the correct factory, and then it uses that factory to create the resource and adds it to the contents. If there is no registered factory, null will be returned; when running within Eclipse, a default XMI factory will be registered, and this will never return null.

I think this might be the problem.

**Comment by uruuru** [comment]
In other words, try something along the lines of (without the GRandom thingy):

https://github.com/eclipse/elk/blob/99b603583ae9fc81e2ea6663dab224ba8c4f1e9d/test/org.eclipse.elk.alg.test/src/org/eclipse/elk/alg/test/PlainJavaInitialization.java#L66-L81

**Comment by Baltoli** [comment]
This is what we needed - if anyone else has the same issue, we needed the code from [here](https://github.com/eclipse/elk/blob/4e545a5100eb647e94e8b52c34e37c327e262019/plugins/org.eclipse.elk.graph.text/src-gen/org/eclipse/elk/graph/text/ElkGraphStandaloneSetupGenerated.java) instead to get the textual format. We just copied the `register()` call from that class into our setup function and the rest worked as expected.

Thanks for your help - much appreciated.
