### ISSUE TITLE
Layered's positionChoiceConstraint not used

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#690]
@soerendomroes is it correct that the option is not used at all at the moment? Am I missing it's usage in the code? Is that by mistake? Can it be removed?

I assume that if it's used it shall only be used in interactive mode? If that's true, we should add a `requires` to the melk`.

**Comment by soerendomroes** [comment]
This option is only used during interactive layout (interactiveLayout is true) by the `InteractivelayoutGraphVisitor` and classes in Klighd.
However, it is allowed to specify interactiveLayout on the root node (and maybe also required). I am not sure whether we can add that as a require constraint.

For example the following should be valid:

```
interactiveLayout: true

node n1 {
	node n2
	node n3 {
		crossingMinimization.positionChoiceConstraint: 2
	}
	node n4

	edge n2 -> n3
	edge n2 -> n4
}
```

**Comment by uruuru** [comment]
I'm referring to the fact that the option is nowhere (afaict) evaluated within elk layered.

**Comment by soerendomroes** [comment]
The `InteractiveLayeredGraphVisitor` is in elk layered and uses this property.

**Comment by uruuru** [comment]
Ah, thanks that's what I was looking for. For some reason my Eclipse didn't come up with this in it's _"References - Workspace"_.
