### ISSUE TITLE
Remove Guava dependency

### ISSUE THREAD

**Issue by BoykoAlex** [eclipse/elk#692]
is Guava dependency necessary for the plugins? I looked through a bit of code around Layered Algorithm, elk.core and elk.graph and looks like Guava can be easily removed.
I'm using ELK from maven central and Guava dependency is undesirable for us. Any chance Guava can be removed?
Is the source code here the same as for ELK libs published on Maven Central?

**Comment by soerendomroes** [comment]
The source code here is the same as for the ELK libs in Maven Central.
@uruuru @cds Do you have any opinions about guava?

**Comment by cds** [comment]
@soerendomroes  I thing you misunderstand me with someone else, i had very less experience with guava to give an opinion.

**Comment by soerendomroes** [comment]
@cds Yes, you are correct. I meant @le-cds

**Comment by BoykoAlex** [comment]
I might be able to provide a PR for Guava removal for algorithms, core, graph. (I'd like to also remove it for the json lib but maybe will postpone it for Guava removal stage 2)

**Comment by uruuru** [comment]
TBH it's not something we desire. What's your problem with it?

**Comment by BoykoAlex** [comment]
Mainly this: https://softwareengineering.stackexchange.com/questions/390120/why-is-it-considered-bad-that-guava-introduced-direct-internal-dependencies

I've tried to remove Guava dependency for **elk.graph**, **elk.core** and algorithm projects but it seems somewhat challenging with `Iterables.concat(...)` replacement...

**Comment by uruuru** [comment]
I'll take a look at your link. 

Please note, though, that even if you were able to remove all current usages, I'm not sure I'd be in for it. I'd like to have the chance to use it in the future.

**Comment by BoykoAlex** [comment]
Thanks for the info! Think i figured out how to load the ELK JS properly in Angular app

**Comment by BoykoAlex** [comment]
Sorry closed by accident...
I'd be happy if Guava is removed from **elk.graph**, **elk.core**, algorithms and possibly **elk.json** excluding tests of course... so ELK JARs one would get from Maven Central.

**Comment by le-cds** [comment]
The way I see it, our usage of Guava can be divided into several categories.

1. Simple convenience methods:
   * Collection creation methods, such as `Sets.newHashSet()` and `Lists.newArrayListWithCapacity(...)`, which come from a time before the diamond operator was introduced. These can be replaced very easily.
   * Methods like `Strings.isNullOrEmpty(...)`, which can be easily replaced as well.
1. Complex data structures. This includes `Iterables.concat(...)`, bidirectional maps etc., which are _a lot_ harder to replace.

Personally, I could see us replacing usages of the first category, but not of the second. Sadly, the second category appears in the plug-ins you noted, @BoykoAlex.

However, even if we removed the Guava dependencies from those core plug-ins, that would still leave algorithm plug-ins. Wouldn't you need those replaced as well, or are you only using algorithms that don't depend on Guava? (do we even have any?)

**Comment by le-cds** [comment]
I'll close this as _won't fix_ for two reasons:

- We don't have a simple drop-in replacement for `Iterables.concat(...)`.
- We want to continue having access to the Guava library.

ELK doesn't need the most recent version, so consuming projects may be able to get away with a dependency to an older Guava version, released before the library was split.
