### ISSUE TITLE
Problems with LayoutGraphView in GTK-based window managers

### ISSUE THREAD

**Issue by HansMontana** [eclipse/elk#70]
Hey there,

I've encountered a weird drawing issue in Ubuntu, which allegedly hasn't occured in Windows- or MacOs-based systems (yet):

The `LayoutGraphView` doesn't seem to function properly, when labels are involved. Have a look for yourself:

![clipping_activated_ buggy](https://cloud.githubusercontent.com/assets/20580972/17027555/909308b0-4f64-11e6-8165-05734f3d57f5.png)

Deleting line 294 in the `GraphRenderer` class seems to be a quick and dirty workaround:
`graphics.setClipping(rect.x, rect.y, rect.width, rect.height);`

![clipping_deactivated](https://cloud.githubusercontent.com/assets/20580972/17027556/9093455a-4f64-11e6-8fa6-3d1114887d64.png)

As the `setClipping`-method certainly has an important purpose, you might want to take a look into this issue.

Some information about my system:
[some_pieces_of_system_info.txt](https://github.com/eclipse/elk/files/376317/some_pieces_of_system_info.txt)

Keep up the good work :)

**Comment by le-cds** [comment]
I'm not sure what the issue is here with the clipping... The call to the clipping method is not all too important, but if we can leave it in, all the better. I tried to make this particular part of the code a bit more robust, could you check if that fixes your issue?

**Comment by le-cds** [comment]
Since we have never seen this issue again, it's probably fixed...
