### ISSUE TITLE
Wrong margin/padding around fixed port label

### ISSUE THREAD

**Issue by lredor** [eclipse/elk#701]
As explain in [gitter](https://gitter.im/eclipse/elk?at=5f5f652ba9c2c8511e946191), it seems that when a port label is set with a fixed location, the layout result is not correct (there is overlap).
[Here](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=OYJwhgDgFgBA4gRgFABswE8D2BXALjAbRgGcBLALwFMAuGAJgQBYBWAGhgDYGYBdJKUpXAgAxlHQAJMADsAJilLTgtAJIA5AMIAZAKoARAKIB9DRJVa9AJQNqk0zLMoBlCpQB0IzNOK5wi3MS0AEQEAAoA8pYAKk7sauGGRloAggBCBlqxMACy6irZOtlGTioAWgbsEdFJaRlOPEFIYCjAmCCkuFAAtrRtwG6UIgoQxO6UKADWbmjoQpSySPPAlJY4uIrKMJFREuFw4WrJWnaYWhhrtABmzaMnjjBRYCDL+ADeSACQM2uEnx8QmDI6y8tA4AA4wexmMw-mQqLQEAB2BDsRiIz58D4CIRPMSSGTyDaqTS6RKmcxWGyfeyOFxUDxeHx+aQBYJhbZZeKJFLpTLsXJqfKFYplCowKpRGq8+qND405yuNxdRSkLrYHowIIACgAzAg3AAGViMOiGgCUsqWKzWRK20V2+0Oxy+YAARuMYFoEMFHs9KLggjB3h8XVg8L8Q-9AR1SCCYIwdVC-h84TQYGC2DAkX9MXKHJQzu6UMQ3BA0CJKF1KCy2RITDYogZLOwAGpGKLhULsdQlQwNT4AXyQQ-lMA0XlwYEUQiDn2+4YIfwBQNj0gROsR7AQdEYsNctEYHE39A3GM+2OEeKkcgUSmJ2n0xnJFmstjztMVnm8vinLMCmvZaJOQSYweTqfk8gKIoSnKSptilOp+3fBV6WVaRVXVYItQQHVDVYOhmHNS1ZGWVY8FtbYHQOI5PgBEBcELcYSzLMAKyrGsAKQtAi09OhgnHFlfyEQNg1DH5F0jZcYzjBAAE5ZKTSNU1BSEs3RENc3lRji1LctK2rXBa3rNRG2bGA2w7LsYB7FQ+1lIco3o8UEFnEN53wCSQyk4E13jZgFJgREdWTZT6CNMKcz+PoBiGUgRjGSY3AAPTo3A3FdNpHBAcJLkuUZDJgABaMFDT+biPS0HVgmydBQjaBi3XGAAxUgAA95hE5N3IjSTox82hCp1WS3EzBhkxTfcYHkrd1I0v4HIc0cnGwV0BMnacQFcsSF2TbzV1oMFjx1DgQsmugdToLdZINSKQwvXFxGvQk72sklHxMMwXypEN5TpdwvyZX9WQAiVgO5Wo+RySDhRgsUJQQzIkJTCBWI2Ut6rq+j11Kn78z+pUVTVDVtQQQijRNIil3q7TmL09iCpCJGrTI9YXsovZqOdF0eK0RhgmW1aJyEkBOsjbrPK8vr9s4S6YBhSMJvhLMDWPbNI1zZCad01j9I4kI6w0Bsm1bdtO27NRewMJGHMc-BQjoLbto88a9rjOgd3YU8FdCuhwt95MNeiwZhlGAZEpS+r0syoQcry-0BpKm6QwWz4rRgAw+JgAW1uFtx7aKgA+ZytvFkLBh89OnAdiWU0nLGYAu1SwWChXq1kA9-PYZuA9uochzTgxvTHIWNrzlzCqL30Xlc0uQ1GEQK4MJwXIlnwngKjhSfYX2TsjNuDpVrcDToZN3Tkf8wUPsLd4+TE+CHIA) is an example corresponding to this image: 
![samplePortLabel](https://user-images.githubusercontent.com/1825882/93124510-fc4d3880-f6c9-11ea-92ce-5c874ccd516a.png)

I expected something more like [this](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=OYJwhgDgFgBA4gRgFABswE8D2BXALjAbRgGcBLALwFMAuGAVgGYAWAOjoBoYAmANgAYYAXSRRSlcCADGUdAAkwAOwAmKUguC0AkgDkAwgBkAqgBEAogH1dszfuMAlU9qQLMSygGUKlFpMwLiuOBquMS0AEQEAAoA8nYAKu6c2tFm5voAggBCpvqJMACyOpr5hvnm7poAWqacMfFpWTnugmFIYCjAmCCkuFAAtrRdwCyUkqoQxN6UKADWLGjo4pRKSMvAlHY4uGoaMLFxstFw0drp+s6Y+hhbtIHYlBduMHFgIOv4AN5IAJALW4Q-b4QTBkbZ+WgMPgINicOh8QFkKi0BBQzhMADsP2E31E4le0jkihUOy0eiMqSsNnsjh+LjcnioPj8ASCChC4Si+zyyVSGWyuU4hW0xVK5SqNRgdTiDX5zVa3zpHi8LD6alIfWwAxgYQAFABOOgsPjsJisPgASnlaw2WxJe3ih2Op3OvzAACNpjB9Ahwi83pRcGEYF9vq6sHgAaGgSCeqRwTAGAxYYDvoiaDAABwcGAITGh7EK1yUK4elDEFgQNCSSh9ShsjmySyOOKmOycABq5ji0UinB0FTMLR+AF8kKPFTBdH5cGA1OJgz8-hGCIDgaC4wpkVxOAguAivLQuAgM5w9QwsT9cRICfJlKp1KSDCYLJTbA4nIX6crfP5ArO2aE2qcvE3IpBYfJNIKRQlGUFTVLU+wyk0Q6fkqjKqgo6qauEOoZjwRomvhFpWko6ybHgdr7I6JxnD8wIgLgJbTOWlZgNWtb1kBKFoKWXpcOEU5sv+4hBiGYb-CuUZrrG8boggyZRmmtA8CeOZ5t8BaKkxZYVlWNZ1rgDZNtoLZtjAnbdr2MD9pog7yqO0YMZKCALqGS74JJobSWCm7cCiaIZimSncMaIWAgWQwjGMpATFMswsAAevRuAsG6XRuCA0QAGZZZMhkwAAtBmRqAjxnr6Aw4T5OgkRdIx7rTAAYqQAAeyyiSm7mRlJMY+bQBUMHqMJ+SmqYHjAep6ju6kaYCDkORO7jYG6gkznOICueJy4pt5G5bpwzBBeNCAMNuMAYuFgJXviMi3sSD7WWSz6WNYb40qGioMt4P4sv+7JAVKoG8o0AoFNBopwRKUpIbkKGphAbE7BWdW1QxyIMCVH1Fl9KpqhqWq6ruhrGkwRGWqudXaSxekcflERw9a5HbA9VFHDRLqurx+hMOES0rdOwkgB1UZdZ5Xm9Xt3CGtmdCjcFKLotNKYFqhVO6Wx+mcREja6M2rYdl2PZ9toA6mHDDmOfgkRcJtW0eaNu3xruTA7kwcvjVwoWe8rKaRaM4yTCM8VJXVqXpeI2W5QG-XFfCobzT81owKY-EwHzq2Cyw1uFQAfM5m2i0Fow+cn7g22LqYzmjOZ0DwsKBVG3x1koh7+fQDf5pd3yjqOSemD6k4C+tWcuQVed+u8rmF6GkySCXpjuC5YsBK8+VcEwZ3onHobNxCULDVvXfCKOQA): 
![expectedResult](https://user-images.githubusercontent.com/1825882/93125504-8649d100-f6cb-11ea-9595-0c22c597685b.png)

**Comment by lredor** [comment]
For information, I'm currently analyzing this problem. I want to add some tests. But when I've looked to org.eclipse.elk.alg.common.nodespacing.InsidePortLabelTest as sample, I saw that the sample data is "completed" by the test with "@DefaultConfiguration".
1- It is simpler for me to do a "real" sample data with all configuration in it. Is there some specific/mandatory rules concerning tests?
2- Is it a way to serialize the graph after the org.eclipse.elk.alg.test.framework.ExperimentStatement.createTestGraph() method (to be able to use it manually after)?

**Comment by le-cds** [comment]
Thanks for looking into the issue, much appreciated!

> 1- It is simpler for me to do a "real" sample data with all configuration in it. Is there some specific/mandatory rules concerning tests?

Not at all. The default configuration is just to make life easier by not having to specify labels and element sizes everywhere. If it's easier to not use it, that's fine as well.

There are rules concerning where exactly to place test models in the `elk-models` repository, and including a licence notice in every file, but I bet you're already aware of those. 🙂 

> 2- Is it a way to serialize the graph after the org.eclipse.elk.alg.test.framework.ExperimentStatement.createTestGraph() method (to be able to use it manually after)?

No built-in way. You could always write a custom configuration method to serialize the graph yourself. After all, when the configuration method is called, layout hasn't been applied yet:

```java
@Configurator
public void serializeGraph(final ElkNode graph) {
    //...
}
```

**Comment by lredor** [comment]
Two pull requests have been created for this issue:
* https://github.com/eclipse/elk-models/pull/8: Test data
* https://github.com/eclipse/elk/pull/732: Tests and fix

**Comment by lredor** [comment]
> Two pull requests have been created for this issue:
> 
> * [eclipse/elk-models#8](https://github.com/eclipse/elk-models/pull/8): Test data
> * #732: Tests and fix

Another pull request updates test test data: https://github.com/eclipse/elk-models/pull/9
