### ISSUE TITLE
Box and Rectpacking Layouters may have elements scaled smaller when given more space

### ISSUE THREAD

**Issue by NiklasRentzCAU** [eclipse/elk#709]
When viewing this graph:

```
algorithm: box

node a
node b
node c
node d
node e
node f
```

in the KLighD viewer, depending on the canvas size and with that the goal aspect ratio, the algorithm may rearrange the elements in a way that is worse for using the available space. Both these screenshots are taken with the same diagram, just the widget size was altered to force a different target aspect ratio:

![Screenshot from 2020-09-25 15-05-24](https://user-images.githubusercontent.com/47597619/94271564-1a286200-ff42-11ea-99fd-28f57d52a84a.png)
![Screenshot from 2020-09-25 15-05-29](https://user-images.githubusercontent.com/47597619/94271575-1bf22580-ff42-11ea-8173-c26c71c15e5d.png)

As seen in the second diagram, now all boxes are stacked on top of each other, resulting in a more zoomed-out view. I would expect the layout to fit the boxes into the given aspect ratio with the biggest possible scaling, not this. I would even expect the boxes to be arranged in a 3x2 instead of a 2x3 or even a 1x6 arrangement, as the available space has definitely more width than height.

Same applies for the same graph, just with the algorithm replaces with 'rectpacking':

![Screenshot from 2020-09-25 15-06-17](https://user-images.githubusercontent.com/47597619/94272035-ca966600-ff42-11ea-8038-31667ee42149.png)
![Screenshot from 2020-09-25 15-06-23](https://user-images.githubusercontent.com/47597619/94272038-cbc79300-ff42-11ea-8c49-966d5fa75e75.png)

**Comment by soerendomroes** [comment]
Are you sure that this is not an issue in KlighD?

**Comment by uruuru** [comment]
It somehow feels as if the aspect ratio is inversed. Could you check which desired aspect ratio is passed to the layouter (simply print it to the console, for instance)? If that matches the the aspect ratio of your viewport, it's likely a layouter issue.

**Comment by soerendomroes** [comment]
Both algorithms seem to get the correct aspect ratio (or at least an aspect ratio that is not inverted).
For me the graph 
```
algorithm: rectpacking

node n1

node n2

node n3

node n4

node n5

node n6
```
behaves normally with the rectpacking algorithm.
However, there seems to be a case in which the rectpacking algorithm can place all boxes in the same row and the box algorithm can not.

**Comment by soerendomroes** [comment]
DAR = 3.28
```
algorithm: rectpacking
spacing.nodeNode: 20
elk.padding: "[top=0.0,left=0.0,bottom=0.0,right=0.0]"

node n1
node n2
node n3
node n4
node n5
node n6
```
![Screenshot from 2020-09-28 17-18-21](https://user-images.githubusercontent.com/6419799/94451424-a8088500-01ae-11eb-83db-081a026e626e.png)

```
algorithm: box
spacing.nodeNode: 20
elk.padding: "[top=0.0,left=0.0,bottom=0.0,right=0.0]"

node n1
node n2
node n3
node n4
node n5
node n6
```
![Screenshot from 2020-09-28 17-19-40](https://user-images.githubusercontent.com/6419799/94451630-eaca5d00-01ae-11eb-90d9-cee7eea27f2c.png)

**Comment by soerendomroes** [comment]
Both algorithms do not take the padding into account and how the padding might change the desired aspect ratio.
```
algorithm: rectpacking
spacing.nodeNode: 0
elk.padding: "[top=0.0,left=1000.0,bottom=0.0,right=0.0]"

node n1
node n2
node n3
node n4
node n5
node n6
```
![Screenshot from 2020-09-28 17-25-23](https://user-images.githubusercontent.com/6419799/94452241-9e335180-01af-11eb-8fc9-0ed283589693.png)
```
algorithm: box
spacing.nodeNode: 0
elk.padding: "[top=0.0,left=1000.0,bottom=0.0,right=0.0]"

node n1
node n2
node n3
node n4
node n5
node n6
```
![Screenshot from 2020-09-28 17-26-05](https://user-images.githubusercontent.com/6419799/94452366-b86d2f80-01af-11eb-9a9c-d34ce9475e12.png)
