### ISSUE TITLE
Consider real node sizes in CoffmanGrahamLayerer

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#71]
The layerer computes a layering subject to a bound on the layering's width. Currently this bound refers to the number of nodes in the layer but can be adapted to consider the actual size of the nodes.

**Comment by le-cds** [comment]
@uruuru Any chance this might ever be implemented?

**Comment by uruuru** [comment]
According to a text book the change is supposed to be straight forward. I've never given it much though so far, however. 
It may be a nice task for a student during a practical course, e.g.
