### ISSUE TITLE
Wrong edge "orientation" when adding property "hierarchyHandling: INCLUDE_CHILDREN"

### ISSUE THREAD

**Issue by lredor** [eclipse/elk#714]
Here is an example without "hierarchyHandling: INCLUDE_CHILDREN":
- In [ELK Demonstrators](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUEQHYQE5qkCMaA3kWsxsAEY4hoBEt3jLQdQo4AMu04BnAHQAHTAGMcSHKTjpuAbQASAfQDCAUQByAFUMAlADRoAartMB5AAo2AksYDKbgCKGAutxMLAC+wcyy0HBosjThwpTUAEwM8YKYHFy8SfxpQszklOKZMvLASipqGjoGJubWdg4u7l6+AUH5zGGdMVExcT2RUNGySXkRfbIAzPHdLIRgVLRydAC0AHzUNNKkSXJjggtL27FoG1s7e9PxRxe7K2eby7FEIUA)
- and as image 
![image](https://user-images.githubusercontent.com/1825882/94602759-98b03700-0295-11eb-8511-b0d1c15ca06d.png)
The port on n1 is on the WEST side and it seems OK for me because there are 2 edges from left to right and only 1 edge from right to left.

But if I add "hierarchyHandling: INCLUDE_CHILDREN", the result is:
- In [ELK Demonstrators](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUAjHsFAMYJYASwAdgSDA2OgJIByAwgDIBVACIBRAPo9aHPkIBKIrkSIMIBHGgYBGNAG8iaAxmAAjHCDQAiLRb2G7G1Tj4mzAZwB0AB0yUcSHAxw6BYA2rQSCgAqIrIANGgAamKRAPIACvHcAMocogC6FvqGAL5FBp7QcGiemmUOahoATLp1dpim5laNNq32Bipqzh0e3sC+-oHBYRFc0XGJyemZXDn5hX0GpRvVldW12xVQVZ6NveW7ngDMdVuGhGDqWl7aALQAfBqa7gyNXqd290eXxqaHen2+vyudUB4J+z1BHyeNSIxSAA)
- and as image 
![image](https://user-images.githubusercontent.com/1825882/94602941-d9a84b80-0295-11eb-8515-b2856c30f85c.png)

The port on n1 is now on the EAST side. It seems not logical.
Ulf explains on [gitter](https://gitter.im/eclipse/elk?at=5f7375ef6a6e094525c49cd5) that the graph is imported differently depending on hierarchy handling. Since no side is set for the ports of n2 their side is "guessed". But he is agree that it is confusing to a user. 

Is it possible to have the same result in this kind of situation?

**Comment by uruuru** [comment]
After having a brief look, the port side selection works as you would expect: more incoming edges than outgoing edges yield `WEST` and the other way around for `EAST`.

During layout of the _inner graph_ a dummy node is created for the hierarchical port (the one on the outer border). And it seems as if the introduced dummy edges do not consider the original edge direction: 
```
// non-hierarchical
// inc, out
[] [e_ n1.n2.p1[n_n2] -> 0[n(external_port)_0]]
[] [e_ n1.n2.p2[n_n2] -> 0[n(external_port)_0]]
[] [e_ n1.n2.p3[n_n2] -> 0[n(external_port)_0]]
// hierarchical
[e_ 0[n(external_port)_n1.p1] -> n1.n2.p1[n_n2]] []
[e_ 0[n(external_port)_n1.p1] -> n1.n2.p2[n_n2]] []
[e_ 0[n(external_port)_n1.p1] -> n1.n2.p3[n_n2]] []
```
