### ISSUE TITLE
Is there a way to force all nodes in one column in children

### ISSUE THREAD

**Issue by BjBe82** [eclipse/elk#716]
For example in the following picture the user wants. Struct,TCS, TTC, EPS and AOCS in one column.

![grafik](https://user-images.githubusercontent.com/61700870/95562833-f888a980-0a1c-11eb-80c2-7385305aeb3d.png)

The json model:

[model.zip](https://github.com/eclipse/elk/files/5353619/model.zip)

**Comment by uruuru** [comment]
By row you mean horizontally aligned?

**Comment by BjBe82** [comment]
Sorry i meant column. Struct,TCS, TTC, EPS and AOCS should be vertically aligned (in one column) to look similar to the alignment of the elements in OBC.

**Comment by uruuru** [comment]
Unfortunately that's not possible. The underlying methodology places nodes that are connected by an edge in a way such that they do not overlap in y-coordinates (left-to-right layout).

**Comment by BjBe82** [comment]
Thanks for the information.
