### ISSUE TITLE
[Web site documentation] Wrong links to dependencies

### ISSUE THREAD

**Issue by lredor** [eclipse/elk#718]
The links to dependencies are wrongly generated :
- ".html" is missing at the end of the URL
- lowercase problem

Examples:
- From [Additional Wrapped Edges Spacing](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-wrapping-additionaledgespacing.html) page, the link to org.eclipse.elk.layered.wrapping.strategy is
[https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-wrapping-strategy](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-wrapping-strategy)
instead of [https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-wrapping-strategy **.html**](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-wrapping-strategy.html)
- From [Interactive Reference Point](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-interactivereferencepoint.html) page, the link to dependency org.eclipse.elk.layered.cycleBreaking.strategy is [https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-cycleBreaking-strategy](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-cycleBreaking-strategy) instead of [https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-  **cyclebreaking** -strategy **.html**](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-cyclebreaking-strategy.html)
- From [Semi-Interactive Crossing Minimization](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-crossingminimization-semiinteractive.html) page, the link to org.eclipse.elk.layered.crossingMinimization.strategy is 
[https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-crossingMinimization-strategy](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-crossingMinimization-strategy) instead of [https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered- **crossingminimization** -strategy **.html**](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-crossingminimization-strategy.html)

**Comment by uruuru** [comment]
Thanks for making us aware.

**Comment by le-cds** [comment]
Hugo, our site generator, lower-cases file names by default. I disabled that and fixed the way we generate links to dependecy pages.
