### ISSUE TITLE
Configure and read layout options in Eclipse and non-Eclipse setup

### ISSUE THREAD

**Issue by NiklasRentzCAU** [eclipse/elk#719]
I am looking for a way to configure and read layout options which works in both the default execution of a running Eclipse Platform and also in a plain Java application not using the Eclipse Platform and with that also not using Extension Points.
I got an `ILayoutSetup` configuring some `ILayoutConfigurationStore.Provider` for exactly this use case, using the following code to read the current configuration of a layout option / store a new value for that option (Xtend code):

```
// configure layout options to be used in the next layout runs
val Injector injector = LayoutConnectorsService.instance.getInjector(null, viewContext)
val ILayoutConfigurationStore.Provider layoutConfigStoreProvider = injector.getInstance(ILayoutConfigurationStore.Provider)
val ILayoutConfigurationStore layoutConfigStore =  layoutConfigStoreProvider.get(viewContext.diagramWorkbenchPart, viewContext.viewModel)
for (option : optionsToSet) {
    layoutConfigStore.setOptionValue(option.id, option.value)
}
```
```
// read the current value of some layout options
val Injector injector = LayoutConnectorsService.instance.getInjector(null, viewContext)
val LayoutConfigurationManager layoutConfigManager = injector.getInstance(LayoutConfigurationManager)
val ILayoutConfigurationStore.Provider layoutConfigStoreProvider = injector.getInstance(ILayoutConfigurationStore.Provider)
for (optionId : optionsIdsToView) {
    val optionData = LayoutMetaDataService.instance.getOptionData(optionId)
    val layoutConfigStore = layoutConfigStoreProvider.get(viewContext.diagramWorkbenchPart, viewContext.viewModel)
    val optionValue = layoutConfigManager.getOptionValue(optionData, layoutConfigStore)
    [...]
}
```
This code works as intended in the Eclipse case. In the Plain Java case however, the `LayoutConnectorsService.instance.getInjector(null, theViewContext)` call always returns `null`, because the `LayoutConnectorsService` only loads the layout setups in a running platform and therefore cannot return the injector for the registered layout setup.
Am I using the classes correctly and is this just not yet migrated to non-Eclipse use cases with service loaders or should I try something different instead? The documentation on the website did not help here, as the section for this use case still has a TODO left in it. [https://www.eclipse.org/elk/documentation/tooldevelopers/usingeclipselayout/advancedconfiguration.html](https://www.eclipse.org/elk/documentation/tooldevelopers/usingeclipselayout/advancedconfiguration.html)

**Comment by uruuru** [comment]
You should be able to at least _read_ the information from the `LayoutMetaDataService`. 

I'm not sure if the injector-based stuff is supposed to be working in plain Java, never used it myself.

**Comment by NiklasRentzCAU** [comment]
Yes, I am able to view the meta data `LayoutOptionData` of all layout options for example defined by the `CoreOptions`, but that only contains the default values and no way to configure or read currently used options such as with the `ILayoutConfigurationStore.setOptionValue` or the `LayoutConfigurationManager.getOptionValue` methods, such as they are available in the `LayoutConnectorsService` in the Eclipse case. I could try to manage such a `ILayoutConfigurationStore` and `LayoutConfigurationManager` externally, but this seems as it should belong to ELK directly also in the plain Java case, as that is generally supported (and working very well!) now.

**Comment by le-cds** [comment]
Configuration stores are not the primary ELK way for managing properties. Rather, they solve the problem of having different layout option sources:

1. The diagram source, which might for example be a KLighD diagram synthesis.
1. The layout options view, which gives people a chance to override layout options with custom values.

The second only makes sense if there is, in fact, a way for users to override layout options. So far, the only way to do so was in an Eclipse context with the layout options view.

If this functionality is to be made available in pure Java, we might as well go the whole way and migrate the whole service plug-in. That, however, would be a considerable amount of work...

**Comment by NiklasRentzCAU** [comment]
A third way to override layout options currently is also with the KLighD diagram options view, where some layout options may also be configured. As migrating the whole service plug-in may be a little much for this use case, I will try to look for a way to store and load the options while using Eclipse or plain Java in KLighD itself for now. Thank you for the comments!

**Comment by le-cds** [comment]
Alrighty. I'll flag and close this as a question for now since I don't think de-Eclipse-fying `core.service` is currently a high priority for us.
