### ISSUE TITLE
Unexpected variation in edge-node spacing

### ISSUE THREAD

**Issue by eliasweatherfield** [eclipse/elk#734]
In [this](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=BYSwpgTghhDGwE8ASUB2ATANiVBzAXAAQCSAcgMIAyAqgCICiA+uUsZbQEr2kBQPqAe3RhCqAIw8A3j0KzRQkeKg8AvvwWiATFNXrhogMw658-agPK1PMOlyKxhALQA+LdduLNT1+fd3DAHTmUN6iYkFiUEA) ELK Demonstrators example, there unexpectedly is more horizontal space between the edge and the node on the left (west of node n1) than there is between the node and the edge on the right (east of node n3). The vertical space south of nodes n1 and n3 is different again.

**Comment by uruuru** [comment]
![image](https://user-images.githubusercontent.com/7552459/99989632-22bade80-2db3-11eb-912c-a35c8f2876f2.png)

current master:
![image](https://user-images.githubusercontent.com/7552459/99990247-e340c200-2db3-11eb-9615-0857a4b75af2.png)

**Comment by eliasweatherfield** [comment]
Thank you very much for your quick fix. What about the difference between the horizontal space (west of node n1 and east of node n3) and the vertical space south of nodes n1 and n3? Isn't that also a bug? Thanks again.

**Comment by uruuru** [comment]
In case you are referring to the fact that the horizontal spacing between edge and node is not 0 in the following example, potentially. @le-cds you looked at the code, any immediate idea? 

![image](https://user-images.githubusercontent.com/7552459/102823599-797bfe00-43db-11eb-9a63-7098dd8d6ebc.png)

```
hierarchyHandling: INCLUDE_CHILDREN
spacing.edgeNode: 0
spacing.edgeNodeBetweenLayers: 0

node n1 {
    node n1a
}
node n2 {
}
node n3 {
    node n3a
}

edge n1 -> n2
edge n2 -> n3
edge n3.n3a -> n1.n1a
```

**Comment by eliasweatherfield** [comment]
Thanks for getting back to me. Yes, that might be it. I was referring to the difference in size between the horizontal space indicated by the red arrow and the vertical space indicated by blue arrow: ![99989632-22bade80-2db3-11eb-912c-a35c8f2876f2](https://user-images.githubusercontent.com/52037235/102824050-5b62cd80-43dc-11eb-9344-af1b6667e5a7.png)

**Comment by uruuru** [comment]
Your values are actually different ones and not directly configurable. The inner node (`n3a`) has padding to the border of its surrounding parent. Is is configured like this:
```
node n3 {
    elk.padding: "[top=0.0,left=0.0,bottom=0.0,right=0.0]"
    node n3a 
}
```
Then, from the border of `n3`, the spacing values I mentioned above come into play.

**Comment by eliasweatherfield** [comment]
Yup.

**Comment by eliasweatherfield** [comment]
@le-cds Are you still looking into this? Should I open a new issue?

**Comment by le-cds** [comment]
@eliasweatherfield If you still consider this a problem, please do feel free to open another issue. Having said that, our resources currently are rather limited, so I cannot promise you a quick fix. :/

**Comment by eliasweatherfield** [comment]
Will do. I appreciate all of you hard work, thanks.
