### ISSUE TITLE
UnsupportedGraphException in the ELK live examples

### ISSUE THREAD

**Issue by parnold-x** [eclipse/elk#735]
Hi,
I playing around to solve another layout problem at the moment and getting this error.
It is also thown in the examples
https://rtsys.informatik.uni-kiel.de/elklive/examples.html?e=hierarchy%2FhierarchicalLayoutMixing

Is this a bug or as intended?

**Comment by uruuru** [comment]
Thanks for reporting this. IIRC this happened before and was supposed to be fixed. 

Maybe a regression due to #700? @le-cds?

**Comment by le-cds** [comment]
I'll definitely have to take a look before we publish 0.7.1.

**Comment by uruuru** [comment]
Taking this chance to hint at #673 😬
