### ISSUE TITLE
Hierarchy negatively affects Port Order

### ISSUE THREAD

**Issue by a-sr** [eclipse/elk#741]
In the following example, the fixed port order gets inverted and crossings are introduced. This occurs as soon as a layout for a fresh diagram with expanded nodes is performed.
In other words:

1. Both nodes collapsed -> layout ok\
![collapsed_good](https://user-images.githubusercontent.com/25612037/102997553-b94efc80-4525-11eb-9b32-7184b7717e4d.png)

2. Expanding both nodes -> layout ok\
![expanded_good](https://user-images.githubusercontent.com/25612037/102997588-cc61cc80-4525-11eb-8fed-f34b63461b76.png)

3. Updating the diagram (e.g. adding a space in the source code and saving, hence no change in topology) -> layout with unnecessary crossings\
![expanded_bad](https://user-images.githubusercontent.com/25612037/102997595-cff55380-4525-11eb-9c6b-d2af509be934.png)

4. Collapsing nodes again -> layout still has unnecessary crossings\
![collapsed_bad](https://user-images.githubusercontent.com/25612037/102997611-d8e62500-4525-11eb-90cb-3aea6c19be6b.png)

It seems the layout is able to prevent these crossings but introduces them if the hierarchy is present and no previous layout information is present.

Further information:
- The nodes have a fixed order constraint for ports and the ports have a fixed side.
- I also confirmed that it is not related to Klighd's Incremental Update.

In the [attached zip](https://github.com/eclipse/elk/files/5735285/layout_logs.zip) you can find the debug logs for the four layout runs.

**Comment by a-sr** [comment]
I also tried setting HIERARCHY_HANDLING to INCLUDE_CHILDREN, which should activate HALS if I remember correctly, but it made it even worse.
![expanded_include_children_bad](https://user-images.githubusercontent.com/25612037/102999837-15b41b00-452a-11eb-9659-cbe632189687.png)

**Comment by soerendomroes** [comment]
Have you tried to specify `LayeredOptions:PORT_INDEX`? It seems to be the case that you set the `FIXED_ORDER` as a `portConstraint`, however, that order is not specified.

**Comment by soerendomroes** [comment]
Setting the port constraints to `FREE` and adding `considerModelOrder.strategy: NODES_AND_EDGES` also seems to work.
