### ISSUE TITLE
java.lang.StackOverflowError

### ISSUE THREAD

**Issue by zangchuan1989** [eclipse/elk#742]
The diagram is a little big. The diagram is very long horizontally. The program running elk reports an error
![image](https://user-images.githubusercontent.com/78139064/106112094-ce075b80-6187-11eb-8a00-25b683b2d7da.png)
![image](https://user-images.githubusercontent.com/78139064/106109235-41a76980-6184-11eb-9147-7335b78077d1.png)
![image](https://user-images.githubusercontent.com/78139064/106109286-53890c80-6184-11eb-9cf0-6d0e63b090e6.png)

**Comment by uruuru** [comment]
Thanks for making us aware. A couple of questions that may help to pinpoint the issue: 

Is it possible to reduce the graph and still trigger the issue? 

Does the issue vanish if you increase stack size? 

Is `separateConnectedComponents` set to true or false?

**Comment by zangchuan1989** [comment]
increase stack size is ok
