### ISSUE TITLE
Radial layout only updates innermost radius

### ISSUE THREAD

**Issue by rhpreston** [eclipse/elk#744]
# Radial layout only updates innermost radius

> This issue was originally [submitted to elkjs](https://github.com/kieler/elkjs/issues/120).

## Expected behavior

Per the [ELK documentation](https://www.eclipse.org/elk/reference/algorithms/org-eclipse-elk-radial.html):

> The radial layouter takes a tree and places the nodes in radial order around the root. The nodes of the same tree level are placed on the same radius.

The layout algorithm includes overlap removal (bold added):

> The overlap removal intermediate processor can be started after the node placement. Due to the node sizes it is still not guaranteed that no overlaps occur, because the radius can be chosen too small. The processor starts with the innermost radius and widens it until no more overlaps on the radius occur. **This is repeated for each radius**.

My expectation is that the radius of all layers would be automatically adjusted to prevent overlaps, and that outer radii would always be larger than inner radii. For example, with only 1 layer, the radius expands as more nodes are added.

5 nodes:

![radial-5](https://user-images.githubusercontent.com/56449771/106319962-344fb500-6240-11eb-8f99-aeedabebef6b.png)

10 nodes:

![radial-10](https://user-images.githubusercontent.com/56449771/106319991-3d408680-6240-11eb-80d7-91e084a64675.png)

## Actual behavior

Only the innermost radius is adjusted during overlap removal. This renders the layout unusable with large numbers of nodes and multiple layers.

5 nodes in first layer, 20 nodes in second layer:

![radial-5-4](https://user-images.githubusercontent.com/56449771/106320015-4598c180-6240-11eb-93af-5e0b243a9b8f.png)

15 nodes in first layer, 30 nodes in second layer:

![radial-15-2](https://user-images.githubusercontent.com/56449771/106320027-4b8ea280-6240-11eb-8fc9-59a72c4d933b.png)

## Steps to reproduce

The following code generates elements that clearly show the issue when rendered with the radial algorithm:

```js
var elements = { nodes: [{ data: { id: "root" } }], edges: [] }
for (i = 0; i < 15; i++) {
  elements.nodes.push({ data: { id: `/${i}` }})
  elements.edges.push({ data: { source: "root", target: `/${i}` }})
  for (j = 0; j < 2; j++) {
    elements.nodes.push({ data: { id: `/${i}/${j}` }})
    elements.edges.push({ data: { source: `/${i}`, target: `/${i}/${j}` }})
  }
}
```

## Context

The examples above were created with a single HTML file using [cytoscape-elk](https://github.com/cytoscape/cytoscape.js-elk).

## Ask

Are there settings I'm missing that could fix this? Is it a bug with elkjs? Could it be an issue with the Java kernel? Any help tracking down the source of this problem would be greatly appreciated :v:

**Comment by soerendomroes** [comment]
Nodes that are not children of the root node are only moved if they overlap if a sorter is added. Moreover, such nodes also have to be moved based on the movement of their parent. Neither if this is currently done and will try to look into it.
