### ISSUE TITLE
Can elk set the alignment of some components

### ISSUE THREAD

**Issue by zangchuan1989** [eclipse/elk#746]
This is a sample graph.

![image](https://user-images.githubusercontent.com/78139064/107351130-37cb2200-6b05-11eb-8cbe-d3af28205850.png)

The red boxes in the picture are aligned vertically.

How to set it？

**Comment by le-cds** [comment]
I'm not sure I understand the question. Do you like it this way and want to know how to force the same kind of alignment in other diagrams? Do you not like it this way and are looking for a way to change it?

**Comment by zangchuan1989** [comment]
I want to get a way to align the nodes of the same type vertically

**Comment by le-cds** [comment]
If it just concerns moving those nodes to the left or to the right of the diagram, the [layer constraint](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-layering-layerConstraint.html) option might be what you're looking for.

If you're looking for a more general solution, I'm afraid there is none. What you can try is to turn [partitioning](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-partitioning-activate.html) on and assign the same [partition](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-partitioning-partition.html) to the nodes that should be vertically align, but you'll have to assign partitions to all other nodes as well, which might not be what you want.

Another solution could be to wrap nodes that should be grouped into a subgraph, but that comes with its own layout problems.
