### ISSUE TITLE
elkt format adds support for portSide property

### ISSUE THREAD

**Issue by itviewer** [eclipse/elk#747]
`^port.side: "WEST"`  syntax kooks weird, add  support `portSide: "WEST"`
```
node op_eq_1 {
    port in1 {
        ^port.side: "WEST"  // should renamed to portSide
    }
}
```

**Comment by uruuru** [comment]
The naming of the layout options is generated automatically and consistently for all layout options. 

The caret `^` in this case is (unfortunately) required by the underlying parsing framework as `port` is already a keyword.

**Comment by le-cds** [comment]
Yeah... I do agree that it looks prerty weird (and is surprising to people), but since we have very limited resources these days, I guess we won't be able to do this. :/
