### ISSUE TITLE
Prevent edges from relocating Nodes?

### ISSUE THREAD

**Issue by MaxEngelstaedter** [eclipse/elk#749]
Hi guys,

I'm new to this whole ELK layouting topic, so I've got a quite simple question. How can I prevent the algorithm from relocating my nodes. See [ELK Demo](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=BYSwpgTghhDGwE8ASUB2ATANiVBzAXAAQCSAcgMIAyAqgCICiA+uUsZbQEr2kBQAzgAcosHLgB0YdLjCkA9ujBEADPyEi8EqTPlgAQmAAuAdzBhUlKAkh9lPKJlyyIIA8AC2RTJciSeApwbksqh8BtA4BjaEAGLEABr0tIwA8hwMHDyZqDqEAEYArrAA1oYAjIQA3jyENYSCwqJi2QpyCkSlAKzVtc1gFrlgmHxiAl6wYG5mBkQAREiMlPTRACqEAGqMy8kACoTJ1MsAysQMM901sMEGUwCC2Liok6jThHPM3Mv0HOubO2eZtUIXgGmFeukKJQMhFK-0BvUIUxcCHKVUBgK8CFk+QMAG0+CAAF6KUpKJQAGgATEoALrnNH+CCBYKhcLPKKxBJJY4MAFomrAwavejPJHQ2F8wgMqEQMBQdCoiWAgB6UrE+LahAA6vRDss6YCAL68vlSwhGZzXBWKmoqgJqkAa+g3XX62pGw3GwjwxEGBAUyqu-mWLG4-FE-Ak8lU2mKqVBEJhKARdnxRKMbn0QOELMC0EzYUGUUU8UmgKEGVyq3W22M+0a7UuxVGrOm80uMBVxU1gx1xSEJ2NiXut2e70i30AZgDioxIbxhOJpMpNJbAXjLKTbKIHLTGazOagIKF44QhAnJfpZYr8qzytV6r7Db1Tc9gNbFo7t9q3d7RAHz75YcaiAhEtARE9SjENtrgAWgAPnAwtJzEa8eGbeECmKQx-Srep1HEXpWj7To6UGIoxHQEAZVgQtgiIWhkk1Xg4R0fpBmGUZhAmKZZnmRYVh+LZdn2I4TnoC9czBCFDEIYtRxyH0ECnTtalnbF53DSNlxjCU42ZRNk23VMuTE-cZ0PQV8xPM8LzfK9ZRva1v3vB1Hx1ADANfWp33bFS+R-B8-2dDy0RA5sWIURCkQAFmnCU1NDBcIyXaNV0ZdcDK3GJjPTUzFQPI8rKQ09ots7z7MrL8bRc+t3KzcLdLLaDPyc6q7UC-tgvqukGpqMdio6OK+QSjTFyjFdYzXfTWUiIzOVynkCssgtRQ6MqalNa8-LRALXKIJ9urSqFmu2u92r2zrB08j1m0kaQ8mkgxIMUikoI-Qh4IerCDFexTopQhyeDusAvshZ6TwnN72w+hDMMhX6Tw6AG5UyIA)

I want the Entities to be vertically aligned inside my Bucket. The Buckets themselves should be horizontally aligned. 
How can I achieve this? I used elk.direction: DOWN inside the Buckets but this does not lead to the expected result.

Thanks for your help :)

**Comment by le-cds** [comment]
Placing them vertically would mean placing them in the same _layer_, as we call it. However, nodes in the same layer cannot be connected by an edge. Thus, what you would like to achieve is not easily possible.

If we had an algorithm that only routed edges through a diagram and left the nodes alone, you could place the nodes to your liking (which, as you describe it, seems straightforward) and have ELK concentrate only on the edges. However, that's not something we support yet, sorry. See #315.

**Comment by Dignitas** [comment]
Hi le-cds,

thanks for your quick reply. Is there any other way of maintaining the vertical alignment of the Entities in the Bucket, e.g. with some extra Ports/Nodes/Edges which I might hide afterwards, even if it's not straight forward?

Regards 

Dignitas

**Comment by soerendomroes** [comment]
I am unsure what exact layout you are desiring. You can always exclude so called [in-layer edges from the layout](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=BYSwpgTghhDGwE8ASUB2ATANiVBzAXAAQCSAcgMIAyAqgCICiA+uUsZbQEr2kBQAzgAcosHLgB0YdLjCkA9ujBEADPyEi8EqTPlgAQmAAuAdzBhUlKAkh9lPKJlyyIIA8AC2RTJciSeApwbksqh8BtA4BjaEAGLEABr0tIwA8hwMHDyZqDqEAEYArrAA1oYAjIQA3jyENYSCwqJi2QpyCkSlAKzVtc1gFrlgmHxiAl6wYG5mBkQAREiMlPTRACqEAGqMy8kACoTJ1MsAysQMM901sMEGUwCC2Liok6jThHPM3Mv0HOubO2eZtUIXgGmFeukKJQMhFK-0BvUIUxcCHKVUBgK8CFk+QMAG0+CAAF6KUpKJQAGgATEoALrnNH+CCBYKhcLPKKxBJJY4MAFomrAwavejPJHQ2F8wgMqEQMBQdCoiWAgB6UrE+LahAA6vRDss6YCAL68vlSwhGZzXBWKmoqgJqkAa+g3XX62pGw3GwjwxEGBAUyqu-mWLG4-FE-Ak8lU2mKqVBEJhKARdnxRKMbn0QOELMC0EzYUGUUU8UmgKEGVyq3W22M+0a7UuxVGrOm80uMBVxU1gx1xSEJ2NiXut2e70i30AZgDioxIbxhOJpMpNJbAXjLKTbKIHLTGazOagIKF44QhAnJfpZYr8qzytV6r7Db1Tc9gNbFo7t9q3d7RAHz75YcaiAhEtARE9SjENtrgAWgAPnAwtJzEa9pwlbILExbEiDCfIwDpI1m3hApikMf0q3qdRxF6Vo+06OlBiKMR0BAGVYELYIiFoZJNV4OEdH6QZhlGYQJimWZ5kWFYfi2XZ9iOE56AvXMwQhQxCGLUcch9BAp07WpZ2xedw0jZcYwlONmUTZNt1TLlFP3GdD0FfMTzPC83yvWUb2tb97wdR8dQAwDX1qd9230vkfwfP9nWCtEQObfiFEQpEABY0L5QzQwXCMl2jVdGXXaytxiOz0wcxUDyPVykNPNKPLCrzKy-G1-PrIKsySiyy2gz9fLau0Yv7OKuoIrSUp0jpMrRbLjMXKMV1jNcrNZSJbM5CqeWqlyC1FDpGpqU1r0itFooCognzGwqoT6067yGi6RsHEKPWbSRpDyNSDEgnSKSgj9CHgr7SIMf6dLSlDvJ4D6wBByFfpPCcAfbIGEJIyFwZPDooblTIgA) if that is what you need. Then you could route the edge yourself.


![Screenshot from 2022-04-05 09-05-53](https://user-images.githubusercontent.com/6419799/161697809-4edf1e1e-357d-4013-876a-c6094c408e29.png)
