### ISSUE TITLE
Get rid of persistent entries

### ISSUE THREAD

**Issue by le-cds** [eclipse/elk#75]
The `EMapPropertyHolder` class currently distinguishes between properties and persistent entries. Properties are not serialized, persistent entries are. Before a graph is serialized, properties have to be turned into persistent entries. After a graph has been loaded, persistent entries have to be turned into properties. This seems unnecessary. Also, try to explain that to clients...

Check if we can get rid of persistent entries by properly including properties into the serialization and deserialization process.

**Comment by spoenemann** [comment]
It would be wonderful to get rid of the persistent entries. EMF offers ways to customize the serialization and parsing. Serializing won't be hards since we always use `toString()` for that. The much harder problem is parsing: we need to load the meta data in order for that to work.

**Comment by le-cds** [comment]
True, that. In general, we have meta data available, even in pure Java applications. We even [have documentation available](https://github.com/eclipse/elk/wiki/Using-Plain-Java-Layout#the-layout-meta-data-service) that tells people what to do in order to get meta data to work then. So the meta data itself is not the problem.

The problem we do have is that the graph does not have access to the meta data service because it is not part of the core plug-in, where the meta data service is defined. As I see it, there are two options:

1. Introduce an indirection, a bit like how `core.service` automatically registers meta data providers. Here, the core plug-in would register itself programmatically with the graph plug-in as "the thing which can turn strings into property instances".
1. Move the graph into the core plug-in to give it access to the meta data provider.

I'm not a big fan of either option: the first one seems like an over-engineered hack, while the second one sacrifices having the basic data structure isolated from everything else. Having said that, and given that the ELK Graph is only meant to be used with ELK (especially since we have now killed the built-in possibilities to attach miscellaneous data to its elements), the second solution seems to me to be the way to go.

Any thoughts?

**Comment by spoenemann** [comment]
I'm fine with 2.

That would mean changing the package name of ElkGraph to `org.eclipse.elk.core.graph`, right?

**Comment by le-cds** [comment]
Yes, the package would have to be renamed. A simple mass-search-and-replace should be the only thing required to migrate the rest of ELK, plus removing the old graph plug-in from the dependencies of other plug-ins.

**Comment by spoenemann** [comment]
Another option:

 3. Keep the graph data structure in elk.graph, but define the custom parser and serializer in elk.core. As far as I understood, this would be done by subclassing `XMIResourceImpl`.
