### ISSUE TITLE
CENTER value has no effect for property org.eclipse.elk.portAlignment when the port is larger than the node

### ISSUE THREAD

**Issue by lredor** [eclipse/elk#751]
As explain in [gitter](https://gitter.im/eclipse/elk?at=6053878ff07ffa1eb54d62c7), it seems that when the port is larger than the node, the `CENTER` value for `org.eclipse.elk.portAlignment` property has no effect on the port.
[Here](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUAHYQAy2EArnOgGagDOORpEBOaJAjGgN5EAkCMxYacNAG1hIoQAcITeDAgl0PAAwAaNFtkjlALxzoArDrQWDAXQOKocAMJqmcKMBgk4TdADEASQANAFEAEQB9AGUAsJCDMk4omBMAOgBjV3dPb180ACIpG3yDaDBUnHSQGHkWCpAAa1SHOABBarASJBxvVKYJBHQnEIA5ABUQgCV7aEkABQAWAQMhMQlpFYUlFTV0AFotXQWAJk3jUzQFy2PNFbs5ITKKqpq6nEbUgD0W1IAjaE4UAA8vR6Cw6Gg9gAOVK3B5PSrVWo4epNb6zPowTjoKJAgCqYwAEgYAL6yMnsTjcY7LORrWgbB6KZRwVTqPSaSz6B7ncyWaxye4iFouEhuDxeHz+YLhaKxeJyRI4ZJpTJi7KSvKFYqlKDlRGvFHvJotdowTrdXr9WiDNDDcZTGaONCLWl0qgMmQPLYstn7Q6XU7e3loADs1zhgpWCJeyNRXx+-yggJBYJwEOhsOjeueSLeH3Rjkx2LQuIJxLkZJEZKAA) is an example corresponding to this image:
![image](https://user-images.githubusercontent.com/1825882/111766709-23b5d580-88a6-11eb-94c2-43232db4e82e.png)
* The first node is OK: the port is centered.
* The second node is KO: the port is not centered.

**Comment by soerendomroes** [comment]
As I understand it the `nodeSize.options: PORTS_OVERHANG` should solve this issue, as seen [here](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUAHYQAy2EArnOgGagDOORpEBOaJAjGgN5E0wkZiw04aANpCRcgA4Qm8GBBLoeABgA0aLbLnDlALxzoArDrSWDIgLq3hiqHADCapnCjAYJOE3QAMQBJAA0AUQARAH0AZWDI8MduDhxYmFMAOgBjDy8fPwC0ACIpO2Lk6DBMnGyQGHkWGpAAa0znOABBerASJBw-TKYJBHRXcIA5ABVwgCVkjrQABQAWAWThMQlpDZETMzQVqwAmTV2HQxEqmrqGppxWzIA9DsyAI2hOKAB5enoWOhoAC0AA5MmdLsJrrV6o0cM02i9oHAhjBOOhYt8AKpTAASyQAvrYiexONxjutLltaDtIWhFMo4Kp1HpNFZ9HT9hYrDZLhdDB13CRPN5fP4gmEonEEklLmROOksrlhfkxUVSuVKlBqjC7vCHm0Ot0YL1+oNhrRRmhxtM5sl5WkMvCIPImR50EtvrMprFot8AGpzXGdCYAcWSC2RyzWgjp1MkMjpRid6AA7CdNGhzrtdtDbnCEc9Xh8oF9fv8cIDQeDc9qbrD7o8kS5Uei0JicfjLkS5ESgA).
