### ISSUE TITLE
Bump Guava version to 21.0

### ISSUE THREAD

**Issue by j-barata** [eclipse/elk#757]
Several classes are using `com.google.common.collect.Streams`, e.g :
- plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/PartitionPreprocessor.java
- plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p5edges/orthogonal/HyperEdgeSegmentSplitter.java
- and many other test classes in test/org.eclipse.elk.alg.layered.test

The `com.google.common.collect.Streams` class was added in version 21.0 (see [javadoc](https://www.javadoc.io/doc/com.google.guava/guava/21.0/com/google/common/collect/Streams.html)), but in ELK plugins the requirements for this dependency have been set to `[15.0,19.0)` in several `pom.xml` files.

It might be the cause of this exception :

> Caused by: java.lang.NoClassDefFoundError: com/google/common/collect/Streams
>	at org.eclipse.elk.alg.layered.p5edges.orthogonal.HyperEdgeSegmentSplitter.findFreeAreas(HyperEdgeSegmentSplitter.java:86) ~[org.eclipse.elk.alg.layered-0.7.1.jar:na]
>	at org.eclipse.elk.alg.layered.p5edges.orthogonal.HyperEdgeSegmentSplitter.splitSegments(HyperEdgeSegmentSplitter.java:58) ~[org.eclipse.elk.alg.layered-0.7.1.jar:na]
>	at org.eclipse.elk.alg.layered.p5edges.orthogonal.OrthogonalRoutingGenerator.breakCriticalCycles(OrthogonalRoutingGenerator.java:459) ~[org.eclipse.elk.alg.layered-0.7.1.jar:na]
>	at org.eclipse.elk.alg.layered.p5edges.orthogonal.OrthogonalRoutingGenerator.routeEdges(OrthogonalRoutingGenerator.java:199) ~[org.eclipse.elk.alg.layered-0.7.1.jar:na]
>	at org.eclipse.elk.alg.layered.p5edges.OrthogonalEdgeRouter.process(OrthogonalEdgeRouter.java:252) ~[org.eclipse.elk.alg.layered-0.7.1.jar:na]
>	at org.eclipse.elk.alg.layered.p5edges.OrthogonalEdgeRouter.process(OrthogonalEdgeRouter.java:1) ~[org.eclipse.elk.alg.layered-0.7.1.jar:na]
>	at org.eclipse.elk.alg.layered.ElkLayered.hierarchicalLayout(ElkLayered.java:252) ~[org.eclipse.elk.alg.layered-0.7.1.jar:na]
>	at org.eclipse.elk.alg.layered.ElkLayered.doCompoundLayout(ElkLayered.java:185) ~[org.eclipse.elk.alg.layered-0.7.1.jar:na]
>	at org.eclipse.elk.alg.layered.LayeredLayoutProvider.layout(LayeredLayoutProvider.java:53) ~[org.eclipse.elk.alg.layered-0.7.1.jar:na]
>	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.executeAlgorithm(RecursiveGraphLayoutEngine.java:250) ~[org.eclipse.elk.core-0.7.1.jar:na]
>	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:218) ~[org.eclipse.elk.core-0.7.1.jar:na]
>	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:96) ~[org.eclipse.elk.core-0.7.1.jar:na]
>	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:72) ~[org.eclipse.elk.core-0.7.1.jar:na]

**Comment by uruuru** [comment]
Note: Minimum versions were supposed to be removed as part of #720. I could imagine that it was only applied to `MANIFEST.MF`s and `pom.xml`s were forgotten.

**Comment by j-barata** [comment]
Actually, I was wondering about the maximum version requirement "guava version < 19.0" implied by the `...,19.0)` setting.

Shouldn't it be either removed or upgraded to `...,21.0]` or `...,22.0)` ?

**Comment by uruuru** [comment]
Yes, at least your `Streams` example strongly suggests this. 

Following the argumentation of #720 (i.e. we do not have the time to properly maintain minimum/maximum versions), I'd suggest to omit the maximum as well. @le-cds?

**Comment by mazu-rok** [comment]
Do you have some workaround to solve this problem?
