### ISSUE TITLE
How to prevent Node centering when edge added?

### ISSUE THREAD

**Issue by omygoodness** [eclipse/elk#787]
Hi,
quick question here. Is there a way to prevent nodes centering after adding edge to it?
I am using elkjs 0.7.1. 

Without edge, everything is aligned to left and this is expected behavior:
![without_edge](https://user-images.githubusercontent.com/5578597/149676503-fbaccc23-5976-4a57-9b59-40fd9187f75e.png)

But when I add edge node is centering itself:
![with_edge](https://user-images.githubusercontent.com/5578597/149676542-f9be1ee8-cac2-4420-a6b8-7f3a9cdea234.png)

[ELK demo page](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGBECWAmkC4oCcD2qAukA04oBsBDAT1QFcMB5ABw2lQDsBnRMUCCSAU3wGsA6QvgDmqZNAwALALatIRYl2Rd4uDlB4DY0ZQGM6jOQCUAkgHEAEgBUceTpv4rhXI+ToNhcgAqUAMgE1fEwA5AFFbdW4+fiZqQl1oD0dYZ2DUWC45ADYABgiOKIEFJRV+BnSuLyJdLmkuBgwYjGRCDC5hYjkAZRMAWS9fcLUCh2LlWH465GdQlK4WJEhmskzh+2ix0vKMqvja+saAM0IANzEu5sJoYUkMWecFqGXVuw1o2PjE4TKKtIzsvJrN5FEglCYfBJJbZcP5cABCXAwAHcuPVfKDkI9IABGQGvQr8TYTaG7Gp1Br8ABGAkO0AAHioAIL4a4MclYRZwxm+RnBADCoQAIvl1iDFON+Lo0EwmF9eoloNJoAAvVr0BgxWrQEwNJTxOgnTKLY74JgvSIOSTQPXIXSSYgWQgMWAsjxyEJ83wAVUFoQA+nyLCZfIKjKFgiLgfw4sg6AYGF9BPpoCdWkansgVpGCXFYNo3YsANoYVDUAC8AFYcth8FxDhgywAmauUzAl6SV6viG4N5sAXWzowxpTGiaYlzaHTkYSsAHVKEYANJ+nr9QYADUgeAAvsNIHboPhYMoGKxC692OooHA5ABOWDYgDslMIAGZHwBaW+3gAcFY-AAsj5ZK+H6EI2P6gQBt5cK+sCHBWr7xIcWSRpwChuDQ8aPJeV5RhCibQrCcjNmhIwbMO4JxJC3xERUCLIqiDDouKWIAXieGioSlGTEoMxzFizxkVxRIxNRiYvmaABqQhZkguLVq8FrRE4LhuF8cgLlYFiUGYlDBNywlRqJJLVPsFLHGcyAXC01y3Pc8xyEJQLKWKYI-DsZnslSNL0kyLLCGyBxyFyPL8kKRk5oQeYaUWJblq+1a1vWZaJdgrYYO2qVdnZDaJQOLlgLuSlQAeR4nmeJUQLhnEwPAiyEFkjaEFwt66IQH6vj+P6wIBlI5NiX4Vo2WQfo+hC3ocj5-r+OQAT+RmcMIaBkNQJj1VA2LYotUBmsmjDrXeD7Pm+n7fn+gHAaB4GQYBMFwQhSG6ChO2QNQqCyvGrAMGQ+D4IVkTjoQsZfMRSAmmaAMFG4oigxU62POenFXpAE2Utir5cLoo05JSFa9QBAGNR+P66NijZfgB7547olIjdihw7ZwLXjY+XAVp+WQAVkXCATkiUfpS026IBWSPhW2OwI2jawABjNQ5EOSPkhjaHABlIfo2lK6P+AE1P+eOHINIHqzk+OEDkzaoQrBSwLeyuvti6MfnbTt3bLgvq6Bj5y6rj7HIQVbwFVHB9jbkCHOgGDlG0CNnmHIecEicBSKwVMAeHkhcLlrCvgB2LhwAJBYafdeHdK54pyOcJ0SCJSHxXIzVeF1XIaMY1jON4wTROjaT5OU9TEt01kDOvct5BrRtOLbeHe3xodiz3k+L7vl+v661dYEQVB93wYhyHW4nUDvZ96rfb9-3H5AQMgx4YNgBDXDhzDqBwxkcdIEj1ecD+XBc9iCsP5Pz+2xn1YaYEYK8wrN+MmKhKQoS4I2LcP8E4-3kIQSkPBEbH2qrggoN5Fiz3wZwNodIOSbSZkVY+aDq4RyjjHLgn8wCFlocjSAydYCpyQI2CsGdr5ZxzkgCsFZw6JAYEoeORcS5IGglXOhFckAgXkew2uYBGy3hyPwcWDcobNxRoQqALNCBsw5h+LmPM+YCyFqTUW4tJbS1lvLa+E9VqL02sQ9B891TuMgMvE6a9zqbxAtvW60FYL7yei9cOp8JDnyQD9P6c8MDA3cMIB+T8X4UFhvfeGsAcE-04PbACqsfwyw-LocJgEMYa1vK+LIo1GzASyBzSkQtCbmkKZASkAF2Y5C4MBF295RolN0D+QWuJeqNjJrjbEhB5qECdig6ubDaqR0wIw5hrDw6cO4eov8mds49lYEAsRDAJHICkdfYuadbyNnLicrm4c1EY2xNoisuiQ76MiIYyASsVZqw1lrHWgF9aCwrEbcxed+rm0tjkI+6DXFTzkFtV63iDrT38avM6G9LohJurvCJj1D6vViV9BJl9kmpPfumTJ19X40q2fgyAj4BqwAmsAj82JCYjMOFjMCZsKZZHZT+bmr5Di6Dmo+ZZyNVkt3WdHTATD8lXPQbsyQucfxZEOUIsApzr7iMkV-OVKMbmyNvPw9Bii9VPOvmoxC7zPlNwNdPO2DsnaDVdhraCHsemUm9r7KaAcg7jxWsiohni6HooYL4rFp114XSAvined0iUH2egiuhZL4lgESVfLxKS77pIqKwOl6CGW5I-iqr+zLR6HDVvU3mj5ZqARTbeFpvNR4+1fBWMWf9AEys4iayICrNnVpYcOgo6rc62vQYI45SiC4GvOUaid0jbnauvta3tlq6FqObLeR1yNtwlRNdwASlVnXoN+Y1ZqrV2qdW6gTfqg1bzDVGuNSa00YE-jmj+AAxO3TGYDcb40Ar3EmZMKYWqHrTemzivHkFtI5GthSjFNRam1DqXUep9QGkNEaY0JpTRmr++ag68KTtIcDZwGACldKA53D8oGe7E37tBqmz5h7wYo1eSdjdOLfIIdPW9mGH04effht9hHP0kZ-X+wDAyTHs05tzXm7FrHCzsRLYVji5ZoqQzUej6DRP3uw0+vDr731Ea-aRv9vH1BUaeDRxExm6HGNMapyxGmciCy09zexumZb6ZoVDATeEhOcBvRhszj7cOmyszJ4j37ZrzX-f88CgLNba11mCw2xtoVm3ZXCzN7CmCGZQyw5lpmsNxck4lj9yW7PkdC9fQttG3PsIy6rdW2WQV63ZuCyFJsYXFatg50OYW9EurbjF2rEnLMEca7Z+TaW3Wvkds7L17sAKe39WNQN-tCCBxyKoa+5WyDIc67VGr4mLMJaWzZuTqWFqtfQe11zl6unrc25628bsfW7b9QGw4ftg2nYmxAPsDdT2FUgGasA81N0t2tc2OHLyyn8FESVDhKcNVIFmnD+dtw04DVeOFtgOPfl1h-IHT9oLTuXQZiTV8qtzE9OAroLnk1YCUjIhg0gFAsLqhwiHAkBEoS-BLYsUiUMCSiQl7RKXGQGIojRBiNiHFapDnFKUKY-EHhOUzJ0luOv3KK6pIQaSsl0wKTlw4GMcZ1SJkd3EwwSAVEowcKpVwFBYpQC0jpPSBlfCRTNxKUyexvKWXOJcXKDlBLG7DxRXXxIKiknMo0ak-BaQMlgMyVk7IQrcl5AKYU9voi5nzJ4OKpZso1jrHlFsbZUAdjSt2W42UCpi-D6UKUH1ZQeHlAmJUqp4yaiVDqNoLRkyGiN1mCvbkJSjiSOOFok41GQBnPOJcK4+gDFCJuEqFPOBlWPPUL7EWZuLD-gAoBICJUjLxhTCaqIPwwLatieBiDkHhyRb48mNFLGBeaeGnOnCaBnAmR8ZnSCNnLIDnLILnXQHnPnGJD6N3U8ClJJc7QtNJDJIQSGelbJN+StZVa7FuXQCCeZAaXzL-MBACERUaTROmD8KaGWXnb8IWfpKhSAMpeCGWCBLgeadTMZT8UmWAT8d8XQB8eaJCeaYOVBcOUdJVLZJzXHLhfHRHPOHVBdMAXIZHOhBHKsT3FHSuZ5SuJ1QTa-UqKg9iXELlJjBg3tL8XGCmNgvMSkTg1lE3Wqf-aeQAueYAnxUAw4WnDmCAvWRnICGA1nQ4dnJNJAlA0ldA8lXNSlHA6lUg0tAg5+IgjAHJYtKtcglGYpUpcpSpGCapV8WpepRpZpVpdpXpSHMANQ5Q2OcdbZa+adHhPhHQknYRbHa9FdS5Y1ddYRS2B5YRWdPdVgEaH8Swq-a9aePg0HWAQQ4Q0FTlcQyQx8aQ7lSCeZHqUNSeAA3-c7IIjFOQMA8I28SApnOI2AuI+AhI7nQ4XnZIs+d3NI7AgtTIwo2lHIrJfIkg-4plNDbpXpKsAZUaO2WAEZaZcZdGRnaZXEdGQ4xZPnN7OhNosg1VOhbo9RXogRI5fovVQYuhQ1EYtda5GRPVOaSYm1XdVRXOKmGHSjOHVSYoyLa8ZY-+fOe-MaR-cBF-KBd-WBL-XnH-f9Sg2nOw2gxwxglwlg9wjg28LgnwluC7K7S-OhW-fkzlUBJ-CBV-aBcU7-HmZBLE9hD7OjHU9hGU6g+wugkZRU5gtwx8dgzwtU7w5o6HY9abJYuQPUwBA0oU9WY00Uj-OBSUi0-9FYgQimIQv+TYsQ6QnYvY2Qw4s7RDS7IzO02qYMgUw04UyBN-KMiUhBC0308OG04oyIeMtYxMjYvWLYtMzqXYmQg4+Q6stkvjOHBHaCH8OHa1LaJWfgJdFue1EwqAAk0VIcnHYnChBpLIcnPAWhc9Q3VDDgfRVuBqNUjuEDbucDNjKDQeLjODOtOMvkkMh-eg5-Us00z-c0pBfnLUvMrcluRjQ8sDQmE8geGDc8keMeWHHHWs-M3+a8ossM+8k0sUp8mMl8kC9QE9KHPcAc0VPca1eRSANRbCgk7Ee2CsccvcRc1gZpEAbcIAA)

I checked all the `layoutOptions` I am using but nothing is causing such behavior so I guess there is some default option for that.
Any help would be appreciated. Thank you.

**Comment by soerendomroes** [comment]
Hi, you can send the alignment of a node:

```
"layoutOptions":  {
    "elk.alignment": "RIGHT",
},
```
https://www.eclipse.org/elk/reference/options/org-eclipse-elk-alignment.html

**Comment by omygoodness** [comment]
@soerendomroes Thank you. Exactly what I was looking for. I didn't think about using `layoutOptions` directly on nodes.
