### ISSUE TITLE
Proper handling of self-loop (labels)

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#79]
Labels on self loops are not handled properly. Depending on the edge style the problem is different:

`ORTHOGONAL`:  The labels of self-loops are not positioned correctly. Subsequent layout runs result in a _walking_ label. It looks like some offset is applied over and over again. 

`POLYLINE`: Self-loops are not positioned at all, existing routes are not cleared. With subsequent layouts this may result in self-loops scattered all over the place. 

A graph for testing: 

```
properties :
    org.eclipse.elk.edgeRouting = POLYLINE

knode n1 {
    kedge (->n1) {
        klabel "litr, sed diam nonumy eirmod tempor invidunt u"
    }
}
```

**Comment by uruuru** [comment]
After the latest elk changes the label does not walk anymore in the orthogonal case. @le-cds do you know labels of self loops are supposed to be handled during orthogonal routing?

**Comment by le-cds** [comment]
Well, at least there was a time when they were supposed to, yes. I implemented code to that effect as part of my diploma thesis back in the day. I will look at this issue once I get to edge labels, which I want to take a look at anyway at some point. If the issue hasn't been solved already until then.
