### ISSUE TITLE
[URGENT] Nightly build is broken

### ISSUE THREAD

**Issue by spoenemann** [eclipse/elk#798]
The nightly build is broken, the last successful build was September 9, 2021.: https://ci.eclipse.org/elk/job/IntegrationNightly/

It fails running `eclipse-jarsigner-plugin`:
```
[ERROR] Failed to execute goal org.eclipse.cbi.maven.plugins:eclipse-jarsigner-plugin:1.1.5:sign (sign) on project org.eclipse.elk.graph:
[Wed Mar 09 03:17:46 UTC 2022] Unable to sign jar '/home/jenkins/agent/workspace/IntegrationNightly/elk/plugins/org.eclipse.elk.graph/target/org.eclipse.elk.graph-0.8.0-SNAPSHOT.jar':
No route to host
```

*Edit:* I first looked at the gpg configuration in the Jenkinsfile, but AFAICT that's just to create signatures for Maven publishing, while the `eclipse-jarsigner-plugin` is about JAR signing by Eclipse.

Who has some knowledge of the Jenkins configuration and is able to fix this?

**Comment by spoenemann** [comment]
As I'm not sure who is responsible for this problem, I additionally created a Help Desk issue:
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/974

**Comment by spoenemann** [comment]
Fixed with Frederic's help.

**Comment by soerendomroes** [comment]
Does anyone get a notification if the build fails?

**Comment by spoenemann** [comment]
Doesn't seem so.
