### ISSUE TITLE
Port anchor behaves unexpectedly

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#81]
The port anchor option as set below does not behave as expected. While the `y` offset of `-10` is properly applied, the `x` offset is ignored. 
The issue originates from the `PortSideProcessor#setPortSide(port)` method, which overwrites any previously set `x` coordinate of the port anchor. 

```
knode n1 {
    kedge (-> n3:p)
}
knode n3 {
    kport p {
        properties: 
            org.eclipse.elk.port.^anchor = "20, -10 " 
        size: width=50 height=50
    }
}
```

**Comment by le-cds** [comment]
I changed the behavior (see the commit message for details). However, I do see that people might want to apply only the y component of the port anchor if the port ends up east or west, and only the x component if the port ends up north or south. Before implementing this, I'd like to know that there actually is someone who wants that. If so, we should simply replace the _fixed port anchor_ flag with an enumeration value that configures not _if_ the port anchor may be modified by the algorithm, but _the extent_ to which it may be.
