### ISSUE TITLE
Feature request: simulation controls to avoid edge overlap in force layout

### ISSUE THREAD

**Issue by timothypratley** [eclipse/elk#811]
One potential control would be overriding the force or charge for nodes and edges

```
graph root
algorithm: force
node n1 {
    layout [ size: 30, 30 ]
    repulsion: 1000
}
node n2 {
    layout [ size: 30, 30 ]
}
node n3 {
    layout [ size: 30, 30 ]
}
edge e1: n1 -> n2 {
}
edge e2: n2 -> n3 {
}
```
![repusion-on-node](https://user-images.githubusercontent.com/49298/159559620-e99d61bb-d379-4fbc-8bf4-b52b14bd1d76.png)

Potential feature: when repulsion is applied to a node (or some similar property) one can make that node more or less repulsive than other nodes. Annotation in red indicating I'd like to push `n1` further away.

Relates to #806 in that it would be nice to be able to do this for edge bendPoints.

Motivation:

The ability to more nicely distribute edges. Here is an example of a layout I made in D3 which allows me to set the force per particle. Each edge can thus be constructed with an intermediate force point of lesser power than nodes. D3 additionally allows one to specify a desirable distance for the edge, which is even more useful (see that visually I am able to make the red line double the length of blue lines, allowing me to spatially represent a negative relationship).

Figure 1: My existing D3 force layout with intermediate nodes, gravity, and distance

![d3-force](https://user-images.githubusercontent.com/49298/159562636-3fd4b95b-dd99-4272-b306-44d1de52d673.png)

By specifying simulation controls I am able to put certain nodes far from each other, edges do not overlap each other or nodes except when unavoidable, and the curves for edges are relatively shallow.

The technique of adding intermediate nodes can be employed in ELK, but the lack of control over the repulsive power causes a more "messy" outcome (see Example 2 below).

Example 2: intermediate nodes on edges [elkt demonstrator](http://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=OYJwhgDgFgBCD28AuAoMAbY8QEslQFsAuGAM2wGMBTFPK8JHeAOwGcSAmABh5WfgAmVGMwCMMAN4oAkOjABPeAFckMANoxWOAF5USAZi4AaGIZgBdFAF8+g4WOYdJMuYpXrNOvTFEnRlm34hEScpWQVlVQ0tXQNjUy4La1tgx2Z9Z3C3KM9Ynz8AlPsMqRgymFdIjxjvQxMzQqoBYGEqUVESMRgAWgA+EVFHFCaWmDaOTsGnPpDh5taOCZCe-rT9OdGqDn1OjnSVkX0gA)

```
graph root
algorithm: force
iterations: 2000
node n1 {
	layout [ size: 30, 30 ]
}
node n1n2 {
	layout [ size: 1, 1]
}
node n2 {
	layout [ size: 30, 30 ]
}
node n2n3 {
	layout [ size: 1, 1]
}
node n3 {
    layout [ size: 30, 30 ]
}
edge e11: n1 -> n1n2
edge e12: n1n2 -> n2
edge e22: n2 -> n2n3
edge e23: n2n3 -> n3
```
![elk-force](https://user-images.githubusercontent.com/49298/159561490-94881ae6-d326-48ef-ac72-7a15a2cd8491.png)

Note that the layout is susceptible to the number of iterations (iterations: 10000+ seem pretty stable, but the default number 300 produces poor edge layouts).

`repulsivePower` currently behaves equivalent to the "edge distance" in that setting it does result in the edge being longer, but as described in #806 it does not create particles. If `repulsivePower` did create `bendPoints`, it would be useful to allow repulsion to be configured such that a different sized force is applied).

Example 3: ELK's `repulsivePower` can "sort of" be currently be used to control edge distance [elkt demonstrator](http://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=OYJwhgDgFgBCD28AuAoMAbY8QEslQFsAuGAM2wGMBTFPK8JHeAOwGcSAmABh65WfgATKjGYBGGAG8UASHRgAnvACuSGAG0YrHAC8qJAMxcANDCMwAuigC+-ISPHMOU2fKWqNW3fphjTYq1sBYVEOcRc5RRU1TW09Ej9fQLsQpwi3aM84nyNTc2TghzCDdKiPWO8E-wL7URLpGEaYDPKveLMTDssbFCpBYBEqMTEScIBaAD5RMTTpGRAqCGV0bQA3KgAFeAB3ek4evoGYIY4OUZnnSdCIhaWVnHWt3ZB920PB05Hrq6dwudvlmtNjs9jAOAd+h9hqMwhIfhJ-otAQ9gc9Xr1IcdTgYYTAfsUMUcqBwDDjQswSj8DCggA)

```
graph root
algorithm: force
iterations: 20000
node n1 {
	layout [ size: 30, 30 ]
}
node n1n2 {
	layout [ size: 1, 1]
}
node n2n1 {
	layout [ size: 1, 1]
}
node n2 {
	layout [ size: 30, 30 ]
}
node n2n3 {
	layout [ size: 1, 1]
}
node n3 {
    layout [ size: 30, 30 ]
}
edge e11: n1 -> n1n2 {
	repulsivePower: 2
}
edge e122: n1n2 -> n2 {
	repulsivePower: 2
}
edge e221: n2 -> n2n1 {
	repulsivePower: 2
}
edge e211: n2n1 -> n1 {
	repulsivePower: 2
}
edge e223: n2 -> n2n3
edge e233: n2n3 -> n3
```

This simple example results in a *very* unstable layout... it changes dramatically for different iteration counts and does not appear to ever stabilize no matter how many iterations are taken.

![unstable-repulsion](https://user-images.githubusercontent.com/49298/159565763-d3e5e29b-0b86-4a7c-9911-464647900251.png)

Note that specifying `model: EADES` does result in a stable (but messy) layout:

![eades](https://user-images.githubusercontent.com/49298/159567619-959aef63-5c1c-4ee2-b083-2e11836bbb06.png)

The "edge nodes" for the dual linked nodes are distributed too widely, and the single linked "edge node" underlaps another edge node for no apparent reason... it should have been pushed to the opposite side (this may have been prevented by initial conditions).

Some layouts do stabilize:

![intermediate-nodes](https://user-images.githubusercontent.com/49298/159563838-9f85f7e9-8361-4e20-b17d-947f18656ad5.png)
 
The force layout provided by ELK might not be able to achieve my goal of distributing nodes and edges with few overlaps. But I'd like to be wrong about that as ELK provides a much nicer structure for selecting layouts and layout properties, which is in my opinion superior to what D3 offers.

A very simple example demonstration of a (somewhat tangential) fundamental difference is that nodes without edges do not cluster into a triangle:

![no-gravity](https://user-images.githubusercontent.com/49298/159566840-a6019ac1-b422-45f0-b158-1401a7f531af.png)

I guess that this is due to a lack of gravity... so another possible feature would be gravity :)
For reference [here are the configuration options available in D3](https://d3-wiki.readthedocs.io/zh_CN/master/Force-Layout/) There aren't a whole lot more than ELK, so I'm hopeful that the gap isn't insurmountable.

Sorry for the long, winding explanation; I thought it important to provide some context of what I am trying to achieve, and how more control over the simulation would bring me a step closer in that direction.

**Comment by timothypratley** [comment]
For reference, here is the equivalent ELK version for the full graph:

[elkt demonstrator](http://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=OYJwhgDgFgBCD28AuAoMAbY8QEslQFsAuGbYAOgFMBjdHCAZ0qvQGtyAzbaylPS8EhzwAdgxIBGAAwypKAvAAmldCQCiAQQAiagMooRSyjBEAWAOwA2ABwwA3igCQ6MAE94AVyQwA2jAY4AF6UkjIANDAAzFIwALpOLgBGKjAARBqKuGAiqSgAvgZGJhbmEvYJbp7efgHBoVIR0XEVyehpAFJgAB6iuQWGysXm5qblzpVevv5BITDSDVEx8eOtaQAylABuOH2Fg2bDAKxjLu6TNTP1jUstKakAQlkiImC7A8YHVicT1dN1c+FFs0VncAJLZN5FA6WABM3zOv1qs3m12BSTuABUoPACGAGJD9hZLJF4VUpkirkDlui2qk1m4XASPkTRg5xgjyZcAQsmtSwKtUgBxfm4FSM-J7ZlWY5s05ki7-FFU260jQYHCuMBQJlDSyWUnnP7IwG8lVpXRgTbZF7aiWURTAYyUEoSImWEifMoAWgAfLrLCh7Y6YM7hqYidYPSVRr7ddZAw6nSyI1GrDG-dD40Gk2GSu6hiMYLHPgHsyGiYcU7rjsWIwng6GbBXUzYixmK-Wc+ZK1ZIwWa+3e53y1ZLNGW-ra2Hh43rC6W7Yp6UZy6q5623GV1YYSyW3Cp2Ot2mw6mvkvTEeeyNTwOCxey43w0cW+n+1vLD3YS3b9CYe+x9uE4br+747lYkR7sBRKRO+kRui2JIHgGQA)

![elk-soci](https://user-images.githubusercontent.com/49298/159646428-94f8b00d-f8bb-47db-962b-59045d65d5e6.png)

I think it's a good layout that would be improved with some controls to avoid edge overlap.

**Comment by soerendomroes** [comment]
> A very simple example demonstration of a (somewhat tangential) fundamental difference is that nodes without edges do not cluster into a triangle:
This happens because separate connected components are layouted separately by default. Setting `spearateConnectedComponents` to `false` creates the same problem.
