### ISSUE TITLE
Make label side selection smart again

### ISSUE THREAD

**Issue by eNBeWe** [eclipse/elk#82]
The placement of labels in the attached graph is not optimal. If two edges were switched, the labels could be placed better.

![suboptimal_label_placement](https://cloud.githubusercontent.com/assets/3796429/18591829/92917dac-7c34-11e6-9244-aa9f0320d8af.png)

```
properties:
    org.eclipse.elk.direction=DOWN
    org.eclipse.elk.layered.edgeLabelSideSelection=DIRECTION_UP

knode stop {
    properties:
        org.eclipse.elk.layered.layering.layerConstraint=FIRST
    kedge (-> rev) {
        klabel "2: _trackSpeed < 0"
    }
    kedge (-> fwd) {
        klabel "1: _trackSpeed > 0"
    }
}

knode rev {
    kedge (-> stop) {
        klabel "1: _trackSpeed == 0"
    }
    kedge (-> fwd) {
        klabel "2: _trackSpeed > 0"
    }
}

knode fwd{
    kedge (-> stop) {
        klabel "1: _trackSpeed == 0"
    }
    kedge (-> rev) {
        klabel "2: _trackSpeed < 0"
    }
}
```

**Comment by le-cds** [comment]
Well, for starters, the strategy is set to `DIRECTION_UP`, so what do you expect? However, I'll repurpose the ticket for something I wanted to do at some point anyway, which is to take another look at the `SMART` edge label placement strategy and think about how to smartly assign edge label sides. And perhaps port labels as well, while we're at it.

**Comment by le-cds** [comment]
Better:

![screen shot 2017-07-22 at 17 23 12](https://user-images.githubusercontent.com/7465584/28492398-19c59512-6f03-11e7-9b51-bde12efd7ab4.png)
