### ISSUE TITLE
Commands should really have a category - Warning

### ISSUE THREAD

**Issue by jmenzies12** [eclipse/elk#847]
Hey there,

We are using Elk version 0.7.0 and are getting a warning in the logs whenever we start our application that the elk config is missing a category for one of its commands. 

`!ENTRY org.eclipse.ui 2 0 2022-06-07 09:08:36.103
!MESSAGE Warnings while parsing the commands from the 'org.eclipse.ui.commands' and 'org.eclipse.ui.actionDefinitions' extension points.
!SUBENTRY 1 org.eclipse.ui 2 0 2022-06-07 09:08:36.103
!MESSAGE Commands should really have a category: plug-in='org.eclipse.elk.conn.gmf', id='org.eclipse.elk.conn.gmf.layoutDiagramFile', categoryId='org.eclipse.elk.core.layout'`

Cheers
Jonathan

**Comment by soerendomroes** [comment]
Are you using `org.eclipse.elk.core.ui` that defines the category?

**Comment by jmenzies12** [comment]
We are not actually, if I activate that plugin in eclipse then the error goes away. Will need to make sure it's included in our product.
