### ISSUE TITLE
Compute reasonable initial coordinates for stress minimization

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#85]
The stress minimizing layouter currently uses ELK Force to compute initial node coordinates. There are surely faster and better methods to do this.

**Comment by le-cds** [comment]
@uruuru Any chance you'll get around to this? If not I'd think about closing the issue.

**Comment by uruuru** [comment]
I won't find the time. 

However, it may be a good option for a student task, e.g. during a practical course or as initial training for a thesis.
