### ISSUE TITLE
Port labels overlap with self loops

### ISSUE THREAD

**Issue by soerendomroes** [eclipse/elk#850]
See https://github.com/lf-lang/lingua-franca/issues/1273

**Comment by Eddykasp** [comment]
[Example 1](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=KYGw1gdAhiDmD2AnAlgFwBYFsBcACEUAnsIsACYBQFuuAdvGcHQIy4De1NXBh8ArqlwBtAM7IAXsDwBmAAwAaXHIC6nLrgAOSVABkoAI1AiIGggGNgmYLVR4AREIDyAVQAqAZQCSAEQCiigDlfAA1XAH1XRzCABUcAJXDPADEYx3cvACEdX2U7NS4tRFQAYXhaEVREKGQbETwkz2DfbzCvP3yaAHpO3BqxRndQADMdeHgNYygzVGQANyhUKVxKvmAO3HWCQxBcO2Y89RpCwQ1WDkPuIn5BUQkpaXlpVQuaAD1jiH6l3wBBd1d1jRAfgDKBdsdcMAoBUDocAL7rdYQjQAVnYwJ412EYkk2AeT2B720n2QjDwv3+wIxoJ2dghUIqywA7vBYeoERckdpNAAmdEvEG8ATYu54x7PF5Eooksm4ADqvkpAq2YLp3KZwBh6w5h2R0n5L0xwtuuPxEouUtQMqkAXirgAEtTtuDufQiug2VwdepkQAWA0XI03HH3cWEj5fbDuFwOp2qiEia4egXarlFTQANgDhyDItNYYFlutUZjjuVNJd6cTAnQzNZKYuCPW3ToDCYtH150OLZouZNSzkihUzZ6R20em2xlMU0s1lsuycbja-lwQVCESisQSYWSqXSniyOU9XVHIOddmkx9wPc03NO2ZPOauxpDYoJFxvvYrdhqtBIt6KOwG27U9vS4FswMfchYCYDQ+QAWgAPjoaQTGYTgdU4ehGDoPku3UPtXyUBRiPNApxxpKdzFnGx7EXDwfBXNdwkiVJt13WJ90PXI0xKMoKiqGpUDqXAGiaFpl0RQNvx5IDeM0M5w2JSN5UVAFGwwzhOGg9tmDQ3AkJYEw8LUPpSWAQYQBGMYJggXg8BWNYaB1HSjI0f1DNoPSNGkbSyBgtys08nk0K0mhXK8kw0WC0KgA)
[Example 2](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=KYGw1gdAhiDmD2AnAlgFwBYFsBcACEUAnsIsACYBQFuuAdvGcHQIy4De1NXBh8ArqlwBtAM7IAXsDwBmAAwAaXHIC6nLrgAOSVABkoAI1AiIGggGNgmYLVR4AREIDyAVQAqAZQCSAEQCiigDlfAA1XAH1XRzCABUcAJXDPADEYx3cvACEdX2U7NS4tRFQAYXhaEVREKGQbETwkz2DfbzCvP3yaGrFGd1AAMx14eA1jKDNUZAA3KFQpXEq+YA7cZYJDEFw7Zjz1GkLBDVYOXe4ifkFRCSlpeWlVE5oAPX2IbrnfAEF3V2WaX-wDKBNvtcMAoBUdrsAL7LZYgjQAVnY-x452EYkk2Bud3+z20r2QjDwn2+-xRgI2dhBYIq8wA7vBIeoYSc4dpNAAmZEPAG8AToq5Y273B54ooEom4ADqvlJPLWQKp7LpwAhyxZu3h0m5D1R-MumOxIpOYtQEqkAXirgAEuT1sD2fQiugmVwNep4QAWHUnPUXDHXYW4l5vbDuFw2u2KkEic4unnqtlFTQANh9uz9AsNQZ5pvNYYjtvlFIdydjAnQ9MZCZOMOW9EYdG1x11Z31AZkCiUsmNmu0enWxlMY0s1lsmycbja-lwQVCESisQSYWSqXSniyOVd6gVlOk24K7MO6d9bf9gqN-xou82NVoJE02jsNYe7rdy3IsCYGi5AFoAHxNiYzCcBqnANkwtBci2O5nlmcxyIoKhJroFJDuYo42PYk4eD4M5zuEkSpMuq6xOum65ChpTlJU1S1PUjTNK0eGwqe9p2Byz4oZoRzBviobSrKPy1qBnCcJ+kHMMBuAASwJjQWoXSEsAvQgAMQwjBAvB4AsSw0BqElyRo3qybQUkaNI4lkF+RlpqZHLAWJNCGWZJhIvZjlAA)

**Comment by soerendomroes** [comment]
The following happens: The SelfLoopPreProcessor deletes all SelfLoops and puts them into a holder to reintroduce them later on.
The LabelAndNodeSizeProcessor checks only if edge connect the ports and does not find any and here just adds the labels directly next to ports. Since this code is not in layered but in common I cannot check whether the SelfLoopHolder has a selfloop for my port.
