### ISSUE TITLE
Fixing node positions in the stress layout

### ISSUE THREAD

**Issue by klaraseitz** [eclipse/elk#851]
I am using the stress majorization layout but I am having issues with keeping nodes on a fixed position. 
Initially, I let the layout run to determine first positions. Later more nodes and links can be added and I recalculate the layout to include them. 
This currently leads to everytime different layouts or at least different positions which makes keeping a mental map of the graph very hard for the user. 
I see that the stress majorization algorithm supports setting nodes as fixed. But when I do that to all but the new nodes then they all get positioned almost on the same spot without any spread. 

Looking through the code I found that it seems to first run the Force Layout which does not take into consideration fixed node positions and only after runs the stress majorization layout. 

Here is my graph with its settings.
```{
  "id":"root",
  "children":[
    {"id":"0" },
    {"id":"1" },
    {"id":"2" },
    {"id":"3" }
  ],
  "layoutOptions":{
    "algorithm":"stress",
    "elk.padding":"[top=50.0,left=50.0,bottom=50.0,right=50.0]",
    "nodeSize.constraints":"[]",
    "interactive":"false",
    "omitNodeMicroLayout":"true",
    "epsilon":"1.0E-4",
    "hierarchyHandling":"SEPARATE_CHILDREN"
  },
  "edges":[
    {
      "id":"0",
      "sources":[ "0" ],
      "targets":[ "1" ]
    },
    {
      "id":"1",
      "sources":[ "1" ],
      "targets":[ "2" ]
    },
    {
      "id":"2",
      "sources":[ "2" ],
      "targets":[ "0" ]
    },
    {
      "id":"3",
      "sources":[ "2" ],
      "targets":[ "3" ]
    }
  ]
}
```
Note on the _interactive_ setting: When enabled all nodes receive the same position. It is always (50.5|50.5). No matter what graph I import. No matter whether _omitNodeMicroLayout_ is true or false. Only when rerunning the layout different positions are assigned. But they are all aligned on a diagonal line as each node's y value is the same as its x value.

Here are the visualized results I am currently achieving:
1. small example graph after stress majorization layout without fixing any positions:
![image](https://user-images.githubusercontent.com/11996418/178002852-4a0845c5-2fe7-4b3f-8e02-157f282f8c93.png)
2. fixing the positions on 2 of the nodes (the red ones) results in this layout:
![image](https://user-images.githubusercontent.com/11996418/178002993-8c22bcb6-f51c-412b-88fd-7b4e47aef877.png)
3. without fixed positions but interactive = true. First all nodes receive the same position (50.5|50.5). And when rerunning the layout it results in this:
![image](https://user-images.githubusercontent.com/11996418/178004132-1c55fdb5-7e9d-4f07-bd6d-10cde062d2be.png)

For my use case I really like the outcome of the stress majorization layout. I'd be grateful to get some tips on how to correctly fix node positions or use the interactive setting. Thanks!

**Comment by soerendomroes** [comment]
`fixed` does only take effect after an initial run of elk.force. `interactive` is designed to work with nodes that already have a position as seen [here](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=OYJwhgDgFgBCD28AuAoMAbY8QEslQFsAuGAZyRAFNTSVL0BrAOgjABM2cA7YEgIgDaSeBAC8AVgAMTSQBp0lAGZIJ0uQCNkwgqpmzcwKCqkyAunxRd4bSgGUcAL0pMAxvC7lw3JKX4DzKN6U4C5IOABulCQUAK6UKPAEeABy1pQAsjguCAAyYACe8DFI0SBxdBCkOOjuJACMMgCiALQALChQOMFgIC5Q+QASYFxs6Ny8MLaNAAoAggBKswAqjQD6AMIDAJI5ACLzjcmWaTBckjAA3igwNzDoBUVIMAIQ8FVhtTBSsjCSpte3RQ4AAelDYpXKtzuYHU9BgfDOFgAvscbKc6pcATd7oVis9Xu8cJ9vl8-liYEDQeCYLF4lD7rD0PCuHVkajKKcAEyY+kPPEvN54IlcEhyUn-KGUsEQum3BlwhGciwoFFWNFcADMPLlfKeAsJnzFZMlIOlNLKsuxMIVmrZYOAHMokhIZxgzQAfOi6GwHTBKHUXRiPVzvb7KJyXdzg2dQ46NZG3Z7NSggA). Nodes that are neither fixed nor have a position are handled as you described.
