### ISSUE TITLE
Mr Tree algorithm - Specify horizontal nodes ordering

### ISSUE THREAD

**Issue by francarmona** [eclipse/elk#873]
Im trying to represent a YES / NO split, and I would like to always have the YES to the left hand side.
Would it be possible by specifying [Priority](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-priority_org-eclipse-elk-mrtree.html) or [Weighting of Nodes](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-mrtree-weighting.html)?
Also if I dynamically add nodes to the graph the horizontal positions of nodes are not stable, I wonder what are the conditions for moving the YES or NO part to the left / right hand side (is it based on number of nodes connected?, number of crossings?, number of edges?, complexity?) 
In layered algorithm I see that it is possible by specifying positions to the nodes, but it would be great if it would be possible also in Mr Tree.

This is what I would like to get:
![mrtree](https://user-images.githubusercontent.com/16519747/192388098-1353438b-bb91-4a33-a2d8-0eb2d10af5ae.png)

Thanks!

**Comment by soerendomroes** [comment]
I think that was already implemented in the thesis mentioned in https://github.com/eclipse/elk/issues/406, which is currently not added to ELK.

**Comment by soerendomroes** [comment]
If I remember correctly, we used the input order as a default ordering and allowed to add constraints to set the level and the position in a level. This would be added in ELK 0.9.0 so it might take a few months until it is available since I am quite busy.

**Comment by francarmona** [comment]
> I think that was already implemented in the thesis mentioned in #406, which is currently not added to ELK.

By this do you mean this feature is already merged in master? I'm thinking about maybe I can build ELKjs myself while you relase 0.9.0 version.

Would you mind to give me an example of how to specify the level and position constraints in the nodes?

Thank you very much

**Comment by fran-carmona** [comment]
Hi @soerendomroes, hope you are well. Is there any updates on this? It would be super helpful to have this feature as I'm a bit limited in my project because of this.
Thanks!

**Comment by soerendomroes** [comment]
We are currently working on ELK 0.9.0 and this ticket is still something we want to add to this release.

**Comment by HP-283** [comment]
Hello, just wanted to ask, how should the configuration settings be configured in the end?

**Comment by soerendomroes** [comment]
@HP-283 You can find all mrtree layout options [here](https://eclipse.dev/elk/reference/algorithms/org-eclipse-elk-mrtree.html). If I understand you correctly, the default ordering would be the input order of nodes and the position constraint (https://eclipse.dev/elk/reference/options/org-eclipse-elk-mrtree-positionConstraint.html) can be changed to change the order for a specific node.

**Comment by HP-283** [comment]
I used this JSON below to test, when I removed e4, n2 and n3 changed the  order unexpectedly. 
How can i fix the order of  n2 and n3 when I add or remove edges.  positionConstraint seems not work.

https://rtsys.informatik.uni-kiel.de/elklive/json.html

```
{
  "id": "root",
  "properties": {
    "elk.algorithm": "elk.mrtree",
    "elk.direction": "DOWN"
  },
  "children": [
    {
      "id": "n1",
      "width": 30,
      "height": 30
    },
    {
      "id": "n2",
      "width": 40,
      "height": 30,
      "layoutOptions": {
        "positionConstraint": 4
      }
    },
    {
      "id": "n3",
      "width": 10,
      "height": 30,
      "layoutOptions": {
        "positionConstraint": 5
      }
    },
    {
      "id": "n4",
      "width": 30,
      "height": 30
    },
    {
      "id": "n5",
      "width": 30,
      "height": 30
    }
  ],
  "edges": [
    {
      "id": "e1",
      "sources": [
        "n1"
      ],
      "targets": [
        "n2"
      ]
    },
    {
      "id": "e2",
      "sources": [
        "n1"
      ],
      "targets": [
        "n3"
      ]
    },
    {
      "id": "e3",
      "sources": [
        "n2"
      ],
      "targets": [
        "n4"
      ]
    },
    {
      "id": "e4",
      "sources": [
        "n3"
      ],
      "targets": [
        "n5"
      ]
    }
  ]
}
```

**Comment by soerendomroes** [comment]
@HP-283 This might be the case, since this was only fixed in 0.9.X, which is currently not included in elklive.

**Comment by sagunji** [comment]
Do you have any idea on how to implement this same requirement in the `DOWN Layered algorithm`?

Code:
```
import Elk from 'elkjs/lib/elk.bundled.js';
import type { ElkNode } from 'elkjs/lib/elk.bundled.js';
import { WorkflowBranchSide } from '@studio/graphql-types';
import type { LayoutAlgorithm } from '.';

const elk = new Elk();

const elkLayout: LayoutAlgorithm = async (nodes, edges, options) => {
  const graph = {
    id: 'elk-root',
    layoutOptions: {
      'elk.algorithm': 'layered',
      'elk.direction': 'DOWN',
      'elk.edgeRouting': 'POLYLINE',
      'elk.spacing.nodeNode': options.spacing[0],
      'elk.spacing.edgeNode': options.spacing[1],
      'elk.layered.spacing.nodeNodeBetweenLayers': '120',
    },
    children: nodes.map(node => {
      return {
        id: node.id,
        width: node.width ?? 0,
        height: node.height ?? 0,
      };
    }),
    edges: edges.map(edge => {
      return {
        id: edge.id,
        sources: [edge.source],
        targets: [edge.target],
      }
    }),
  };

  // We create a map of the laid out nodes here to avoid multiple traversals when
  // looking up a node's position later on.
  const root = await elk.layout(graph);
  const layoutNodes = new Map<string, ElkNode>();

  (root.children ?? []).forEach(node => {
    layoutNodes.set(node.id, node);
  });

  const nextNodes = nodes.map(node => {
    const elkNode = layoutNodes.get(node.id)!;

    const position = {
      x: elkNode.x!,
      y: elkNode.y!,
    };

    return {
      ...node,
      position,
    };
  });

  return { nodes: nextNodes, edges };
};

export default elkLayout;

```

My data struct can distinguish only the immediate edges/nodes connected to the parent.

**Comment by soerendomroes** [comment]
@sagunji Can you please create a separate ticket for this and please recreate your problem in [elklive](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html)?
