### ISSUE TITLE
Remove "duplicated" keyword from metadata language

### ISSUE THREAD

**Issue by le-cds** [eclipse/elk#9]
Remove the `duplicated` keyword from the meta data language. Instead, always generate property definitions in the generated properties class. These definitions use the default values of existing definitions if the default value is not overridden, and a custom default value if it is. All layout algorithms then reference the locally declared properties. That way, we can choose to override a default value later without having to change our algorithms to not use the original property definition, but the local one.

**Comment by spoenemann** [comment]
In case the default value is not overridden I would just create a reference to the already defined property, e.g.
```java
public static final IProperty<Knödel> KNOEDEL = CoreOptions.KNOEDEL;
```

**Comment by le-cds** [comment]
I was going to implement this, but there is a problem with multiple layout algorithms declaring support for the same layout option, but with different default values. The two algorithms need to use different `IProperty` objects to access the layout options due to the different default values. I see three possible solutions:

1. Generate multiple Java classes from each .elkm file. One that contains all the basic layout option definitions and one for each layout algorithm. This would require us to change the .elkm language to be able to specify the names of the additional classes (we cannot simply use the name of the layout provider class since that is not guaranteed to be unique within a plug-in).

    This option would be my favorite as it fits in well with our "write one .elkm file and be done with it" philosophy. I'm not sure, however, if this can be done with Xtext. @spoenemann what do you think about this?

1. Limit each .elkm file such that at most one layout algorithm can be declared in it. This would only affect plugins that offer more than one layout algorithm, such as our interface to Graphviz. They would need to provide one .elkm file per layout algorithm, and possibly one .elkm file to declare options shared between the algorithms.

    This is a viable backup option in case the first option is not possible.

1. Generate a complete set of `IProperty` objects for each supported property and algorithm, but prefix each with the algorithm's name.

    I don't think this will work well. We use a similar approach for default option values already, but those are constants that are used internally. Layout properties are supposed to be used by algorithm users, and thus shouldn't become too long.

Once I have confirmation that option 1 would work, I would go ahead and implement that.

**Comment by spoenemann** [comment]
You can generate as many classes or interfaces as you like in the `MetaDataJvmModelInferrer`. Just call `acceptor.accept(...)` for each type you want to create. Of course these types can also reference each other. An idea how this could look like:

* We generate a main class for the layout options and an additional class for each algorithm, each implementing `ILayoutMetaDataProvider`.
* In its `apply(..)` method, the main class first registers its layout options and then calls `apply(..)` for each of the algorithm classes.

**Comment by uruuru** [comment]
:+1:

**Comment by le-cds** [comment]
Nice, then this is what I'll be doing. Thanks for the quick reply. :smiley:
