### ISSUE TITLE
Wrong "TAIL" edge label layout

### ISSUE THREAD

**Issue by lredor** [eclipse/elk#905]
It seems that the location of an edge label with property "edgeLabels.placement: TAIL" is non deterministic between several layouts.
Here is an example, each diagram is the result of the previous layout, you can see that the "begin" label move at each layout. The property "noLayout" is set to true to see the state before layout:

- First layout: [Elklive link](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=OYJwhgDgFgBAdgUwO4H0CWBnDBXBKAmaYoYAtiidAFAA2YAngPbYAuMA2jBmgF4IBcMAIwBmABwB2ADQwALBIAMMALpUwNYIxBoWUUoK3AAdAgDGNNBAwITNANZG69BCAT4qcRgBkGzFoJYQXA9GfAQYADkhGABvKgBIJz8OBPiIRm4WNEY4QVkAJhl8hVTuPkF8sVkZIVkxBNV4zzCAZV4bUjQ4NFJsfRgAIgAKUSMFKXyATjGASgGE9JAWHwAjBBoMIwg6UwRSBDh-QfZlecSwNZoYLyFBAcHY1KTWFPi39Mzs3OERSZkAVlS8TKAhgYiKQlSjSaoQQq3Wm22YF2+0Od3YAAkUABhACiEQAKriAEoyABqKAJAHkAAoyACSERa9IAIrjTgkAL4LLRsGnROJvZ5sdhAj46L6CAC0+UKMAkIiBIMEInGMFVUNShhM5ks1lsDgAeosWEYVlowiAqQAza3WI5SsRjLkJZrhCL5R5C3wvUVvNIZCU5QRCCTVdX1f3K4QKNVCWOat5utp8Iydbq9frDeNjKQ5hRzVIm+EbLY7PYHI4DE5nc6Xa7-O4PQVJ2ElxHl1FVzE4-FE0kwCl4wkkhlM1ns2vc968mA0z0t85MX1AgOfYMwGVykSA-3A9oqtUa-3Q+LaswWKw2dZGk1mi0uG12hAOp0lN7T6duYDhXG3OfRFKAB8kT5EY85ekuyR+m81imFkOQwLiLTRDBsEsGASyCOCYKRv6Bz4CG-xymIeHxNC0LnrqV4GkYhrfjYuhoKYdiIFgFTOt69ZePkdy7IcLj3IuwqvP64oId8ABsQgyJMkJ7tGsgiBCQKngx7ZlsiFZojAw79qk051us1wiHcazAF0QlAiJaFrkG3xCDJMDFKu0a-CpJ5AupFwIppKKVoIBIAIL0l4BlPD5VxeLIdwEVZ-o2au4mSsI+ThpM+SuQezmSR5bxqfgP4aUi-k6RiuJBSy4XxNy3JAA)
- Second layout: [Elklive link](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=OYJwhgDgFgBAdgUwO4H0CWBnDBXBKAmaYoYAtiidAFAA2YAngPbYAuMA2jBmgF4IBcMAIwBmABwB2ADQwALBIAMMALpUwNYIxBoWUUoK3AAdAgDGNNBAwITNANZG69BCAT4qcRgBkGzFoJYQXA9GfAQYADkhGABvKgBIJz8OBPiIRm4WNEY4QVkAJhl8hVTuPkF8sVkZIVkxBNV4zzCAZV4bUjQ4NFJsfRgAIgAKUSMFKXyATjGASgGE9JAWHwAjBBoMIwg6UwRSBDh-QfZlecSwNZoYLyFBAcHY1KTWFPi39Mzs3OERSZkAVlS8TKAhgYiKQlSjSaoQQq3Wm22YF2+0Od3YAAkUABhACiEQAKriAEoyABqKAJAHkAAoyACSERa9IAIrjTgkAL4LLRsGnROJvZ5sdhAj46L6CAC0+UKMAkIiBIMEInGMFVUNShhM5ks1lsDgAeosWEYVlowiAqQAza3WI5SsRjLkJZrhCL5R5C3wvUVvNIZCU5QRCCTVdX1f3K4QKNVCWOat5utp8Iydbq9frDeNjKQ5hRzVIm+EbLY7PYHI4DE5nc6Xa7-O4PQVJ2ElxHl1FVzE4-FE0kwCl4wkkhlM1ns2vc968mA0z0t85MX1AgOfYMwGVykSA-3A9oqtUa-3Q+LaswWKw2dZGk1mi0uG12hAOp0lN7T6duYDhXG3OfRFKAB8kT5EY85ekuyR+m81imFkOQwLiLTRDBsEsGASyCOCYKRv6Bz4CG-xymIeHxNC0LnrqV4GkYhrfjYuhoKYdiIFgFTOt69ZePkdy7IcLj3IuwqvP64oId8ABsQgyJMkJ7tGsgiBCQKngx7ZlsiFZojAw79qk051us1wiHcazAF0QlAiJaFrkG3z5MpMD-GR+7lOqfwwPk8lvGp+A-hpSIopWggEgAgvSXgGU8FzGV4sh3ARVn+jZq7iZKwj5OGkz5Ku0b5JJKknkC6mxaWQXaUcGK4mFLLRfE3LckAA)
- Third layout: [Elklive link](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=OYJwhgDgFgBAdgUwO4H0CWBnDBXBKAmaYoYAtiidAFAA2YAngPbYAuMA2jBmgF4IBcMAIwBmABwB2ADQwALBIAMMALpUwNYIxBoWUUoK3AAdAgDGNNBAwITNANZG69BCAT4qcRgBkGzFoJYQXA9GfAQYADkhGABvKgBIJz8OBPiIRm4WNEY4QVkAJhl8hVTuPkF8sVkZIVkxBNV4zzCAZV4bUjQ4NFJsfRgAIgAKUSMFKXyATjGASgGE9JAWHwAjBBoMIwg6UwRSBDh-QfZlecSwNZoYLyFBAcHY1KTWFPi39Mzs3OERSZkAVlS8TKAhgYiKQlSjSaoQQq3Wm22YF2+0Od3YAAkUABhACiEQAKriAEoyABqKAJAHkAAoyACSERa9IAIrjTgkAL4LLRsGnROJvZ5sdhAj46L6CAC0+UKMAkIiBIMEInGMFVUNShhM5ks1lsDgAeosWEYVlowiAqQAza3WI5SsRjLkJZrhCL5R5C3wvUVvNIZCU5QRCCTVdX1f3K4QKNVCWOat5utp8Iydbq9frDeNjKQ5hRzVIm+EbLY7PYHI4DE5nc6Xa7-O4PQVJ2ElxHl1FVzE4-FE0kwCl4wkkhlM1ns2vc968mA0z0t85MX1AgOfYMwGVykSA-3A9oqtUa-3Q+LaswWKw2dZGk1mi0uG12hAOp0lN7T6duYDhXG3OfRFKAB8kT5EY85ekuyR+m81imFkOQwLiLTRDBsEsGASyCOCYKRv6Bz4CG-xymIeHxNC0LnrqV4GkYhrfjYuhoKYdiIFgFTOt69ZePkdy7IcLj3IuwqvP64oId8ABsQgyJMkJ7tGsgiBCQKngx7ZlsiFZojAw79qk051us1wiHcazAF0QlAiJaFrkG3w7rJkmrtGvwqSeQLqRcCKaSilaCASACC9JeAZTzeVcXiyHcBFWf6NmruJkrCPk4aTPkLkHjA+SSe5bxqfgP4aUifk6RiuKBSyYXxNy3JAA)
- Fourth layout: [Elklive link](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=OYJwhgDgFgBAdgUwO4H0CWBnDBXBKAmaYoYAtiidAFAA2YAngPbYAuMA2jBmgF4IBcMAIwBmABwB2ADQwALBIAMMALpUwNYIxBoWUUoK3AAdAgDGNNBAwITNANZG69BCAT4qcRgBkGzFoJYQXA9GfAQYADkhGABvKgBIJz8OBPiIRm4WNEY4QVkAJhl8hVTuPkF8sVkZIVkxBNV4zzCAZV4bUjQ4NFJsfRgAIgAKUSMFKXyATjGASgGE9JAWHwAjBBoMIwg6UwRSBDh-QfZlecSwNZoYLyFBAcHY1KTWFPi39Mzs3OERSZkAVlS8TKAhgYiKQlSjSaoQQq3Wm22YF2+0Od3YAAkUABhACiEQAKriAEoyABqKAJAHkAAoyACSERa9IAIrjTgkAL4LLRsGnROJvZ5sdhAj46L6CAC0+UKMAkIiBIMEInGMFVUNShhM5ks1lsDgAeosWEYVlowiAqQAza3WI5SsRjLkJZrhCL5R5C3wvUVvNIZCU5QRCCTVdX1f3K4QKNVCWOat5utp8Iydbq9frDeNjKQ5hRzVIm+EbLY7PYHI4DE5nc6Xa7-O4PQVJ2ElxHl1FVzE4-FE0kwCl4wkkhlM1ns2vc968mA0z0t85MX1AgOfYMwGVykSA-3A9oqtUa-3Q+LaswWKw2dZGk1mi0uG12hAOp0lN7T6duYDhXG3OfRFKAB8kT5EY85ekuyR+m81imFkOQwLiLTRDBsEsGASyCOCYKRv6Bz4CG-xymIeHxNC0LnrqV4GkYhrfjYuhoKYdiIFgFTOt69ZePkdy7IcLj3IuwqvP64oId8ABsQgyJMkJ7tGsgiBCQKngx7ZlsiFZojAw79qk051us1wiHcazAF0QlAiJaFrkG3zyDUIiyKu0a-CpJ5AupFwIppKKVoIBIAIL0l4BlPD5VxeLIdwEVZ-o2au4mSsI+ThpM+SuQeMD5JJHlvGp+A-hpSL+TpGK4kFLLhfE3LckAA)

The corresponding successive layout results are like this: 
![successiveLayoutResults](https://user-images.githubusercontent.com/1825882/209295983-427a4dcf-d6bf-40fe-8d0d-3b2419ecac57.png)

**Comment by lredor** [comment]
And for information, the problem does not exist without container and without border nodes: sample in [ELK live](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=OYJwhgDgFgBAdgUwO4H0CWBnDBXBKAmaYoYAtiidAFAA2YAngPbYAuMA2jBmgF4IBcMAIwBmABwB2ADQwALBIAMMALpUwNYIxBoWUUoK3AAdAgDGNNBAwITNANZG69BCAT4qcRgBkGzFoJYQXCoPRnwEGAA5ACYYAG8qAEgnPw4kxIhGbhY0RjhBaIUZAE4RdO4+QREimGqk1QBfEM9wqJF4pJTWNMSMrJ1c-OFi2RKy3oqBWpq6xMaQt2AImJgAWgA+No7errZ2dMTrUxy8mABRAGUhHt7DljAQfxgAVhqhBTEDxIQ4fEEhEYyd6fW6qXpgxKGEzmSzWWwOAB6ixsujQpjsiCwBSMCnSdAARggaDAvNFBAAiUw-FgucnbHa+br7W59bKDf4KERAoRCL6TQSyLkwaK80EHZE+Qk0DBGCB0KmkamCADCZ0iABUzgAldJNBlSkkiCmE4BoOB0hK3XY3XqZNl5QTPIWyXEs-m1YoyEUHCHffBLSVEmVysAKpUwdUAQQAkl5dXiwAavLIKT98BaDtbmbc7QMHcIAGwF7nRPm8KbRYvC0Xg8X+hCB6Wy+UIRVwJ4ACTOkYAIvGmkA).

**Comment by lredor** [comment]
I looked a bit at the code level to see if there was anything "obvious" between a different treatment for `org.eclipse.elk.core.options.EdgeLabelPlacement.TAIL` and for `org.eclipse.elk.core. options.EdgeLabelPlacement.HEAD` but I saw nothing.

**Comment by lredor** [comment]
Not sure about all consequences, but this change fixes the problem:

diff --git a/plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/EndLabelPostprocessor.java b/plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/EndLabelPostprocessor.java
index d6f7826..ad6d48b 100644
--- a/plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/EndLabelPostprocessor.java
+++ b/plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/intermediate/EndLabelPostprocessor.java
@@ -1,5 +1,5 @@
 /*******************************************************************************
- * Copyright (c) 2012, 2020 Kiel University and others.
+ * Copyright (c) 2012, 2022 Kiel University and others.
  * 
  * This program and the accompanying materials are made available under the
  * terms of the Eclipse Public License 2.0 which is available at
@@ -51,7 +51,7 @@
         // We iterate over each node's label cells and offset and place them
         layeredGraph.getLayers().stream()
                 .flatMap(layer -> layer.getNodes().stream())
-                .filter(node -> node.getType() == NodeType.NORMAL && node.hasProperty(InternalProperties.END_LABELS))
+                .filter(node -> ((node.getType() == NodeType.NORMAL || node.getType() == NodeType.EXTERNAL_PORT) && node.hasProperty(InternalProperties.END_LABELS)))
                 .forEach(node -> processNode(node));
         
         monitor.done();

**Comment by lredor** [comment]
I've done a corresponding pull request https://github.com/eclipse/elk/pull/906

**Comment by lredor** [comment]
As the corresponding commit has been merged, I think that this issue can be closed, with milestone 0.9.0, except if some additional tests are planned to be done.

**Comment by soerendomroes** [comment]
A test would be nice. Thank you for your effort @lredor

**Comment by lredor** [comment]
@soerendomroes I have added a test with https://github.com/eclipse/elk/pull/913 and associated data in https://github.com/eclipse/elk-models/pull/17.

**Comment by lredor** [comment]
The test also covers center and head labels. Even if only tail label is problematic in #905. But it could help to detect a possible regression later...

**Comment by lredor** [comment]
The fix and tests have been merged on master branch so I consider this issue as solved. I think it can be added to 0.9.0 milestone
