### ISSUE TITLE
Layered Layout with Hardcoded Layer Choices, Potentially Empty Layers

### ISSUE THREAD

**Issue by simonwarchol** [eclipse/elk#908]
Hi there,
I'm new to Elk and am trying to make a layout with a predetermined number of layers and where nodes are hardcoded to each layer.
For instance, in [this](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUDAHZx7ADGcMAbjgDLYQCuc6cUrORfpEAjjSkAjGgDeGbHjJgAdJlxQAwgggwqOFRFIBnLsDIc04zACMcINACJRNtAF8iAoSIBMk6crmKZq9U1tXQMoI3J0TwsrW3cHZ1dhUgBmLyVZUgV0gI0tHX1DY3QAFmlLaxtk+KJCMCTxAFoAPg8agjqRRpaUoiA) elklive example
![image](https://user-images.githubusercontent.com/3915140/211215815-632e6066-16d4-41bd-9ac0-9f15e570956f.png)
I'd instead like node 3 to appear something like 
![image](https://user-images.githubusercontent.com/3915140/211215963-12009b1c-320c-4f7c-a7b6-956ad335795f.png)

Thanks so much in advance for the help :)

**Comment by soerendomroes** [comment]
Hi, layerChoiceConstraints are not directly supported by ELK but require postprocessing by the core.service package, which is eclipse dependent. Try setting the position of the nodes and set the interactive cycle breaking and layering strategies as seen [here](https://rtsys.informatik.uni-kiel.de/elklive/examples.html?e=user-hints%2Finteractive-constraints%2FinteractiveLayeredLayout_snake_pseudo_positions).

**Comment by soerendomroes** [comment]
In this case, I suggest using partition instead, as seen [here](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUAM44AOwUwcOAwhAHaM4DGtBDS5TOjcJdADNQZIpShx4MJjEZgAdMHYwAbjRzo4UAK44ijCARxpGARjQBvImltoJUqbPkKH0pugAMRAL4GjJowATFY2dm5OjHKKETKM6Ga+-samAMyhdvZUjnHRrtnu8WiJfoRggRYAtAB8pkFAA).

**Comment by simonwarchol** [comment]
Fantastic, thanks so much.
