### ISSUE TITLE
Generate documentation for melk

### ISSUE THREAD

**Issue by DAGobertGans** [eclipse/elk#91]
Implement a documentation generator that creates markdown documentation for the algorithms and layout options that are declared in *.melk files.

**Comment by le-cds** [comment]
One detail I would like to see in the documentation is a list of `ILayoutMetaDataProvider`s. The target audience here are plain Java users of ELK who need to register the providers manually to be able to use ELK ([see this piece of documentation](https://github.com/eclipse/elk/wiki/Using-Plain-Java-Layout)). I see two ways for presenting this list:

1. Present a list of all meta data providers generated from melk files. For each melk file, this would be the `metadataClass` specified in its `bundle` section. For each such class, list the layout algorithms defined in the melk file.
1. For each layout algorithm, specify the meta data provider class that defines the algorithm and all properties. This would be the same class I was referring to in the first item.

I guess the second version would be more helpful to the target audience, whose use case would mainly be "I want to use algorithm X, what do I have to register in order for that to work?".

**Comment by uruuru** [comment]
I wonder whether we should have a documentation field for the `group`s as well. It would allow us to add some high level documentation for them.

**Comment by le-cds** [comment]
I'm all for that.

**Comment by le-cds** [comment]
Also, the documentation should make clear what kind of an option a given option is. The currently supported kinds are: advanced, programmatic, output, and global.

**Comment by le-cds** [comment]
If we keep all of the documentation in our repository and only supplement that with the automatically generated documentation, it would be easy to keep the documentation for past releases around. This way, people using an older release would not be fooled by up-to-date documentation that does not apply to the release they are using.

I guess the generator should always generate to a "Nightly" documentation tree. Whenever we do a release, one of the things we should do is copy the current state of the nightly documentation tree over to a release tree and link to that from the documentation start page, or something.

**Comment by le-cds** [comment]
I just stumbled upon #14. Those information should be presented in the documentation for options as well as for their values.

**Comment by le-cds** [comment]
I guess this is fixed by now. Thanks, @DAGobertGans :+1:
