### ISSUE TITLE
does node label placement effect edge routing?

### ISSUE THREAD

**Issue by alixander** [eclipse/elk#915]
if i set it a node label to a particular location, can it influence edge routing to avoid overlapping with that label?

**Comment by soerendomroes** [comment]
I don't think it does, see [here](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=KYGw1gdAJglgTsAxgFxgewHYC4AEARAeQHUA5AKAzSmBwwEYcBvMgSBAEMBPNAV2RwDaOAM4wAXsFx0A7AAYANDjoAOWTgC6rStQAy7AEahhEAA4dEwALbAMyXACIBACQD6AYQCiJACoeASooAai4AQgTe3gQAsooEAKreAMoAknge6vasJmhwyHqGIMZm7BbWtrjJJClpZDh1ONm5bpjCyHDsMLbCuABiyQAaHngu1R619RwFOPYAHnPzC4tLmSyN-CYMzPXbOAB6axCi1LiJ8d5O43UAvlk56wBMTJc7+3eHMMc4pwkX2zerdwaAGYnjt6q9cu9Pt9zs9-msGgAWUFgvYHI6SL5nX71G43YBQADmNHopkeAFoAHy0e4UKgk+5AA).

**Comment by alixander** [comment]
thanks @soerendomroes ! btw, yesterday I couldn't figure out why ELK was introducing a lot of unnecessary bends in the routes. tried a lot of things, but ultimately just ended up removing the bends myself as post-processing: https://github.com/terrastruct/d2/pull/1033.

**Comment by soerendomroes** [comment]
This usually happens because of the node placement algorithm and sometimes if hierarchy handling is set to INCLUDE_CHIDLREN. Which node placement strategy are you using?

**Comment by soerendomroes** [comment]
Maybe ELK could do something similar with [node flexibility](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-nodePlacement-networkSimplex-nodeFlexibility.html) set to ports. Have you tried this option?
