### ISSUE TITLE
Horizontal and Vertical Partitions

### ISSUE THREAD

**Issue by simonwarchol** [eclipse/elk#928]
Hi All,
I was wondering if there is a straightforward to maintain both horizontal and vertical partitions, such that in the [this example](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUAM44AOwUwcOAwhAHaM4DGtBDS5TOjcJdADNQZIpShx4MJjEZgAdMHYwAbjRzo4UAK44ijCARxpGARjQBvImltoJUqbPkKH0pugAMRAL4GjJowATFY2dm5OjHKKETKM6Ga+-samAMyhdvZUjnHRrtnu8WhBSYYpjAAsGeEFkXmxHmiJfkSEYIEWALQAfKYlbYEhPWmtBO2mVcOMqUA ), n1, n2, and n3 all appear in a straight line.
Thanks so much!

**Comment by soerendomroes** [comment]
We currently do not have a node placement algorithm that supports this.
You can however set a straightness priority as seen [here](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUAM44AOwUwcOAwhAHaM4DGtBDS5TOjcJdADNQZIpShx4MJjEZgAdMHYwAbjRzo4UAK44ijCARxpGARjQBvImltoJUqbPkKH0pugAMRAL4GjJowATFY2dm5OjHKKETKM6Ga+-samAMyhdvZUjnHRrtnu8WhBSYYpjAAsGeEFkXmxHmiJfkSEYIEWALQAfKYlbYEhPWnVtuSw0PBYCiTawDBgCHAsJIJNnt5+A6ZVw4ypQA).
