### ISSUE TITLE
Unable to set LayeredOption 

### ISSUE THREAD

**Issue by BoiseStateCS410** [eclipse/elk#929]
I am altering Layered code in small ways to prepare a new variant. This means that I need to be able to set values for LayeredOptions. 

The attached minimum working example fails when attempting to set LayeredOption. The code and pom.xml file are attached.

I have searched to find examples where this was done in other code but couldn't find any. Thank you as always for your help. I very much hope that this is due to a knowledge gap that you can resolve quickly.

[javacode.txt](https://github.com/eclipse/elk/files/11657966/javacode.txt)
[pomxml.txt](https://github.com/eclipse/elk/files/11657967/pomxml.txt)

**Comment by soerendomroes** [comment]
You should not try to set a string as a layout option. Try using LayeredOptions.ALGORITHM_ID instead.
`g.getProperty(CoreOptions.ALGORITHM, LayeredOptions.ALGORITHM_ID)`
