### ISSUE TITLE
Rename "insets" to "padding"

### ISSUE THREAD

**Issue by le-cds** [eclipse/elk#93]
To be more consistent with popular terminology (especially in web development), rename insets to padding. This will affect several layout options and a few classes, but shouldn't be too bad.

**Comment by le-cds** [comment]
Absolutely. Also, we have two insets classes now: `ElkInsets`, which is used for the insets properties, and `Insets`, which is used during node size calculation. I guess we should kill the latter and use the former instead?

**Comment by uruuru** [comment]
Everything should be renamed accordingly. I left the ``LInsets`` class of ELK Layered for the moment since it's only internal.
