### ISSUE TITLE
LayeredOptions not available to set for k-graph?

### ISSUE THREAD

**Issue by BoiseStateCS410** [eclipse/elk#931]
[javacoderev2.txt](https://github.com/eclipse/elk/files/11689428/javacoderev2.txt)
[pomxml.txt](https://github.com/eclipse/elk/files/11689430/pomxml.txt)
[errormessage.txt](https://github.com/eclipse/elk/files/11689432/errormessage.txt)

In the above MWE, the code  fails with ClassNotFoundError when attempting to set a LayeredOption on a K-graph.
I assume from this that I can't set LayeredOptions on a K-graph?
Is there a sequence of steps I could take to 
1. convert K-graph to L-graph
2. set LayeredOptions to values other than the defaults
3. proceed with layout
Thank you, as always.
Mike

**Comment by soerendomroes** [comment]
I usually refer to the KGraph as the graph data structure of KLighD. Do you mean the ElkGraph?

You can set LayeredOptions on an LGraph or an ElkGraph.

**Comment by BoiseStateCS410** [comment]
Soeren
Yes I mean the ElkGraph.
If I can set LayeredOptions on an ElkGraph, why does the code I supplied fail with the error sequence I provided?
Am I missing a line of code in that program?
Thank you
Mike

**Comment by BoiseStateCS410** [comment]
I've discovered a configuration issue that may well have caused my issue. I'm opening another issue to ask for help with it. Thank you for your attempt to replicate.
Mike
