### ISSUE TITLE
How to force nodes to be positioned in same order as they described in model

### ISSUE THREAD

**Issue by redexp** [eclipse/elk#943]
Good day

Here is an [example](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEAiEwCeBTKPAEwwCg8QBrAOiJkIGM4YIA7dAEQHkB1AOVIIYBYFAYIcACWCsiIGKzDoMAST4BhADIBVDgFEA+uskrNHAEp6+ZUqwhE8aLgFc4AZxgO0Ab1Jp-aHZeAAo+fgER2DgQrmgA2mgeAF546ACMAAwZADRoAOwArGgAuuER-tgARhSYwRg+aFExcPGJMCnpeblpRcVoAL5lA0NBjuppYeUBTbEJyalomTn5vUORwNUgmOP13o24za3znd29wxGDEaNo6gBMk1P70bNtHYtZuYUla9MbNRh3XZPQ5zdoLNJdRZnS4BQYjexjADMDymMxaoLeS0+q0e+0220RQLRRzBJyhJXOsNIQ2IYEcoQAtAA+G5pGlEOloRksu7szncm6I0hwoA)

I need nodes C1, C2 and C3 to be positioned in same order as they edges with P described. I can't understand why C3 with absolutely same size as C1 and C2 is positioned on first place.

I'v tried all layer options with words `order` or `placement` but nothing helps

Thanks for any help

**Comment by soerendomroes** [comment]
See [here](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEAiEwCeBTKPAEwwCg8QBrAOiJkIGM4YIA7dAEQHkB1AOVIB6QWgQwCwKAwQ4AEsFZEQMVmHQYAknwDCAGQCqHAKIB9bbI26OAJSN8MaYWiIQ8AZzSsIcNAHdolGhwEGB4iAR+8AhoSBBEFGjQ8VCJAA7MbG6kpF7xaFwArnBuMHkA3qQMmaUEALJxFFxQydRucFDAcHhgOOh8XMYAyiYAgnwcJkYcAOJGg6Roi54NaAAKaBVLW2jYOBBFaADaaCUAXnjoAIwADNcANGgA7ACsaAC6C9uL2ABGCRirBxlHa4fY+Y5nC5oS6PB6XV5vNAAX0+ixRW1yeDQ2kuG1R212YKOJxg5yutweL3e+K2v3+OKBIL2BwhpKhMLhCOR+PRS0x2IATHivt9QSySWToRSngiaUs6SBMNoBYzCeLIVdYdCuby0dkMSttABmYUitXgiXs6VUj4ikF-RUYY2qsUWjXQrXw97crYo-HEUJrNAAWgAfNjLv6iIH1mHBVGYyHw8bSH6gA).
Or look [here](https://eclipse.dev/elk/blog/posts/2023/23-01-09-constraining-the-model.html) for details.

**Comment by soerendomroes** [comment]
>  I can't understand why C3 with absolutely same size as C1 and C2 is positioned on first place.

To prevent local minima the graph starting configurations are randomized per default. Moreover, strategies before crossing minimization might scramble the order since it is not part of the contract. So the reason is the used [random seed](https://eclipse.dev/elk/reference/options/org-eclipse-elk-randomSeed.html).
