### ISSUE TITLE
is there a way to load this project in latest versions of intellij ? 

### ISSUE THREAD

**Issue by ymolists** [eclipse/elk#950]
Hi Team.

It has been a while since i used maven/eclipse. Is anyone familiar with loading this project in current intellij versions please ? I tried loading the maven project in <root>/build but that failed miserably. image attached below.

Best Regards

![image](https://github.com/eclipse/elk/assets/6591993/55b25da6-93ce-45c5-bd8d-83504142964f)

**Comment by soerendomroes** [comment]
Since the algorithms need an installed ELK meta-compiler, I do not think that this will work.
