### ISSUE TITLE
compaction.connectedComponents does not respect edge labels

### ISSUE THREAD

**Issue by soerendomroes** [eclipse/elk#953]
This model
```
node main_x {
  elk.direction: RIGHT
  compaction.connectedComponents: true
  port p0
  node main_x_src {
    port p1
  }
  edge e0: main_x_src.p1 -> p0 {
    label "0"
  }
}
```
draws the label outside the drawing.

This model
```
node main_x {
  elk.direction: RIGHT
  compaction.connectedComponents: true
  portConstraints: FIXED_POS
  port p0
  node main_x_src {
    port p1
  }
  edge e0: main_x_src.p1 -> p0 {
    label "0"
  }
}
```
somehow does not since the fixed port position seems to however rescue it.

It seems that connected components compaction does somehow disrespect the edge label.

**Comment by soerendomroes** [comment]
![lf-issue1624-bad](https://github.com/eclipse/elk/assets/6419799/d01812d5-9ec7-4886-b76d-307801bf6c6a)
![lf-issue1624-good](https://github.com/eclipse/elk/assets/6419799/d08fef99-f280-4fb6-bb29-39b5f85553f1)

**Comment by Eddykasp** [comment]
https://github.com/eclipse/elk/pull/1081
