### ISSUE TITLE
关于antv/x6与elkjs在vue2架构中实现拖拽式部署

### ISSUE THREAD

**Issue by wuhongru222** [eclipse/elk#954]
我目前在做一个类似于https://x6.antv.antgroup.com/examples/showcase/practices/#elk       的拖拽式部署，但是该案例不支持拖拽，然后我自己研究了两天，我发现antv/x6生成的数据 跟elkjs所需要的数据截然不同，我想问的是，elkjs所需要的数据格式是固定的么？有支持拖拽的案例么？基于其他的库开发的也行

**Comment by Eddykasp** [comment]
The communication language of this project is English. In order for someone to be able to help you please provide an explanation of your problem, what you have tried, what you expected to happen and what actually happened in English.

If you have a concrete question about layout settings or a bug report it is helpful to show it using [elklive](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html).

If you have a question about other tools that integrate ELK then we may not be able to help and you should probably ask the maintainers of those other tools.
