### ISSUE TITLE
Edge Labels merge hyperedges

### ISSUE THREAD

**Issue by eNBeWe** [eclipse/elk#96]
If two edge labels are placed in the same or adjacient layers, and during crossing minimization the labels are placed next to each other, the hyperedges can get mixed up.

See this kgt:
```
properties:
	org.eclipse.elk.randomSeed=1  // Kaputt
//	org.eclipse.elk.randomSeed=2  // Heil
//	org.eclipse.elk.randomSeed=3  // Anders Kaputt
	
knode N4 {
	kedge (-> N5)
}
knode N2 {
	kedge (-> N3)
}
knode N1 {
	properties:
		org.eclipse.elk.portConstraints = FIXED_SIDE
	kport P1 {
		properties:
			org.eclipse.elk.port.side = WEST
	}
	kport P2 {
		properties:
			org.eclipse.elk.port.side = EAST
	}
	kedge (:P2 -> N5) {
		klabel "Forward Label"
	}
	kedge (:P2 -> N2)
}
knode N3 {
	kedge (-> N4)
}
knode N5 {
	kedge (-> N1: P1) {
		klabel "Feedback Label"
	}
}
```

If the labels are placed on opposite sides of the diagram, the layout is fine:
![hyperedge-working](https://cloud.githubusercontent.com/assets/3796429/21185375/b2044800-c210-11e6-9097-cea66f9bb335.png)

If the labels are on the same side, the edges are merged:
![hyperedge-broken1](https://cloud.githubusercontent.com/assets/3796429/21185382/bddf507a-c210-11e6-952d-bfb177cd8426.png)
![hyperedge-broken2](https://cloud.githubusercontent.com/assets/3796429/21185383/bf924b48-c210-11e6-8ebe-11d6cb22bf81.png)

This issue has been observed in the release 0.1.0.

**Comment by le-cds** [comment]
The solution required messing with the long edge sources and targets, which caused other parts of the code to fail. The new code keeps long edge sources and targets and introduces additional properties that allow the dummy merger to make more informed decisions.
