### ISSUE TITLE
multiple edges between two nodes overlap when using grapviz twopi/circo

### ISSUE THREAD

**Issue by 3Prophet** [eclipse/elk#961]
The documentation for graphviz twopi and circo states that multiple edges with the same source and target nodes are supported. 

The provided parameters however do not allow to reach edge separation.

In the graphviz algorithm(twopi/circo) the edge separation is reached by setting splines=false. It is not clear how that can be reached from elk.

**Comment by soerendomroes** [comment]
Hi, can you please provide an example graph and a sketch of how you expect the drawing to look?

**Comment by 3Prophet** [comment]
Thank you for the quick response.

Here is What we would like to achieve:

  1. Have no overlap for multiple edges between the same nodes
  2. Have optimal graph compactness, i.e. that there is not to much empty space between the nodes.
  
  Here is an example of a desired output:
![Example](https://github.com/eclipse/elk/assets/6282187/1f12e10b-5030-4420-b0b5-14f4847cf565)

Here is an example of how it looks like now:
![Example_as_is](https://github.com/eclipse/elk/assets/6282187/c5bc2513-c477-4cc8-92b8-96c6b3b026b2)

Here are more detailed requirements with the reference to graphviz

Handling of edge overlap in graphviz:
  "splines" is the parameter that determines edge overlap in graphviz ( https://graphviz.org/docs/attrs/splines/)
   Edges do not overlap When splines value is set to "false" or to "line". In all the other cases edges do overlap.
Current handling of  edge overlap in Elk:
  Edge overlap in Elk https://eclipse.dev/elk/reference/options/org-eclipse-elk-edgeRouting.html
Desired handling of edge overlap in Elk:
  Extend org.eclipse.elk.core.options.EdgeRouting to include LINE

Handling graph compactness in graphviz:
  For "circo", graph compactness is affected by changing the parameter "mindist": https://graphviz.org/docs/attrs/mindist/
  For "twopi", graph compactness is affected by changing the parameter "ranksep": https://graphviz.org/docs/attrs/ranksep/
Current handling of graph compactness in Elk:
   there is a single parameter "Node Spacing": https://eclipse.dev/elk/reference/options/org-eclipse-elk-spacing-nodeNode.html
Desired handling of graph compactness in Elk:
 Introduce parameters that will map to mindist and ranksep for circo and twopi respectively 

Shown examples can be reproduced at: https://rsms.me/graphviz/
using the following dataset:

# Graph compactness for circo
layout=circo
mindist=0.7

# Graph compactness for twopi
#layout=twopi
#ranksep=1.0

# Resolving overlaps for multiple edges between same nodes
splines=line

# Default node attributes
node [
  shape = rect
  style="filled,bold"
  color=black
  fillcolor="#F2F2F2"
  fontname=Inter
]


# Edges
SG -> UK
UK -> SG
UK -> CH
SG -> CA
SG -> JP
US -> US02
SG -> FR
CN -> CN_2D
DE -> DE_2D
CH -> US
JP -> JP_2D
DE -> CH
DE -> SG
US -> FR
JP -> CH
CN -> CH
SG -> DE
US -> CH
UK -> UK_2D
DE -> FR
SG -> CN
CN -> FR
US -> US_2D
SG -> US
CH -> CH_2D
CA -> CA_2D
CH -> FR
UK -> FR
SG -> CH
CH -> CA
FR -> FR_2D
CA -> CH



Thank you in advance for your time

**Comment by soerendomroes** [comment]
Currently, mindest and ranksep are set by ELK to `spacing.nodeNode` / 72 (DPI) so we will most likely not add two additional option for this.
If I have time I will try to add the `line`or `false` option to work by setting `UNDEFINED` edgeRouting. However, a quick test showed that there might be more problems to this.

**Comment by 3Prophet** [comment]
Thank you very much for your reply and time.
We would be happy to see UNDEFINED mapped to line or false among the upcoming changes.
Have a good day

**Comment by soerendomroes** [comment]
That will not matter, I think the graphviz version we are using here just does not support the edge drawing style you are envisioning.
