### ISSUE TITLE
Edge End Texture Length for the Layered algorithm?

### ISSUE THREAD

**Issue by diegosogari** [eclipse/elk#971]
I need to draw markers (arrowheads) at the end of edges, and these markers may be hollow or transparent and must not be drawn over the nodes. In order to preserve this effect, edges must be shortened by a specified length. For this purpose, there's an [Edge End Texture Length](https://eclipse.dev/elk/reference/options/org-eclipse-elk-mrtree-edgeEndTextureLength.html) option, but apparently it only applies to the Mr. Tree algorithm.

Do you know of a similar option for the Layered algorithm?

Note that it wouldn't suffice to add margins to the nodes, because the margin value would depend on the angle of incidence of the edge. Actually, a workaround would be to calculate this angle and shorten the edges after the layout, but I was looking for a built-in option that could do this for me.

**Comment by soerendomroes** [comment]
This seems to be a bug in our visualization, I guess the underlying data may be correct.
