### ISSUE TITLE
Hierarchical edge label not showing properly

### ISSUE THREAD

**Issue by diegosogari** [eclipse/elk#981]
As the title says, a label on a hierarchical edge is not being properly laid out. Here's an example ([link to model]):

```
node n1
node n2 {
    node n3
}
edge n1 -> n2.n3 {
    label 'abc'
}
```

Is this only a visualization issue?

[link to model]: https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=HYewJgpgBMCMBQpIwExQN7ytm5rAGZ4BfeCMAc31igFoA+VAOkIyxwBsBDAIwg6gByXgGNBJIA

**Comment by soerendomroes** [comment]
No, the hierarchical edge cannot be routed. You can either add an intermediate port to route the edge through and split the edge in two or enable `hierarchyHandling: INCLUDE_CHILDREN`. I recommend the first option.

**Comment by diegosogari** [comment]
Thanks!
