### ISSUE TITLE
Can you pass custom properties to graphviz?

### ISSUE THREAD

**Issue by mbwgh** [eclipse/elk#994]
I am trying to use the [ordering](https://graphviz.org/docs/attrs/ordering/) attribute, which does not seem to be among the supported properties. I haven't found an obvious extension point after having spent some time looking at the docs and stepping through the code.

Is it possible to attach such a custom property to a node, in a way that it will be picked up by the graphviz layouter (I guess in the end `DotExporter.java`) and passed to graphviz?

**Comment by soerendomroes** [comment]
Hi, ELK uses an old version of graphviz, I do not know if this option is even supported. If I remember correctly, the implementation in ELK does not allow passing new options to graphviz, sorry.
