### ISSUE TITLE
Question: How to group nodes by layers?

### ISSUE THREAD

**Issue by Daniel-Khodabakhsh** [eclipse/elk#999]
Experimenting with ELK and was wondering if someone could either help me by pointing me in the right direction or letting me know that it is not currently possible with ELK.

In the following image, the red line separates layer 1 nodes with layer 2 nodes, and the blue line separates layers 2 and 3. How can these be discretely grouped? That is to say, all layer 1 nodes have a separation with layer 2 nodes and so on?

![image](https://github.com/eclipse/elk/assets/9839187/b41831cf-d4c7-428e-929d-e544b054f3f3)

[Link](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYHIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvKBBAgXgOYpKToALALYJ4CQkQCmSSdAS4AvjggBjAZDzQZ9eAG1cEYFDiJ6ARmxgA7jEHwAzAAYsYAZMhcB6B47BKDYEYwYvQATJY20HZgTi5uHl4+fspsQSYI9PYRtgI+ce6e3jG+-myBxiEALNlRucX5CUVOyQFpIQCsNdGxrgWJxS1lbaYAbF11PfGFSaWpFaYA7ON5vY0zKYbzGQAcy-Wr0wOzm8GmAJx7k31NJRvlpxlmjpfOB-3Nx-fp5hYukd2vKbvW6tLbmcJ-HIrIE3QZzB7mLKQ2rQ67rUEIszVZEAhqHD53YaPTo4iaAtFHQlgsxjUmotaUjHfMxLOn7GHoobU3Zsq4MglMkJmC688n8kFchGhZ6ivHAuEnb6hX7WKHsikCyVKiGqlHq8UKr4hUJI3W4t6wz5EsLYs1kuWWqlSkl2+n4iXwpW013692G62hVk+vl+q1g0I84Ni0NOpUiqMOzlgAC6KVkXEkzDA+i1YkkKsYZCQKkzelMFhTLnQBCQGfQWd0pnCKf9W0kOsLpGLpez5YQlbA1drknrZYyWRbYYeklNne7DdME9Tg5rdYXGWqk9jedtc5L6-onQHQ7XY-oYy3gsQkhde57jYyR+XJ5HB6Wl9z1+9d4PT6rq9fM9dg-FMQAUIA)

<details>
<summary>JSON</summary>

```javascript
{
  id: 'root',
  layoutOptions: {
    'algorithm': 'layered'
  },
  children: [
    { id: 'n1', width: 30, height: 30 },
    { id: 'n2', width: 30, height: 30 },
    { id: 'n3', width: 30, height: 30 },
    { id: 'n4', width: 30, height: 30 },
    { id: 'n5', width: 30, height: 30 },
    { id: 'n6', width: 30, height: 30 },
    { id: 'n7', width: 30, height: 30 },
    { id: 'n8', width: 30, height: 30 },
    { id: 'n9', width: 30, height: 30 },
    { id: 'n10', width: 30, height: 30 },
    { id: 'n11', width: 30, height: 30 },
    { id: 'n12', width: 30, height: 30 },
    { id: 'n13', width: 30, height: 30 },
    { id: 'n14', width: 30, height: 30 },
    { id: 'n15', width: 30, height: 30 },
    { id: 'n16', width: 30, height: 30 },
    { id: 'n17', width: 30, height: 30 },
    { id: 'n18', width: 30, height: 30 },
    { id: 'n19', width: 30, height: 30 },
    { id: 'n20', width: 30, height: 30 },
    { id: 'n21', width: 30, height: 30 },
    { id: 'n22', width: 30, height: 30 },
    { id: 'n23', width: 30, height: 30 },
    { id: 'n24', width: 30, height: 30 },
    { id: 'n25', width: 30, height: 30 },
    { id: 'n26', width: 30, height: 30 },
    { id: 'n27', width: 30, height: 30 },
    { id: 'n28', width: 30, height: 30 },
    { id: 'n29', width: 30, height: 30 },
  ],
  edges: [
    { id: 'e1', sources: [ 'n1' ], targets: [ 'n2' ] },
    { id: 'e2', sources: [ 'n1' ], targets: [ 'n3' ] },
    { id: 'e3', sources: [ 'n3' ], targets: [ 'n4' ] },
    { id: 'e4', sources: [ 'n5' ], targets: [ 'n6' ] },
    { id: 'e5', sources: [ 'n5' ], targets: [ 'n7' ] },
    { id: 'e6', sources: [ 'n5' ], targets: [ 'n8' ] },
  ]
}
```

</details>

I looked through many of the options and the following option in the root `layoutOptions` has some good results but with some drawbacks:

```javascript
'org.eclipse.elk.hierarchyHandling': 'INCLUDE_CHILDREN'
```

![With hierarchyHandling = INCLUDE_CHILDREN](https://github.com/eclipse/elk/assets/9839187/5105ad5e-e7eb-4370-be97-8091c9a971ff)

The issue with this is that each layer only has one column. Is it possible to have this discrete separation of layers but also wrap them within some specified height?

When using:

```javascript
'org.eclipse.elk.direction': 'DOWN',
'org.eclipse.elk.layered.spacing.nodeNodeBetweenLayers': 30
```

It appears to conform to what I'm looking for:

![With direction = DOWN and nodeNodeBetweenLayers = 30](https://github.com/eclipse/elk/assets/9839187/f082c1ae-1ae9-4551-9bbf-9b8a9ae28e90)

but this is very fragile because if the `org.eclipse.elk.layered.spacing.nodeNodeBetweenLayers` option is changed or a new node is added, it loses cohesion:

![Fragile direction = DOWN](https://github.com/eclipse/elk/assets/9839187/210217c0-a84a-445f-b979-7099ba0223cf)

I also tried explicitly setting

```javascript
'org.eclipse.elk.partitioning.activate': true
```

in the root and

```javascript
layoutOptions: {
  'org.eclipse.elk.partitioning.partition': i
}
```

for each node, where `i` is replaced with the layer, but this made no difference.

[Link](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYHIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvKBBAikgOYB0ApgGM8kKoz788Aax4E8XTpHQALALYJ4CQkT5I+0bLnadeg4aPF8pPKgSS1aDSPV4EBtAG4F0fdWHRJSPhwIAF9gsAElSDxoXXp4AG1DMGAoOER6AEZsMAB3GGV4AGYABiwwJT5ILiV0YrL8YjJKGjomFg5ufiERMQlpGztFNqdeQfs230yQsDDk1JgNegAmHPzoQrBS8srq2vryrWbqB3aUzpMe837rWwnHZ1uh099lmbm2FLSlorWCpQOFSqNTqWwaR3IJzazHOxm6Zj6lgGd2GDzGKJe8Des3CEAW6QQ9AALH8NgCwTtgfsKY0SJDWgwYcALvDehYrONUfRRk97vRfEV3rivosMgBWUmbbZAvag6UQlqnJks0xsm6c048jWTeDTHHzb4ZABskvJ0t2IMBCqhjI6cNV1yRvK5WoxOrA2I+bHxSwA7KbARbqfKmvSlXaug7ERy3WjnZiPUKDaLCQAOAM0oNy8GhxXQiOXBHs5HPEaPbUMV5Jz4+jIATgz5qp2cOuZtZ2Z9qu0ZLfNdpcruur3sNhMyJUbDSzVrbDI7Ku7xfjZfRA-5Q-1NdHWWy5XWUqnzZndLztthkcX6tj3PL16mw7x28yqz3-0DR5p1rnyq7Rava-7Pl703EcUyyX5XzJd9ZWPY5vwLVlHRjADbzXYCvUfMDMhJSCD0pGDP1ncNz0LNUnQrG9VyAjcMJFAksglXCzUPAiQxPdsfwvP9yOvQCuXQ4VazHE0mOgy1CPY+CSMQntlzjCiBOTejMn9UTMw-Ni4OIzsuLI5C+1Q6iwD1WihKydM1KbVic0k7SF24-SXUM-iaMEp8G0sljxM0sN82kqMlwoviExMtywOWCdPPw7ybK0vydNIpDeycqiXOMh86KWZZdzyN91Os1tbPi+y9OSzVnJCjKzOWF9cqg-KYsKuKzwSmTAt4ir3VCpSsoguq8JlRraWa+df1KuTKImxSt3CnD+uY6Lg1i3yWpKpKJuCrqqu3ZZGPmsSlqalbRt09ags6wd0pAzD6OWET9oaw7huOzjEtk87Usq67MoyZZVIeqyhq-OyxrOjrPq277qosgGvKe4HitB97wam1yet+jzYcWltntPE63valCIcu7qIAAXXCPQuD4GEkhmgk+ByxgyCQAQacSDJsjACm-Fsan0Fp36EG5qHRz4WrmdIVn2bABJOeFnn0D5vgBY5wlfhF0yxb6yXpcF9WFfKJXuBV-XiQV0WUz4ObdbZs2JW5o3ldV2XjQtrWrb222ZblwkHcV52zf9TWwoZ+7vftw3eZNl3ffodMQ9wMmQBCIA)

<details>
<summary>JSON</summary>

```javascript
{
  id: 'root',
  layoutOptions: {
    'org.eclipse.elk.algorithm': 'layered',
    'org.eclipse.elk.partitioning.activate': true,
  },
  children: [
    { id: 'n1', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n2', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 2} },
    { id: 'n3', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 2} },
    { id: 'n4', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 3} },
    { id: 'n5', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n6', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 2} },
    { id: 'n7', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 2} },
    { id: 'n8', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 2} },
    { id: 'n9', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n10', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n11', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n12', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n13', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n14', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n15', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n16', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n17', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n18', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n19', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n20', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n21', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n22', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n23', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n24', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n25', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n26', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n27', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n28', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n29', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
  ],
  edges: [
    { id: 'e1', sources: [ 'n1' ], targets: [ 'n2' ] },
    { id: 'e2', sources: [ 'n1' ], targets: [ 'n3' ] },
    { id: 'e3', sources: [ 'n3' ], targets: [ 'n4' ] },
    { id: 'e4', sources: [ 'n5' ], targets: [ 'n6' ] },
    { id: 'e5', sources: [ 'n5' ], targets: [ 'n7' ] },
    { id: 'e6', sources: [ 'n5' ], targets: [ 'n8' ] },
  ]
}
```

</details>

**Comment by soerendomroes** [comment]
Per default ELK handles all connected components separately. Hence, you need to disable that for partition to affect all nodes, as seen [here]({
  id: 'root',
  layoutOptions: {
    'org.eclipse.elk.algorithm': 'layered',
    'org.eclipse.elk.partitioning.activate': true,
    'separateConnectedComponents': false
  },
  children: [
    { id: 'n1', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n2', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 2} },
    { id: 'n3', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 2} },
    { id: 'n4', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 3} },
    { id: 'n5', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n6', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 2} },
    { id: 'n7', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 2} },
    { id: 'n8', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 2} },
    { id: 'n9', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n10', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n11', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n12', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n13', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n14', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n15', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n16', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n17', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n18', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n19', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n20', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n21', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n22', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n23', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n24', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n25', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n26', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n27', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n28', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
    { id: 'n29', width: 30, height: 30, layoutOptions: {'org.eclipse.elk.partitioning.partition': 1} },
  ],
  edges: [
    { id: 'e1', sources: [ 'n1' ], targets: [ 'n2' ] },
    { id: 'e2', sources: [ 'n1' ], targets: [ 'n3' ] },
    { id: 'e3', sources: [ 'n3' ], targets: [ 'n4' ] },
    { id: 'e4', sources: [ 'n5' ], targets: [ 'n6' ] },
    { id: 'e5', sources: [ 'n5' ], targets: [ 'n7' ] },
    { id: 'e6', sources: [ 'n5' ], targets: [ 'n8' ] },
  ]
}).

**Comment by soerendomroes** [comment]
To have multiple columns of unconnected nodes could be solved by adding a [separate partition](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYHIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvKBBAikgOYB0ApgGM8kKoz788Aax4E8XTpHQALALYJ4CQkT5I+0bLnadeg4aPF8pPKgSS1aDSPV4EBtAG4F0fdWHRJSPhw2RDEbJC8+AGEGekFvaBiVKgY+enRGXwAzWTFgtgQBBkYYHQBZFGhLCiQqpB5Gf0iuIl8EADkKABEAUQBlAH0AQXaugZ6ugHF+hDAAejmwAHVOSUYwBjwiMAB3RSUwS0kwAAYeAA4eAA14ASUCZz4wLz8lJ-QUKjAkSC4ldB4uAAvvk7pA8NBdPR4ABtQxgYBQOCIegARmwuxgyngAGYTlgwG9fv9cfj8MQyJQaHQmCwONx+EIRGIJNJwvYaU5eOzFDTfKigWAQfDETANPQAEwYvbQbFgPEEol-dCkglaSnUBy0hH0kxM8ys6y2DmOZxGuy8hi+HGC4UhUXIhD0HHSrFKVWEvjElXysnq8iamnMHXGRlmFlHc0m+hcqOW+jW235CAO8UAFldsvdvsVXuVHv9VK1weAurDzIsVh5Wtj1b58DTSZFSPFAFZM3KFZ7vQWKQHqcU6aHTBXDXXTdzjfH+U37S2UQA2DvZrtKkk58kkfvFocMkcGyPjmNmo+JoXJhHzp0AdmXHrXPq7hcDg5De-1EarU5rJ+-9fls5sKmKLnHeG4Pr2W5FkGu56uGlZsn+E5xlqZ52kBV70AAnGBq55uuT59tBr6lsOH4IShnK-haqHwAK57NmKKKoicuFkhBG7PgO2qke+8Fjkhx6TjR-70ehKaYai6IEjKnbsfhj5+kRL48WW+6fohInIaedGARJTFOqiUoyW694KZBGrcSWankQJWlCZRVq6Qxc4GWiLomVmZk9pxylWbB5YHl+9m1oJM4uRhbmohmnlybmPmEVBKnWWR-GHoJoX2eF4mXlF7axSu8kJUpSX+W+cGjulIXUdG2UXsBhlLgV3n5r5pU7uVgUaY5Dk6WAYn1ZJt7NeB5ltZZHW8RVQWadGmW1c5OUNWioEjXhxVqn5k02WlwVzTV06LYNUU4WtRWtYlE0wZ16kUUe82HWAEp6bljqSqxZ3xRdJVXSRO2VXt8YPbRT0vctErSZiXmjRtm6-apqUA7NQMHSDz0Rfpb0SsZUNxd232be111TV1d0Zaj-7o0tmESh5uOFV9BE-duxP-TNPXA5TYM0zF9MtUzhPwylfFIxzFNOaDGOveKEr5XzMME3DLN-Yj7P3eLCbwFTx1Y018vrYrXHbar3Xq8JC2S9TbkSsN+vnQLSvEQjItq+T5uPdrjFY6tduM4pgvK8702m27PW+J7rlY6dvv4w7RusybZPVe7aOAQAuvkehcHwwZwpHGh8JDjBkEgAg57CzGzBnfi2NnGQV06UpgGnUsNXwOPF6Qpfl2AMKV83BLoLXfD173KIus3rdXnwdOd93ufj1Xg-D6PfdOhmk9W46fC83PZcL067YDzX3Ajwf9BLpvOsF3Le892v9BH9XQ+n6vKK3lfXsF3rd-n0-y+v3PqBT+EA04gCBEAA). I also set considerModelOrder to ensure that the drawing order remains stable.
Please indicate whether this solves your problem or what aspects are still to be considered.

**Comment by Daniel-Khodabakhsh** [comment]
Thanks @soerendomroes ! The examples look promising. I will play with them a little bit and update this ticket with the results or if anything else is needed 👍

**Comment by Daniel-Khodabakhsh** [comment]
This is in the right direction of solving the problem at hand. It made me realise a requirement I haven't mentioned in the original post: the ability to compact the nodes as tightly as possible according to a specified height for the overall graph. Using `'considerModelOrder.strategy': 'NODES_AND_EDGES'` and `'separateConnectedComponents': false` really help with this. In the following two examples, I manually arranged the nodes into the appropriate partitions to compact them:

| [Taller](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYHIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvKBBAikgOYB0ApgGM8kKoz788Aax4E8XTpHQALALYJ4CQkT5I+0bLnadeg4aPF8pPKgSS1aDSPV4EBtAG4F0fdWHRJSPhw2RDEbJC8+AGEGekFvaBiVKgY+enRGXwAzWTFgtgQBBkYYHQBZFGhLCiQqpB5Gf0iuIl8EADkKABEAUQBlAH0AQXaugZ6ugHF+hDAAejmwAHVOSUYwBjwiMAB3RSUwS0kwAAYeAA4eAA14ASUCZz4wLz8lJ-QUKjAkSC4ldB4uAAvvk7pA8NBdPR4ABtQxgYBQOCIegARmwuxgyngAGYTlgwG9fv9cfj8MQyJQaHQmCwONx+EIRGIJNJwvYaU5eOzFDTfKigWAQfDETANPQAEwYvbQbFgPEEol-dCkglaSnUBy0hH0kxM8ys6y2DmOZxGuy8hi+CWC4UhUXIhD0HHSrFKVWEvjElXysnq8iamnMHXGRlmFlHc0m+hcqOW+jW235CAO8UAFldsvdvsVXuVHv9VK1weAurDzIsVh5Wtj1b5uKTIqR4tR6IJMrlCs93oLFID1OKdNDpgrhrrpu5xvj-Mb9ubKIArJnO2SlSSc+SSP3i0OGSODZHxzGzUfE0Lkwj506AGzL7Ndtc+ruFwODkN7-URqtTmsnn-1+VZzYVMUQAdjvD1H17LciyDXc9XDSs2X-Cc4y1XwcSAlMr3oc4II3KCNxfAdtVLYdPyQtDOT-C10Ibc8mzFFEAE58IfPN12fPtYLfMiP0QscUOPSdaIAgUGLnJinVRE42NXDinz9bjX1Ist9y-ZDRNQ094HEu1gJw1EpXbN1IIU6CNRIks1IowStOEqirV0rDLyktEXRMrMzJ7IjlKs+DywPb97NrISZwkgy3NRDNPJXXMfK4mCVOs8iBMPITQvs8L9OwqKl1i+95ISpSkv898ENHdKQpo6NsovEDpNvArvPzXzSp3crAo0xyHJ0sA9PqwzwOagjzLayyOr4iqgs06NMtq+ictcx00Twkb2OKtU-Mmmy0uCuaauneAbQi3KVtRVj1qK1rEomuDOvUyij3mo6wBOpaGslWSrvim6Sru3jdsq-b4xeui3pcz6JTbTEvNGzbNwB1TUuB2bQcO8H3sGtyJWM2G4u7P6tva+6pq6p6MoxgCscYlaJQ8-HCt+zj-u3UmgZmnqwYAzDTuW8UJRixmWpZ4mkZS-jUa5qmnMAvmofy4X4aJxG2cBlHOeemWE0W7G6aapWNpV4ido17qtZEha5Y+nCJWGw3rtF1WeORyXNcpy3XoG2mBbWh3mcUsW1dd6bzY9nqzxtnHLv9wmnZN9mzYp6rPcxoCAF18j0Lg+GDOFJMdPgYcYMgkAEXPYRRdEwEzvxbBzjJK6dKUa-lq8+DxkvSDLiuwBhKvZlr9B674Ru+5RF1W6jwuGa7nu84nweCWH7hR4Xp0MynvWND4IW5-L9f6CXGvl5Hsf+5vQe26kvhFf33uL6Ppe69X8+wKv6ed4N+-D+Poez8PnhLeuB04gCBEAA) | [Shorter](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYHIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvKBBAikgOYB0ApgGM8kKoz788Aax4E8XTpHQALALYJ4CQkT5I+0bLnadeg4aPF8pPKgSS1aDSPV4EBtAG4F0fdWHRJSPhw2RDEbJC8+AGEGekFvaBiVKgY+enRGXwAzWTFgtgQBBkYYHQBZFGhLCiQqpB5Gf0iuIl8EADkKABEAUQBlAH0AQXaugZ6ugHF+hDAAejmwAHVOSUYwBjwiMAB3RSUwS0kwAAYeAA4eAA14ASUCZz4wLz8lJ-QUKjAkSC4ldB4uAAvvk7pA8NBdPR4ABtQxgYBQOCIegARmwuxgyngAGYTlgwG9fv9cfj8MQyJQaHQmCwONx+EIRGIJNJwvYaU5eOzFDTfKigWAQfDETANPQAEwYvbQbFgPEEol-dCkglaSnUBy0hH0kxM8ys6y2DmOZxGuy8hi+CWC4UhUXIhD0HHSrFKVWEvjElXysnq8iamnMHXGRlmFlHc0m+hcqOW+jW235CAO8WogBsrtl7t9iq9yo9-qpWuDwF1YeZFisPK1sZrfNxSYWqJFSPFABYs3KFZ7vYWKQHqcU6aHTJXDfXTdzjfHfDik62xSjUeiCTLu2SlSTc+SSIOSyOGWODZHJzGzWfE0KsM3F476ABWLs5ntbn09ouB4cho-6iPVmdawvQCGzAdsmzmYR6EkO9xUzNc3Q9N9+z3Ysg0PPVwyrNkQKnOMtV8B8IKgmD7TbFEAHZnyQ-Ntw-Ac0O-MtRz-bD8M5YCLQI+AiOvBYSNglFzmondkJ3T8h21ZjfywidcPPacuNA3iQX4pxSLYVMUQAThE19aPfP0GK-KTy2Pf8cKUvDL3gAU+LmFsyKXJ1UROPTNwMlCNUk0szNYuSrIU9irVsiDHM08iXKlBDsxovtxOMnyMIrE8AMCut5P5MLBJcl0Yo3PN4vo1CTN8ljZNPeSMsCrL7PClNIrRTt8pfDyiqMkqkp-TDx0q9LOOjK9VIcnK0SfFq4oLBLOoPbqUos4KgpssAbTq0bUSoibRM86bvNm6SetSyzo2qwb4HA+ycXW4Stv09q1US-a-IqtKToG2dzogiV1t0262qm4q9vQubzLYs9To+sCvtGiU3L+wqAY6oGmOe3rXvjCHuKh+zvqc+8JVXTFYu2+7d2R0zyrR46MferGVJvOZcYi5zJWiomCt7RGHpm4GDvmsGqtp5Tobx8UJTy9nWoRuikf3XnUaOxbMdA9MIKu0WUQlZrJcmmXufJsqZKppWhZCsBVcumHxp1kmubJuWUcpxXwdNhN4At4b1eZ-H4Jtu67Ykp6nYWl3FLO821Zhza-f+vX7cYimjedwWw8h+c1o1p0JRumPpcM-WHcTw6Q5Txa5xF72xd+3PObjwP5eDgX+tTrH0+GpmAF18j0Lg+GDOFM74QnGDIJABD72Fl1mLu-FsXuMknrPp+vHK+DZkfSDHiewBhKewBn9A574Bed5RF195XweJY3rf+7P6eCUP7hj7vp1Owvu1K8QPhtZv8fX8fA-Wez8T67ydJmD+yYESRT4NbP+28wGAP3o-I+oDKLL0-g1ZyfBfbwIAU+ZBwD54AOEpA3AHcQBAiAA) |
| --- | --- |
| ![image](https://github.com/eclipse/elk/assets/9839187/6dbd965d-83b6-4f76-96a5-850caf4855cd) | ![image](https://github.com/eclipse/elk/assets/9839187/ed01ad3e-c864-4a31-8cd3-2b77c116248e) |

It'll be a lot of work programmatically arranging the nodes in the appropriate partition. With this other criteria in mind, is there an easy way to wrap the nodes to a specified height without using partitions?

**Comment by soerendomroes** [comment]
Maybe you could try Coffman & Graham minimal layer width layer assignment (and a simple node placement strategy to create the blocks. [In this example](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYHIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvKBBAikgOYB0ApgGM8kKoz788Aax4E8XTpHQALALYJ4CQkT5I+0bLggB6I4k69Bw0eL5SeVAklq0GkerwIDaANwLo+6mDoSKR8OGyIYg5IfnwAwgz0gv7QCSpUDHz06IyBAGayYuFsCAIMjDA6ALIo0LYUSHVIPIzBsVxEgQgAchQAIgCiAMoA+gCC3X0jA30A4sPYYCZgAOqckoxgDHhEYADuikpgtpJgAAw8ABw8ABrwAkoE7nxgfkFKL+goVGBIkFxKdA8QyIPYxKhUNy8ATkWjuFptfwdLpjABKfUWywAKkpIJseASQQgwQQIVCETEkZ0NFUAKoAGSxAElpnMBpjTASeK96NB3nj9mQ8HzZHgUHsgihXtA+QAjTySPaOPl6Lh8TYEcgoFR+SACUW7eViPkMd4vAiMKjJX66qUACg+uig6DA0BQ6rA9AwuPcAEoieZ+EIRGIJNJoJBdF46PQuqimbMABJYgwRBAWq1eVG2wIAJmK7C0OnJrUpfGR8AARHEKAAxWtVCYjWaosaJsZVStYJamJl5MDRZwxqCbCOMAiyvB6MBcolFv7wsp5PI6+izGKPFQ8ecAITIvMCADZu8suWAEsvV2AAGRgdcETdgFRuSA6vD7GDKfDEYvuMD6+gwFlF5SGNYE0y9OoAAVCAEPgVCyIFS3aalECGJkqig+l2R7MAcQFHVdioVBoFIODjmgNUgKyaBNllch-0QnQNTwd9II9NwzUjb9tCQID91o8CwAAX2KB5IGFXR6HgABtEFgCgOBEHoABGRYDmgZR4AAZjObsPn+QEdL0niyEoGgY2YMBgA4bggysUMTnsRwh1ceFB0UGNAhU4SRILazFI0ehc3Uz8lGM-S+EM9AItM8hqBcJgWFsixg2sMNnKcTy3N4DzEsCbTfNE+TAuU7TQs08KwF0yLotirQzISyzksDSwQxsOw8pjckuoYAqiv8hSYCCgAWCqtOqkyDIBGLJu7Br4os8oWrstr0qc3r6B6lzstjeARoGkrhuUgBWcaqpqsBpqMua4vMxKrJs1q0sczqdsS7asvy+AfL8o6lIQehD3O2Lrtmy6Fvu5rrJS+z2oyzbPtcvbqsOiIhoB+gAHYQdusH6uIRqlqSmHnocjrpER9z3q8nS0bYDGgsuXHLvx27Iaa5bSdWl6Kcy5Gkd2-q-vR0rAYAThZqaopmgmSEWh6VtS8mEZpnL+aFn76YgRnlJUs4pdq2X2cJhXoaenmVY2tWtupr7abAX7itF47AZUtTuw0ibWZlm6IdNqGuYt5X4et+31c27ztYC13VJCz2wtB33wZMjnice2G1teymbcF77Hej3W3fKhPKqTuqTflwOSeDuH1re8Pbdym2o5FhmxdUsbS+96WK-9qvOZrzPedVxu84dp3Bo7lSzu7i7e+N-uicV7mQ-rnOx7t5HW+d9vY5U4G5-LxfU4DweM7J0OG4FrfNYLtudennGj7x5O5eX83h6t6-dvHvqtYfjHTGKlmYvx9n3U+A905KzrtnDWH1b750nv9IKKlJZgIXn7SBH8g5fyvhvG+zdG55kLh3XMBsMFGywfNM+0DV6wL5lTIh294C5lIbHXMHsPxl1fhAmhUCV61yzow3OiCHZsMAUXYK8duE9yoSnfhOCh6X3XvA7qYj-5gAkbvR+HCS6yPnvI9+ZtcEqLgUwtRmjtFTw4V3Axx9qF3XPjA4Ro9CGWJRtYlBylcyz3sbwk+iiTHKMtvgjxf9PHsMxrmQ+-jwGBKcXQoRI8w7uMjqwqJQVczPziZghRiTBF4NURY9JWjMk+NAbkoxlclEX1CcU0RzC75eJdtE9BVSrpvxqcEupa9zGNI8SQtuABdYoqp1SyW8QgPgXDGBkCQHBKyMk9YIDAKMoIjg1Q5Fkj41ZwzJFiz4DIuZpAFkTLAMst2ezuzoE2XwbZFyyp7IOa7Pg+iTlnKWU8tZNy7kPMufQMaayXkAz4HYj5iydmAzOj8jZ3B7lfMBsDYFOigEaD4H4iF5yAUwvWbc+F-zlI4xRTY0FsSsWIvoLi35BLKXMxJbgYZIBhJAA), you can see it work without partition. You can also activate partition with it but it is no longer guaranteed that the partitions are next to each other.

**Comment by soerendomroes** [comment]
As I see it Coffman & Graham will work for you, since your elements have the same size, hence you can approximate the elements per layer based on your desired aspect ratio.

**Comment by Daniel-Khodabakhsh** [comment]
Thanks again @soerendomroes ! You're right, Coffman & Graham fits my use-case exactly! I'm having some issues with the ordering but I'll open a separate ticket for that. I'll close this one 👍
